import json,pathlib,decimal,collections
D=decimal.Decimal;root=pathlib.Path('/root/mgs-agent/work/adops-revenue-1547811852405178460');rows=json.loads((root/'normalized-rows.json').read_text());dash=json.loads((root/'dashboard-aggregates.json').read_text())['data'];rates={x['month']:D(x['usd_cad']) for x in dash['rates']};mapping={'autocreditadx':'AutoCreditAdx','cephyric':'Cephyric','cliquet':'Cliquet','cliquetfinanzas':'Cliquet Finanzas','ducapes':'Ducapes','ducapesfinance':'Ducapes Finance','eggbev':'Eggbev','eggbevfinanzas':'Eggbev Finanzas','escalatepower':'Escalatepower','financeadx':'FinanceAdx','gamingadx':'GamingAdx','helixenit':'Helixenit','infinitynexx':'Infinitynexx','lyzmo':'Lyzmo','lyzmofinanzas':'Lyzmo Finanzas','marevelx':'Marevelx','mavroa':'Mavroa','newsoun':'Newsoun','newsounde':'Newsoun DE','newsounfinanzas':'Newsoun Finanzas','openzed':'Openzed','openzedfinanzas':'Openzed Finanzas','portalrelevante':'Portal Relevante','topfeed':'FinanceTopFeed','topfeedfinanzas':'TopFeed Finanzas','vizioid':'Vizioid','wavesbee':'WavesBee','xyvlov':'Xyvlov','yolokfx':'Yolokfx','zuoutfinanzas':'Zuout Finanzas','zytiva':'Zytiva','zytivafinanzas':'Zytiva Finanzas','creditoparaveiculo':'CreditoParaVeiculo','fincgriffin':'Fincgriffin','gamezonead':'GameZoneAd'};unknown=sorted({r['brand'] for r in rows if r['brand'] not in mapping});expected=collections.defaultdict(D);source=collections.defaultdict(lambda:{'currency':None,'revenue':D(0),'network':None})
for r in rows:
 if r['brand'] not in mapping:continue
 key=(r['month'],mapping[r['brand']],r['country']);v=D(r['revenue']);source[key]['currency']=r['currency'];source[key]['network']=r['network'];source[key]['revenue']+=v;expected[key]+=v/rates[r['month']] if r['currency']=='CAD' else v
actual={(x['competence'],x['site'],x['country']):D(str(x['gross_usd'])) for x in dash['aggregates']};diff=[]
for k in sorted(expected):
 e=expected[k];a=actual.get(k,D(0));d=a-e;diff.append({'month':k[0],'site':k[1],'country':k[2],'network':source[k]['network'],'source_currency':source[k]['currency'],'source_revenue':str(source[k]['revenue']),'expected_usd':str(e),'dashboard_usd':str(a),'difference_usd':str(d),'missing_dashboard_key':k not in actual})
material=[x for x in diff if abs(D(x['difference_usd']))>D('0.02')];out={'pass':True,'rates':{k:str(v) for k,v in rates.items()},'mapping':mapping,'unknown_brands':unknown,'comparisons':diff,'material_differences':sorted(material,key=lambda x:abs(D(x['difference_usd'])),reverse=True),'summary':{m:{'report_expected_usd':str(sum((expected[k] for k in expected if k[0]==m),D(0))),'dashboard_same_keys_usd':str(sum((actual.get(k,D(0)) for k in expected if k[0]==m),D(0))),'difference_usd':str(sum((actual.get(k,D(0))-expected[k] for k in expected if k[0]==m),D(0))),'material_keys':sum(x['month']==m for x in material)} for m in ['2026-08','2026-09']}};(root/'compare-dashboard.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'pass':True,'rates':out['rates'],'unknown_brands':unknown,'summary':out['summary'],'top_material':out['material_differences'][:20]},ensure_ascii=False))
