from audit import *
from collections import Counter
A=cmap('principal');C=cmap('principal','CAIXA SINTETICO')
V=lambda cc,x:val(cc.get(x,{}));N=lambda cc,x:V(cc,x) if isinstance(V(cc,x),(int,float)) else 0
issues=[]
def add(id,kind,scope,description,evidence,proposal=None):
 issues.append({'id':id,'classification':kind,'scope':scope,'description':description,'evidence':evidence,'proposal':proposal,'state':'reported_waiting_manual' if id=='F01' else 'queued_not_presented','authorization_to_write':False})
add('F01','confirmed_error',['CAIXA SINTETICO!J70'],'Yolokfx gross J37 omitted from JBF rev-share.',{'formula':formula(C['J70']),'J37':N(C,'J37'),'profit_overstatement_usd':N(C,'J37')*.1*.95,'half_brl_overstatement':N(C,'J37')*.1*.95*.5*N(C,'J2')},'=SUM(J37:J51,J62)*$B$3*-1')
add('F02','confirmed_error',['Agosto 2026!KX83'],'Eggbev closing revenue omits Brazil LD36 despite inclusion in daily/site totals.',{'formula':formula(A['KX83']),'missing_gross_usd':N(A,'LD36'),'gross_existing':N(A,'KX83'),'gross_expected':sum(N(A,x) for x in ['KU36','LD36','LM36'])},'=SUM(KU36,LD36,LM36)')
add('F03','confirmed_error',['Agosto 2026!MZ83'],'Cliquet closing revenue omits Brazil NF36.',{'formula':formula(A['MZ83']),'missing_gross_usd':N(A,'NF36'),'gross_existing':N(A,'MZ83'),'gross_expected':sum(N(A,x) for x in ['MW36','NF36','NO36'])},'=SUM(MW36,NF36,NO36)')
add('F04','confirmed_error',['Agosto 2026!P178'],'JBF invalid-traffic consolidation omits Yolokfx AGQ84 and lower Infinitynexx AFN185.',{'formula':formula(A['P178']),'AGQ84':N(A,'AGQ84'),'AFN185':N(A,'AFN185'),'missing_invalid_usd':sum(N(A,x) for x in ['AGQ84','AFN185'])},'Add $AGQ$84 and $AFN$185 to the existing SUM, preserving every current constituent.')
add('F05','confirmed_error',['Agosto 2026!ACE36:ACF36','Agosto 2026!ABM36:ABN36','Agosto 2026!ABV36:ABW36'],'Helixenit country total ROI converts USD revenue to BRL but divides by USD costs; MX currently affected, DE/US latent.',{'ACE36':V(A,'ACE36'),'ACE36_expected':N(A,'ABY36')/abs(N(A,'ACC36'))-1,'ACF36':V(A,'ACF36'),'ACF36_expected':N(A,'ACA36')/(abs(N(A,'ACC36'))+abs(N(A,'ACB36')))-1},'Repair one country pair at a time; use the same USD/USD identity and empty guards as the daily country formulas, without *$F$1.')
add('F06','confirmed_error',['Agosto 2026!AGH135:AGI135'],'Lower Infinitynexx consolidated day-31 ROI formulas are absent although revenue/spend exist.',{'actual':['',''],'gross_roi_expected':(N(A,'AFK135')+N(A,'AFT135'))/abs(N(A,'AGF135'))-1,'net_roi_expected':N(A,'AGB135')/(abs(N(A,'AGF135'))+abs(N(A,'AGC135'))+abs(N(A,'AGD135')))-1},'Translate row134 formulas down exactly one row; validate both cells.')
add('F07','latent_formula_gap',['Agosto 2026!AOT35:AOU35'],'ZA consolidated day-31 ROI formulas absent; currently zero activity masks the gap.',{'previous_formulas':[formula(A['AOT34']),formula(A['AOU34'])]},'Restore by exact relative translation from row34 after authorization.')
add('F08','confirmed_error',['Agosto 2026!APD5:APD35'],'Global gross ROI reconstructs gross from net with uniform 10% share; net already excludes invalid traffic and M2 uses 5%.',{'sample':formula(A['APD5'])},'Use actual USD-normalized gross components, including every country and both special blocks; do not invert a uniform share.')
add('F09','confirmed_error',['Agosto 2026!APD36'],'Monthly gross ROI uses unweighted AVERAGEIF of daily ratios and excludes valid zero-ROI days.',{'formula':formula(A['APD36']),'actual':V(A,'APD36'),'gross':N(C,'J58'),'spend':abs(N(A,'APB36')),'expected':N(C,'J58')/abs(N(A,'APB36'))-1},'Compute ratio from monthly gross and monthly spend; do not average daily ROI.')
add('F10','metric_definition_review',['Agosto 2026!APE5:APE35'],'Net-ROI denominator includes invalid traffic although AOW revenue already excludes it. The convention also differs from Caixa J79 (profit/media).',{'sample':formula(A['APE5']),'net_already_excludes_invalid':True},'Confirm chosen KPI definition before editing; preserve separate labels for profit/media and return/all-costs.')
add('F11','confirmed_error',['Agosto 2026!APE36'],'Monthly net ROI averages daily ratios instead of a ratio of monthly components.',{'formula':formula(A['APE36']),'actual':V(A,'APE36')},'After net-ROI definition is agreed, compute from monthly components; never average daily ratios.')
add('F12','confirmed_error',['Isliago Agosto 2026!C14:F14'],'Projection range21:51 includes month/year and only Aug1–29, instead of the 31 daily rows23:53.',{'range_current':'A21:A51/C21:C51','range_calendar_correct':'A23:A53/C23:C53','current_projection_equals_total_by_coincidence':True},'Correct exact date band and separately agree a complete-period projection rule.')
for id,name,den in [('F13','george',20),('F14','joe',30)]:
 cc=cmap(name)
 add(id,'confirmed_error',[name+' Agosto 2026!C14:F14'],'Projection uses last nonblank revenue of first site as days completed for entire portfolio, even after the calendar month ended.',{'denominator':den,'actual_total_D12':N(cc,'D12'),'projected_D14':N(cc,'D14'),'current_salary_stays_R3000_floor':True},'Define a portfolio-wide data-completeness cutoff; closed complete months must not extrapolate from a site with no recent revenue.')
add('F15','label_error',['Isliago Agosto 2026!A1','George Agosto 2026!A1','Nicolas Agosto 2026!A1','Joe Agosto 2026!A1'],'Four August manager tabs still display Julho; identities, tabs, and imported dates are August.',{'kelly_correct':'Agosto','four_incorrect':'Julho'},'Change only A1 to Agosto in each confirmed file, one verified scope at a time.')
add('F16','reporting_gap',['Agosto 2026!AMC:AOU'],'Country summary excludes BR despite Brazilian revenue/spend in the source blocks.',{'missing_gross_usd':sum(N(A,x) for x in ['BP36','EO36','LD36','NF36','PH36','SB36','SB136'])},'Add an approved BR summary or explicitly label the existing country overview partial; structural work requires separate scope.')
add('F17','business_evidence_needed',['Agosto 2026!O121:P121'],'SMS Funnel has independently entered USD and BRL amounts, inconsistent with provisional F1; a settled transaction rate could justify this.',{'usd':N(A,'O121'),'brl':N(A,'P121'),'implied_rate':N(A,'P121')/N(A,'O121'),'provisional_rate':N(A,'F1')},'Check payment proof before choosing source currency. Do not auto-convert or classify as confirmed accounting error.')
add('F18','latent_formula_gap',['Agosto 2026!D38','Agosto 2026!V38','Agosto 2026!AN38','Agosto 2026!FY38','Agosto 2026!GQ38','Agosto 2026!AKD38','Agosto 2026!AKU38','Agosto 2026!ALL38'],'Eight dormant summary cells sum empty rows37:38 instead of monthly gross; zero blocks hide the defect. YMonetize retirement stays respected.',{x:formula(A[x]) for x in ['D38','V38','AN38','FY38','GQ38','AKD38','AKU38','ALL38']},'Disposition per inactive block before reuse; do not reactivate YMonetize or expand correction scope.')
add('F19','confirmed_error',['Agosto 2026!P171'],'SB-CAD payout estimate omits lower Infinitynexx net-before-tax contribution AFN184:AFN186.',{'formula':formula(A['P171']),'omitted_usd':sum(N(A,'AFN'+str(r)) for r in [184,185,186])},'Add the lower Infinitynexx subtotal to existing SB-CAD constituents; preserve USD/CAD grouping distinct from partner grouping.')
save('findings-queue.json',issues)
manifest=json.loads((ROOT/'manifest.json').read_text());tabs=[dict(book=k,**t) for k,ob in manifest.items() for t in ob['tabs']]
recomp=json.loads((ROOT/'formula-recomputation-summary.json').read_text());status=dict(sum((Counter(v['counts']) for v in recomp.values()),Counter()))
coverage={'books':len(manifest),'tabs':len(tabs),'cells':sum(x['cells'] for x in tabs),'formulas':sum(x['formulas'] for x in tabs),'displayed_errors':sum(len(x['errors']) for x in tabs),'formula_recompute':status,'manager_spill_cells':sum(v['spill_cells'] for k,v in recomp.items() if not k.startswith('principal:')),'semantic_tests':sum(len(json.loads((ROOT/f).read_text())) for f in ['semantic-checks.json','extended-semantic-checks.json','spend-calendar-checks.json']),'findings_by_class':dict(Counter(i['classification'] for i in issues)),'google_writes':0,'initial_final_entered_deltas':sum(len(v) for v in json.loads((ROOT/'final-scope-diff.json').read_text()).values()),'initial_final_effective_deltas':sum(v['effective_deltas'] for v in json.loads((ROOT/'final-effective-diff.json').read_text()).values())}
save('coverage.json',coverage)
bridge=json.loads((ROOT/'J81-J137-bridge.json').read_text())
report=['# Reauditoria financeira Agosto 2026 — 2026-09-05','', 'Autorização: Rodolfo, mensagem1545832349957234688, thread1545426987756298340.','', '**Resultado: FAIL semântico. Varredura diagnóstica concluída; nenhuma correção nas planilhas foi executada.**','', '## Cobertura',json.dumps(coverage,ensure_ascii=False,indent=2),'', 'Leitura completa das abas Agosto 2026 e CAIXA SINTETICO da principal e Agosto 2026 dos cinco gestores ativos. API Sheets pelo helper/SA canônico, inclusive células ocultas/filtradas. Gustavo não integra o escopo ativo. As sete abas foram relidas integralmente ao final: nenhum delta de fórmula, valor digitado ou valor efetivo.','', 'As fórmulas foram inventariadas e reavaliadas uma a uma sobre seus precedentes capturados. As dez GOOGLEFINANCE foram verificadas como dependências voláteis/provisórias, sem pretensão de reproduzir a cotação externa. Ausência de erros de execução não equivale a acerto semântico.','', 'As referências históricas de CAIXA foram lidas em seus alvos exatos para validar as fórmulas desta aba; isto não constitui auditoria integral de Janeiro–Julho. As taxas de pagamento de agosto continuam provisórias conforme regra aprovada. Valores digitados foram lidos e testados quanto a tipo, datas, sinais/consolidação/moeda; sem os comprovantes/exportações originais, a auditoria não atesta veracidade documental ou completude do faturamento/custos lançados.','', '## Conciliação J81/J137',json.dumps(bridge,ensure_ascii=False,indent=2),'', 'A diferença está integralmente explicada no snapshot: J70 omite rev share de Yolokfx; KX83/MZ83 omitem BR de Eggbev/Cliquet, afetando lucros e invalidos AV; P178 omite invalidos de Yolokfx e Infinitynexx inferior. Resíduo apenas de precisão float inferior a um centavo. A correção deve ocorrer nas origens, nunca forçando igualdade entre as células finais.','', '## Fila de achados — apresentação ao Rodolfo um por vez','Apenas F01 foi apresentado e aguarda a edição manual de J70. F02 em diante ainda não foram apresentados como instrução de correção. Cada impacto deve ser relido ao vivo após correções anteriores.','']
for i in issues:
 report += ['### '+i['id']+' — '+i['classification'],'Escopo: '+', '.join(i['scope']),i['description'],'Evidência: '+json.dumps(i['evidence'],ensure_ascii=False),'Próxima proposta (não autorizada): '+str(i['proposal']),'']
report+=['## Limites e status institucional','O PASS global antigo foi superado por esta reauditoria, preservando os artefatos históricos. O dashboard existente continua dependente das fontes com erros pendentes. Não foi auditado nem alterado nesta tarefa.','Artefatos locais: manifest.json; all-cell-inventory.jsonl; formula-recomputation.jsonl; semantic-checks.json; extended-semantic-checks.json; spend-calendar-checks.json; manager-semantic-audit.json; J81-J137-bridge.json; findings-queue.json; final/.']
(ROOT/'REPORT.md').write_text('\n'.join(report)+'\n')
print(json.dumps(coverage,ensure_ascii=False));print('Report',str(ROOT/'REPORT.md'))
