import test from 'node:test';import assert from 'node:assert/strict';import {planRollover,nextMonth} from '../scripts/finance-month-rollover-core.mjs';
const site={id:'site-a',kind:'site',new:true,name:'A',status:'ATIVO',domain:'a.example',countries:['US'],currency:'USD',manager:'joe',network:'SB Rede1'};
const row=(p,additions=[])=>({id:'workspace-'+p,state:'draft',additions});
function setup(from='2026-10'){return {s:row(from,[structuredClone(site),{kind:'direct_monthly_cost',id:'sms-direct-old',amount:'100',authority:'1555422806940983327'},{kind:'expense',id:'company|121',amount:'95000'},{id:'revenue',date:from+'-01',gross:'200'}]),t:row(nextMonth(from),[{...site,status:'INATIVO'},{kind:'data_cutoff',date:null}]),r:{accounts:[{id:'111111',name:'A-US-X-G004',verified:true,bindings:{[from]:['A']},auto_spend_binding:{[from]:{site:'A',country:'US'}},manager_bindings:{[from]:{code:'G004',key:'joe'}}}]}};}
test('October-November and December-January carry current config only',()=>{for(const from of ['2026-10','2026-12']){const {s,t,r}=setup(from),before=structuredClone({s,t,r}),p=planRollover(s,t,r);assert.equal(p.to,nextMonth(from));assert.equal(p.additions.find(a=>a.kind==='site').status,'ATIVO');assert.deepEqual(p.additions.filter(a=>a.kind!=='site'),t.additions.filter(a=>a.kind!=='site'));assert.deepEqual(p.accounts[0].bindings[p.to],['A']);assert.deepEqual({s,t,r},before);}});
test('new mid-month operation is included; SMS history and recharge never copied',()=>{const {s,t,r}=setup();s.additions.push({...site,id:'site-new',name:'New'});r.accounts.push({id:'222222',bindings:{'2026-10':['New']},auto_spend_binding:{'2026-10':{site:'New',country:'US'}}});const p=planRollover(s,t,r);assert.ok(p.additions.some(a=>a.name==='New'));assert.ok(!p.additions.some(a=>a.id==='sms-direct-old'||a.id==='company|121'||a.id==='revenue'));});
test('explicit target empty account binding and site override survive repeated runs',()=>{const {s,t,r}=setup();r.accounts[0].bindings['2026-11']=[];const p=planRollover(s,t,r,{protectedSites:['site-a']});assert.equal(p.additions[0].status,'INATIVO');assert.deepEqual(p.accounts[0].bindings['2026-11'],[]);assert.equal(p.accounts[0].auto_spend_binding['2026-11'],undefined);const again=planRollover(s,{...t,additions:p.additions},{accounts:p.accounts},{protectedSites:['site-a'],previous:p.proof});assert.deepEqual(again.accounts[0].bindings['2026-11'],[]);assert.equal(again.changes.length,0);});
test('late source changes refresh inherited fields but never a later target edit',()=>{const {s,t,r}=setup(),p=planRollover(s,t,r),target={...t,additions:p.additions},reg={accounts:p.accounts};s.additions[0].status='INATIVO';let a=planRollover(s,target,reg,{previous:p.proof});assert.equal(a.additions[0].status,'INATIVO');target.additions[0].owner='target-specific';a=planRollover(s,target,reg,{previous:p.proof});assert.equal(a.additions[0].owner,'target-specific');assert.equal(a.additions[0].status,'ATIVO');});
test('replay is idempotent and nonadjacent periods fail',()=>{const {s,t,r}=setup(),p=planRollover(s,t,r),a=planRollover(s,{...t,additions:p.additions},{accounts:p.accounts},{previous:p.proof});assert.equal(a.changes.length,0);assert.throws(()=>planRollover(s,row('2026-12'),r));});
test('unresolved source destination blocks without invented site',()=>{const {s,t,r}=setup();r.accounts[0].auto_spend_binding['2026-10'].site='Unknown';const p=planRollover(s,t,r);assert.equal(p.blocked.length,1);assert.ok(!p.additions.some(a=>a.name==='Unknown'));});
