#!/usr/bin/env node
const fs = require('fs');
const cp = require('child_process');
const path = require('path');
const { chromium } = require('/root/mgs-agent/tools/meta-library-collector/node_modules/playwright');
const SOURCE='Infinitynexx - MX-CC-ES/ES-ZW-SR - g004-d Joe';
const TARGET='Infinitynexx - MX-CC-ES/ES-ZW-SR - g001-d Icaro';
const OUT='/root/mgs-agent/work/sb-template-clone-infinitynexx-g001-icaro';
const STATE='/root/.local/share/mgs/smartbidding_state_headed.json';
const UA='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36';
const STATUS=new Set(['APPROVED','INVALID_FORMAT','REJECTED','ERROR','REJECTED_REASON']);
function secret(field){return cp.execFileSync('op',['item','get','Zeus - Smartbidding Dashboard','--vault','MGS Conteúdo','--field',field,'--reveal'],{encoding:'utf8'}).trim();}
function parse(r){return typeof r.MESSAGES==='string'?JSON.parse(r.MESSAGES):(r.MESSAGES||[]);}
function clean(m){const o={};for(const [k,v] of Object.entries(m))if(!STATUS.has(k))o[k]=v;return o;}
function expected(m){const o=clean(m);for(const k of ['LINK_1','LINK_2'])if(o[k])o[k]=o[k].replace(/([?&]utm_medium=)g004-d(?=(&|$))/g,'$1g001-d');return o;}
function canon(m){const x=clean(m), ks=['MESSAGE_ID','TEXT','DESCRIPTION','IMAGE','CTA_1','LINK_1','CTA_2','LINK_2','TEXT_2'],o={};for(const k of ks)o[k]=x[k]==null?'':x[k];return o;}
function count(ms,medium){let n=0;for(const m of ms)for(const k of ['LINK_1','LINK_2'])if((m[k]||'').includes(`utm_medium=${medium}`))n++;return n;}
async function login(page,ctx){const b=await page.locator('body').innerText({timeout:15000});if(!b.includes('Log in to Smart Bidding')&&!b.includes('Email address'))return;await page.locator('input[type="email"]:visible, input[name="username"]:visible, input[name="email"]:visible, input:visible').first().fill(secret('username'));await page.locator('input[type="password"]:visible').first().fill(secret('password'));await page.getByRole('button',{name:/Continue|Log in|Login/i}).first().click();await page.waitForLoadState('networkidle',{timeout:90000});await page.waitForTimeout(3000);await ctx.storageState({path:STATE});}
(async()=>{const browser=await chromium.launch({headless:false,args:['--disable-blink-features=AutomationControlled']});const ctx=await browser.newContext({storageState:fs.existsSync(STATE)?STATE:undefined,viewport:{width:1600,height:1000},userAgent:UA});const page=await ctx.newPage();const rows=[];page.on('response',async r=>{if(r.url().includes('/broadcast/Messenger')&&r.status()===200&&r.request().method()==='GET'){try{const d=await r.json();if(Array.isArray(d))rows.push(...d);}catch(_){}}});try{await page.goto('https://app.smartbiddingdigital.com/accounts',{waitUntil:'networkidle',timeout:90000});await page.waitForTimeout(2500);await login(page,ctx);try{await page.locator('.p-dropdown').first().click({timeout:10000});await page.waitForTimeout(500);await page.getByText('Messenger',{exact:true}).last().click({timeout:10000});await page.waitForTimeout(2500);}catch(_){}await page.getByText('Broadcast Template',{exact:true}).click({timeout:15000});await page.waitForTimeout(7000);const d=new Map();for(const r of rows)d.set(r.ID||r.NAME,r);const all=[...d.values()],ss=all.filter(r=>r.NAME===SOURCE),ts=all.filter(r=>r.NAME===TARGET);if(ss.length!==1||ts.length!==1)throw new Error(`exact counts source=${ss.length} target=${ts.length}`);const s=ss[0],t=ts[0],sm=parse(s),tm=parse(t),em=sm.map(expected);const checks={distinct_id:t.ID!==s.ID,exact_name:t.NAME===TARGET,company:t.COMPANY===s.COMPANY,publisher_id:t.PUBLISHER_ID===s.PUBLISHER_ID,language:t.LANGUAGE===s.LANGUAGE,utm_content_mask:(t.UTM_CONTENT_MASK||'')===(s.UTM_CONTENT_MASK||''),message_count_30:tm.length===30,g001_links_30:count(tm,'g001-d')===30,no_g004_links:count(tm,'g004-d')===0,content_and_urls_exact:JSON.stringify(tm.map(canon))===JSON.stringify(em.map(canon)),pages_zero:Number(t.PAGES||0)===0,leads_zero:Number(t.LEADS||0)===0};const report={source_id:s.ID,target_id:t.ID,target_name:t.NAME,messages:tm.length,g001_links:count(tm,'g001-d'),g004_links:count(tm,'g004-d'),pages:t.PAGES,leads:t.LEADS,checks};fs.writeFileSync(path.join(OUT,'target-live-readback.json'),JSON.stringify(t,null,2));fs.writeFileSync(path.join(OUT,'validation.json'),JSON.stringify(report,null,2));const failed=Object.entries(checks).filter(([,v])=>!v).map(([k])=>k);if(failed.length)throw new Error(`validation failed: ${failed.join(', ')}`);console.log(JSON.stringify({status:'OK',...report,validation:path.join(OUT,'validation.json')},null,2));}finally{await browser.close();}})().catch(e=>{console.error(e.stack||String(e));process.exit(1);});
