import json,sys,os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

# Keep Chromium Unix socket paths under Linux's length limit.
os.environ['TMPDIR'] = '/root/.hermes/profiles/zeus/cache/scratch'
cfg=json.load(sys.stdin)
with sync_playwright() as p:
    chrome=Path('/root/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome')
    if not chrome.exists():
        chrome=Path('/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome')
    browser=p.chromium.launch(headless=True,executable_path=str(chrome))
    context=browser.new_context(viewport={'width':1280,'height':850})
    # Synthetic local-test session; no production users or credentials.
    context.add_cookies([{'name':'mgs_session','value':cfg['session'],'url':cfg['url'],'httpOnly':True,'sameSite':'Strict'}])
    page=context.new_page();errors=[]
    page.on('pageerror',lambda error:errors.append(type(error).__name__))
    response=page.goto(cfg['url']+'/admin');assert response.status==200
    page.get_by_role('button',name='Cadastro domínios',exact=True).click()
    page.locator('#new-domain').fill('qa.example.com, sub.qa.example.com')
    page.get_by_role('button',name='Adicionar domínio',exact=True).click()
    expect(page.locator('#dns-instructions')).to_be_visible()
    expect(page.locator('#dns-host')).to_have_text('Domínio: qa.example.com')
    expect(page.locator('#dns-record')).to_contain_text('2.25.165.171')
    expect(page.locator('#domain-list strong')).to_have_text(['qa.example.com','sub.qa.example.com'])
    page.reload()
    expect(page.locator('#domain-list strong')).to_have_text(['qa.example.com','sub.qa.example.com'])
    page.get_by_role('button',name='Ver instruções DNS',exact=True).first.click()
    expect(page.locator('#dns-notice')).to_contain_text('apenas conexões do proxy Cloudflare')
    page.get_by_role('button',name='Verificar',exact=True).first.click()
    expect(page.locator('.domain-status').first).to_contain_text('Pendente',timeout=10000)
    assert page.locator('.domain-status.verified').count()==0
    # Synthetic frontend-only positive result; real backend positive proof is separate.
    page.route('**/api/domains/check',lambda route: route.fulfill(status=200,content_type='application/json',body=json.dumps({'host':'qa.example.com','verified':True,'message':'Teste local positivo da interface','checked_at':'2026-01-01T00:00:00Z'})))
    page.get_by_role('button',name='Verificar',exact=True).first.click()
    expect(page.locator('.domain-status.verified')).to_have_count(1)
    assert page.locator('#domain-list button.verified').count()==1
    page.unroute('**/api/domains/check')
    page.get_by_role('button',name='Rotas',exact=True).click()
    page.get_by_role('button',name='Nova rota',exact=True).click()
    page.locator('#host').fill('test.wantabrand.invalid')
    page.locator('#path').fill('/qa-route')
    page.locator('#destination').fill('https://wantabrand.com/qa-one')
    page.get_by_role('button',name='Salvar e aplicar',exact=True).click()
    page.get_by_role('button',name='Editar destino',exact=True).wait_for()
    page.locator('#routes summary').click()
    assert page.locator('.destination').inner_text()=='https://wantabrand.com/qa-one'
    page.get_by_role('button',name='Editar destino',exact=True).click()
    assert page.locator('#host').get_attribute('readonly') is not None
    assert page.locator('#path').get_attribute('readonly') is not None
    page.locator('#destination').fill('https://wantabrand.com/qa-two')
    page.get_by_role('button',name='Salvar e aplicar',exact=True).click()
    expect(page.locator('.destination')).to_have_text('https://wantabrand.com/qa-two')
    page.get_by_role('button',name='Editar destino',exact=True).click()
    page.locator('#weighted').check()
    page.locator('.target-url').nth(1).fill('https://wantabrand.com/qa-three')
    page.locator('.target-weight').nth(0).fill('30')
    page.locator('.target-weight').nth(1).fill('70')
    page.get_by_role('button',name='Salvar e aplicar',exact=True).click()
    expect(page.locator('.destination')).to_have_text(['30% — https://wantabrand.com/qa-two','70% — https://wantabrand.com/qa-three'])
    page.reload()
    expect(page.locator('.destination')).to_have_text(['30% — https://wantabrand.com/qa-two','70% — https://wantabrand.com/qa-three'])
    page.locator('#search').fill('absent')
    assert page.locator('#routes .empty').inner_text()=='Nenhuma rota corresponde ao filtro.'
    page.locator('#search').fill('')
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
    page.get_by_role('button',name='Grupos',exact=True).click()
    page.locator('#group-name').fill('QA · US-CC-ES')
    page.get_by_role('button',name='Criar grupo',exact=True).click()
    expect(page.locator('#groups tr')).to_have_count(1)
    page.get_by_role('button',name='Destinos',exact=True).click()
    page.get_by_role('button',name='Novo destino',exact=True).click()
    page.locator('#destination-name').fill('QA Landing 02')
    page.locator('#catalog-group').select_option(label='QA · US-CC-ES')
    page.locator('#catalog-url').fill('https://wantabrand.com/qa-two')
    page.get_by_role('button',name='Salvar destino',exact=True).click()
    expect(page.locator('#destinations tr')).to_have_count(1)
    page.reload()
    expect(page.locator('#destinations tr')).to_have_count(1)
    did=page.locator('#destinations tr td').first.inner_text()
    page.get_by_role('button',name='Rotas',exact=True).click()
    page.get_by_role('button',name='Editar destino',exact=True).click()
    page.locator('#route-group').select_option(label='QA · US-CC-ES')
    page.locator('.target-picker').first.select_option(did)
    assert page.locator('.target-url').first.get_attribute('readonly') is not None
    page.get_by_role('button',name='Salvar e aplicar',exact=True).click()
    expect(page.locator('#editor')).to_be_hidden()
    page.get_by_role('button',name='Nova rota',exact=True).click()
    page.locator('#host').fill('test.wantabrand.invalid')
    page.locator('#path').fill('/qa-reuse')
    page.locator('#route-name').fill('Shared route')
    page.locator('#route-group').select_option(label='QA · US-CC-ES')
    page.locator('#destination-picker').select_option(did)
    page.get_by_role('button',name='Salvar e aplicar',exact=True).click()
    expect(page.locator('#routes .route')).to_have_count(2)
    page.get_by_role('button',name='Destinos',exact=True).click()
    expect(page.locator('#destinations tr td').nth(4)).to_have_text('2')
    page.locator('#destination-search').fill('not-present')
    expect(page.locator('#destinations .empty')).to_be_visible()
    page.locator('#destination-search').fill('')
    page.locator('#destinations button').first.click()
    page.locator('#catalog-url').fill('https://wantabrand.com/qa-updated')
    page.once('dialog',lambda dialog:dialog.dismiss())
    page.get_by_role('button',name='Salvar destino',exact=True).click()
    expect(page.locator('#destination-editor')).to_be_visible()
    expect(page.locator('#destinations tr td').nth(3)).to_have_text('https://wantabrand.com/qa-two')
    page.once('dialog',lambda dialog:dialog.accept())
    page.get_by_role('button',name='Salvar destino',exact=True).click()
    expect(page.locator('#destination-editor')).to_be_hidden()
    expect(page.locator('#destinations tr td').nth(3)).to_have_text('https://wantabrand.com/qa-updated')
    page.reload()
    expect(page.locator('#destinations tr td').nth(3)).to_have_text('https://wantabrand.com/qa-updated')
    page.get_by_role('button',name='Rotas',exact=True).click()
    expect(page.locator('.destination')).to_have_count(3)
    assert sorted(page.locator('.destination').all_text_contents())==sorted(['https://wantabrand.com/qa-updated','30% — https://wantabrand.com/qa-updated','70% — https://wantabrand.com/qa-three'])
    page.get_by_role('button',name='Destinos',exact=True).click()
    page.locator('#destinations button').first.click()
    page.locator('#catalog-url').fill('https://wantabrand.com/qa-two')
    page.once('dialog',lambda dialog:dialog.accept())
    page.get_by_role('button',name='Salvar destino',exact=True).click()
    expect(page.locator('#destination-editor')).to_be_hidden()
    # Group rename must update membership atomically, survive reload, and reject duplicates.
    page.get_by_role('button',name='Grupos',exact=True).click()
    page.get_by_role('button',name='Editar nome',exact=True).click()
    expect(page.locator('#group-name')).to_have_value('QA · US-CC-ES')
    page.locator('#group-name').fill('QA · RENAMED')
    page.get_by_role('button',name='Salvar nome',exact=True).click()
    expect(page.locator('#groups tr td').first).to_have_text('QA · RENAMED')
    expect(page.locator('#groups tr td').nth(1)).to_have_text('2')
    expect(page.locator('#groups tr td').nth(2)).to_have_text('1')
    page.reload()
    expect(page.locator('#groups tr td').first).to_have_text('QA · RENAMED')
    page.get_by_role('button',name='Ver rotas',exact=True).click()
    expect(page.locator('#route-group-filter')).to_have_value('QA · RENAMED')
    expect(page.locator('#routes .route')).to_have_count(2)
    page.get_by_role('button',name='Destinos',exact=True).click()
    expect(page.locator('#destinations tr td').nth(2)).to_have_text('QA · RENAMED')
    page.get_by_role('button',name='Grupos',exact=True).click()
    page.get_by_role('button',name='Editar nome',exact=True).click()
    page.locator('#group-name').fill('QA · CANCELLED')
    page.get_by_role('button',name='Cancelar edição',exact=True).click()
    expect(page.locator('#groups tr td').first).to_have_text('QA · RENAMED')
    page.locator('#group-name').fill('QA · OTHER')
    page.get_by_role('button',name='Criar grupo',exact=True).click()
    expect(page.locator('#groups tr')).to_have_count(2)
    renamed=page.locator('#groups tr').filter(has_text='QA · RENAMED')
    renamed.get_by_role('button',name='Editar nome',exact=True).click()
    page.locator('#group-name').fill('QA · OTHER')
    page.get_by_role('button',name='Salvar nome',exact=True).click()
    expect(page.locator('#message')).to_contain_text('Já existe um grupo')
    expect(page.locator('#groups tr')).to_have_count(2)
    page.get_by_role('button',name='Cancelar edição',exact=True).click()
    for view in ['Rotas','Destinos','Grupos','Cadastro domínios']:
        page.get_by_role('button',name=view,exact=True).click()
        page.set_viewport_size({'width':390,'height':844})
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
        page.set_viewport_size({'width':1280,'height':850})
    page.get_by_role('button',name='Sair',exact=True).click()
    page.wait_for_url('**/login')
    assert page.get_by_role('button',name='Entrar',exact=True).is_visible()
    assert not errors,errors
    browser.close()
print(json.dumps({'browser':'chromium','create_route':True,'edit_destination':True,'filter':True,'mobile_no_horizontal_overflow':True,'logout':True,'javascript_errors':0}))
