import pathlib,json,hashlib,datetime,fcntl,os,subprocess,re,urllib.request
R=pathlib.Path('/root/mgs-agent');W=pathlib.Path(__file__).parent;ident='finance-cleanup-executed-1552362272725401693';now=datetime.datetime.now(datetime.timezone.utc).isoformat();d=json.loads((W/'deletion-result.json').read_text());s=json.loads((W/'smoke-result.json').read_text());assert d['status']=='filesystem_completed_validated' and s['pass'] and d['deleted_count']==270 and len(d['deleted'])==270;assert all(not os.path.lexists(x) for x in d['deleted']);assert not (W/'closure-result.json').exists()
a=subprocess.run(['bash',str(R/'scripts/send-report-infra-embed.sh'),'--action','removida','--type','cleanup/test-data/audit','--path','apps/finance-system/private:270alvos do manifesto c50e6d99faedbc4fa6709397a02c55f6fe28fd4949feb208858697b5f7616621','--reason','Confirmacao critica Rodolfo1552362272725401693. Limpeza estrita de residuos de testes.','--evidence','184529arquivos;55.57GB efetivos liberados;disco82.15% para55.30%;355hashes e9amostras iguais;13stages preservados;fingerprintsprod identicos;APIhealth e browser desktop/mobileOK;zeroPOSTfinanceiro;sem restart.'],capture_output=True,text=True,timeout=60);assert a.returncode==0;match=re.search(r'message_id=(\d+)',a.stdout);assert match is not None;mid=match.group(1)
token=next(l.split('=',1)[1].strip().strip('\"').strip("'") for l in pathlib.Path('/root/.hermes/profiles/zeus/.env').read_text().splitlines() if l.startswith('DISCORD_BOT_TOKEN='))
req=urllib.request.Request(f'https://discord.com/api/v10/channels/1498132022634483894/messages/{mid}',headers={'Authorization':'Bot '+token,'User-Agent':'MGS/1.0'})
with urllib.request.urlopen(req,timeout=20) as response:msg=json.load(response)
assert not msg['content'] and len(msg['embeds'])==1 and not msg.get('mentions')
result={**d,'status':'completed_validated','smoke':s,'report_infra_message_id':mid,'report_infra_readback':True,'governance_errors':[],'closed_at':now};p=W/'closure-result.json';p.write_text(json.dumps(result,indent=2));h=hashlib.sha256(p.read_bytes()).hexdigest();(W/'closure-result.sha256').write_text(h+'  '+p.name+'\n');subprocess.run(['sha256sum','-c','closure-result.sha256'],cwd=W,check=True)
receipt={'id':ident,'type':'finance-cleanup-execution','authority':'1552362272725401693','status':'completed_validated','updated_at':now,'manifest_sha256':d['manifest_sha256'],'path':str(p),'sha256':h,'report_path':'reports/'+ident+'.md','report_infra_message_id':mid,'deleted_count':270,'observed_reclaimed_bytes':d['observed_reclaimed_bytes'],'financial_writes':0,'protected_unchanged':True}
with (R/'data/infra-inventory.json').open('r+') as f:
 fcntl.flock(f,fcntl.LOCK_EX);inv=json.load(f)
 for item in inv['runtime_artifacts']:
  if item.get('id')=='finance-cleanup-manifest-1552361649480933457':item.update(status='executed_validated',deleted=270,confirmation='1552362272725401693',result_path=str(p),result_sha256=h,updated_at=now)
  if item.get('id')=='finance-cleanup-audit-1552356639850373301':item.update(status='analysis_followed_by_confirmed_execution',execution_report=receipt['report_path'],updated_at=now)
 inv['runtime_artifacts']=[x for x in inv['runtime_artifacts'] if x.get('id')!=ident]+[receipt];inv['_meta']['updated_at']=now;f.seek(0);json.dump(inv,f,ensure_ascii=False,indent=2);f.write('\n');f.truncate();f.flush();os.fsync(f.fileno())
e={'timestamp':now,'agent':'zeus','action':'finance_cleanup_final_receipt','confirmation_message_id':'1552362272725401693','artifact_id':ident,'result_sha256':h,'report_infra_message_id':mid,'status':'completed_validated'}
with (R/'logs/events-audit.jsonl').open('a') as f:fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps(e)+'\n');f.flush();os.fsync(f.fileno())
assert next(x for x in json.loads((R/'data/infra-inventory.json').read_text())['runtime_artifacts'] if x.get('id')==ident)==receipt;assert e in [json.loads(x) for x in (R/'logs/events-audit.jsonl').read_text().splitlines()[-15:]];assert hashlib.sha256(p.read_bytes()).hexdigest()==h;assert json.loads(p.read_text())['report_infra_readback'];print(json.dumps({'closure':'completed_validated','inventory_audit_readback':True,'report_infra_readback':True,'message_id':mid,'result_sha256':h}))
