"""Verify account ownership artifacts, persist inventory/audit, send one canonical embed and read back."""
import pathlib,json,hashlib,datetime,fcntl,os,subprocess,re,sys,urllib.request
M=pathlib.Path('/root/mgs-agent');R=M/'apps/finance-system';D=R/'private/account-managers-1547052028663169105';K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard');ID='zeus-finance-account-managers-1547052028663169105';AUTH='1547052028663169105';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def read(p):return json.loads(pathlib.Path(p).read_text())
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
prod=read(D/'production.json');ui=read(D/'browser.json');published=read(D/'published.json');plan=read(D/'plan.json');assert prod['pass'] and prod['readback'] and prod['idempotent'] and prod['unrelated_state_unchanged'] and prod['duplicate_accounts']==0 and prod['exceptions']==[];assert len(prod['accounts'])==len(plan['accounts'])==9;assert ui['pass'] and ui['views']==8 and len(ui['managers'])==5 and ui['js_errors']==[];assert published['services']==['active']*3
log=(D/'node-complete.log').read_text();assert '# tests 88' in log and '# pass 88' in log and '# fail 0' in log
run=subprocess.run(['python3','-m','unittest','discover','-s','tests','-p','test_account_manager_costs.py'],capture_output=True,text=True,cwd=R);assert run.returncode==0;(D/'python-tests.log').write_text(run.stdout+run.stderr)
for f,h in published['files'].items():assert sha(R/f)==h
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,str(R/'deploy'));from runcloud_ops import ssh
remote=json.loads(ssh('sudo -n python3 -c '+__import__('shlex').quote('import pathlib,hashlib,json;r=pathlib.Path("/home/mgsfinance/releases/pg-auth-1545934831664242748");print(json.dumps({f:hashlib.sha256((r/f).read_bytes()).hexdigest() for f in '+repr(list(published['files']))+'}))')));assert remote==published['files']
contract=read(M/'data/finance-media-spend-contract.json');cron=subprocess.check_output(['crontab','-l'],text=True);assert contract['cron'] in cron and cron.count('finance_media_spend_sync.py')==1
registry=read(M/'data/knowledge-registry.json');assert len([x for x in registry['entries'] if x['canonical_key']=='finance.account-site-manager-ownership' and x['status']=='active'])==1
assert 'G001' in (K/'references/account-manager-bindings.md').read_text() and '1547052028663169105' in (M/'docs/finance-account-ownership.md').read_text()
names=list(published['files'])+['deploy/account-assignment-release.py','deploy/account-assignment-finalize.py','tests/account-manager-bindings.test.mjs','tests/test_account_manager_costs.py','tests/account-manager-public.mjs'];paths=[R/f for f in names]+[M/'docs/finance-account-ownership.md',M/'docs/finance-system-product-direction.md',M/'docs/finance-decisions-2026-09-08.md',M/'data/finance-media-spend-contract.json',M/'data/knowledge-registry.json',M/'data/agent-checkpoints.json',K/'SKILL.md',K/'references/account-manager-bindings.md',K/'references/api-first-site-daily-spend.md'];manifest=[{'path':str(p),'sha256':sha(p),'size_bytes':p.stat().st_size} for p in paths]
summary={'pass':True,'accounts':len(plan['accounts']),'verified_account_days':sum(7 for a in plan['accounts']),'sites':4,'browser_views':ui['views'],'manager_views':len(ui['managers']),'node_tests':88,'python_tests':3,'changed_financial_fields':prod['changed_fields'],'duplicates':0,'exceptions':[],'idempotent':True,'other_periods_users_payments_preserved':True,'cron_unchanged':True,'remote_code_hashes':True,'source':'docs/finance-account-ownership.md','backup_remote':published['backup'],'inventory_paths':len(manifest)}
record={'id':ID,'agent':'zeus','type':'finance_account_site_manager_bindings','authorization_message_id':AUTH,'source_message_id':'1547048317853114438','source_thread_id':'1545426987756298340','updated_at':now,'paths':manifest,'summary':summary,'evidence_directory':str(D),'backup_remote':published['backup'],'backup_local':[str(D/'backup-code.tar.gz'),str(D/'backup-data.dump')],'report_infra_pending':True}
p=M/'data/infra-inventory.json'
def inventory_update(report=None):
 with (M/'data/.infra-inventory.lock').open('a') as lock:
  fcntl.flock(lock,fcntl.LOCK_EX);data=read(p);items=data.setdefault('runtime_artifacts',[]);rows=[x for x in items if x.get('id')==ID]
  if rows:rows[0].update(record if report is None else {'report_infra_pending':False,'report_infra':report})
  else:assert report is None;items.append(record)
  tmp=p.with_suffix('.account-manager-pending');tmp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');tmp.chmod(p.stat().st_mode&0o777);os.replace(tmp,p);assert len([x for x in read(p)['runtime_artifacts'] if x.get('id')==ID])==1
inventory_update();(D/'manifest.json').write_text(json.dumps(manifest,indent=2))
if not (D/'report-send.log').exists():
 result=subprocess.run([str(M/'scripts/send-report-infra-embed.sh'),'--action','modificada','--type','finance-app/data/skill/continuidade','--path','apps/finance-system; docs/finance-account-ownership.md; finance-media-spend-contract; skill mgs-finance-dashboard','--reason','Rodolfo1547052028663169105 confirmou gestores G001-G006 e nove vínculos: Vizioid/MGS, Yolokfx por gestor, Mattei1 GameZoneAd, Infinitynexx Joe titular e G001 Ícaro.','--evidence','9cadastros/63conta-dia relidos;14campos pendentes preenchidos;zero duplicata/replay sem alteração;88Node+3Python;4sites/8visões/5gestores;backup dual hash+restore;histórico/acessos/pagamentos/cron preservados;sem escrita Meta/Google/Sheets.'],capture_output=True,text=True,timeout=90);(D/'report-send.log').write_text(result.stdout+result.stderr);assert result.returncode==0
match=re.search(r'message_id=(\d+)',(D/'report-send.log').read_text());assert match;mid=match[1]
# Token stays in memory; exact target GET verifies empty content/single embed/no mention/no thread.
sys.path.insert(0,str(R));import importlib.util
spec=importlib.util.spec_from_file_location('finance_notices',R/'finance-notifications.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod);token=mod.dotenv_values('/root/.hermes/profiles/zeus/.env')['DISCORD_BOT_TOKEN'];request=urllib.request.Request('https://discord.com/api/v10/channels/1498132022634483894/messages/'+mid,headers={'Authorization':'Bot '+token,'User-Agent':'MGS-Finance-Infra/1.0'})
with urllib.request.urlopen(request,timeout=20) as response:message=json.load(response)
assert message['id']==mid and message['channel_id']=='1498132022634483894' and message['content']=='' and len(message['embeds'])==1 and not message.get('mentions') and not message.get('mention_roles') and not message.get('mention_everyone') and not message.get('thread');assert AUTH in json.dumps(message['embeds']);report={'message_id':mid,'channel_id':message['channel_id'],'readback':True,'empty_content':True,'embeds':1,'mentions':0};inventory_update(report);summary['report_infra']=report;(D/'final-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2))
with (M/'logs/events-audit.jsonl').open('a') as f:f.write(json.dumps({'ts':now,'actor':'zeus','action':'finance_account_site_manager_assignments_verified','authorization':AUTH,'source':'1547048317853114438','thread_id':'1545426987756298340','artifact_id':ID,'summary':summary},ensure_ascii=False)+'\n')
print(json.dumps(summary,ensure_ascii=False))
