"""Install only the requested finance schedule after global eight-day preflight."""
import pathlib,json,subprocess,time,hashlib,os
ROOT=pathlib.Path(__file__).resolve().parents[1];D=ROOT/'private/spend-import-1546991137171181578';proof=D/'schedule-preflight.json';c=json.loads(proof.read_text());assert c['pass'] and c['civil_dates']==8 and not c['operational_conflicts'] and time.time()-proof.stat().st_mtime<600
before=subprocess.check_output(['crontab','-l'],text=True);assert 'finance_media_spend_sync.py' not in before;backup=D/'root-crontab-before.txt';backup.write_text(before);os.chmod(backup,0o600)
script=ROOT/'finance_media_spend_sync.py';log=pathlib.Path('/root/mgs-agent/logs/finance-media-spend.log');log.touch(exist_ok=True)
line=c['schedule']+" /usr/bin/flock -n /var/lock/mgs-finance-media-spend.cron.lock /bin/sh -c '/bin/sleep 25; /usr/bin/timeout 900s /usr/bin/python3 "+str(script)+" --scheduled >> "+str(log)+" 2>&1'"
text=before.rstrip()+"\n\n# MGS finance daily ad-spend; authorization1546991137171181578; Eastern; global8-day preflight\n"+line+'\n';subprocess.run(['crontab','-'],input=text,text=True,check=True);actual=subprocess.check_output(['crontab','-l'],text=True);assert actual==text and actual.count(str(script))==1
contract={'id':'finance-daily-ad-spend','authorization':'1546991137171181578','thread_id':'1545426987756298340','schedule':c['schedule'],'timezone':'America/New_York','stagger_seconds':25,'window':'month of yesterday: day1 through yesterday, account-native calendar dates','minimum_period':'2026-09','registered_accounts_only':True,'unregistered_discovery_report_only':True,'no_automatic_registration_or_allocation':True,'cron':line,'state':'/root/mgs-agent/data/finance-media-spend-state.json','script':str(script),'log':str(log),'preflight':str(proof),'crontab_sha256':hashlib.sha256(actual.encode()).hexdigest(),'backup':str(backup),'readback':True}
p=pathlib.Path('/root/mgs-agent/data/finance-media-spend-contract.json');p.write_text(json.dumps(contract,ensure_ascii=False,indent=2));assert json.loads(p.read_text())==contract;(D/'schedule-installed.json').write_text(json.dumps(contract,ensure_ascii=False,indent=2));print(json.dumps({'pass':True,'schedule':c['schedule'],'timezone':contract['timezone'],'unique_entry':True,'other_entries_preserved':True,'contract':str(p)}))
