"""Record verified finance UI artifacts without replacing unrelated inventory entries."""
import pathlib,json,datetime,hashlib,fcntl,os,subprocess,sys
ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';STATE=APP/'private/ui-redesign-1546005809845243944';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
checks={name:json.loads((STATE/name).read_text()) for name in ['api-evidence.json','local-browser-evidence.json','public-browser-evidence.json','native-pg-evidence.json','deploy-evidence.json','cron-tests.json','schedule-preflight.json']}
assert all(v['pass'] for k,v in checks.items() if 'pass' in v);assert not checks['schedule-preflight.json']['operational_conflicts']
j=json.loads(pathlib.Path('/root/.hermes/profiles/zeus/cron/jobs.json').read_text());jobs=j if isinstance(j,list) else j['jobs'];job=next(x for x in jobs if x['id']=='685397627b29');assert job['enabled'] and job['schedule']['expr']=='26,56 * * * *' and job['script']=='mgs-finance-quotes.py' and job['no_agent'];assert job['last_status']=='ok'
sync=json.loads((APP/'private/quote-sync-state.json').read_text());assert sync['ok']
entry={'id':'zeus-finance-ui-1546005809845243944','agent':'zeus','type':'financial_application_ui_and_quote_lifecycle','owner':'Rodolfo / Zeus','authorization_message_id':'1546005809845243944','thread_id':'1545426987756298340','status':'published_and_validated_full_product_migration_open','updated_at':now,'canonical_source':str(ROOT/'docs/finance-system-product-direction.md'),'report_path':str(ROOT/'reports/finance-ui-redesign-1546005809845243944.md'),'evidence_path':str(STATE),'runtime':{'host':'MatteiInc01','url':'https://dash.mgsdigitalcorp.com','release':'/home/mgsfinance/releases/pg-auth-1545934831664242748','service':'mgs-finance-dash','database':'mgs_finance','auth_user':'rodolfo','credential_changes':0,'system_config_writes':0},'cron':{'id':job['id'],'profile':'zeus','schedule':job['schedule']['expr'],'stagger_seconds':25,'script':'mgs-finance-quotes.py','no_agent':True,'deliver':'discord:1498132022634483894','last_status':job['last_status'],'last_run_at':job.get('last_run_at')},'tests':{'python':20,'node':5,'browser_views':6,'viewports':[390,768,1440],'js_errors':0,'native_pg_restore':True,'baseline_cells':85868,'public_test_financial_writes':0},'preserved':['Google Sheets','source baseline','credentials','permissions','/etc','gateway','unrelated sites/services'],'retained_artifacts':{'remote_backup':'/home/zeus/mgs-finance-backups/1546005809845243944','isolated_database':'mgs_finance_ui_1546005809845243944','local_test_artifacts':str(STATE),'deletion_performed':False},'skill':'mgs-finance-dashboard@0.1.17','remaining':['GAM report importers','Facebook/Google spend importers','full native master-data and period lifecycle','official Sheet cutover']}
paths=[APP/'sync-quotes.py',APP/'cron-quotes.py',APP/'apply-live-quotes.mjs',APP/'workspace.mjs',APP/'ui_model.py',pathlib.Path('/root/.hermes/profiles/zeus/scripts/mgs-finance-quotes.py')]
invpath=ROOT/'data/infra-inventory.json'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);inv=json.loads(invpath.read_text());inv['runtime_artifacts']=[x for x in inv.get('runtime_artifacts',[]) if x.get('id')!=entry['id']]+[entry]
 for p in paths:
  stat=p.stat();meta={'path':str(p),'size_bytes':stat.st_size,'modified_at':datetime.datetime.fromtimestamp(stat.st_mtime,datetime.timezone.utc).isoformat(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'description':'Finance UI/quote lifecycle; authorization 1546005809845243944'}
  inv['scripts']=[x for x in inv['scripts'] if x.get('path')!=str(p)]+[meta]
 ce={'entry':'Hermes zeus 685397627b29: 26,56 * * * * +25s -> mgs-finance-quotes.py','job_id':'685397627b29','description':'Google SA read-only FX sync; fixed rates protected; isolated financial workspace'}
 inv['crons']=[x for x in inv['crons'] if x.get('job_id')!='685397627b29']+[ce]
 inv['_meta']['updated_at']=now
 temp=invpath.with_suffix('.ui-update.tmp')
 with temp.open('w') as out:json.dump(inv,out,ensure_ascii=False,indent=2);out.flush();os.fsync(out.fileno())
 os.replace(temp,invpath);read=json.loads(invpath.read_text());assert next(x for x in read['runtime_artifacts'] if x.get('id')==entry['id'])==entry
with (ROOT/'logs/events-audit.jsonl').open('a') as f:f.write(json.dumps({'timestamp':now,'agent':'zeus','event':'finance_ui_redesign_validated','authorization':'1546005809845243944','entry':entry,'schedule_baselines':checks['schedule-preflight.json']['baseline_collisions']},ensure_ascii=False)+'\n')
summary={'pass':True,'inventory_id':entry['id'],'cron_readback':entry['cron'],'checks':{k:v.get('pass',not v.get('operational_conflicts')) for k,v in checks.items()},'source_writes':0,'native_migration_complete':False,'report':entry['report_path']}
(STATE/'final-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2));print(json.dumps(summary,ensure_ascii=False))
