"""Inventory/readback for approved finance operations and Nicolas-only pilot."""
import pathlib,json,datetime,hashlib,fcntl,os,subprocess
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';AUTH='1546642267291394199';S=A/('private/payments-'+AUTH);K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard')
checks={n:json.loads((S/n).read_text()) for n in ['prepared.json','pg-exercise.json','published.json','deploy-readback.json','public-browser.json','notification-canary.json']}
assert all(checks[n]['pass'] for n in checks if n!='notification-canary.json');assert checks['notification-canary.json']['readback'];ui=checks['public-browser.json'];assert ui['periods']==17 and ui['expense_rows']==44 and ui['nicolas_blocks']==8 and ui['no_extra_users'] and ui['js_errors']==0;assert 'Ran 40 tests' in (S/'python-tests.log').read_text() and '# pass 34' in (S/'node-tests.log').read_text();assert 'version: 0.1.25' in (K/'SKILL.md').read_text();assert subprocess.check_output(['systemctl','is-active','mgs-finance-meta-lookup.service'],text=True).strip()=='active'
files=['server.mjs','auth.mjs','finance-ops.mjs','finance-ops-schema.sql','manager-view.mjs','manager-layout.json','public/app.js','public/index.html','public/refinements.css','public/financial-summary.js','public/operations.js','public/operations.html','public/operations.css','finance-notifications.py','meta-lookup-worker.py','deploy/finance-notices.mjs','deploy/payments-release.py','deploy/payments-ui-polish.py','deploy/record-payments-inventory.py','tests/payments-inspect.py','tests/financial-summary.test.mjs','tests/finance-ops.test.mjs','tests/payments-pg.mjs','tests/reset-payments-stage.mjs','tests/payments-browser.mjs','tests/run-payments-public.py','tests/ui-country-blocks.test.mjs','tests/ui-layout.test.mjs','tests/ui-review.test.mjs']
paths=[A/f for f in files]+[R/'docs/finance-system-product-direction.md',R/('reports/finance-payments-'+AUTH+'.md'),K/'SKILL.md',K/'references/payments-approvals-nicolas-pilot.md'];assert len(paths)==len(set(paths));now=datetime.datetime.now(datetime.timezone.utc).isoformat();service=json.loads((A/'private/meta-lookup-worker-state.json').read_text());assert service['ok'] and service.get('notifications',{}).get('ok');(S/'service-readback.json').write_text(json.dumps(service,indent=2))
entry={'id':'zeus-finance-payments-'+AUTH,'agent':'zeus','type':'finance_operations_approvals_nicolas_pilot','authorization_message_ids':[AUTH,'1546642892427366510','1546643762686730382','1546645188523331624','1546645785729572895'],'thread_id':'1545426987756298340','status':'published_verified_nicolas_pilot_awaiting_owner_review','updated_at':now,'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-payments-'+AUTH+'.md','evidence_path':str(S),'authorization_scope':{'native_app_only':True,'owner':'rodolfo','partner':'read_and_propose_owner_approval_required','manager_pilot':'nicolas','activity_owner_only':True,'real_users_created':0,'credential_changes':0,'transfers':0},'service':{'unit':'mgs-finance-meta-lookup.service','active':True,'new_unit':False,'new_cron':False,'meta_writes':0,'notifications':'Discord + in-app, isolated failures','canary_message_id':checks['notification-canary.json']['message_id']},'tests':{'python':40,'node':34,'periods':17,'expense_rows':44,'expense_height_max_px':ui['max_expense_height'],'manager_blocks':8,'manager_api_denials':10,'js_errors':0,'restore_api':True,'public_browser':True,'production_financial_test_writes':0,'sheet_writes':0},'retained_artifacts':{'remote_backup':'/home/zeus/mgs-finance-backups/'+AUTH,'stage':'/var/tmp/mgs-finance-payments-'+AUTH,'database':'mgs_finance_payments_'+AUTH,'backup_hashes':checks['prepared.json']['backup'],'worker_before':str(S/'meta-worker-before.py')},'limits':['Nicolas pilot only; no replication before Rodolfo OK','No actual payment or automatic legacy ok migration without payment data','Existing native/trial migration remains separate initiative'],'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}
p=R/'data/infra-inventory.json'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);d=json.loads(p.read_text());items=d.setdefault('runtime_artifacts',[]);idx=next((i for i,v in enumerate(items) if v.get('id')==entry['id']),None)
 if idx is None:items.append(entry)
 else:items[idx]=entry
 scripts=d.setdefault('scripts',[])
 for f in paths:
  if f.suffix not in ['.py','.js','.mjs']:continue
  row={'path':str(f),'size_bytes':f.stat().st_size,'sha256':entry['files'][str(f)],'modified_at':datetime.datetime.fromtimestamp(f.stat().st_mtime,datetime.timezone.utc).isoformat(),'description':'Finance operations/Nicolas pilot '+AUTH};idx=next((i for i,x in enumerate(scripts) if x.get('path')==str(f)),None)
  if idx is None:scripts.append(row)
  else:scripts[idx]=row
 d['_meta']['updated_at']=now;t=p.with_suffix('.payments-update.tmp')
 with t.open('w') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
 os.replace(t,p);fd=os.open(p.parent,os.O_DIRECTORY);os.fsync(fd);os.close(fd);assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])==entry
with (R/'logs/events-audit.jsonl').open('a') as f:
 fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps({'timestamp':now,'agent':'zeus','event':'finance_payments_access_pilot_validated','authorization_message_ids':entry['authorization_message_ids'],'authorization_scope':entry['authorization_scope'],'inventory_id':entry['id'],'report':entry['report_path'],'tests':entry['tests'],'production_financial_mutations':0})+'\n');f.flush();os.fsync(f.fileno())
out={'pass':True,'inventory_readback':True,'skill_readback':'0.1.25','files':len(paths),'inventory_id':entry['id'],'tests':entry['tests'],'notification_readback':checks['notification-canary.json']['message_id']};(S/'final-evidence.json').write_text(json.dumps(out,indent=2));print(json.dumps(out))
