"""Inventory, audit and direct REPORT-INFRA with exact remote readback."""
import pathlib,json,os,hashlib,datetime,fcntl,subprocess,urllib.request,importlib.util
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';D=A/'private/manager-access-1546858367635685396';K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard');marker='FINANCE-MANAGERS-1546858367635685396'
files=[A/f for f in ['manager-view.mjs','manager-layouts.json','finance-ops.mjs','finance-ops-schema.sql','public/operations.js','public/navigation.js','deploy/manager-access-prepare.py','deploy/manager-access-release.py','deploy/manager-access-schema.py','deploy/manager-access-migration.sql','deploy/manager-access-create.py','deploy/record-manager-access-inventory.py','tests/manager-access-pg.mjs','tests/manager-access-public.mjs','tests/cash-carry-diagnosis.py','tests/closed-roi-repair.py','tests/july-salary-restore.py']]+[R/'context/team.md',R/'docs/finance-system-product-direction.md',R/'reports/finance-manager-access-1546858367635685396.md',K/'SKILL.md',K/'references/closed-history-jan-jul-feasibility.md',K/'references/manager-access-and-history-dispositions.md']
required=['prepared.json','pg-exercise.json','local-tests.json','published.json','schema-mgs_finance.json','schema-file.json','public-readback.json','deploy-readback.json','april-readback.json','roi-apply-readback.json','july-salary-readback.json','dash-salary-carry-readback.json'];proof={n:json.loads((D/n).read_text()) for n in required};assert all(v['pass'] for v in proof.values());users=json.loads((D/'users-created.json').read_text());assert len(users)==4 and {u['username'] for u in users}=={'joe','isliago','kelly','icaro'} and all(u['pass'] and u['enabled'] for u in users);assert proof['public-readback.json']['denials']==70;assert proof['roi-apply-readback.json']['changed_cells']==280;assert proof['july-salary-readback.json']['july_salary_brl']==1500
for u in users:assert json.loads((D/(u['username']+'-1password.json')).read_text())['readback']
now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':marker.lower(),'agent':'zeus','authorization_message_ids':['1546858367635685396','1546866505663254599'],'thread_id':'1545426987756298340','status':'access_and_sheet_corrections_verified_history_import_pending','updated_at':now,'type':'finance_manager_access_and_closed_history_dispositions','evidence_path':str(D),'backup_remote':'/home/zeus/mgs-finance-backups/1546858367635685396','isolated_database':'mgs_finance_managers_1546858367635685396','stage':'/var/tmp/mgs-finance-managers-1546858367635685396','scope':{'new_users':[u['username'] for u in users],'public_manager_logins':5,'node_tests':52,'stage_workspaces':85,'stage_values':396270,'stage_denials':100,'public_denials':70,'roi_changed_cells':280,'numeric_cells_preserved':33165,'july_salary_cell':'Julho 2026!O156','july_salary_brl':1500,'august_salary_brl':3000,'sheet_carry_restored':True,'history_imported':False,'august_opening_still_fixed':True,'gateway_restart':False,'dash_restart':True},'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);p=R/'data/infra-inventory.json';data=json.loads(p.read_text());items=data.setdefault('runtime_artifacts',[]);existing=next((x for x in items if x.get('id')==entry['id']),None)
 if existing:assert existing['files']==entry['files'],'Concurrent inventory differs'
 else:
  items.append(entry);data['_meta']['updated_at']=now;t=p.with_suffix('.manager-access.tmp')
  with t.open('w') as f:json.dump(data,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
  os.replace(t,p)
 assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])['files']==entry['files']
spec=importlib.util.spec_from_file_location('notice',A/'finance-notifications.py');assert spec and spec.loader;m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);token=m.dotenv_values('/root/.hermes/profiles/zeus/.env')['DISCORD_BOT_TOKEN'];headers={'Authorization':'Bot '+token,'User-Agent':'MGS-Readback'};base='https://discord.com/api/v10/channels/1498132022634483894/messages'
def get(url):return json.load(urllib.request.urlopen(urllib.request.Request(url,headers=headers),timeout=25))
def matches():return [d for d in get(base+'?limit=50') if marker in json.dumps(d.get('embeds',[]))]
found=matches()
if not found:
 env=dict(os.environ);env['MGS_DISCORD_BOT_TOKEN_OVERRIDE']=token;env.pop('MGS_DISCORD_API_URL_OVERRIDE',None)
 result=subprocess.run([str(R/'scripts/send-report-infra-embed.sh'),'--action','modificada','--type','finance-manager-access','--path','Finance app/access/1Password4users;Jan/Feb280ROI;JulhoO156;team/skill/registry','--reason',marker+': Rodolfo confirmou quatro acessos e George=Ícaro; resolveu ressalvas e restaurou Jislaine julho1500, agosto3000.','--evidence','52NodePASS;restore85visoes/396270valores/100negativas;5loginsreais/70APIs403/20checks/0JS;4cofresreadback.280ROIguardados,33165númerosiguais. JulhoO156−1500/saldos0.71readback, agosto3000. Backupduplo/hash/restore. HistóricoJan-Jul e vínculo abertura interno pendentes; acessoBot/gatewaypreservados.'],env=env,text=True,capture_output=True,timeout=75)
 assert result.returncode==0,'Helper failed: reconcile readback before retry';found=matches()
assert len(found)==1;message=get(base+'/'+found[0]['id']);assert message['content']=='' and len(message['embeds'])==1 and not message.get('mentions')
out={'pass':True,'inventory_readback':True,'report_message_id':message['id'],'report_readback':True,'files':len(files),'new_users':4,'roi_cells':280,'july_salary_restored':True,'history_import_pending':True};(D/'final-readback.json').write_text(json.dumps(out,indent=2))
with (R/'logs/events-audit.jsonl').open('a') as f:
 fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps({'timestamp':now,'event':'finance_manager_access_and_closed_history_corrections','agent':'zeus','authorization_message_ids':entry['authorization_message_ids'],'scope':entry['scope'],**out})+'\n');f.flush();os.fsync(f.fileno())
print(json.dumps(out))
