"""Record verified finance deliverables and retained recovery artifacts; no financial writes."""
import pathlib,json,datetime,hashlib,fcntl,os
ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';AUTH='1546579646227943506';STATE=APP/('private/networks-'+AUTH)
checks={n:json.loads((STATE/n).read_text()) for n in ['local-migration.json','local-integration.json','local-browser.json','public-browser.json','pg-exercise.json','production-readback.json','deploy-evidence.json','sheets-repair-readback.json','final-financial-parity.json']}
assert all(v.get('pass',v.get('pass_daily_values',False)) for v in checks.values());assert len(checks['production-readback.json']['periods'])==17
assert next(p for p in checks['public-browser.json']['periods'] if p['period']=='2026-09')['wavesbee_input_currency']=='GBP'
assert '# pass 23' in (STATE/'node-tests.log').read_text() and '# fail 0' in (STATE/'node-tests.log').read_text();assert 'Ran 36 tests' in (STATE/'python-tests.log').read_text() and '\nOK' in (STATE/'python-tests.log').read_text()
files=['workspace.mjs','accounts.mjs','worker.py','site_catalog.py','public/app.js','public/refinements.css','networks.py','networks.mjs','network-rules.json','network-migration.mjs','deploy/apply-networks.mjs','deploy/network-preflight.py','deploy/network-release.py','deploy/network-month-label.py','deploy/network-v2-release.py','deploy/record-network-inventory.py','tests/test_network_policy.py','tests/network-ui.test.mjs','tests/network-integration.mjs','tests/network-browser.mjs','tests/run-network-public.py','tests/reconcile-network-source.py','tests/repair-sheet-networks.py','tests/final-network-parity.py','tests/workspace.test.mjs']
paths=[APP/f for f in files]+[ROOT/'docs/finance-system-product-direction.md',ROOT/('reports/finance-networks-'+AUTH+'.md')]+[pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard')/f for f in ['SKILL.md','references/trial-payroll-review.md','references/monthly-networks-and-sheet-parity.md']]
now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':'zeus-finance-networks-'+AUTH,'agent':'zeus','type':'financial_application_networks_and_sheet_formulas','owner':'Rodolfo / Zeus','authorization_message_ids':[AUTH,'1546593628602900673','1546595495726547094'],'thread_id':'1545426987756298340','status':'published_verified_with_separate_september_followups','updated_at':now,'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-networks-'+AUTH+'.md','evidence_path':str(STATE),'tests':{'python':36,'node':23,'final_frontend':16,'periods':17,'sites':41,'public_browser':True,'pg_restore_readback':True,'sheet_cells':4204,'sheet_formula_changes':4202,'sheet_errors':0,'sheet_unexpected_changes':0,'daily_comparisons':28548,'daily_mismatches':0},'runtime':checks['deploy-evidence.json'],'known_gaps':['September WavesBee source CAD vs dashboard GBP requires scope confirmation','September Sheet payroll IMPORTRANGE still references August; verify manager month tabs before fixing','Two spend-bearing source labels lack safe account ID; amounts preserved/match','Parallel trial and full native migration/DR/cutover not completed'],'retained_artifacts':{'remote_backup':'/home/zeus/mgs-finance-backups/'+AUTH,'stage':'/var/tmp/mgs-finance-networks-'+AUTH,'database':'mgs_finance_networks_'+AUTH,'local_test_database':str(STATE/'isolated-pglite'),'backup_hashes':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in STATE.iterdir() if p.name in ['code-before.tar.gz','finance-before.dump','code-before-network-v2.tar.gz','finance-before-network-v2.dump','app-before-month-label.js','sheets-repair-before.json']}},'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}
p=ROOT/'data/infra-inventory.json'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);inv=json.loads(p.read_text());items=inv.setdefault('runtime_artifacts',[]);i=next((i for i,x in enumerate(items) if x.get('id')==entry['id']),None)
 if i is None:items.append(entry)
 else:items[i]=entry
 for artifact in paths:
  if artifact.suffix not in ['.py','.mjs','.js']:continue
  st=artifact.stat();meta={'path':str(artifact),'size_bytes':st.st_size,'modified_at':datetime.datetime.fromtimestamp(st.st_mtime,datetime.timezone.utc).isoformat(),'sha256':entry['files'][str(artifact)],'description':'Finance monthly networks '+AUTH};items=inv.setdefault('scripts',[]);idx=next((i for i,x in enumerate(items) if x.get('path')==str(artifact)),None)
  if idx is None:items.append(meta)
  else:items[idx]=meta
 inv['_meta']['updated_at']=now;tmp=p.with_suffix('.networks-update.tmp')
 with tmp.open('w') as f:json.dump(inv,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
 os.replace(tmp,p);assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])==entry
with (ROOT/'logs/events-audit.jsonl').open('a') as f:f.write(json.dumps({'timestamp':now,'agent':'zeus','event':'finance_networks_sheets_validated','authorizations':entry['authorization_message_ids'],'inventory_id':entry['id'],'report':entry['report_path'],'sheet_cells_updated':4204,'source_formulas_changed':4202,'production_test_financial_writes':0,'known_gaps':entry['known_gaps']},ensure_ascii=False)+'\n')
(STATE/'final-evidence.json').write_text(json.dumps({'pass':True,'inventory_readback':True,'inventory_id':entry['id'],'tests':entry['tests'],'known_gaps':entry['known_gaps'],'report':entry['report_path']},ensure_ascii=False,indent=2));print(json.dumps({'inventory_readback':True,'files':len(paths),'tests':entry['tests'],'followups':entry['known_gaps']},ensure_ascii=False))
