"""Inventory and direct canonical REPORT-INFRA with exact readback; no duplicate report."""
import pathlib,json,os,hashlib,datetime,fcntl,subprocess,urllib.request,importlib.util
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';D=A/'private/usability-1546729477319696405';K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard');marker='FINANCE-USABILITY-1546729477319696405'
files=[A/f for f in ['public/navigation.js', 'public/navigation.css', 'public/operations.js', 'public/app.js', 'manager-view.mjs', 'finance-ops.mjs', 'workspace.mjs', 'server.mjs', 'sync-quotes.py', 'google-finance-quotes.json', 'deploy/bootstrap-gbp-google-finance.py', 'deploy/usability-release.py', 'deploy/record-usability-inventory.py', 'tests/usability.test.mjs', 'tests/usability-pg.mjs', 'tests/usability-export.mjs', 'tests/usability-browser.mjs', 'tests/usability-overflow-probe.mjs', 'tests/jislaine-pg.mjs', 'tests/usability-live-changes.mjs', 'tests/nicolas-real-login.mjs']]+[R/'docs/finance-system-product-direction.md',R/'reports/finance-usability-1546729477319696405.md',K/'SKILL.md',K/'references/usability-google-finance-nicolas-jislaine.md',K/'references/manager-layout-and-total-contrast.md']
for n in ['live-browser.json','usability-deploy-readback.json','database-final-readback.json','prewrite-backup.json','nicolas-real-login.json','quote-activation.json']:assert json.loads((D/n).read_text())['pass']
live=json.loads((D/'live-browser.json').read_text());salary=json.loads((D/'salary-live-months.json').read_text());assert len(salary)==17 and len({x['period'] for x in salary})==17 and all(x['after']==3000 and x['pass'] for x in salary);assert '# fail 0' in (D/'node-tests.log').read_text();assert len(json.loads((D/'live-checks.json').read_text()))==52
now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':marker.lower(),'agent':'zeus','authorization_message_ids':['1546729477319696405'],'thread_id':'1545426987756298340','status':'published_verified','updated_at':now,'type':'finance_usability_and_authorized_data','evidence_path':str(D),'backup_remote':'/home/zeus/mgs-finance-backups/1546729477319696405','isolated_database':'mgs_finance_usability_1546729477319696405','stage':'/var/tmp/mgs-finance-usability-1546729477319696405','scope':{'frontend_backend_files':8,'owner_browser_checks':52,'forms':28,'node_tests':52,'python_tests':43,'salary_months':17,'salary_brl':3000,'nicolas_enabled':True,'critical_confirmation':'Rodolfo direct mid-turn sim after exact Nicolas activation confirmation','gbp_auto_period':'2026-08','google_quote_sheet':'1Zk-b8OoaDHrvFtuerf5IuO2jx-phVWXMYi79yqVTZX4','quote_cron_id':'685397627b29','gateway_restart':False,'dash_restart':True},'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);p=R/'data/infra-inventory.json';data=json.loads(p.read_text());items=data.setdefault('runtime_artifacts',[]);existing=next((x for x in items if x.get('id')==entry['id']),None)
 if existing:assert existing['files']==entry['files'],'Concurrent inventory differs'
 else:
  items.append(entry);data['_meta']['updated_at']=now;t=p.with_suffix('.manager-layout.tmp')
  with t.open('w') as f:json.dump(data,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
  os.replace(t,p)
 assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])['files']==entry['files']
spec=importlib.util.spec_from_file_location('notice',A/'finance-notifications.py');assert spec is not None and spec.loader is not None;m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);token=m.dotenv_values('/root/.hermes/profiles/zeus/.env')['DISCORD_BOT_TOKEN'];headers={'Authorization':'Bot '+token,'User-Agent':'MGS-Readback'};base='https://discord.com/api/v10/channels/1498132022634483894/messages'
def get(url):return json.load(urllib.request.urlopen(urllib.request.Request(url,headers=headers),timeout=25))
def matches():return [d for d in get(base+'?limit=50') if marker in json.dumps(d.get('embeds',[]))]
found=matches()
if not found:
 env=dict(os.environ);env['MGS_DISCORD_BOT_TOKEN_OVERRIDE']=token;env.pop('MGS_DISCORD_API_URL_OVERRIDE',None)
 r=subprocess.run([str(R/'scripts/send-report-infra-embed.sh'),'--action','modificada','--type','finance-usability','--path','Finance system UI/backend + Google Finance source + salario17meses + Nicolas login + skill0.1.29','--reason',marker+': nove ajustes Rodolfo; continuacoes diretas Jislaine3000todosmeses e usuarioNicolas confirmado sim.','--evidence','52Node/43Python +10targetedPASS;13secoes x4telas=52checks,28forms;Nicolas6checks/10APIs403/logout401.17salarios3000readback;demaisfuncionarios/ledger/baselinepreservados.3quotes/GBPautoagosto;cron30min. Backupduplo/hash/restores. Timeout420s reconciliado sem repetirwrites. Cofresemexporsegredos. Registry/inventario/readback.'],env=env,text=True,capture_output=True)
 assert r.returncode==0,'Helper failed: reconcile readback before retry';found=matches()
assert len(found)==1;message=get(base+'/'+found[0]['id']);assert message['content']=='' and len(message['embeds'])==1 and not message.get('mentions')
out={'pass':True,'inventory_readback':True,'report_message_id':message['id'],'report_readback':True,'files':len(files),'node_tests':52,'python_tests':43,'owner_checks':52,'salary_months':len(salary),'nicolas_verified':True};(D/'final-readback.json').write_text(json.dumps(out,indent=2))
with (R/'logs/events-audit.jsonl').open('a') as f:
 fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps({'timestamp':now,'event':'finance_usability_salary_and_nicolas_published','agent':'zeus','authorization_message_ids':entry['authorization_message_ids'],'scope':entry['scope'],**out})+'\n');f.flush();os.fsync(f.fileno())
print(json.dumps(out))
