import datetime,fcntl,hashlib,json,os,pathlib,tempfile
ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';AUTH='1555455453410885714';EVID=APP/'private'/('sms-manager-commission-note-'+AUTH)
files=['apps/finance-system/manager-view.mjs','apps/finance-system/finance-ops.mjs','apps/finance-system/public/operations.js','apps/finance-system/public/operations.css','apps/finance-system/tests/manager-current-period.test.mjs','apps/finance-system/tests/manager-layout.test.mjs','apps/finance-system/tests/finance-ops.test.mjs','apps/finance-system/deploy/sms-manager-commission-note-release.py','apps/finance-system/deploy/record-sms-manager-commission-note-inventory.py','docs/finance-system-product-direction.md','reports/finance-sms-manager-commission-note-1555455453410885714.md','profiles/zeus-skills/ops/mgs-finance-dashboard/SKILL.md','profiles/zeus-skills/ops/mgs-finance-dashboard/references/current-manager-tabs-reconciliation.md']
for f in files:
 if not (ROOT/f).is_file():raise FileNotFoundError(f)
hashes={f:hashlib.sha256((ROOT/f).read_bytes()).hexdigest() for f in files};prepared=json.loads((EVID/'prepared.json').read_text());published=json.loads((EVID/'published.json').read_text());browser=json.loads((EVID/'public-browser.json').read_text());assert prepared['pass'] and published['pass'] and published['data_unchanged'] and browser['pass'] and len(browser['checks'])==10
entry={'id':'zeus-finance-sms-manager-commission-note-'+AUTH,'agent':'zeus','type':'finance_manager_sms_commission_bridge_ui','owner':'Rodolfo / Zeus','authorization_message_id':AUTH,'thread_id':'1554520572950618173','status':'published_verified','updated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-sms-manager-commission-note-'+AUTH+'.md','evidence_path':'apps/finance-system/private/sms-manager-commission-note-'+AUTH,'files':hashes,'runtime':{'url':'https://dash.mgsdigitalcorp.com/operations?view=manager&period=2026-09','host':'MatteiInc01 / 162.55.28.178','services':published['services'],'financial_data_unchanged':True,'gateway_restarted':False},'validation':{'focused_node_tests':21,'public_checks':10,'commission_bridges_exact':10,'managers':5,'viewports':['desktop','mobile'],'overflow':0,'js_errors':0,'same_origin_failures':0},'backup':{'path':published['rollback'],'sha256':prepared['backup_sha256']},'stage':prepared['stage'],'supersedes_inventory_id':'zeus-finance-sms-manager-note-1555449010519679079'}
invp=ROOT/'data/infra-inventory.json';auditp=ROOT/'logs/events-audit.jsonl'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);inv=json.loads(invp.read_text());items=inv.setdefault('runtime_artifacts',[]);items[:]=[x for x in items if x.get('id')!=entry['id']];items.append(entry);inv['last_updated']=entry['updated_at'];fd,tmp=tempfile.mkstemp(prefix='infra-inventory-',suffix='.json',dir=invp.parent);os.close(fd);pathlib.Path(tmp).write_text(json.dumps(inv,ensure_ascii=False,indent=2)+'\n');json.loads(pathlib.Path(tmp).read_text());os.replace(tmp,invp)
with auditp.open('a') as f:f.write(json.dumps({'timestamp':entry['updated_at'],'agent':'zeus','event':'FINANCE_SMS_MANAGER_COMMISSION_NOTE_PUBLISHED','authorization':AUTH,'thread_id':entry['thread_id'],'inventory_id':entry['id'],'report_path':entry['report_path'],'data_unchanged':True,'gateway_restarted':False},ensure_ascii=False)+'\n')
rows=[x for x in json.loads(invp.read_text())['runtime_artifacts'] if x.get('id')==entry['id']];assert len(rows)==1 and rows[0]['files']==hashes
print(json.dumps({'pass':True,'inventory_id':entry['id'],'files':len(hashes),'readback':True,'audit_logged':True}))
