"""Inventory and exact readback for navigation/profile release and API preflight."""
import pathlib,json,datetime,hashlib,fcntl,os,re
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';AUTH='1546682010066489394';S=A/('private/navigation-'+AUTH);K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard')
checks={n:json.loads((S/n).read_text()) for n in ['prepared.json','pg-exercise.json','published.json','deploy-readback.json','public-browser.json','spend-preflight.json']};assert all(v['pass'] for v in checks.values());ui=checks['public-browser.json'];assert ui['js_errors']==0 and ui['no_extra_users'];assert '# pass 38' in (S/'node-tests.log').read_text() and '# fail 0' in (S/'node-tests.log').read_text();assert 'Ran 40 tests' in (S/'python-tests.log').read_text() and '\nOK' in (S/'python-tests.log').read_text();assert 'version: 0.1.26' in (K/'SKILL.md').read_text()
files=['finance-ops.mjs','finance-ops-schema.sql','public/app.js','public/index.html','public/operations.js','public/operations.html','public/navigation.js','public/navigation.css','deploy/navigation-release.py','deploy/record-navigation-inventory.py','tests/navigation-profile.test.mjs','tests/navigation-pg.mjs','tests/navigation-browser.mjs','tests/run-navigation-public.py','tests/spend-api-preflight.py','tests/july-canary-bridge.py'];paths=[A/f for f in files]+[R/'docs/finance-system-product-direction.md',R/('reports/finance-navigation-'+AUTH+'.md'),K/'SKILL.md',K/'references/navigation-profiles-media-spend.md'];assert len(paths)==len(set(paths));now=datetime.datetime.now(datetime.timezone.utc).isoformat()
entry={'id':'zeus-finance-navigation-'+AUTH,'agent':'zeus','type':'finance_navigation_profile_spend_preflight','authorization_message_ids':[AUTH,'1546685677599465513'],'thread_id':'1545426987756298340','status':'navigation_profiles_published_spend_automation_pending','updated_at':now,'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-navigation-'+AUTH+'.md','evidence_path':str(S),'scope':{'manager_pilot':'nicolas','real_users_created':0,'credentials_changed':0,'production_financial_inputs_changed':0,'sheet_writes':0,'meta_writes':0,'new_crons':0,'new_grants':0,'google_ads_api_verified':False},'tests':{'node':38,'python':40,'periods':ui['periods'],'js_errors':0,'profile_edit_readback':checks['pg-exercise.json']['profile_edit_readback'],'sidebar_browser':True,'layout':ui['layout']},'retained_artifacts':{'backup':'/home/zeus/mgs-finance-backups/'+AUTH,'stage':checks['prepared.json']['stage'],'database':checks['prepared.json']['database'],'backup_hashes':checks['prepared.json']['backup']},'limits':['Spend API collector/scheduler not activated','Timezone for 7am pending','Google Ads developer token/SA access pending','July screenshots are comparison evidence only; manual last-day shortcut is not a system rule','Rodolfo bootstrap protected; manager rollout pending pilot approval'],'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}
p=R/'data/infra-inventory.json'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);d=json.loads(p.read_text());items=d.setdefault('runtime_artifacts',[]);idx=next((i for i,v in enumerate(items) if v.get('id')==entry['id']),None)
 if idx is None:items.append(entry)
 else:items[idx]=entry
 scripts=d.setdefault('scripts',[])
 for f in paths:
  if f.suffix not in ['.py','.js','.mjs']:continue
  row={'path':str(f),'size_bytes':f.stat().st_size,'sha256':entry['files'][str(f)],'modified_at':datetime.datetime.fromtimestamp(f.stat().st_mtime,datetime.timezone.utc).isoformat(),'description':'Finance navigation/profile '+AUTH};idx=next((i for i,x in enumerate(scripts) if x.get('path')==str(f)),None)
  if idx is None:scripts.append(row)
  else:scripts[idx]=row
 d['_meta']['updated_at']=now;t=p.with_suffix('.navigation-update.tmp')
 with t.open('w') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
 os.replace(t,p);fd=os.open(p.parent,os.O_DIRECTORY);os.fsync(fd);os.close(fd);assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])==entry
with (R/'logs/events-audit.jsonl').open('a') as f:
 fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps({'timestamp':now,'agent':'zeus','event':'finance_navigation_profiles_validated','authorization_message_ids':entry['authorization_message_ids'],'scope':entry['scope'],'inventory_id':entry['id'],'report':entry['report_path'],'tests':entry['tests']})+'\n');f.flush();os.fsync(f.fileno())
out={'pass':True,'inventory_readback':True,'skill_readback':'0.1.26','files':len(paths),'inventory_id':entry['id'],'tests':entry['tests']};(S/'final-evidence.json').write_text(json.dumps(out,indent=2));print(json.dumps(out))
