import datetime,fcntl,hashlib,json,os,pathlib,tempfile
ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';AUTH='1555422806940983327';EVID=APP/'private'/('sms-direct-'+AUTH)
files=[
 'apps/finance-system/worker.py','apps/finance-system/direct_costs.py','apps/finance-system/monthly-review.mjs','apps/finance-system/simple-review.mjs','apps/finance-system/period-preview.mjs','apps/finance-system/sms-direct-cost-cli.mjs','apps/finance-system/workspace.mjs','apps/finance-system/public/app.js','apps/finance-system/tests/test_direct_costs.py','apps/finance-system/tests/monthly-review.test.mjs','apps/finance-system/tests/ui-review.test.mjs','apps/finance-system/deploy/sms-direct-cost-release.py','apps/finance-system/deploy/sms-direct-ui-release.py','apps/finance-system/deploy/record-sms-direct-inventory.py','docs/finance-system-product-direction.md','reports/finance-sms-direct-cost-1555422806940983327.md','profiles/zeus-skills/ops/mgs-finance-dashboard/SKILL.md','profiles/zeus-skills/ops/mgs-finance-dashboard/references/prepaid-direct-cost-reclassification.md'
]
for f in files:
 if not (ROOT/f).is_file():raise FileNotFoundError(f)
hashes={f:hashlib.sha256((ROOT/f).read_bytes()).hexdigest() for f in files}
prepared=json.loads((EVID/'prepared.json').read_text());runtime=json.loads((EVID/'final-runtime.json').read_text());browser=json.loads((EVID/'public-browser.json').read_text());history=json.loads((EVID/'history-refresh-production.json').read_text())
assert prepared['pass'] and prepared['restore_readback'] and runtime['pass'] and browser['pass'] and all(x['status']=='ready' and x['documents']==6 for x in history['periods'])
entry={'id':'zeus-finance-sms-direct-'+AUTH,'agent':'zeus','type':'finance_sms_prepaid_to_direct_cost_reclassification','owner':'Rodolfo / Zeus','authorization_message_ids':[AUTH,'1555431089957376065'],'thread_id':'1554520572950618173','status':'published_verified','updated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-sms-direct-cost-'+AUTH+'.md','evidence_path':'apps/finance-system/private/sms-direct-'+AUTH,'files':hashes,'runtime':{'url':'https://dash.mgsdigitalcorp.com','host':'MatteiInc01 / 162.55.28.178','services':runtime['services'],'workspace_revisions':{x['id']:x['revision'] for x in runtime['database']['workspaces']},'direct_cost_rows':12,'ledger_count':runtime['database']['ledger_count'],'gateway_restarted':False},'history_refresh':{'periods':['2026-05','2026-06','2026-07'],'documents':18,'immutable_versions':True},'backups':prepared['backup'],'stage':prepared['stage'],'stage_database':prepared['database'],'validation':{'node_tests':228,'node_pass':227,'node_skip':1,'node_fail':0,'python_targeted':5,'python_full':'timeout_420s_not_claimed_pass','public_browser':browser,'authenticated_api':True,'fixed_brl_fx_test':True,'idempotent_verify':True},'rollback':{'code':'/home/zeus/mgs-finance-backups/sms-direct-'+AUTH+'/code-before.tar.gz','ui':'/home/zeus/mgs-finance-backups/sms-direct-'+AUTH+'/ui-visibility-before.tar.gz','database':'/home/zeus/mgs-finance-backups/sms-direct-'+AUTH+'/finance-before.dump','warning':'Nunca restaurar dump sobre atividade posterior sem nova reconciliação'}}
invp=ROOT/'data/infra-inventory.json';auditp=ROOT/'logs/events-audit.jsonl'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);inv=json.loads(invp.read_text());items=inv.setdefault('runtime_artifacts',[]);items[:]=[x for x in items if x.get('id')!=entry['id']];items.append(entry);inv['last_updated']=entry['updated_at'];fd,tmp=tempfile.mkstemp(prefix='infra-inventory-',suffix='.json',dir=invp.parent);os.close(fd);pathlib.Path(tmp).write_text(json.dumps(inv,ensure_ascii=False,indent=2)+'\n');json.loads(pathlib.Path(tmp).read_text());os.replace(tmp,invp)
with auditp.open('a') as f:f.write(json.dumps({'timestamp':entry['updated_at'],'agent':'zeus','event':'FINANCE_SMS_DIRECT_COST_PUBLISHED','authorization':AUTH,'thread_id':entry['thread_id'],'inventory_id':entry['id'],'report_path':entry['report_path'],'evidence_path':entry['evidence_path'],'workspace_revisions':entry['runtime']['workspace_revisions'],'ledger_count':entry['runtime']['ledger_count'],'gateway_restarted':False},ensure_ascii=False)+'\n')
check=json.loads(invp.read_text());rows=[x for x in check['runtime_artifacts'] if x.get('id')==entry['id']];assert len(rows)==1 and rows[0]['files']==hashes
print(json.dumps({'pass':True,'inventory_id':entry['id'],'files':len(hashes),'readback':True,'audit_logged':True}))
