"""Record verified finance-history delivery and direct REPORT-INFRA, no credentials in output."""
import pathlib,json,os,hashlib,datetime,fcntl,subprocess,urllib.request,importlib.util
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';D=A/'private/history-import-1546884731436671056';K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard');marker='FINANCE-HISTORY-1546884731436671056'
files=[A/f for f in ['server.mjs','workspace.mjs','finance-ops.mjs','history.mjs','public/app.js','public/operations.js','public/navigation.js','public/history.html','public/history.css','public/history.js','tests/history-import-capture.py','tests/history-import-build.py','tests/history.test.mjs','tests/history-pg.mjs','tests/history-public.mjs','deploy/history-schema.sql','deploy/history-import.mjs','deploy/history-release.py','deploy/record-history-inventory.py']]+[R/'docs/finance-system-product-direction.md',R/'reports/finance-history-import-1546884731436671056.md',K/'SKILL.md',K/'references/closed-history-jan-jul-feasibility.md',K/'references/manager-access-and-history-dispositions.md',K/'references/closed-history-import-and-carry.md']
required=['built.json','prepared.json','fidelity.json','local-tests.json','stage-tests.json','import-mgs_finance.json','published.json','deploy-readback.json','public-readback.json'];proof={n:json.loads((D/n).read_text()) for n in required};assert all(v['pass'] for v in proof.values());pub=proof['public-readback.json'];build=proof['built.json'];assert pub['real_logins']==6 and pub['history_month_checks']==42 and pub['viewports']==84 and pub['public_cells_verified']==build['cells']==377906 and pub['js_errors']==0 and pub['july_to_august'];assert proof['fidelity.json']['numeric_identical']==build['numeric']==300089;assert proof['import-mgs_finance.json']['verified']==40 and len(proof['import-mgs_finance.json']['months'])==7;assert proof['stage-tests.json']['denied']==217
now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':marker.lower(),'agent':'zeus','authorization_message_ids':['1546884731436671056'],'thread_id':'1545426987756298340','status':'closed_history_and_internal_opening_verified','updated_at':now,'type':'finance_closed_history_import','evidence_path':str(D),'backup_remote':'/home/zeus/mgs-finance-backups/1546884731436671056','isolated_database':'mgs_finance_history_1546884731436671056','stage':'/var/tmp/mgs-finance-history-1546884731436671056','scope':{'historical_months':7,'monthly_tabs':40,'monthly_cells':build['cells'],'numeric_values_identical':build['numeric'],'node_tests':56,'stage_denials':217,'public_denials':pub['denials'],'public_logins':6,'public_month_checks':42,'public_viewports':84,'july_to_august_internal':True,'august_opening_still_fixed':False,'sheets_write':False,'credentials_changed':False,'gateway_restart':False,'finance_service_restart':True,'source_march_april_mismatch_preserved':True,'protected_nonfinancial_text_cells':len(build['protected_text_cells'])},'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);p=R/'data/infra-inventory.json';data=json.loads(p.read_text());items=data.setdefault('runtime_artifacts',[]);existing=next((x for x in items if x.get('id')==entry['id']),None)
 if existing:assert existing['files']==entry['files'],'Concurrent inventory differs'
 else:
  items.append(entry)
  for x in items:
   if x.get('id')=='finance-managers-1546858367635685396':x['history_pending_status_superseded_by']=entry['id']
  data['_meta']['updated_at']=now;t=p.with_suffix('.history.tmp')
  with t.open('w') as f:json.dump(data,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
  os.replace(t,p)
 assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])['files']==entry['files']
spec=importlib.util.spec_from_file_location('notice',A/'finance-notifications.py');assert spec and spec.loader;m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);token=m.dotenv_values('/root/.hermes/profiles/zeus/.env')['DISCORD_BOT_TOKEN'];headers={'Authorization':'Bot '+token,'User-Agent':'MGS-Readback'};base='https://discord.com/api/v10/channels/1498132022634483894/messages'
def get(url):return json.load(urllib.request.urlopen(urllib.request.Request(url,headers=headers),timeout=25))
def matches():return [d for d in get(base+'?limit=50') if marker in json.dumps(d.get('embeds',[]))]
found=matches()
if not found:
 env=dict(os.environ);env['MGS_DISCORD_BOT_TOKEN_OVERRIDE']=token;env.pop('MGS_DISCORD_API_URL_OVERRIDE',None)
 result=subprocess.run([str(R/'scripts/send-report-infra-embed.sh'),'--action','modificada','--type','finance-closed-history','--path','Finance app10files;PGfinance_history40rows;scripts/skill0.1.31/docs/registry','--reason',marker+': Rodolfo autorizou importarJan–Jul fechado e substituir abertura fixa por fechamentoJulho interno.','--evidence','40abas+Caixa;377906células/300089númerosiguais;56testsPASS;stage217negativas/85mesesatuais. Público6logins/42meses/84viewports/41negativas/0JS,July→Aug71centavosinternos. Backupduplo/hash/restore;appSELECTsomente. DiferençaMarço−67.10→Abril0.73sinalizada/preservada. Sheets/credenciais/gatewayintactos. Relatório reports/finance-history-import-1546884731436671056.md'],env=env,text=True,capture_output=True,timeout=75)
 assert result.returncode==0,'Helper failed: reconcile readback before retry';found=matches()
assert len(found)==1;message=get(base+'/'+found[0]['id']);assert message['content']=='' and len(message['embeds'])==1 and not message.get('mentions')
out={'pass':True,'inventory_readback':True,'report_message_id':message['id'],'report_readback':True,'files':len(files),'historical_months':7,'history_import_pending':False,'july_to_august_internal':True,'source_discrepancy_preserved':True};(D/'final-readback.json').write_text(json.dumps(out,indent=2))
with (R/'logs/events-audit.jsonl').open('a') as f:
 fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps({'timestamp':now,'event':'finance_closed_history_import_and_internal_carry','agent':'zeus','authorization_message_ids':entry['authorization_message_ids'],'scope':entry['scope'],**out})+'\n');f.flush();os.fsync(f.fileno())
print(json.dumps(out))
