"""Inventory/audit for the verified currency repair and additional site-label request."""
import pathlib,json,datetime,hashlib,fcntl,os
ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';AUTH='1546607083468623912';STATE=APP/('private/wavesbee-'+AUTH);SKILL=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard')
checks={n:json.loads((STATE/n).read_text()) for n in ['sheet-readback.json','pg-exercise.json','production-readback.json','deploy-readback.json','public-browser.json','wantabrand-deploy.json']};assert all(x['pass'] for x in checks.values());assert checks['public-browser.json']['wantabrand_display_readback'];assert len(checks['public-browser.json']['periods'])==17;assert 'version: 0.1.23' in (SKILL/'SKILL.md').read_text();assert 'Wantabrand display' in (SKILL/'references/wavesbee-cad-september-recheck.md').read_text()
for file,expected in [('python-tests.log','Ran 38 tests'),('node-tests.log','# pass 25'),('site-display-tests.log','# pass 17')]:assert expected in (STATE/file).read_text()
files=['worker.py','workspace.mjs','currency_bridge.py','currency-migration.mjs','public/app.js','deploy/apply-currency.mjs','deploy/currency-release.py','deploy/wantabrand-label.py','deploy/record-currency-inventory.py','tests/wavesbee-inspect.py','tests/wavesbee-sheet.py','tests/test_wavesbee_currency.py','tests/currency.test.mjs','tests/site-display.test.mjs','tests/wavesbee-browser.mjs','tests/run-wavesbee-public.py']
paths=[APP/f for f in files]+[ROOT/'docs/finance-system-product-direction.md',ROOT/('reports/finance-wavesbee-'+AUTH+'.md')]+[SKILL/f for f in ['SKILL.md','references/wavesbee-cad-september-recheck.md','references/monthly-networks-and-sheet-parity.md']]
now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':'zeus-finance-currency-'+AUTH,'agent':'zeus','type':'finance_monthly_currency_and_site_display','authorization_message_ids':[AUTH],'authorization_addendum':'Rodolfo live thread: Wantabrand US-CC-ES + Wantabrand BR-CAR-BR -> Wantabrand in sites','thread_id':'1545426987756298340','status':'published_verified','updated_at':now,'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-wavesbee-'+AUTH+'.md','evidence_path':str(STATE),'tests':{'python':38,'node':25,'frontend_final':17,'periods':17,'sheet_cells_changed':33,'sheet_errors':0,'outside_scope_changes':0,'public_browser':True,'isolated_restore_api':True},'known_gaps':['Separate unedited Sheet manager projection E14/F14 and H1 Caixa J2 references; current September literal/piso verified, not full future parity','Original two spending account identity gaps remain, amounts preserved','Trial/native migration/recurring DR and cutover remain separate initiative'],'resolved_followups':['WavesBee CAD August/September both surfaces','September literal-August payroll claim superseded by live readback','G29 principal empty by design due blank D29; no formula error'],'retained_artifacts':{'remote_backup':'/home/zeus/mgs-finance-backups/'+AUTH,'stage':'/var/tmp/mgs-finance-currency-'+AUTH,'database':'mgs_finance_currency_'+AUTH,'backup_hashes':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in STATE.iterdir() if p.name in ['code-before.tar.gz','finance-before.dump','app-before-wantabrand.js','sheets-before.json']}},'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}
p=ROOT/'data/infra-inventory.json'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);inv=json.loads(p.read_text());items=inv.setdefault('runtime_artifacts',[]);idx=next((i for i,x in enumerate(items) if x.get('id')==entry['id']),None)
 if idx is None:items.append(entry)
 else:items[idx]=entry
 prior=next((x for x in items if x.get('id')=='zeus-finance-networks-1546579646227943506'),None)
 if prior:prior['september_followups_superseded_by']=entry['id']
 for artifact in paths:
  if artifact.suffix not in ['.py','.mjs','.js']:continue
  st=artifact.stat();meta={'path':str(artifact),'size_bytes':st.st_size,'modified_at':datetime.datetime.fromtimestamp(st.st_mtime,datetime.timezone.utc).isoformat(),'sha256':entry['files'][str(artifact)],'description':'Finance WavesBee CAD + Wantabrand '+AUTH};items=inv.setdefault('scripts',[]);idx=next((i for i,x in enumerate(items) if x.get('path')==str(artifact)),None)
  if idx is None:items.append(meta)
  else:items[idx]=meta
 inv['_meta']['updated_at']=now;tmp=p.with_suffix('.currency-update.tmp')
 with tmp.open('w') as f:json.dump(inv,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
 os.replace(tmp,p);assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])==entry
with (ROOT/'logs/events-audit.jsonl').open('a') as f:f.write(json.dumps({'timestamp':now,'agent':'zeus','event':'finance_currency_and_display_validated','authorization':AUTH,'authorization_addendum':entry['authorization_addendum'],'inventory_id':entry['id'],'report':entry['report_path'],'sheet_cells_updated':33,'production_financial_test_writes':0,'known_gaps':entry['known_gaps']},ensure_ascii=False)+'\n')
(STATE/'final-evidence.json').write_text(json.dumps({'pass':True,'inventory_readback':True,'skill_readback':'mgs-finance-dashboard 0.1.23','inventory_id':entry['id'],'tests':entry['tests'],'report':entry['report_path']},indent=2));print(json.dumps({'inventory_readback':True,'skill_readback':'0.1.23','files':len(paths),'tests':entry['tests']}))
