"""Inventory/audit and one canonical direct embed for verified native history + Zeus PT transcription."""
import pathlib,json,os,hashlib,datetime,fcntl,subprocess,urllib.request,importlib.util,yaml
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';D=A/'private/history-ui-1546894693135028234';K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard');O=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/hermes-agent-operations');ST=R/'work/stt-portuguese-1546894693135028234';marker='FINANCE-NATIVE-HISTORY-1546896342805123125'
files=[A/f for f in ['public/app.js','public/operations.js','public/navigation.js','public/index.html','public/operations.html','finance-ops.mjs','history.mjs','public/history-dashboard.js','public/history-operations.js','tests/history-dashboard.test.mjs','tests/history-ui-public.mjs','tests/history-ui-pg.mjs','tests/history-ui-run.py','deploy/history-ui-release.py','deploy/record-history-ui-inventory.py']]+[R/'docs/finance-system-product-direction.md',R/'reports/finance-native-history-1546896342805123125.md',K/'SKILL.md',K/'references/native-closed-month-views.md',K/'references/closed-history-import-and-carry.md',O/'SKILL.md',O/'references/portuguese-stt-language.md',pathlib.Path('/root/.hermes/profiles/zeus/config.yaml'),R/'profiles/zeus-config.yaml',ST/'apply-and-test.py']
proof={n:json.loads((D/n).read_text()) for n in ['prepared.json','stage-pg.json','unit-readback.json','coverage-readback.json','published.json','deploy-readback.json','production-readback.json']};assert all(v['pass'] for v in proof.values());pub=proof['production-readback.json'];assert pub['logins']==6 and len(pub['months'])==42 and pub['payments']==42 and pub['viewports']==84 and pub['payload_cells']==377906 and not pub['js_errors'] and pub['carry'];assert proof['coverage-readback.json']['gross_headers']==858 and proof['coverage-readback.json']['blocks']==504;assert proof['published.json']['financial_data_history_and_users_unchanged'];stt=json.loads((ST/'readback.json').read_text());assert stt['pass'] and stt['resolved_language']=='pt' and stt['transcription_success'] and not stt['restart'];assert all(yaml.safe_load(pathlib.Path(x['path']).read_text())['stt']['local']['language']=='pt' for x in stt['files'])
now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':marker.lower(),'agent':'zeus','authorization_message_ids':['1546894693135028234','1546896342805123125'],'additional_authority':'Rodolfo mid-turn request for Portuguese audio transcription in same thread','thread_id':'1545426987756298340','status':'native_closed_month_views_and_zeus_stt_pt_verified','updated_at':now,'type':'finance_native_history_and_stt_language','evidence_path':str(D),'stt_evidence_path':str(ST),'backup_remote':'/home/zeus/mgs-finance-backups/1546896342805123125','stage':'/var/tmp/mgs-finance-history-ui-1546896342805123125','isolated_database':'mgs_finance_history_ui_1546896342805123125','scope':{'native_menu_months':7,'monthly_cells_exact':pub['payload_cells'],'blocks':504,'gross_headers':858,'daily_numeric_values':194814,'unit_tests':proof['unit-readback.json']['tests'],'stage_denials':217,'current_manager_months':85,'public_logins':6,'public_month_views':42,'public_payments':42,'public_viewports':84,'public_denials':pub['denials'],'javascript_errors':0,'finance_data_and_history_unchanged':True,'sheets_write':False,'credentials_changed':False,'gateway_restart':False,'finance_service_restart':True,'history_menu_removed':True,'carry_in_payments':True,'stt_language':'pt','stt_same_audio_validated':True,'login_limit_preserved':True},'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);p=R/'data/infra-inventory.json';d=json.loads(p.read_text());items=d.setdefault('runtime_artifacts',[]);existing=next((x for x in items if x.get('id')==entry['id']),None)
 if existing:assert existing['files']==entry['files'],'Reconcile concurrent inventory before retry'
 else:
  items.append(entry)
  for x in items:
   if x.get('id')=='finance-history-1546884731436671056':x['presentation_superseded_by']=entry['id']
  d['_meta']['updated_at']=now;t=p.with_suffix('.native-history.tmp')
  with t.open('w') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
  os.replace(t,p)
 assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])['files']==entry['files']
spec=importlib.util.spec_from_file_location('notice',A/'finance-notifications.py');assert spec and spec.loader;m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);token=m.dotenv_values('/root/.hermes/profiles/zeus/.env')['DISCORD_BOT_TOKEN'];headers={'Authorization':'Bot '+token,'User-Agent':'MGS-Readback'};base='https://discord.com/api/v10/channels/1498132022634483894/messages'
def get(url):return json.load(urllib.request.urlopen(urllib.request.Request(url,headers=headers),timeout=25))
def matches():return [d for d in get(base+'?limit=50') if marker in json.dumps(d.get('embeds',[]))]
found=matches()
if not found:
 env=dict(os.environ);env['MGS_DISCORD_BOT_TOKEN_OVERRIDE']=token;env.pop('MGS_DISCORD_API_URL_OVERRIDE',None)
 r=subprocess.run([str(R/'scripts/send-report-infra-embed.sh'),'--action','modificada','--type','finance-native-history/stt-pt','--path','Finance9arquivos;Zeusconfig+mirror;skillsfinance0.1.32/Hermes;docs/registry/checkpoint','--reason',marker+': Rodolfo corrigiu histórico para os mesmos menus de agosto, saldo em Pagamentos, e pediu transcrição portuguesa.','--evidence','Público6logins/42meses/42pagamentos/84viewports/16negativas/0JS;377906células intactas.64tests;stage217negações+85mesesatuais;504blocos/858Gross completos.9arquivos/readback,backupduplo+restore;dados/usuários/histórico imutável preservados. Sem Sheets/credenciais/gatewayrestart. STTlocal.language=pt e mesmo áudio PTvalidados;config+mirror iguais. Limite10logins/15min preservado e validação retomada apósjanela. RessalvaMarço→Abril e ausênciasoriginais preservadas. reports/finance-native-history-1546896342805123125.md'],env=env,text=True,capture_output=True,timeout=75)
 assert r.returncode==0,'Helper failed: reconcile Discord before retry';found=matches()
assert len(found)==1;message=get(base+'/'+found[0]['id']);assert message['content']=='' and len(message['embeds'])==1 and not message.get('mentions')
out={'pass':True,'inventory_readback':True,'report_message_id':message['id'],'report_readback':True,'files':len(files),'closed_month_views':len(pub['months']),'stt_pt':True,'no_financial_writes':True};(D/'final-readback.json').write_text(json.dumps(out,indent=2))
with (R/'logs/events-audit.jsonl').open('a') as f:
 fcntl.flock(f,fcntl.LOCK_EX);f.write(json.dumps({'timestamp':now,'event':'finance_native_closed_views_and_zeus_stt_pt','agent':'zeus','authorization_message_ids':entry['authorization_message_ids'],'scope':entry['scope'],**out})+'\n');f.flush();os.fsync(f.fileno())
print(json.dumps(out))
