"""Inventory/readback of finance billing-origin, BM lookup and brand release."""
import pathlib,json,datetime,hashlib,fcntl,os,subprocess
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';AUTH='1546618148571058266';S=A/('private/origin-'+AUTH);K=pathlib.Path('/root/.hermes/profiles/zeus/skills/ops/mgs-finance-dashboard');unit=pathlib.Path('/etc/systemd/system/mgs-finance-meta-lookup.service')
checks={n:json.loads((S/n).read_text()) for n in ['prepared.json','pg-exercise.json','published.json','deploy-readback.json','service-install.json','public-browser.json']};assert all(v['pass'] for v in checks.values());assert len(checks['public-browser.json']['periods'])==17 and len(checks['public-browser.json']['expense_editors'])==56;assert 'Ran 40 tests' in (S/'python-tests.log').read_text() and '# pass 28' in (S/'node-tests.log').read_text();assert 'version: 0.1.24' in (K/'SKILL.md').read_text();assert subprocess.check_output(['systemctl','is-active','mgs-finance-meta-lookup.service'],text=True).strip()=='active';assert unit.read_bytes()==(A/'deploy'/unit.name).read_bytes()
files=['worker.py','ui_model.py','site_catalog.py','workspace.mjs','accounts.mjs','auth.mjs','public/app.js','public/index.html','public/login.html','public/login.css','public/refinements.css','public/mgs-logo.png','public/favicon.ico','public/favicon-32.png','public/apple-touch-icon.png','meta-lookup.mjs','meta-lookup-worker.py','deploy/meta-lookup-queue.py','deploy/origin-release.py','deploy/install-meta-service.py','deploy/mgs-finance-meta-lookup.service','deploy/build-brand-assets.py','deploy/record-origin-inventory.py','tests/test_expense_origin.py','tests/origin-editor.test.mjs','tests/origin-pg.mjs','tests/reset-origin-stage.mjs','tests/origin-browser.mjs','tests/run-origin-public.py']
paths=[A/f for f in files]+[unit,R/'docs/finance-system-product-direction.md',R/('reports/finance-origin-'+AUTH+'.md'),K/'SKILL.md',K/'references/billing-origin-meta-id-and-brand.md'];now=datetime.datetime.now(datetime.timezone.utc).isoformat();entry={'id':'zeus-finance-origin-'+AUTH,'agent':'zeus','type':'finance_billing_origin_meta_lookup_brand','authorization_message_ids':[AUTH,'1546619674320441415','1546624782785716305'],'thread_id':'1545426987756298340','status':'published_verified','updated_at':now,'canonical_source':'docs/finance-system-product-direction.md','report_path':'reports/finance-origin-'+AUTH+'.md','evidence_path':str(S),'service':{'host':'Zeus','unit':str(unit),'enabled':True,'active':True,'meta_writes':0,'credential_change':False,'web_app_network_opened':False},'tests':{'python':40,'node':28,'focused_auth_display':4,'periods':17,'expense_editors':56,'js_errors':0,'bm_lookup_ms':checks['public-browser.json']['lookup_ms'],'restore_api_real_meta':True,'production_financial_test_writes':0,'sheet_writes':0},'retained_artifacts':{'remote_backup':'/home/zeus/mgs-finance-backups/'+AUTH,'stage':'/var/tmp/mgs-finance-origin-'+AUTH,'database':'mgs_finance_origin_'+AUTH,'backup_hashes':checks['prepared.json']['backup']},'limits':['Meta IDs must be visible to the finance identity in BM Digital Trust; inaccessible IDs fail closed','Prior native/trial migration and historical account identity gaps remain separate initiative'],'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}
p=R/'data/infra-inventory.json'
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);d=json.loads(p.read_text());items=d.setdefault('runtime_artifacts',[]);idx=next((i for i,v in enumerate(items) if v.get('id')==entry['id']),None)
 if idx is None:items.append(entry)
 else:items[idx]=entry
 scripts=d.setdefault('scripts',[])
 for f in paths:
  if f.suffix not in ['.py','.js','.mjs']:continue
  row={'path':str(f),'size_bytes':f.stat().st_size,'sha256':entry['files'][str(f)],'modified_at':datetime.datetime.fromtimestamp(f.stat().st_mtime,datetime.timezone.utc).isoformat(),'description':'Finance billing/BM/brand '+AUTH};idx=next((i for i,x in enumerate(scripts) if x.get('path')==str(f)),None)
  if idx is None:scripts.append(row)
  else:scripts[idx]=row
 d['_meta']['updated_at']=now;t=p.with_suffix('.origin-update.tmp')
 with t.open('w') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.flush();os.fsync(f.fileno())
 os.replace(t,p);fd=os.open(p.parent,os.O_DIRECTORY);os.fsync(fd);os.close(fd);assert next(x for x in json.loads(p.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])==entry
with (R/'logs/events-audit.jsonl').open('a') as f:f.write(json.dumps({'timestamp':now,'agent':'zeus','event':'finance_origin_meta_brand_validated','authorization_message_ids':entry['authorization_message_ids'],'inventory_id':entry['id'],'report':entry['report_path'],'tests':entry['tests'],'production_financial_mutations':0})+'\n')
out={'pass':True,'inventory_readback':True,'skill_readback':'0.1.24','files':len(paths),'inventory_id':entry['id'],'tests':entry['tests']};(S/'final-evidence.json').write_text(json.dumps(out,indent=2));print(json.dumps(out))
