import assert from 'node:assert/strict';import {isDeepStrictEqual} from 'node:util';import {calculate} from './storage.mjs';import {PERIODS} from './periods.mjs';
export const AUTH='1547732274936553532',SITES=[{id:'newsite-mgs-cephyric',name:'Cephyric',countries:['FR']},{id:'newsite-mgs-escalatepower',name:'Escalatepower',countries:['US']},{id:'newsite-mgs-mavroa',name:'Mavroa',countries:['US']}];
export function policyRows(period){const cutoff={kind:'data_cutoff',id:'data-cutoff-'+period,date:period==='2026-08'?'2026-08-31':period==='2026-09'?'2026-09-09':null,source:period==='2026-09'?'GAM e mídia completos até 09/09/2026':'Competência encerrada' ,authorization:AUTH},sites=period>='2026-09'?SITES.map(s=>({kind:'site',id:s.id,new:true,name:s.name,status:'INATIVO',countries:s.countries,manager:'SEM_COMISSAO',owner:'MGS',manager_names:['MGS'],partner:'SB Rede1',network:'SB Rede1',currency:'CAD',invalid_source:'L1',assignment_authority:AUTH})):[];return {cutoff,sites};}
export function desiredAdditions(additions,period){const {cutoff,sites}=policyRows(period),names=new Set(SITES.map(s=>s.name));for(const a of additions.filter(a=>a.kind==='site'&&names.has(a.name)))assert.ok(sites.some(s=>s.id===a.id)&&a.new,'Conflicting site registration '+a.name);return [...additions.filter(a=>a.kind!=='data_cutoff'&&!(a.kind==='site'&&names.has(a.name))),cutoff,...sites];}
const cashKeys=['gross','invalid','net','tax','spend','company_expenses','personnel','profit'];
export async function migrateCurrentPolicy(db,{authority=AUTH}={}){assert.equal(authority,AUTH);const rows=(await db.query("SELECT * FROM scenarios WHERE id LIKE 'workspace-%' ORDER BY id")).rows;assert.equal(rows.length,PERIODS.length);const prepared=[];
 for(const s of rows){const period=s.id.slice(10),additions=desiredAdditions(s.additions,period);if(isDeepStrictEqual(additions,s.additions)&&s.result.domain.realized){prepared.push({s,additions,result:s.result,changed:false});continue;}const result=await calculate({period,overrides:s.overrides,additions});assert.equal(result.summary.counts.error||0,0);for(const k of cashKeys)assert.equal(String(result.domain.cash[k]),String(s.result.domain.cash[k]),period+' '+k);const oldActive=Number(s.result.domain.allocation?.active_units),newActive=Number(result.domain.allocation?.active_units);assert.equal(newActive,oldActive,period+' active units');const expected=policyRows(period).cutoff.date,realized=result.domain.realized;assert.equal(realized.cutoff_date,expected);assert.equal(realized.elapsed_days,expected?Number(expected.slice(-2)):0);if(period==='2026-08')assert.equal(String(realized.profit),String(result.domain.cash.profit));if(period==='2026-09'){const fixed=Number(result.domain.cash.company_expenses)+Number(result.domain.cash.personnel),variable=result.domain.facts.filter(f=>f.date<=expected).reduce((n,f)=>n+Number(f.profit||0),0),estimate=(variable*30/9+fixed)/2;assert.ok(Math.abs(Number(result.domain.projection.half_usd)-estimate)<1e-7);}if(period>'2026-09')assert.equal(result.domain.projection.half_usd,null);for(const site of SITES){const c=result.domain.site_catalog.find(x=>x.name===site.name);if(period>='2026-09'){assert.ok(c);assert.equal(c.status,'INATIVO');assert.equal(c.manager,'SEM_COMISSAO');}else assert.ok(!c);}prepared.push({s,additions,result,changed:true});}
 const changes=prepared.filter(x=>x.changed);if(!changes.length)return {pass:true,changed:false,periods:rows.length,updated:0,sites:SITES.map(x=>x.name)};
 await db.transaction(async tx=>{for(const x of changes){const locked=(await tx.query('SELECT revision FROM scenarios WHERE id=$1 FOR UPDATE',[x.s.id])).rows[0];assert.equal(locked.revision,x.s.revision);const recovery='recovery-current-policy-'+AUTH+'-'+x.s.id.slice(10);await tx.query("INSERT INTO scenarios(id,import_id,name,state,revision,overrides,additions,result) VALUES($1,$2,$3,'locked',$4,$5::jsonb,$6::jsonb,$7::jsonb) ON CONFLICT(id) DO NOTHING",[recovery,x.s.import_id,'Recovery before current cutoff/site policy '+AUTH,x.s.revision,JSON.stringify(x.s.overrides),JSON.stringify(x.s.additions),JSON.stringify(x.s.result)]);const u=await tx.query("UPDATE scenarios SET additions=$1::jsonb,result=$2::jsonb,revision=revision+1,updated_at=now() WHERE id=$3 AND revision=$4 AND state='draft' RETURNING revision",[JSON.stringify(x.additions),JSON.stringify(x.result),x.s.id,x.s.revision]);assert.equal(u.rows.length,1);}
  await tx.query('INSERT INTO audit_events(actor,action,after_data) VALUES($1,$2,$3::jsonb)',['zeus','CURRENT_REALIZED_CUTOFF_AND_INACTIVE_SITES_APPLIED',JSON.stringify({authorization:AUTH,periods:changes.map(x=>x.s.id.slice(10)),cutoffs:Object.fromEntries(PERIODS.map(p=>[p.id,policyRows(p.id).cutoff.date])),inactive_sites:SITES.map(x=>x.name),cash_unchanged:true,active_units_unchanged:true})]);});
 const after=(await db.query("SELECT id,revision,additions,result FROM scenarios WHERE id LIKE 'workspace-%' ORDER BY id")).rows;for(const x of prepared){const a=after.find(r=>r.id===x.s.id);assert.deepEqual(a.additions,x.additions);assert.deepEqual(a.result,x.result);assert.equal(a.revision,x.s.revision+(x.changed?1:0));}return {pass:true,changed:true,periods:rows.length,updated:changes.length,sites:SITES.map(x=>x.name),cutoffs:Object.fromEntries(PERIODS.map(p=>[p.id,policyRows(p.id).cutoff.date]))};}
