import fs from 'node:fs/promises';
import path from 'node:path';
import {randomUUID,randomBytes,scrypt} from 'node:crypto';
import {promisify} from 'node:util';
import {AsyncLocalStorage} from 'node:async_hooks';
import {root,scenario,validateText} from './storage.mjs';
import {periodInfo,workspaceId,today} from './periods.mjs';
import {managerView,validManager,managerBook} from './manager-view.mjs';
import {isHistory,historyOpening,historyView,historyDocument} from './history.mjs';
const derive=promisify(scrypt),context=new AsyncLocalStorage(),wrapped=new WeakSet();
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
export const opsSchema=await fs.readFile(path.join(root,'finance-ops-schema.sql'),'utf8');
export function cents(value){const m=/^(-?)(\d+)(?:\.(\d+))?$/.exec(String(value));if(!m)fail('Valor monetário inválido');const decimal=(m[3]||'').padEnd(3,'0');const v=BigInt(m[2])*100n+BigInt(decimal.slice(0,2))+(decimal[2]>='5'?1n:0n);if(v>100000000000n)fail('Valor monetário fora do limite');return Number(m[1]?-v:v);}
export function ledgerSummary(periods,entries,opening,selected){const movement=period=>entries.filter(x=>x.period===period&&!x.voided_at).reduce((s,x)=>s+Number(x.amount_cents)*Number(x.direction),0);const previous=opening+periods.filter(p=>p.period<selected).reduce((s,p)=>s+p.due+movement(p.period),0);const due=periods.find(p=>p.period===selected)?.due||0;const balance=previous+due+movement(selected),paid=entries.some(e=>!e.voided_at&&e.kind==='payment'&&e.period<=selected);return {previous,due,movement:movement(selected),balance,status:balance<0?'Crédito':balance===0?(paid?'Conferido':'Sem valor a pagar'):paid?'Parcial':'A conferir'};}
export function mayRequest(url){return /^\/api\/scenarios\/[^/]+\/(inputs|entries|entry-values|lock|ui-inputs|expenses|expenses\/[^/]+\/delete|rates|sites)$/.test(url)||/^\/api\/ad-accounts(?:\/[^/]+)?$/.test(url)||/^\/api\/finance\/(users|ledger|ledger\/[a-f0-9-]+\/void|users\/[a-z0-9_.-]+)$/.test(url);}
const actor=req=>req.auth?.username||'rodolfo',role=req=>req.auth?.role||'owner';
const noSecrets=value=>{if(!value||typeof value!=='object')return;for(const [k,v]of Object.entries(value)){if(/password|token|secret|csrf|salt|credential/i.test(k))fail('Credenciais não podem fazer parte de propostas');noSecrets(v);}};
export const clean=value=>{if(value instanceof Date)return Number.isFinite(value.getTime())?value.toISOString():null;if(!value||typeof value!=='object')return value;if(Array.isArray(value))return value.map(clean);return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,/password|token|secret|csrf|salt|hash/i.test(k)?'[PROTEGIDO]':clean(v)]));};
const audit=(tx,who,action,before,after)=>tx.query('INSERT INTO audit_events(actor,action,before_data,after_data) VALUES($1,$2,$3::jsonb,$4::jsonb)',[who,action,JSON.stringify(clean(before||{})),JSON.stringify(clean(after||{}))]);
export function profileFields(b){noSecrets(b);const display_name=validateText(b.display_name,'Nome completo',120);const value=(k,max)=>{const v=b[k]??'';if(typeof v!=='string'||v.length>max||/[\x00-\x1f\x7f]/.test(v))fail('Campo inválido: '+k);return v.trim();};const email=value('email',254),phone=value('phone',40),discord_id=value('discord_id',20);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('E-mail inválido');if(phone&&!/^\+?[0-9() .-]{5,40}$/.test(phone))fail('Telefone inválido');if(discord_id&&!/^[0-9]{17,20}$/.test(discord_id))fail('ID Discord inválido; use apenas os dígitos originais');return {display_name,email,phone,discord_id};}
const publicUser=u=>({username:u.username,display_name:u.display_name,email:u.email||'',phone:u.phone||'',discord_id:u.discord_id||'',role:u.role,manager_key:u.manager_key,enabled:u.enabled,revision:u.revision});
const OWNER_PROFILE='master-owner-profile';
export async function ownerProfile(db){const r=await db.query('SELECT revision,result FROM scenarios WHERE id=$1',[OWNER_PROFILE]);return {username:'rodolfo',display_name:'Rodolfo',email:'',phone:'',discord_id:'',...(r.rows[0]?.result?.profile||{}),revision:r.rows[0]?.revision||0,role:'owner',manager_key:null,enabled:true,protected:true};}
export async function identity(db,username){if(username==='rodolfo')return ownerProfile(db);const r=await db.query('SELECT * FROM finance_users WHERE username=$1 AND enabled',[username]);return r.rows[0]||null;}
async function saveProfile(db,username,b,who){
 // PROFILE_FIELDS_ONLY: contact edits cannot change identity, permissions or credentials.
 if(Object.keys(b).some(k=>!['display_name','email','phone','discord_id','revision'].includes(k))||!Number.isInteger(b.revision))fail('Somente dados cadastrais e revisão são permitidos');
 const profile=profileFields(b);
 await db.transaction(async tx=>{
  if(username==='rodolfo'){
   if(who!=='rodolfo')fail('Somente Rodolfo pode editar seus dados',403);
   const initial={summary:{kind:'owner_contact_profile'},domain:{},results:{},issues:[],boundaries:[],profile:{display_name:'Rodolfo',email:'',phone:'',discord_id:''}};
   await tx.query("INSERT INTO scenarios(id,import_id,name,state,result) SELECT $1,import_id,'Perfil cadastral do administrador','draft',$2::jsonb FROM scenarios WHERE id='baseline' ON CONFLICT(id) DO NOTHING",[OWNER_PROFILE,JSON.stringify(initial)]);
   const old=(await tx.query('SELECT revision,result FROM scenarios WHERE id=$1 FOR UPDATE',[OWNER_PROFILE])).rows[0];if(!old||old.revision!==b.revision)fail('Perfil alterado; atualize antes de salvar',409);
   await tx.query('UPDATE scenarios SET result=$2::jsonb,revision=revision+1,updated_at=now() WHERE id=$1',[OWNER_PROFILE,JSON.stringify({...old.result,profile})]);
   await audit(tx,who,'USER_PROFILE_CHANGED',{username,...old.result.profile},{username,...profile});
  }else{
   const old=(await tx.query('SELECT * FROM finance_users WHERE username=$1 FOR UPDATE',[username])).rows[0];if(!old||old.revision!==b.revision)fail('Usuário/revisão incompatível',409);
   await tx.query('UPDATE finance_users SET display_name=$2,email=$3,phone=$4,discord_id=$5,revision=revision+1 WHERE username=$1',[username,profile.display_name,profile.email,profile.phone,profile.discord_id]);
   await audit(tx,who,'USER_PROFILE_CHANGED',publicUser(old),{username,...profile});
  }
 });
 return username==='rodolfo'?ownerProfile(db):publicUser((await db.query('SELECT * FROM finance_users WHERE username=$1',[username])).rows[0]);
}
function payees(domain){return [{id:'geizian',label:'Geizian · Sócio (50%)',manager:null},...domain.expenses.filter(e=>e.category==='personnel').map(e=>({id:e.id,label:e.label,manager:e.manager||null}))];}
async function ledger(db,period,counterparty,req){
 periodInfo(period);
 const rows=(await db.query(`SELECT id,result->'domain'->'cash' AS cash,result->'domain'->'realized' AS realized,result->'domain'->'expenses' AS expenses,updated_at,
  result #>> ARRAY['results','principal|Agosto 2026|F1','actual'] AS fx,
  result #>> ARRAY['results','principal|Agosto 2026|H1','actual'] AS fx_cad,
  result #>> ARRAY['results','principal|Agosto 2026|I1','actual'] AS fx_gbp
  FROM scenarios WHERE id LIKE 'workspace-%' AND id <= $1 ORDER BY id`,[workspaceId(period)])).rows;
 const selected=rows.find(r=>r.id===workspaceId(period));if(!selected)fail('Competência indisponível',404);
 const parties=payees({expenses:selected.expenses});counterparty=counterparty||(role(req)==='manager'?parties.find(p=>p.manager===managerBook(req.auth.manager_key))?.id:'geizian');const selectedParty=parties.find(p=>p.id===counterparty);if(!selectedParty)fail('Beneficiário inválido');if(role(req)==='manager'&&selectedParty.manager!==managerBook(req.auth.manager_key))fail('Acesso restrito',403);
 const periods=rows.map(r=>({period:r.id.slice(10),due:r.id.slice(10)>today().slice(0,7)?0:counterparty==='geizian'?cents(r.realized?.half_brl??r.cash.half_brl):Math.abs(cents(r.expenses.find(e=>e.id===counterparty)?.brl||0))}));const entries=(await db.query('SELECT * FROM finance_ledger WHERE counterparty=$1 AND period <= $2 ORDER BY effective_date,created_at,id',[counterparty,period])).rows;const historical=counterparty==='geizian'?await historyOpening(db):null;const opening=historical?cents(historical.raw):0;
 const exchanges=[['USD → BRL',selected.fx],['USD/CAD',selected.fx_cad],['GBP → USD',selected.fx_gbp]].filter(([,value])=>value!==null&&value!==undefined&&value!=='').map(([label,value])=>({label,value}));const indicators=role(req)==='manager'?null:{exchange_rates:exchanges,status:'Provisório',source:'dash',updated_at:selected.updated_at};
 return {period,counterparty,party:selectedParty,currency:'BRL',provisional:true,opening,opening_source:historical?.source||null,periods,entries,indicators,...ledgerSummary(periods,entries,opening,period),parties:role(req)==='manager'?parties.filter(p=>p.manager===managerBook(req.auth.manager_key)):parties};
}
export async function installFinanceOps(app,db){
 if(!db.production)await db.exec(opsSchema);
 if(!wrapped.has(db)){const transaction=db.transaction.bind(db);db.transaction=async fn=>{const c=context.getStore();if(!c?.approval)return transaction(fn);if(c.used)fail('Aprovação já utilizada',409);return transaction(async tx=>{const r=await tx.query("SELECT * FROM finance_approvals WHERE id=$1 FOR UPDATE",[c.approval]);if(r.rows[0]?.status!=='pending')fail('Proposta já decidida',409);const result=await fn(tx);await tx.query("UPDATE finance_approvals SET status='approved',decided_at=now(),decided_by=$2 WHERE id=$1",[c.approval,c.owner]);await audit(tx,c.owner,'PROPOSAL_APPROVED',{id:c.approval,author:r.rows[0].actor},{id:c.approval,path:r.rows[0].path});c.used=true;return result;});};wrapped.add(db);}
 app.use(async(req,res,next)=>{
  const r=role(req),url=req.path,ownerHistoryRefresh=r==='owner'&&(url==='/api/history-refreshes'||url.startsWith('/api/history-refreshes/'));
  if(!['GET','HEAD','OPTIONS'].includes(req.method)&&!ownerHistoryRefresh&&(url.startsWith('/api/history')||/workspace-2026-0[1-7](?:\/|$)/.test(url)||isHistory(req.body?.period)))return res.status(409).json({error:'Histórico fechado: edição, recálculo e novos lançamentos indisponíveis'});
  if(url.startsWith('/api/scenarios/master-owner-profile'))return res.status(403).json({error:'Use o cadastro de perfil'});
  if(r==='manager'){
   const allowed=(url==='/api/finance/profile'&&['GET','POST'].includes(req.method))||req.method==='GET'&&['/','/operations','/operations.html','/operations.js','/operations.css','/app.css','/refinements.css','/navigation.css','/navigation.js','/mgs-logo.png','/favicon.ico','/api/periods','/history','/history.html','/history.js','/history.css','/history-dashboard.js','/history-operations.js','/api/history','/api/history/periods','/api/manager-workspace','/api/finance/ledger'].includes(url);
   if(!allowed)return res.status(403).json({error:'Acesso restrito à sua visão de gestor'});
   if(url==='/')return res.redirect(303,'/operations?view=manager');
  }
  if(r!=='owner'&&(url.includes('/audit')||url.startsWith('/api/finance/activity')||url.endsWith('/credential')))return res.status(403).json({error:'Somente Rodolfo'});
  if(r==='partner'&&!['GET','HEAD','OPTIONS'].includes(req.method)&&url!=='/api/meta-account-lookups'&&url!=='/api/google-account-lookups'&&url!=='/api/finance/profile'){
   if(!mayRequest(url))return res.status(403).json({error:'Ação indisponível para proposta'});noSecrets(req.body);
   const id=randomUUID();await db.transaction(async tx=>{await tx.query('INSERT INTO finance_approvals(id,actor,path,payload) VALUES($1,$2,$3,$4::jsonb)',[id,actor(req),url,JSON.stringify(req.body)]);await audit(tx,actor(req),'PROPOSAL_CREATED',null,{id,path:url,payload:req.body});});
   return res.status(202).json({pending:true,request_id:id,message:'Proposta enviada. Nenhum dado financeiro foi alterado; aguarde Rodolfo.'});
  }
  const approval=req.headers['x-finance-approval'];if(approval){if(r!=='owner'||!mayRequest(url)||req.method!=='POST')fail('Aprovação inválida',403);const a=(await db.query('SELECT * FROM finance_approvals WHERE id=$1',[approval])).rows[0];if(!a||a.status!=='pending'||a.path!==url)fail('Proposta incompatível',409);req.body=a.payload;req.proposalActor=a.actor;return context.run({approval,owner:actor(req),used:false},next);}
  next();
 });
 app.get('/operations',(req,res)=>res.sendFile(path.join(root,'public/operations.html')));
 app.get('/api/manager-workspace',async(req,res)=>{const period=String(req.query.period||'2026-08');if(isHistory(period))return res.json(await historyView(b=>historyDocument(db,period,b),period,req.auth,req.query.manager===undefined?undefined:String(req.query.manager)));periodInfo(period);if(role(req)==='partner')fail('Prévia de gestor restrita a Rodolfo',403);const key=role(req)==='manager'?req.auth.manager_key:String(req.query.manager||'nicolas');if(!validManager(key))fail('Gestor não autorizado',403);if(role(req)==='manager'&&req.query.manager!==undefined&&req.query.manager!==key)fail('Acesso restrito ao próprio gestor',403);const s=await scenario(db,workspaceId(period));res.json(managerView(s,[],period,key));});
 app.get('/api/finance/profile',async(req,res)=>{const u=await identity(db,actor(req));if(!u)fail('Usuário não disponível',401);res.json({...publicUser(u),protected:actor(req)==='rodolfo'});});
 app.post('/api/finance/profile',async(req,res)=>{res.json(await saveProfile(db,actor(req),req.body,actor(req)));});
 app.get('/api/finance/users',async(req,res)=>{res.json([await ownerProfile(db),...(await db.query('SELECT username,display_name,email,phone,discord_id,role,manager_key,enabled,revision FROM finance_users ORDER BY username')).rows]);});
 app.post('/api/finance/users',async(req,res)=>{const b=req.body,username=validateText(b.username,'Usuário',40),profile=profileFields(b),name=profile.display_name;if(!/^[a-z0-9_.-]{3,40}$/.test(username)||username==='rodolfo')fail('Usuário inválido ou reservado');if(!['partner','manager'].includes(b.role)||b.role==='manager'&&!validManager(b.manager_key))fail('Gestor não autorizado');noSecrets(b);await db.transaction(async tx=>{await tx.query('INSERT INTO finance_users(username,display_name,role,manager_key,enabled,email,phone,discord_id) VALUES($1,$2,$3,$4,false,$5,$6,$7)',[username,name,b.role,b.role==='manager'?b.manager_key:null,profile.email,profile.phone,profile.discord_id]);await audit(tx,actor(req),'USER_CREATED_DISABLED',null,{username,display_name:name,role:b.role,manager_key:b.role==='manager'?b.manager_key:null});});res.status(201).json(publicUser((await db.query('SELECT * FROM finance_users WHERE username=$1',[username])).rows[0]));});
 app.post('/api/finance/users/:username',async(req,res)=>{const b=req.body;noSecrets(b);const editing=Object.hasOwn(b,'display_name');if(!Number.isInteger(b.revision)||(!editing&&typeof b.enabled!=='boolean')||(editing&&Object.hasOwn(b,'enabled')))fail('Estado/revisão inválidos');if(editing)return res.json(await saveProfile(db,req.params.username,b,actor(req)));if(req.params.username==='rodolfo')fail('Login e acesso do administrador são protegidos',403);const profile=null;await db.transaction(async tx=>{const old=(await tx.query('SELECT * FROM finance_users WHERE username=$1 FOR UPDATE',[req.params.username])).rows[0];if(!old||old.revision!==b.revision)fail('Usuário/revisão incompatível',409);if(editing){await tx.query('UPDATE finance_users SET display_name=$2,email=$3,phone=$4,discord_id=$5,revision=revision+1 WHERE username=$1',[old.username,profile.display_name,profile.email,profile.phone,profile.discord_id]);await audit(tx,actor(req),'USER_PROFILE_CHANGED',publicUser(old),{username:old.username,...profile});}else{if(b.enabled&&!old.password_hash)fail('Defina primeiro uma senha pelo administrador');await tx.query('UPDATE finance_users SET enabled=$2,revision=revision+1 WHERE username=$1',[old.username,b.enabled]);await tx.query('UPDATE auth_sessions SET revoked=true WHERE username=$1',[old.username]);await audit(tx,actor(req),'USER_ACCESS_CHANGED',publicUser(old),{username:old.username,enabled:b.enabled});}});res.json(publicUser((await db.query('SELECT * FROM finance_users WHERE username=$1',[req.params.username])).rows[0]));});
 app.post('/api/finance/users/:username/credential',async(req,res)=>{if(role(req)!=='owner')fail('Somente Rodolfo',403);const b=req.body;if(typeof b.password!=='string'||b.password.length<14||Buffer.byteLength(b.password)>1024||!Number.isInteger(b.revision))fail('Senha exige pelo menos 14 caracteres e revisão válida');const salt=randomBytes(24).toString('hex'),hash=(await derive(b.password,salt,64)).toString('hex');await db.transaction(async tx=>{const u=await tx.query('UPDATE finance_users SET salt=$2,password_hash=$3,enabled=true,revision=revision+1 WHERE username=$1 AND revision=$4 RETURNING username',[req.params.username,salt,hash,b.revision]);if(!u.rows.length)fail('Usuário/revisão incompatível',409);await tx.query('UPDATE auth_sessions SET revoked=true WHERE username=$1',[req.params.username]);await audit(tx,actor(req),'USER_CREDENTIAL_SET',null,{username:req.params.username,enabled:true});});res.json(publicUser((await db.query('SELECT * FROM finance_users WHERE username=$1',[req.params.username])).rows[0]));});
 app.get('/api/finance/approvals',async(req,res)=>{const owner=role(req)==='owner';res.json((await db.query('SELECT id,actor,path,payload,status,created_at,decided_at,decided_by,reason FROM finance_approvals '+(owner?'':'WHERE actor=$1 ')+'ORDER BY created_at DESC LIMIT 200',owner?[]:[actor(req)])).rows);});
 app.post('/api/finance/approvals/:id/reject',async(req,res)=>{if(role(req)!=='owner')fail('Somente Rodolfo',403);const reason=validateText(req.body.reason,'Motivo',300);await db.transaction(async tx=>{const r=await tx.query("UPDATE finance_approvals SET status='rejected',decided_at=now(),decided_by=$2,reason=$3 WHERE id=$1 AND status='pending' RETURNING id",[req.params.id,actor(req),reason]);if(!r.rows.length)fail('Proposta já decidida',409);await audit(tx,actor(req),'PROPOSAL_REJECTED',null,{id:req.params.id,reason});});res.json((await db.query('SELECT id,status,reason FROM finance_approvals WHERE id=$1',[req.params.id])).rows[0]);});
 app.get('/api/finance/activity',async(req,res)=>{if(role(req)!=='owner')fail('Somente Rodolfo',403);const offset=Math.max(0,Number(req.query.offset)||0),who=String(req.query.actor||''),values=who?[who]:[],where=who?'WHERE actor=$1':'';values.push(offset);const rows=(await db.query(`SELECT id,scenario_id,actor,action,before_data,after_data,created_at FROM audit_events ${where} ORDER BY id DESC LIMIT 101 OFFSET $${values.length}`,values)).rows;res.json({rows:clean(rows.slice(0,100)),offset,has_more:rows.length>100});});
 app.get('/api/finance/ledger',async(req,res)=>res.json(await ledger(db,String(req.query.period||'2026-08'),String(req.query.counterparty||''),req)));
 app.post('/api/finance/ledger',async(req,res)=>{const b=req.body;periodInfo(b.period);await ledger(db,b.period,b.counterparty,req);if(!['adjustment','payment'].includes(b.kind)||![1,-1].includes(b.direction)||b.kind==='payment'&&b.direction!==-1)fail('Natureza do lançamento inválida');if(typeof b.amount!=='string'||!/^\d+(?:\.\d{1,2})?$/.test(b.amount)||cents(b.amount)<=0)fail('Valor positivo, com no máximo 2 casas');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||!Number.isFinite(Date.parse(b.date))||new Date(b.date).toISOString().slice(0,10)!==b.date||b.date>today())fail('Informe uma data real, não futura');const description=validateText(b.description,'Descrição',300),id=typeof b.id==='string'&&/^[a-f0-9-]{36}$/.test(b.id)?b.id:randomUUID();await db.transaction(async tx=>{const r=await tx.query('INSERT INTO finance_ledger(id,counterparty,period,effective_date,kind,amount_cents,direction,description,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING RETURNING id',[id,b.counterparty,b.period,b.date,b.kind,cents(b.amount),b.direction,description,actor(req)]);if(!r.rows.length)fail('Lançamento já registrado; confira o extrato antes de repetir',409);await audit(tx,actor(req),'LEDGER_ENTRY_RECORDED',null,{id,...b,amount_cents:cents(b.amount)});});res.status(201).json((await db.query('SELECT * FROM finance_ledger WHERE id=$1',[id])).rows[0]);});
 app.post('/api/finance/ledger/:id/void',async(req,res)=>{const reason=validateText(req.body.reason,'Motivo do estorno',300);await db.transaction(async tx=>{const before=(await tx.query('SELECT * FROM finance_ledger WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!before||before.voided_at)fail('Lançamento não disponível para estorno',409);await tx.query('UPDATE finance_ledger SET voided_at=now(),voided_by=$2 WHERE id=$1',[req.params.id,actor(req)]);await audit(tx,actor(req),'LEDGER_ENTRY_VOIDED',before,{id:req.params.id,reason});});res.json((await db.query('SELECT * FROM finance_ledger WHERE id=$1',[req.params.id])).rows[0]);});
}
