// Authenticated on-demand lookup queue. No Meta token or network in the web process.
import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID} from 'node:crypto';import {root} from './storage.mjs';
export const LOOKUP_DIR=path.join(root,'private/meta-account-lookups');
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
export function accountId(value){if(typeof value!=='string'||!/^\d{5,30}$/.test(value))fail('Informe somente o ID numérico da conta, sem act_');return value;}
const file=id=>{if(typeof id!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id))fail('Consulta inválida');return path.join(LOOKUP_DIR,id+'.json');};
export async function readLookup(id){let d;try{d=JSON.parse(await fs.readFile(file(id),'utf8'));}catch(e){if(e.code==='ENOENT')fail('Consulta não encontrada',404);throw e;}if(d.request_id!==id)fail('Consulta inconsistente',503);return d;}
export async function startLookup(id,actor){accountId(id);await fs.mkdir(LOOKUP_DIR,{recursive:true,mode:0o700});const files=(await fs.readdir(LOOKUP_DIR)).filter(f=>f.endsWith('.json'));if(files.length>=10000)fail('Fila requer manutenção; contate Zeus',503);let pending=0;for(const name of files){const d=JSON.parse(await fs.readFile(path.join(LOOKUP_DIR,name),'utf8'));if(d.status==='pending'&&Date.now()-Date.parse(d.requested_at)<120000){pending++;if(d.account_id===id&&d.actor===actor)return d;}}if(pending>=16)fail('Consultas em andamento; aguarde',429);const d={request_id:randomUUID(),account_id:id,actor,status:'pending',requested_at:new Date().toISOString()};await fs.writeFile(file(d.request_id),JSON.stringify(d),{flag:'wx',mode:0o600});return d;}
export function publicLookup(d){const expired=d.status==='pending'&&Date.now()-Date.parse(d.requested_at)>120000;return {request_id:d.request_id,account_id:d.account_id,status:expired?'error':d.status,name:d.name,currency:d.currency,timezone:d.timezone,business_id:d.business_id,verified_at:d.verified_at,error:expired?'A consulta demorou demais. Tente novamente; nenhum cadastro foi feito.':d.error};}
export async function verifiedAccount(requestId,id){const d=await readLookup(requestId);if(d.account_id!==accountId(id)||d.status!=='ready'||d.business_id!=='155263197283282'||!d.verified_at||Date.now()-Date.parse(d.verified_at)>600000)fail('Consulte novamente este ID na BM antes de salvar');if(!d.name||!['USD','BRL','CAD','GBP'].includes(d.currency)||!d.timezone)fail('Dados incompletos ou moeda não suportada na BM');return d;}
export function installMetaLookup(app){app.post('/api/meta-account-lookups',async(req,res)=>res.status(202).json(publicLookup(await startLookup(req.body.id,req.actor||'Operador local'))));app.get('/api/meta-account-lookups/:id',async(req,res)=>res.json(publicLookup(await readLookup(req.params.id))));}
