import fs from 'node:fs';
import assert from 'node:assert/strict';
import {openPostgres,calculate} from '/home/mgsfinance/releases/pg-auth-1545934831664242748/storage.mjs';
const [phase,database,planPath]=process.argv.slice(2);assert.ok(['apply','verify'].includes(phase));assert.match(database,/^mgs_finance(?:_gam_1547692440574627921)?$/);const plan=JSON.parse(fs.readFileSync(planPath,'utf8'));assert.equal(plan.authorization_message_id,'1547692440574627921');assert.equal(plan.period,'2026-09');assert.equal(plan.source_sha256,'f7047d7ab39a1412a969bc3528bc9b5c6fd763306ad2145ee98a545c81c55477');
const db=await openPostgres({database});const scenarioId=plan.scenario_id,prefix='gam-2026-09-01-09-f7047d7ab39a';
const number=v=>Number(v||0),near=(a,b,t=1e-7)=>Math.abs(number(a)-number(b))<=t;
const currentValue=(row,key)=>row.overrides?.[key]??'';
const rate=(row,key)=>String(row.overrides?.[key]??row.result?.results?.[key]?.actual??'');
function refreshedEntries(row){const q={USDBRL:rate(row,'principal|Agosto 2026|F1'),USDCAD:rate(row,'principal|Agosto 2026|H1'),GBPUSD:rate(row,'principal|Agosto 2026|I1')},r={invalid_rate:rate(row,'principal|Agosto 2026|L1'),share_rate:rate(row,'principal|Agosto 2026|D1'),tax_rate:rate(row,'principal|Agosto 2026|C1')};for(const v of Object.values({...q,...r}))assert.match(v,/^\d+(?:\.\d+)?$/);return plan.native_entries.map(x=>({...x,...r,quotes:q}));}
function targetState(row){const entries=row.additions.filter(x=>x.source_import_id===prefix||String(x.id||'').startsWith(prefix));return {revision:row.revision,state:row.state,inputs:Object.fromEntries(plan.changes.map(x=>[x.key,currentValue(row,x.key)])),entries};}
function validateResult(before,result,entries){assert.equal(result.summary.counts.error||0,0);const byId=new Map(result.domain.facts.map(x=>[x.id,x]));for(const e of entries){const f=byId.get(e.id);assert.ok(f,e.id);assert.equal(f.site,e.site);assert.equal(f.country,e.country);assert.equal(f.date,e.date);assert.equal(f.manager,e.manager);const expected=e.currency==='CAD'?number(e.gross)/number(e.quotes.USDCAD):e.currency==='BRL'?number(e.gross)/number(e.quotes.USDBRL):e.currency==='GBP'?number(e.gross)*number(e.quotes.GBPUSD):number(e.gross);assert.ok(near(f.gross,expected,1e-7),e.id);}
 const actual={};for(const f of result.domain.facts)if(f.date>='2026-09-01'&&f.date<='2026-09-09')actual[f.date]=(actual[f.date]||0)+number(f.gross);const cadRate=number(entries[0].quotes.USDCAD);for(let d=1;d<=9;d++){const day='2026-09-'+String(d).padStart(2,'0'),usd=number(plan.source_totals['USD|'+day]),cad=number(plan.source_totals['CAD|'+day]),expected=usd+cad/cadRate;assert.ok(near(actual[day],expected,2e-7),day+' '+actual[day]+' '+expected);}
 const priorFacts=before.result.domain.facts.filter(f=>f.date>='2026-09-01'&&f.date<='2026-09-09');assert.ok(near(priorFacts.reduce((s,f)=>s+number(f.gross),0),0,1e-10),'days1-9 already contain revenue');
 for(const k of ['spend','company_expenses','personnel'])assert.ok(near(result.domain.cash[k],before.result.domain.cash[k],1e-8),k);
 return {daily_usd:actual,cad_rate:cadRate,gross_usd:result.domain.cash.gross,spend_usd:result.domain.cash.spend,company_expenses_usd:result.domain.cash.company_expenses,personnel_usd:result.domain.cash.personnel};}
try{
 if(phase==='apply'){
  const out=await db.transaction(async tx=>{
   const row=(await tx.query('SELECT * FROM scenarios WHERE id=$1 FOR UPDATE',[scenarioId])).rows[0];assert.ok(row);assert.equal(row.state,'draft');const entries=refreshedEntries(row),existing=targetState(row).entries;
   const allInputsSame=plan.changes.every(x=>String(currentValue(row,x.key))===String(x.value));const existingSimple=existing.map(x=>({id:x.id,gross:String(x.gross),currency:x.currency,date:x.date,site:x.site,country:x.country,manager:x.manager})).sort((a,b)=>a.id.localeCompare(b.id));const plannedSimple=entries.map(x=>({id:x.id,gross:String(x.gross),currency:x.currency,date:x.date,site:x.site,country:x.country,manager:x.manager})).sort((a,b)=>a.id.localeCompare(b.id));
   if(existing.length||allInputsSame){assert.equal(JSON.stringify(existingSimple),JSON.stringify(plannedSimple),'existing import differs');assert.ok(allInputsSame,'partial existing input import');return {already_applied:true,before_revision:row.revision,after_revision:row.revision,result:row.result,entries};}
   assert.ok(plan.changes.every(x=>currentValue(row,x.key)===''),'target revenue input already populated');const otherAdditions=row.additions.filter(x=>!(x.source_import_id===prefix||String(x.id||'').startsWith(prefix)));assert.equal(otherAdditions.length,row.additions.length);
   const overrides={...row.overrides,...Object.fromEntries(plan.changes.map(x=>[x.key,x.value]))},additions=[...otherAdditions,...entries];const result=await calculate({period:plan.period,overrides,additions});const metrics=validateResult(row,result,entries);
   const u=await tx.query("UPDATE scenarios SET overrides=$1::jsonb,additions=$2::jsonb,result=$3::jsonb,revision=revision+1,updated_at=now() WHERE id=$4 AND revision=$5 AND state='draft' RETURNING revision",[JSON.stringify(overrides),JSON.stringify(additions),JSON.stringify(result),scenarioId,row.revision]);assert.equal(u.rows.length,1);
   await tx.query('INSERT INTO audit_events(scenario_id,actor,action,before_data,after_data) VALUES($1,$2,$3,$4::jsonb,$5::jsonb)',[scenarioId,'zeus','GAM_REVENUE_IMPORTED',JSON.stringify({revision:row.revision,gross_days_1_9:0}),JSON.stringify({authorization:'1547692440574627921',source_sha256:plan.source_sha256,date_range:plan.date_range,source_rows:plan.source_rows,input_fields:plan.changes.length,native_entries:entries.length,totals:plan.source_totals,validation:'18 currency-days reconciled'})]);
   return {already_applied:false,before_revision:row.revision,after_revision:u.rows[0].revision,result,entries,metrics};
  });
  const row=(await db.query('SELECT * FROM scenarios WHERE id=$1',[scenarioId])).rows[0],state=targetState(row);assert.equal(state.revision,out.after_revision);assert.equal(state.entries.length,plan.native_entries.length);assert.ok(plan.changes.every(x=>String(state.inputs[x.key])===String(x.value)));const audit=(await db.query("SELECT id,actor,action,after_data,created_at FROM audit_events WHERE scenario_id=$1 AND action='GAM_REVENUE_IMPORTED' ORDER BY id DESC LIMIT 1",[scenarioId])).rows[0];assert.ok(audit||out.already_applied);
  console.log(JSON.stringify({pass:true,database,phase,already_applied:out.already_applied,before_revision:out.before_revision,after_revision:out.after_revision,input_fields:plan.changes.length,native_entries:state.entries.length,source_rows:plan.source_rows,source_sha256:plan.source_sha256,all_18_currency_days:true,pending_classifications:0,baseline_untouched:true,other_additions_preserved:true,audit_id:audit?.id||null,metrics:out.metrics||null}));
 }else{
  const row=(await db.query('SELECT * FROM scenarios WHERE id=$1',[scenarioId])).rows[0],state=targetState(row),entries=state.entries;assert.equal(entries.length,plan.native_entries.length);assert.ok(plan.changes.every(x=>String(state.inputs[x.key])===String(x.value)));const expected=plan.native_entries.map(x=>x.id).sort();assert.deepEqual(entries.map(x=>x.id).sort(),expected);const audit=(await db.query("SELECT id,actor,action,after_data,created_at FROM audit_events WHERE scenario_id=$1 AND action='GAM_REVENUE_IMPORTED' ORDER BY id DESC LIMIT 1",[scenarioId])).rows[0];assert.ok(audit);console.log(JSON.stringify({pass:true,database,phase,revision:row.revision,input_fields:plan.changes.length,native_entries:entries.length,source_rows:plan.source_rows,audit_id:audit.id,source_sha256:audit.after_data.source_sha256,all_18_currency_days:audit.after_data.validation==='18 currency-days reconciled'}));
 }
}finally{await db.close();}
