import {chromium} from '/root/mgs-agent/apps/finance-system/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const base='https://dash.mgsdigitalcorp.com',dir='/root/mgs-agent/work/finance-revenue-1547692440574627921';const plan=JSON.parse(await fs.readFile(dir+'/import-plan.json','utf8'));const chunks=[];for await(const c of process.stdin)chunks.push(c);const credential=JSON.parse(Buffer.concat(chunks).toString());let browser;
const n=v=>Number(v||0),near=(a,b,t=1e-7)=>Math.abs(n(a)-n(b))<=t;
try{
 browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/New_York'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);
 await page.goto(base);await page.waitForURL('**/login');await page.locator('#username').fill(credential.username);await page.locator('#password').fill(credential.password);await page.locator('button[type=submit]').click();await page.waitForSelector('.cards');
 const meRes=await context.request.get(base+'/api/auth/me');assert.equal(meRes.status(),200);const me=await meRes.json();assert.equal(me.username,'rodolfo');assert.equal(me.role,'owner');
 const res=await context.request.get(base+'/api/workspace?period=2026-09');assert.equal(res.status(),200);const w=await res.json();assert.equal(w.id,'workspace-2026-09');assert.equal(w.state,'draft');assert.ok(w.revision>=80);
 const imported=w.additions.filter(x=>x.source_import_id==='gam-2026-09-01-09-f7047d7ab39a');assert.equal(imported.length,plan.native_entries.length);assert.deepEqual(imported.map(x=>x.id).sort(),plan.native_entries.map(x=>x.id).sort());for(const x of plan.changes)assert.equal(String(w.model.inputs[x.key].value),String(x.value));
 const byAddition=new Map(imported.map(x=>[x.id,x])),origins={};for(const f of w.domain.facts.filter(f=>f.date>='2026-09-01'&&f.date<='2026-09-09')){const keys=[...new Set(w.model.facts[f.id]?.gross||[])];if(keys.length){for(const key of keys){const x=w.model.inputs[key];if(!x)continue;const currency=x.book==='principal'&&x.source===f.source?.gross?'USD':x.currency;origins[currency+'|'+f.date]=(origins[currency+'|'+f.date]||0)+n(x.value);}}else{const a=byAddition.get(f.id);if(a)origins[a.currency+'|'+f.date]=(origins[a.currency+'|'+f.date]||0)+n(a.gross);}}
 const nonzeroOrigins=Object.fromEntries(Object.entries(origins).filter(([,v])=>Math.abs(v)>1e-12));assert.deepEqual(Object.keys(nonzeroOrigins).sort(),Object.keys(plan.source_totals).sort());for(const [k,v] of Object.entries(plan.source_totals))assert.ok(near(nonzeroOrigins[k],v,2e-7),k+' '+nonzeroOrigins[k]+' '+v);
 const activity=await context.request.get(base+'/api/finance/activity');assert.equal(activity.status(),200);const events=await activity.json();assert.ok(events.rows.some(x=>x.action==='GAM_REVENUE_IMPORTED'&&x.after_data?.source_sha256===plan.source_sha256));
 await page.locator('#period').selectOption('2026-09');await page.waitForFunction(()=>document.querySelector('.context-note')?.textContent.includes('Setembro 2026'));await page.locator('#nav [data-main-view=movement]').click();await page.waitForFunction(()=>document.querySelector('#title')?.textContent==='Relatório Diário');const body=await page.locator('#content').innerText();assert.ok(body.includes('Gross CAD'));assert.equal(await page.locator('[data-financial-total] tbody tr').count(),31);
 for(const [query,site] of [['topfeed','FinanceTopFeed'],['yolokfx','Yolokfx'],['mavroa','Mavroa'],['escalatepower','Escalatepower']]){await page.locator('#siteSearch').fill(query);await page.waitForFunction(s=>document.querySelectorAll(`[data-site="${s}"]`).length>0,site);assert.ok(await page.locator(`[data-site="${site}"]`).count()>0,site);}await page.locator('#siteSearch').fill('');await page.screenshot({path:dir+'/dashboard-september-desktop.png',fullPage:false});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.screenshot({path:dir+'/dashboard-september-mobile.png',fullPage:false});assert.equal(errors.length,0,JSON.stringify(errors));
 const logout=await context.request.post(base+'/api/auth/logout',{headers:{Origin:base,'X-CSRF-Token':me.csrf},data:{}});assert.equal(logout.status(),200);
 const out={pass:true,identity:'rodolfo',role:'owner',period:'2026-09',revision:w.revision,source_sha256:plan.source_sha256,source_rows:plan.source_rows,input_fields:plan.changes.length,native_entries:imported.length,origin_totals:nonzeroOrigins,all_18_currency_days:true,audit_readback:true,daily_table_rows:31,desktop:true,mobile:true,js_errors:0,download_excel_sha256:plan.source_sha256};await fs.writeFile(dir+'/public-readback.json',JSON.stringify(out,null,2));console.log(JSON.stringify({pass:true,revision:w.revision,input_fields:out.input_fields,native_entries:out.native_entries,all_18_currency_days:true,audit_readback:true,daily_table_rows:31,desktop:true,mobile:true,js_errors:0}));
}catch(e){console.log(JSON.stringify({pass:false,name:e.name,message:String(e.message).slice(0,1400)}));process.exitCode=1;}finally{await browser?.close();}
