import {openPostgres} from '/home/mgsfinance/releases/pg-auth-1545934831664242748/storage.mjs';
import assert from 'node:assert/strict';
const db=await openPostgres({database:'mgs_finance'});const out={};
try{
 const tableNames=['imports','source_cells','scenarios','entity_versions','audit_events','acceptance_runs','finance_history','finance_ledger','finance_approvals','finance_users','auth_sessions','auth_limits'];out.table_counts={};for(const table of tableNames)out.table_counts[table]=Number((await db.query(`SELECT count(*)::int n FROM ${table}`)).rows[0].n);
 out.source={imports:(await db.query('SELECT id,source_sha256,period,created_at FROM imports ORDER BY created_at')).rows,source_cells_by_kind:(await db.query('SELECT kind,count(*)::int n FROM source_cells GROUP BY kind ORDER BY kind')).rows};
 const rows=(await db.query("SELECT * FROM scenarios WHERE id LIKE 'workspace-%' ORDER BY id")).rows;out.workspaces=[];const issues=[];
 for(const row of rows){const period=row.id.slice(10),facts=row.result?.domain?.facts||[],catalog=row.result?.domain?.site_catalog||[],managers=row.result?.domain?.managers||[],additions=row.additions||[],ids=additions.map(x=>x.id).filter(Boolean),duplicates=[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))],cutoffs=additions.filter(x=>x.kind==='data_cutoff'),dailyRevenue=additions.filter(x=>x.source_import_type==='gam_email_daily'),accountSpend=additions.filter(x=>x.kind==='account_spend'),expense=additions.filter(x=>x.kind==='expense'),rates=additions.filter(x=>x.kind==='rate');const badFactDates=facts.filter(x=>!String(x.date||'').startsWith(period+'-')).length;const nonfinite=['gross','invalid','net','tax','spend','profit'].filter(key=>!Number.isFinite(Number(row.result?.domain?.cash?.[key])));const sourceCurrencyTotals={};for(const a of dailyRevenue){const key=a.source_date+'|'+a.currency;sourceCurrencyTotals[key]=(sourceCurrencyTotals[key]||0)+Number(a.gross||0);}const summary={id:row.id,state:row.state,revision:row.revision,period,error_count:Number(row.result?.summary?.counts?.error||0),facts:facts.length,bad_fact_dates:badFactDates,additions:additions.length,duplicate_addition_ids:duplicates,cutoff_count:cutoffs.length,cutoff_date:cutoffs[0]?.date??null,revenue_dates:[...new Set(dailyRevenue.map(x=>x.source_date))].sort(),revenue_entries:dailyRevenue.length,revenue_source_totals:sourceCurrencyTotals,spend_min_date:accountSpend.map(x=>x.date).sort()[0]||null,spend_max_date:accountSpend.map(x=>x.date).sort().at(-1)||null,spend_entries:accountSpend.length,expense_overrides:expense.length,rate_overrides:rates.length,sites:catalog.length,active_sites:catalog.filter(x=>x.status==='ATIVO').length,inactive_sites:catalog.filter(x=>x.status==='INATIVO').length,manager_rows:managers.length,realized:row.result?.domain?.realized,projection:row.result?.domain?.projection,cash:row.result?.domain?.cash,nonfinite_cash:nonfinite};out.workspaces.push(summary);if(summary.state!=='draft'||summary.error_count||badFactDates||duplicates.length||cutoffs.length!==1||nonfinite.length)issues.push({period,type:'workspace_invariant',summary:{state:summary.state,errors:summary.error_count,badFactDates,duplicates:duplicates.length,cutoffs:cutoffs.length,nonfinite}});}
 const expected=[];for(let y=2026,m=8;y<2028;){expected.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m===13){m=1;y++;}if(y===2028)break;}assert.equal(expected.at(-1),'2027-12');if(JSON.stringify(out.workspaces.map(x=>x.period))!==JSON.stringify(expected))issues.push({type:'workspace_period_set'});
 for(const w of out.workspaces){const expectedCutoff=w.period==='2026-08'?'2026-08-31':w.period==='2026-09'?'2026-09-10':null;if(w.cutoff_date!==expectedCutoff)issues.push({period:w.period,type:'cutoff',actual:w.cutoff_date,expected:expectedCutoff});if(w.period>'2026-09'&&w.projection?.half_usd!==null)issues.push({period:w.period,type:'future_projection'});}
 const sep=out.workspaces.find(x=>x.period==='2026-09');const latestRevenue=sep.revenue_dates.at(-1)||'2026-09-09';if(sep.cutoff_date>latestRevenue||sep.cutoff_date>sep.spend_max_date)issues.push({type:'cutoff_exceeds_complete_sources',cutoff:sep.cutoff_date,latestRevenue,latestSpend:sep.spend_max_date});out.current_source_alignment={cutoff:sep.cutoff_date,latest_revenue:latestRevenue,latest_spend:sep.spend_max_date,pass:sep.cutoff_date<=latestRevenue&&sep.cutoff_date<=sep.spend_max_date};
 out.history={rows:(await db.query('SELECT period,book,count(*)::int versions,max(imported_at) latest FROM finance_history GROUP BY period,book ORDER BY period,book')).rows,periods:(await db.query('SELECT period,count(DISTINCT book)::int books,count(*)::int versions FROM finance_history GROUP BY period ORDER BY period')).rows};
 out.users=(await db.query("SELECT role,enabled,count(*)::int n,count(manager_key)::int with_manager FROM finance_users GROUP BY role,enabled ORDER BY role,enabled")).rows;out.sessions=(await db.query("SELECT count(*) FILTER(WHERE NOT revoked AND expires_at>now())::int active,count(*) FILTER(WHERE revoked)::int revoked,count(*) FILTER(WHERE expires_at<=now())::int expired FROM auth_sessions")).rows[0];out.approvals=(await db.query('SELECT status,count(*)::int n FROM finance_approvals GROUP BY status ORDER BY status')).rows;out.ledger=(await db.query('SELECT kind,count(*)::int n,count(*) FILTER(WHERE voided_at IS NOT NULL)::int voided FROM finance_ledger GROUP BY kind ORDER BY kind')).rows;out.audit={max_id:Number((await db.query('SELECT coalesce(max(id),0)::bigint id FROM audit_events')).rows[0].id),actions:(await db.query('SELECT action,count(*)::int n FROM audit_events GROUP BY action ORDER BY n DESC,action LIMIT 20')).rows,daily_gam_20260910:Number((await db.query("SELECT count(*)::int n FROM audit_events WHERE action='GAM_EMAIL_DAILY_IMPORTED' AND after_data->>'date'='2026-09-10'")).rows[0].n)};out.recoveries=(await db.query("SELECT id,state,revision FROM scenarios WHERE id LIKE 'recovery-%' ORDER BY id")).rows;out.issues=issues;out.pass=issues.length===0&&out.current_source_alignment.pass;console.log(JSON.stringify(out));
}finally{await db.close();}
