import sys,json,re,urllib.parse,pathlib,datetime
from decimal import Decimal as D
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env,load_service_account,service_account_access_token,api_json
load_env();sa=load_service_account();assert sa['client_email']=='mgsagent@mgs-core-prod.iam.gserviceaccount.com';token=service_account_access_token(['https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/drive.metadata.readonly']);quota='mgs-core-prod';sid='16umGPmLukDGQtCEBh2inYLnE9xcqWbHa3gJCM9HG9ak';OUT=pathlib.Path('/root/mgs-agent/work/finance-payments-indicators-1547706561210753114')
active=json.loads((OUT/'july-active-history-refs.json').read_text());hist={c['a1']:c for c in active['cells']};live_summary=json.loads((OUT/'july-live-summary.json').read_text())['points'];formula=live_summary['H136']['formula'];refs=re.findall(r'(?<![!A-Z0-9_])([A-Z]{1,3}\d+)',formula);assert refs and len(refs)==len(set(refs))
points=['F1','J1','K1','L1','F103','F129','F132','H136','I136','I137'];spec=[('Julho 2026',a) for a in dict.fromkeys(refs+points)]+[('Junho 2026','F132')];ranges=[f"'{s}'!{a}" for s,a in spec]
q=urllib.parse.urlencode([('ranges',r) for r in ranges]+[('majorDimension','ROWS'),('valueRenderOption','UNFORMATTED_VALUE'),('dateTimeRenderOption','SERIAL_NUMBER')]);status,data=api_json('GET','https://sheets.googleapis.com/v4/spreadsheets/'+sid+'/values:batchGet?'+q,token,quota_project=quota);assert status==200
values={(s,a):(v.get('values') or [[None]])[0][0] for (s,a),v in zip(spec,data['valueRanges'])};cur=lambda a:D(str(values['Julho 2026',a] or 0));old=lambda a:D(str(hist[a].get('value') or 0))
changes=[]
for a in refs:
 delta=cur(a)-old(a)
 if abs(delta)>D('0.000000001'):changes.append({'cell':a,'before':str(old(a)),'after':str(cur(a)),'delta':str(delta)})
sum_delta=sum((D(x['delta']) for x in changes),D(0));h_before=old('H136');h_after=cur('H136');h_bridge=(h_after-h_before)-sum_delta;assert abs(h_bridge)<D('0.000001')
fx_before=old('F1');fx_after=cur('F1');i137_before=old('I137');i137_after=cur('I137');assert abs(i137_after-h_after*fx_after/D(2))<D('0.000001');assert abs(i137_before-h_before*fx_before/D(2))<D('0.000001')
due_before=D(active['closure']['due']['raw']);due_after=cur('F103');due_delta=due_after-due_before;due_bridge=due_delta-(i137_after-i137_before);assert abs(due_bridge)<D('0.000001')
previous_before=D(active['closure']['previous']['raw']);previous_after=cur('F129');balance_before=D(active['closure']['balance']['raw']);balance_after=cur('F132');balance_bridge=(balance_after-balance_before)-(due_delta+previous_after-previous_before);assert abs(balance_bridge)<D('0.000001')
invalid_before={a:old(a) for a in ['J1','K1','L1']};invalid_after={a:cur(a) for a in ['J1','K1','L1']};assert invalid_before==invalid_after;assert fx_before==fx_after
status,drive=api_json('GET','https://www.googleapis.com/drive/v3/files/'+sid+'?fields=id,modifiedTime&supportsAllDrives=true',token,quota_project=quota);assert status==200
out={'pass':True,'captured_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dashboard_snapshot_capture':active['captured_at'],'dashboard_source_sha256':active['source_sha256'],'live_modifiedTime':drive['modifiedTime'],'h136_formula_unchanged':True,'h136_before':str(h_before),'h136_after':str(h_after),'h136_delta':str(h_after-h_before),'changed_components':changes,'fx_before':str(fx_before),'fx_after':str(fx_after),'invalid_rates_before':{k:str(v) for k,v in invalid_before.items()},'invalid_rates_after':{k:str(v) for k,v in invalid_after.items()},'due_before':str(due_before),'due_after':str(due_after),'due_delta':str(due_delta),'previous_before':str(previous_before),'previous_after':str(previous_after),'previous_delta':str(previous_after-previous_before),'balance_before':str(balance_before),'balance_after':str(balance_after),'balance_delta':str(balance_after-balance_before),'movement_delta':'0','current_june_close':str(D(str(values['Junho 2026','F132']))),'bridges':{'h136':str(h_bridge),'due':str(due_bridge),'balance':str(balance_bridge)},'sheet_writes':0}
(OUT/'july-difference-analysis.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps(out,ensure_ascii=False))
