import pathlib,json,hashlib,datetime,fcntl,os
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';P=R/'data/infra-inventory.json';AUTH='1547790708344234056';ID='zeus-finance-current-policy-1547732274936553532';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
with open('/var/lock/infra_discovery.lock','a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);data=json.loads(P.read_text());entry=next(x for x in data['runtime_artifacts'] if x.get('id')==ID);entry['authorization_message_ids']=list(dict.fromkeys(entry['authorization_message_ids']+[AUTH]));entry['updated_at']=now;entry['status']='published_verified_cards_100_percent';by={x['path']:x for x in entry['paths']};
 for p in [A/'public/app.js',A/'public/index.html',A/'tests/ui-country-blocks.test.mjs',A/'tests/current-policy-public.mjs',R/'docs/finance-system-product-direction.md',R/'reports/finance-current-policy-1547732274936553532.md',R/'profiles/zeus-skills/ops/mgs-finance-dashboard/SKILL.md',R/'profiles/zeus-skills/ops/mgs-finance-dashboard/references/current-realized-cutoff-site-status-history-refresh.md']:
  by[str(p)]={'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
 entry['paths']=list(by.values());entry['validation'].update({'node_tests':113,'cards_100_percent':True,'estimated_full_usd_public_readback':94549.28307745779});entry['backup_cards_100']='/home/zeus/mgs-finance-backups/'+AUTH;data['_meta']['updated_at']=now;tmp=P.with_name(P.name+'.cards100.pending');tmp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');os.replace(tmp,P);rb=next(x for x in json.loads(P.read_text())['runtime_artifacts'] if x.get('id')==ID);assert rb['validation']['cards_100_percent'] and rb['validation']['node_tests']==113
with (R/'logs/events-audit.jsonl').open('a') as f:f.write(json.dumps({'timestamp':now,'actor':'zeus','event':'finance_dashboard_cards_100_percent_published_verified','authorization_message_id':AUTH,'source_thread_id':'1545426987756298340','inventory_id':ID,'files':['apps/finance-system/public/app.js','apps/finance-system/public/index.html'],'tests':{'node':113,'public_browser':True,'js_errors':0},'database_writes':0,'backup':'/home/zeus/mgs-finance-backups/'+AUTH},ensure_ascii=False)+'\n')
out={'pass':True,'timestamp':now,'inventory_id':ID,'inventory_readback':True,'node_tests':113,'public_browser':True,'realized_full_usd':28364.784923237337,'estimated_full_usd':94549.28307745779,'july_unchanged_brl':-1090.0485236818408,'backup':'/home/zeus/mgs-finance-backups/'+AUTH};(R/'work/finance-current-policy-1547732274936553532/cards-100-final-readback.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps(out))
