import sys,pathlib,hashlib,json,shlex
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,'/root/mgs-agent/apps/finance-system/deploy');from runcloud_ops import ssh
AUTH='1547790708344234056';A=pathlib.Path('/root/mgs-agent/apps/finance-system');TARGET='/home/mgsfinance/releases/pg-auth-1545934831664242748';BACKUP='/home/zeus/mgs-finance-backups/'+AUTH;STAGE='/var/tmp/mgs-finance-cards-100-'+AUTH;files=['public/app.js','public/index.html'];new={f:hashlib.sha256((A/f).read_bytes()).hexdigest() for f in files};before={f:ssh('sudo -n -u mgsfinance sha256sum '+TARGET+'/'+f).split()[0] for f in files};assert all(before[f]!=new[f] for f in files);ssh('sudo -n install -d -o zeus -g zeus -m 700 '+BACKUP+' && sudo -n tar -czf '+BACKUP+'/code-before.tar.gz -C '+TARGET+' '+' '.join(files)+' && sudo -n chown zeus:zeus '+BACKUP+'/code-before.tar.gz && chmod 600 '+BACKUP+'/code-before.tar.gz');ssh('sudo -n install -d -o mgs_pg -g mgs_pg -m 700 '+STAGE+'/public');
for f in files:ssh('sudo -n -u mgs_pg tee '+STAGE+'/'+f+' >/dev/null',(A/f).read_bytes());assert ssh('sudo -n -u mgs_pg sha256sum '+STAGE+'/'+f).split()[0]==new[f]
ssh('sudo -n -u mgs_pg /var/tmp/mgs-finance-current-policy-1547732274936553532/node --check '+STAGE+'/public/app.js')
try:
 code="import pathlib,shutil,os,pwd;s=pathlib.Path('"+STAGE+"');t=pathlib.Path('"+TARGET+"');u=pwd.getpwnam('mgsfinance')\nfor f in "+repr(files)+":\n p=t/f;q=p.with_name(p.name+'.cards100-pending');shutil.copy2(s/f,q);os.chown(q,u.pw_uid,u.pw_gid);q.chmod(0o600);os.replace(q,p)";ssh('sudo -n python3 -c '+shlex.quote(code));assert {f:ssh('sudo -n -u mgsfinance sha256sum '+TARGET+'/'+f).split()[0] for f in files}==new;status=ssh('sudo -n -u runcloud-www curl --silent --show-error --fail-with-body --unix-socket /run/mgs-finance-dash.sock -H '+shlex.quote('Host: dash.mgsdigitalcorp.com')+' -H '+shlex.quote('X-Forwarded-Proto: https')+' -o /dev/null -w '+shlex.quote('%{http_code}')+' http://localhost/?period=2026-09');assert status=='302'
except Exception:
 ssh('sudo -n tar -xzf '+BACKUP+'/code-before.tar.gz -C '+TARGET+' && sudo -n chown -R mgsfinance:mgsfinance '+TARGET);raise
out={'pass':True,'authorization':AUTH,'before':before,'after':new,'backup':BACKUP,'http_unauthenticated':302,'database_writes':0,'service_restart':False};pathlib.Path('/root/mgs-agent/work/finance-current-policy-1547732274936553532/cards-100-release.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
