import pathlib,json,hashlib,datetime,fcntl,os,sys,shlex,subprocess
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,'/root/mgs-agent/apps/finance-system/deploy');from runcloud_ops import ssh
R=pathlib.Path('/root/mgs-agent');A=R/'apps/finance-system';D=R/'work/finance-current-policy-1547732274936553532';AUTH='1547732274936553532';TARGET='/home/mgsfinance/releases/pg-auth-1545934831664242748';ENV='env LD_LIBRARY_PATH=/opt/mgs-postgresql18/usr/lib/x86_64-linux-gnu ';PG='sudo -n -u mgs_pg '+ENV+'/opt/mgs-postgresql18/usr/lib/postgresql/18/bin/psql -h /run/mgs-postgresql18 -U mgs_pg -d mgs_finance -At -v ON_ERROR_STOP=1 -c '
remote_files=['server.mjs','history-refresh.mjs','history-source-import.mjs','history-source-cli.mjs','current-policy.mjs','current-policy-cli.mjs','worker.py','workspace.mjs','finance-ops.mjs','deploy/meta-lookup-queue.py','public/app.js','public/financial-summary.js','public/refinements.css','public/operations.js','public/operations.html','public/operations.css','public/history-operations.js']
remote_hash={f:ssh('sudo -n -u mgsfinance sha256sum '+shlex.quote(TARGET+'/'+f)).split()[0] for f in remote_files};local_hash={f:hashlib.sha256((A/f).read_bytes()).hexdigest() for f in remote_files};assert remote_hash==local_hash
services=subprocess.check_output(['systemctl','is-active','mgs-finance-meta-lookup.service'],text=True).strip(),ssh('systemctl is-active mgs-postgresql18 mgs-finance-dash mgs-finance-dash.socket').split();assert services[0]=='active' and services[1]==['active']*3
worker=json.loads((A/'private/meta-lookup-worker-state.json').read_text());build=hashlib.sha256((A/'meta-lookup-worker.py').read_bytes()).hexdigest()[:16];assert worker.get('ok') is True and worker.get('pending')==0 and worker.get('worker_build')==build
q="""SELECT json_build_object('workspaces',(SELECT count(*) FROM scenarios WHERE id LIKE 'workspace-%'),'cutoffs',(SELECT count(*) FROM scenarios s,jsonb_array_elements(s.additions) a WHERE s.id LIKE 'workspace-%' AND a->>'kind'='data_cutoff'),'inactive_site_rows',(SELECT count(*) FROM scenarios s,jsonb_array_elements(s.additions) a WHERE s.id LIKE 'workspace-%' AND a->>'kind'='site' AND a->>'name' IN ('Cephyric','Escalatepower','Mavroa') AND a->>'status'='INATIVO'),'sep_cutoff',(SELECT result#>>'{domain,realized,cutoff_date}' FROM scenarios WHERE id='workspace-2026-09'),'sep_days',(SELECT result#>>'{domain,realized,elapsed_days}' FROM scenarios WHERE id='workspace-2026-09'),'sep_realized',(SELECT result#>>'{domain,realized,profit}' FROM scenarios WHERE id='workspace-2026-09'),'sep_estimate_half',(SELECT result#>>'{domain,projection,half_usd}' FROM scenarios WHERE id='workspace-2026-09'),'history_baseline',(SELECT count(*) FROM finance_history),'july_currency',(SELECT result#>>'{history_payload,correction,currency}' FROM scenarios WHERE id=(SELECT result->'versions'->>'2026-07/principal' FROM scenarios WHERE id='master-history-source')),'july_balance',(SELECT result#>>'{history_payload,closure,balance,raw}' FROM scenarios WHERE id=(SELECT result->'versions'->>'2026-07/principal' FROM scenarios WHERE id='master-history-source')),'workspace_recoveries',(SELECT count(*) FROM scenarios WHERE id LIKE 'recovery-current-policy-1547732274936553532-%'),'history_recoveries',(SELECT count(*) FROM scenarios WHERE id LIKE 'recovery-history-pointer-1547732274936553532-%'));""";db=json.loads(ssh(PG+shlex.quote(q)).strip());assert db['workspaces']==17 and db['cutoffs']==17 and db['inactive_site_rows']==48 and db['sep_cutoff']=='2026-09-09' and int(db['sep_days'])==9 and db['history_baseline']==40 and db['july_currency']=='CAD' and db['workspace_recoveries']==17 and db['history_recoveries']>=1
queue_code="""import pathlib,json
rows=[]
for p in pathlib.Path('/home/mgsfinance/releases/pg-auth-1545934831664242748/private/meta-account-lookups').glob('*.json'):
 d=json.loads(p.read_text())
 if d.get('platform')=='history':rows.append(d)
rows.sort(key=lambda x:x.get('requested_at',''));print(json.dumps([{k:d.get(k) for k in ['request_id','status','period','captured_at','changed','documents','policy_correction']} for d in rows[-8:]]))
""";queue=json.loads(ssh('sudo -n -u mgsfinance python3 -c '+shlex.quote(queue_code)));ready=[x for x in queue if x['status']=='ready'];assert ready and ready[-1]['period']=='2026-07' and ready[-1]['documents']==6 and ready[-1]['policy_correction']['currency']=='CAD'
public=json.loads((A/'private/current-policy-1547732274936553532/public-readback.json').read_text());assert public['pass'] and public['periods']==24 and public['js_errors']==0 and public['manager_privacy']['pass']
validation=json.loads((D/'validation-summary.json').read_text());assert validation['pass'] and validation['node_tests']['passed']==112 and validation['python_tests']['passed']==74
now=datetime.datetime.now(datetime.timezone.utc).isoformat();files=[A/f for f in remote_files]+[A/f for f in ['meta-lookup-worker.py','history_refresh.py','history_policy.py','tests/current-policy.test.mjs','tests/history-refresh.test.mjs','tests/current-policy-public.mjs','tests/history-refresh-public.mjs','tests/test_realized_cutoff.py','tests/test_history_queue_transport.py','tests/financial-summary.test.mjs','tests/payment-indicators.test.mjs','tests/navigation-profile.test.mjs','tests/ui-country-blocks.test.mjs','tests/fixtures/mgs-logo-original.png']]+[R/'docs/finance-system-product-direction.md',R/'reports/finance-current-policy-1547732274936553532.md',R/'profiles/zeus-skills/ops/mgs-finance-dashboard/SKILL.md',R/'profiles/zeus-skills/ops/mgs-finance-dashboard/references/current-realized-cutoff-site-status-history-refresh.md']
entry={'id':'zeus-finance-current-policy-1547732274936553532','agent':'zeus','type':'finance_dashboard_policy_release','owner':'Zeus/Finance','authorization_message_ids':['1547727478011727963','1547731247793709056',AUTH,'1547775936697737288'],'source_thread_id':'1545426987756298340','status':'published_verified','updated_at':now,'paths':[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files],'evidence_path':str(D),'report_path':str(R/'reports/finance-current-policy-1547732274936553532.md'),'backup_remote':'/home/zeus/mgs-finance-backups/'+AUTH,'isolated_database':'mgs_finance_current_policy_'+AUTH,'production_release':TARGET,'validation':{'node_tests':112,'python_tests':74,'payment_months':24,'viewports':[390,1440],'js_errors':0,'history_refresh_documents':6,'manager_privacy':True},'runtime':{'services':['mgs-postgresql18','mgs-finance-dash','mgs-finance-dash.socket','mgs-finance-meta-lookup'],'cutoff_september':'2026-09-09','inactive_site_rows':48,'history_baseline_rows':40,'july_correction':'SB Tech Bot 629.28 CAD'}}
P=R/'data/infra-inventory.json';lockpath='/var/lock/infra_discovery.lock'
with open(lockpath,'a') as lock:
 fcntl.flock(lock,fcntl.LOCK_EX);raw=P.read_bytes();data=json.loads(raw);items=data.setdefault('runtime_artifacts',[]);items[:]=[x for x in items if x.get('id')!=entry['id']];items.append(entry);data['_meta']['updated_at']=now;tmp=P.with_name(P.name+'.finance-current-policy.pending');tmp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');os.replace(tmp,P);assert next(x for x in json.loads(P.read_text())['runtime_artifacts'] if x.get('id')==entry['id'])['validation']['node_tests']==112
 audit={'timestamp':now,'actor':'zeus','event':'finance_current_policy_published_verified','authorization_message_ids':entry['authorization_message_ids'],'source_thread_id':entry['source_thread_id'],'inventory_id':entry['id'],'evidence':str(D),'outcome':'published_verified','cutoff_september':'2026-09-09','inactive_sites':['Cephyric','Escalatepower','Mavroa'],'history_refresh':'ready_6_documents_cad_preserved','tests':{'node':112,'python':74,'public':True}};(R/'logs/events-audit.jsonl').open('a').write(json.dumps(audit,ensure_ascii=False)+'\n')
out={'pass':True,'timestamp':now,'remote_hashes_match':True,'services':['active']*4,'worker_build':build,'worker_pending':0,'database':db,'history_refresh':ready[-1],'public':public,'tests':validation['node_tests']['passed']+validation['python_tests']['passed'],'inventory_id':entry['id'],'inventory_readback':True,'audit_event':audit['event']};(D/'final-readback.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'pass':True,'services':out['services'],'tests':out['tests'],'cutoff':db['sep_cutoff'],'sep_realized':db['sep_realized'],'history_refresh_documents':ready[-1]['documents'],'inventory_id':entry['id']}))
