import sys,hashlib,pathlib,shlex,json
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,'/root/mgs-agent/apps/finance-system/deploy');from runcloud_ops import ssh
AUTH='1547732274936553532';local=pathlib.Path('/root/mgs-agent/apps/finance-system/finance-ops.mjs');target='/home/mgsfinance/releases/pg-auth-1545934831664242748/finance-ops.mjs';stage='/var/tmp/mgs-finance-current-policy-'+AUTH+'/finance-ops.mjs';backup='/home/zeus/mgs-finance-backups/'+AUTH+'/finance-ops-before-history-refresh-guard.mjs';new=hashlib.sha256(local.read_bytes()).hexdigest();old=ssh('sudo -n -u mgsfinance sha256sum '+target).split()[0];assert old!=new
ssh('sudo -n cp '+target+' '+backup+' && sudo -n chown zeus:zeus '+backup+' && sudo -n chmod 600 '+backup);ssh('sudo -n -u mgs_pg tee '+stage+' >/dev/null',local.read_bytes());assert ssh('sudo -n -u mgs_pg sha256sum '+stage).split()[0]==new;ssh('sudo -n -u mgs_pg /var/tmp/mgs-finance-current-policy-'+AUTH+'/node --check '+stage)
try:
 ssh('sudo -n systemctl stop mgs-finance-dash.socket mgs-finance-dash.service');code="import pathlib,shutil,os,pwd;p=pathlib.Path('"+target+"');q=p.with_name(p.name+'.guard-pending');shutil.copy2('"+stage+"',q);u=pwd.getpwnam('mgsfinance');os.chown(q,u.pw_uid,u.pw_gid);q.chmod(0o600);os.replace(q,p)";ssh('sudo -n python3 -c '+shlex.quote(code));ssh('sudo -n systemctl start mgs-finance-dash.socket mgs-finance-dash.service');assert ssh('systemctl is-active mgs-finance-dash mgs-finance-dash.socket').split()==['active','active'];assert ssh('sudo -n -u runcloud-www curl --silent --show-error --fail-with-body --unix-socket /run/mgs-finance-dash.sock -H '+shlex.quote('Host: dash.mgsdigitalcorp.com')+' -H '+shlex.quote('X-Forwarded-Proto: https')+' -o /dev/null -w '+shlex.quote('%{http_code}')+' http://localhost/login')=='200'
except Exception:
 ssh('sudo -n cp '+backup+' '+target+' && sudo -n chown mgsfinance:mgsfinance '+target+' && sudo -n chmod 600 '+target+' && sudo -n systemctl start mgs-finance-dash.socket mgs-finance-dash.service');raise
out={'pass':True,'file':'finance-ops.mjs','before_sha256':old,'after_sha256':new,'backup':backup,'services':['active','active'],'login_probe':200,'database_writes':0};pathlib.Path('/root/mgs-agent/work/finance-current-policy-'+AUTH+'/history-refresh-guard-release.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
