import sys,pathlib,hashlib,json,shlex,subprocess,time
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,'/root/mgs-agent/apps/finance-system/deploy');from runcloud_ops import ssh
AUTH='1547732274936553532';root=pathlib.Path('/root/mgs-agent');local=root/'apps/finance-system/deploy/meta-lookup-queue.py';target='/home/mgsfinance/releases/pg-auth-1545934831664242748/deploy/meta-lookup-queue.py';stage='/var/tmp/mgs-finance-current-policy-'+AUTH+'/deploy/meta-lookup-queue.py';backup='/home/zeus/mgs-finance-backups/'+AUTH+'/meta-lookup-queue-before-history-support.py';new=hashlib.sha256(local.read_bytes()).hexdigest();old=ssh('sudo -n -u mgsfinance sha256sum '+target).split()[0];assert old!=new
ssh('sudo -n cp '+target+' '+backup+' && sudo -n chown zeus:zeus '+backup+' && sudo -n chmod 600 '+backup);ssh('sudo -n -u mgs_pg tee '+stage+' >/dev/null',local.read_bytes());assert ssh('sudo -n -u mgs_pg sha256sum '+stage).split()[0]==new;ssh('sudo -n -u mgs_pg python3 -m py_compile '+stage)
subprocess.run(['systemctl','stop','mgs-finance-meta-lookup.service'],check=True,timeout=60)
try:
 code="import pathlib,shutil,os,pwd;p=pathlib.Path('"+target+"');q=p.with_name(p.name+'.history-pending');shutil.copy2('"+stage+"',q);u=pwd.getpwnam('mgsfinance');os.chown(q,u.pw_uid,u.pw_gid);q.chmod(0o600);os.replace(q,p)";ssh('sudo -n python3 -c '+shlex.quote(code));assert ssh('sudo -n -u mgsfinance sha256sum '+target).split()[0]==new;subprocess.run(['systemctl','start','mgs-finance-meta-lookup.service'],check=True,timeout=60)
except Exception:
 ssh('sudo -n cp '+backup+' '+target+' && sudo -n chown mgsfinance:mgsfinance '+target+' && sudo -n chmod 600 '+target);subprocess.run(['systemctl','start','mgs-finance-meta-lookup.service'],check=True,timeout=60);raise
time.sleep(55);active=subprocess.check_output(['systemctl','is-active','mgs-finance-meta-lookup.service'],text=True).strip();state=json.loads((root/'apps/finance-system/private/meta-lookup-worker-state.json').read_text());expected=hashlib.sha256((root/'apps/finance-system/meta-lookup-worker.py').read_bytes()).hexdigest()[:16];assert active=='active' and state.get('ok') is True and state.get('worker_build')==expected
out={'pass':True,'before_sha256':old,'after_sha256':new,'backup':backup,'worker_service':active,'worker_build':state['worker_build'],'pending':state.get('pending'),'queue_history_transport':True};(root/('work/finance-current-policy-'+AUTH+'/history-transport-release.json')).write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
