import sys,json,hashlib,shlex,pathlib,tarfile,io,fcntl,subprocess
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,'/root/mgs-agent/apps/finance-system/deploy');from runcloud_ops import ssh
AUTH='1547732274936553532';ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';STATE=ROOT/('work/finance-current-policy-'+AUTH);TARGET='/home/mgsfinance/releases/pg-auth-1545934831664242748';BACKUP='/home/zeus/mgs-finance-backups/'+AUTH;STAGE='/var/tmp/mgs-finance-current-policy-'+AUTH;DB='mgs_finance_current_policy_'+AUTH
FILES=['server.mjs','history-refresh.mjs','history-source-import.mjs','history-source-cli.mjs','current-policy.mjs','current-policy-cli.mjs','worker.py','workspace.mjs','finance-ops.mjs','public/app.js','public/financial-summary.js','public/refinements.css','public/operations.js','public/operations.html','public/operations.css','public/history-operations.js'];LOCAL_ONLY=['history_refresh.py','history_policy.py','meta-lookup-worker.py'];EXISTING=[f for f in FILES if not f in ['history-refresh.mjs','current-policy.mjs','current-policy-cli.mjs']];phase=sys.argv[1]
ENV='env LD_LIBRARY_PATH=/opt/mgs-postgresql18/usr/lib/x86_64-linux-gnu ';BIN='/opt/mgs-postgresql18/usr/lib/postgresql/18/bin/';PG='sudo -n -u mgs_pg '+ENV+BIN;SOCK='/run/mgs-postgresql18';docs=[json.loads(p.read_text()) for p in sorted((STATE/'july-refresh-overlay-canary').glob('*.json'))];assert len(docs)==6 and all(d['period']=='2026-07' for d in docs);payload=json.dumps(docs,ensure_ascii=False).encode();new={f:hashlib.sha256((APP/f).read_bytes()).hexdigest() for f in FILES}
CHECK="""SELECT json_build_object('baseline',md5(result::text),'source_cells',(SELECT count(*) FROM source_cells)) FROM scenarios WHERE id='baseline';SELECT json_build_object('ledger_count',count(*),'ledger_hash',md5(coalesce(jsonb_agg(x ORDER BY id)::text,''))) FROM finance_ledger x;SELECT json_build_object('history_count',count(*),'history_hash',md5(string_agg(period||'/'||book||'/'||source_sha256,'|' ORDER BY period,book))) FROM finance_history;SELECT json_build_object('users_count',count(*),'users_hash',md5(coalesce(jsonb_agg(x ORDER BY username)::text,''))) FROM finance_users x;SELECT json_build_object('accounts_revision',revision,'accounts',md5(result::text),'additions',md5(additions::text)) FROM scenarios WHERE id='master-ad-accounts';SELECT json_build_object('id',id,'revision',revision,'state',state,'overrides',md5(overrides::text),'cash',md5((result->'domain'->'cash')::text),'active_units',result#>>'{domain,allocation,active_units}') FROM scenarios WHERE id LIKE 'workspace-%' ORDER BY id;"""
def dbcheck(database='mgs_finance'):return ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d '+shlex.quote(database)+' -At -v ON_ERROR_STOP=1 -c '+shlex.quote(CHECK),timeout=240)
def exists(path,user=None):return bool(ssh('if '+(('sudo -n -u '+user+' ') if user else '')+'test -e '+shlex.quote(path)+'; then echo yes; fi').strip())
def rh(path,user='mgsfinance'):return ssh('sudo -n -u '+user+' sha256sum '+shlex.quote(path)).split()[0]
def remote_hashes():return {f:rh(TARGET+'/'+f) if exists(TARGET+'/'+f,'mgsfinance') else None for f in FILES}
def services():return ssh('systemctl is-active mgs-postgresql18 mgs-finance-dash mgs-finance-dash.socket').split()
def save(name,obj):(STATE/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def load(name):return json.loads((STATE/name).read_text())
def bundle():
 b=io.BytesIO()
 with tarfile.open(fileobj=b,mode='w:gz') as t:
  for f in FILES:t.add(APP/f,arcname=f)
 return b.getvalue()
def query_summary(database='mgs_finance'):
 q="""SELECT json_build_object('workspaces',(SELECT count(*) FROM scenarios WHERE id LIKE 'workspace-%'),'cutoffs',(SELECT count(*) FROM scenarios s,jsonb_array_elements(s.additions) a WHERE s.id LIKE 'workspace-%' AND a->>'kind'='data_cutoff'),'inactive_sites',(SELECT count(*) FROM scenarios s,jsonb_array_elements(s.additions) a WHERE s.id LIKE 'workspace-%' AND a->>'kind'='site' AND a->>'name' IN ('Cephyric','Escalatepower','Mavroa') AND a->>'status'='INATIVO'),'sep_realized',(SELECT result->'domain'->'realized' FROM scenarios WHERE id='workspace-2026-09'),'sep_projection',(SELECT result->'domain'->'projection' FROM scenarios WHERE id='workspace-2026-09'),'july_due',(SELECT result#>>'{history_payload,closure,due,raw}' FROM scenarios WHERE id=(SELECT result->'versions'->>'2026-07/principal' FROM scenarios WHERE id='master-history-source')),'july_balance',(SELECT result#>>'{history_payload,closure,balance,raw}' FROM scenarios WHERE id=(SELECT result->'versions'->>'2026-07/principal' FROM scenarios WHERE id='master-history-source')));""";return json.loads(ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d '+shlex.quote(database)+' -At -c '+shlex.quote(q),timeout=180).strip())
if phase=='prepare':
 assert services()==['active']*3 and not exists(BACKUP) and not exists(STAGE) and not ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d postgres -At -c '+shlex.quote("SELECT 1 FROM pg_database WHERE datname='"+DB+"'")).strip();before_files=remote_hashes();before_db=dbcheck();ssh('sudo -n install -d -o zeus -g zeus -m 700 '+shlex.quote(BACKUP));ssh('sudo -n tar -czf '+shlex.quote(BACKUP+'/code-before.tar.gz')+' -C '+shlex.quote(TARGET)+' '+' '.join(shlex.quote(f) for f in EXISTING)+' && sudo -n chown zeus:zeus '+shlex.quote(BACKUP+'/code-before.tar.gz')+' && chmod 600 '+shlex.quote(BACKUP+'/code-before.tar.gz'));ssh(PG+'pg_dump -h '+SOCK+' -U mgs_pg -Fc mgs_finance > '+shlex.quote(BACKUP+'/mgs_finance-before.dump')+' && chmod 600 '+shlex.quote(BACKUP+'/mgs_finance-before.dump'),timeout=300);ssh(ENV+BIN+'pg_restore --list '+shlex.quote(BACKUP+'/mgs_finance-before.dump')+' >/dev/null')
 # Backup the prior local worker source from Git before the in-memory service is restarted.
 prior_worker=subprocess.check_output(['git','-C',str(ROOT),'show','HEAD:apps/finance-system/meta-lookup-worker.py']);(STATE/'meta-lookup-worker-before.py').write_bytes(prior_worker)
 ssh(PG+'createdb -h '+SOCK+' -U mgs_pg '+DB+' && '+PG+'pg_restore -h '+SOCK+' -U mgs_pg -d '+DB+' < '+shlex.quote(BACKUP+'/mgs_finance-before.dump'),timeout=300);assert dbcheck(DB)==before_db
 ssh('sudo -n cp -a '+shlex.quote(TARGET)+' '+shlex.quote(STAGE)+' && sudo -n chown -R mgs_pg:mgs_pg '+shlex.quote(STAGE),timeout=300);ssh('sudo -n -u mgs_pg tar -xzf - -C '+shlex.quote(STAGE),bundle(),timeout=180);ssh('sudo -n cp /home/mgsfinance/runtime/node-v22.23.2-linux-x64/bin/node '+shlex.quote(STAGE+'/node')+' && sudo -n chown mgs_pg:mgs_pg '+shlex.quote(STAGE+'/node')+' && sudo -n chmod 700 '+shlex.quote(STAGE+'/node'))
 for f,h in new.items():assert rh(STAGE+'/'+f,'mgs_pg')==h
 policy=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/current-policy-cli.mjs '+DB,timeout=600).strip());assert policy['pass'] and policy['updated']==17;history=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/history-source-cli.mjs '+DB+' '+AUTH,payload,timeout=600).strip());assert history['pass'] and history['verified']==6 and history['months']==1;repeat_policy=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/current-policy-cli.mjs '+DB,timeout=600).strip());repeat_history=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/history-source-cli.mjs '+DB+' '+AUTH,payload,timeout=600).strip());assert not repeat_policy['changed'] and not repeat_history['changed'];summary=query_summary(DB);assert summary['workspaces']==17 and summary['cutoffs']==17 and summary['inactive_sites']==48 and summary['sep_realized']['cutoff_date']=='2026-09-09' and round(float(summary['july_balance']),2)==-1090.05
 out={'pass':True,'before_files':before_files,'new_files':new,'before_db':before_db,'backup':BACKUP,'backup_code_sha256':rh(BACKUP+'/code-before.tar.gz','zeus'),'backup_db_sha256':rh(BACKUP+'/mgs_finance-before.dump','zeus'),'stage':STAGE,'stage_database':DB,'policy':policy,'history':{k:v for k,v in history.items() if k!='versions'},'summary':summary,'idempotent':True,'services':services(),'production_writes':0};save('prepared.json',out);print(json.dumps({'pass':True,'files':len(FILES),'policy_periods':policy['updated'],'history_docs':history['verified'],'july_balance':summary['july_balance'],'sep_realized':summary['sep_realized']['profit'],'backup_db_sha256':out['backup_db_sha256']}))
elif phase=='publish':
 pre=load('prepared.json');assert pre['pass'] and remote_hashes()==pre['before_files'] and dbcheck()==pre['before_db'] and services()==['active']*3
 with (APP/'private/quote-sync.lock').open('a') as lock:
  fcntl.flock(lock,fcntl.LOCK_EX)
  try:
   ssh('sudo -n systemctl stop mgs-finance-dash.socket mgs-finance-dash.service')
   code='import pathlib,shutil,os,pwd;s=pathlib.Path('+repr(STAGE)+');t=pathlib.Path('+repr(TARGET)+');u=pwd.getpwnam("mgsfinance")\nfor f in '+repr(FILES)+':\n p=t/f;q=p.with_name(p.name+".policy-pending");shutil.copy2(s/f,q);os.chown(q,u.pw_uid,u.pw_gid);q.chmod(0o600);os.replace(q,p)';ssh('sudo -n python3 -c '+shlex.quote(code),timeout=180);assert remote_hashes()==new
   policy=json.loads(ssh('sudo -n -u mgsfinance /home/mgsfinance/runtime/node-v22.23.2-linux-x64/bin/node '+TARGET+'/current-policy-cli.mjs mgs_finance',timeout=600).strip());assert policy['pass']
   history=json.loads(ssh('sudo -n -u mgsfinance /home/mgsfinance/runtime/node-v22.23.2-linux-x64/bin/node '+TARGET+'/history-source-cli.mjs mgs_finance '+AUTH,payload,timeout=600).strip());assert history['pass'] and history['verified']==6
   ssh('sudo -n systemctl start mgs-finance-dash.socket mgs-finance-dash.service');assert services()==['active']*3
   subprocess.run(['systemctl','restart','mgs-finance-meta-lookup.service'],check=True,timeout=60);assert subprocess.check_output(['systemctl','is-active','mgs-finance-meta-lookup.service'],text=True).strip()=='active'
  except Exception:
   # Keep new inert files; restore every previously active code file and approved data from recovery scenarios.
   ssh('sudo -n tar -xzf '+shlex.quote(pre['backup']+'/code-before.tar.gz')+' -C '+shlex.quote(TARGET)+' && sudo -n chown -R mgsfinance:mgsfinance '+shlex.quote(TARGET));rollback="""BEGIN;DO $$ DECLARE r record; BEGIN FOR r IN SELECT id,result->'history_pointer' p FROM scenarios WHERE id LIKE 'recovery-history-pointer-1547732274936553532-%' ORDER BY created_at DESC LIMIT 1 LOOP UPDATE scenarios SET result=r.p,revision=revision+1,updated_at=now() WHERE id='master-history-source'; END LOOP; FOR r IN SELECT * FROM scenarios WHERE id LIKE 'recovery-current-policy-1547732274936553532-%' LOOP UPDATE scenarios SET overrides=r.overrides,additions=r.additions,result=r.result,revision=revision+1,updated_at=now() WHERE id='workspace-'||right(r.id,7); END LOOP; END $$;INSERT INTO audit_events(actor,action,after_data) VALUES('zeus','CURRENT_POLICY_ROLLBACK','{"authorization":"1547732274936553532"}');COMMIT;""";ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d mgs_finance -v ON_ERROR_STOP=1 -c '+shlex.quote(rollback),timeout=180);ssh('sudo -n systemctl start mgs-finance-dash.socket mgs-finance-dash.service');(APP/'meta-lookup-worker.py').write_bytes((STATE/'meta-lookup-worker-before.py').read_bytes());subprocess.run(['systemctl','restart','mgs-finance-meta-lookup.service'],check=True,timeout=60);save('rollback.json',{'pass':True,'reason':'publish_exception','services':services()});raise
 summary=query_summary();assert summary['workspaces']==17 and summary['cutoffs']==17 and summary['inactive_sites']==48 and summary['sep_realized']['cutoff_date']=='2026-09-09' and round(float(summary['july_balance']),2)==-1090.05;out={'pass':True,'policy':policy,'history':{k:v for k,v in history.items() if k!='versions'},'summary':summary,'hashes':remote_hashes(),'services':services(),'worker_service':'active','backup':pre['backup']};save('published.json',out);print(json.dumps({'pass':True,'policy_updated':policy['updated'],'history_changed':history['changed'],'july_due':summary['july_due'],'july_balance':summary['july_balance'],'sep_realized_profit':summary['sep_realized']['profit'],'sep_estimate_half':summary['sep_projection']['half_usd'],'services':out['services']}))
elif phase=='verify':
 pre=load('prepared.json');pub=load('published.json');assert remote_hashes()==new and services()==['active']*3 and subprocess.check_output(['systemctl','is-active','mgs-finance-meta-lookup.service'],text=True).strip()=='active';summary=query_summary();assert summary==pub['summary'];invariants=dbcheck().splitlines();before=pre['before_db'].splitlines();assert invariants[:5]==before[:5];out={'pass':True,'hashes':new,'services':services(),'worker_service':'active','summary':summary,'immutable_manifests':invariants[:5],'backup_code_sha256':pre['backup_code_sha256'],'backup_db_sha256':pre['backup_db_sha256']};save('deploy-readback.json',out);print(json.dumps({'pass':True,'files':len(new),'services':out['services'],'worker':out['worker_service'],'july_balance':summary['july_balance'],'sep_cutoff':summary['sep_realized']['cutoff_date'],'sep_realized':summary['sep_realized']['profit'],'immutable_manifests':True}))
else:raise ValueError('phase')
