import sys,json,hashlib,shlex,pathlib,tarfile,io
sys.path.insert(0,'/root/mgs-agent/scripts');from mgs_google_workspace_auth import load_env
load_env();sys.path.insert(0,'/root/mgs-agent/apps/finance-system/deploy');from runcloud_ops import ssh
AUTH='1547732274936553532';ROOT=pathlib.Path('/root/mgs-agent');APP=ROOT/'apps/finance-system';STATE=ROOT/('work/finance-current-policy-'+AUTH);TARGET='/home/mgsfinance/releases/pg-auth-1545934831664242748';BACKUP='/home/zeus/mgs-finance-backups/'+AUTH;STAGE='/var/tmp/mgs-finance-current-policy-'+AUTH;DB='mgs_finance_current_policy_'+AUTH
FILES=['server.mjs','history-refresh.mjs','history-source-import.mjs','history-source-cli.mjs','current-policy.mjs','current-policy-cli.mjs','worker.py','workspace.mjs','finance-ops.mjs','public/app.js','public/financial-summary.js','public/refinements.css','public/operations.js','public/operations.html','public/operations.css','public/history-operations.js'];ENV='env LD_LIBRARY_PATH=/opt/mgs-postgresql18/usr/lib/x86_64-linux-gnu ';BIN='/opt/mgs-postgresql18/usr/lib/postgresql/18/bin/';PG='sudo -n -u mgs_pg '+ENV+BIN;SOCK='/run/mgs-postgresql18';new={f:hashlib.sha256((APP/f).read_bytes()).hexdigest() for f in FILES};docs=[json.loads(p.read_text()) for p in sorted((STATE/'july-refresh-overlay-canary').glob('*.json'))];payload=json.dumps(docs,ensure_ascii=False).encode();assert len(docs)==6
CHECK="""SELECT json_build_object('baseline',md5(result::text),'source_cells',(SELECT count(*) FROM source_cells)) FROM scenarios WHERE id='baseline';SELECT json_build_object('ledger_count',count(*),'ledger_hash',md5(coalesce(jsonb_agg(x ORDER BY id)::text,''))) FROM finance_ledger x;SELECT json_build_object('history_count',count(*),'history_hash',md5(string_agg(period||'/'||book||'/'||source_sha256,'|' ORDER BY period,book))) FROM finance_history;SELECT json_build_object('users_count',count(*),'users_hash',md5(coalesce(jsonb_agg(x ORDER BY username)::text,''))) FROM finance_users x;SELECT json_build_object('accounts_revision',revision,'accounts',md5(result::text),'additions',md5(additions::text)) FROM scenarios WHERE id='master-ad-accounts';SELECT json_build_object('id',id,'revision',revision,'state',state,'overrides',md5(overrides::text),'cash',md5((result->'domain'->'cash')::text),'active_units',result#>>'{domain,allocation,active_units}') FROM scenarios WHERE id LIKE 'workspace-%' ORDER BY id;"""
def dbcheck(database):return ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d '+database+' -At -v ON_ERROR_STOP=1 -c '+shlex.quote(CHECK),timeout=240)
def exists(p,user=None):return bool(ssh('if '+(('sudo -n -u '+user+' ') if user else '')+'test -e '+shlex.quote(p)+'; then echo yes; fi').strip())
def rh(p,user):return ssh('sudo -n -u '+user+' sha256sum '+shlex.quote(p)).split()[0]
def remote_hashes():return {f:(rh(TARGET+'/'+f,'mgsfinance') if exists(TARGET+'/'+f,'mgsfinance') else None) for f in FILES}
def bundle():
 b=io.BytesIO()
 with tarfile.open(fileobj=b,mode='w:gz') as t:
  for f in FILES:t.add(APP/f,arcname=f)
 return b.getvalue()
def query_summary(database):
 q="""SELECT json_build_object('workspaces',(SELECT count(*) FROM scenarios WHERE id LIKE 'workspace-%'),'cutoffs',(SELECT count(*) FROM scenarios s,jsonb_array_elements(s.additions) a WHERE s.id LIKE 'workspace-%' AND a->>'kind'='data_cutoff'),'inactive_sites',(SELECT count(*) FROM scenarios s,jsonb_array_elements(s.additions) a WHERE s.id LIKE 'workspace-%' AND a->>'kind'='site' AND a->>'name' IN ('Cephyric','Escalatepower','Mavroa') AND a->>'status'='INATIVO'),'sep_realized',(SELECT result->'domain'->'realized' FROM scenarios WHERE id='workspace-2026-09'),'sep_projection',(SELECT result->'domain'->'projection' FROM scenarios WHERE id='workspace-2026-09'),'july_due',(SELECT result#>>'{history_payload,closure,due,raw}' FROM scenarios WHERE id=(SELECT result->'versions'->>'2026-07/principal' FROM scenarios WHERE id='master-history-source')),'july_balance',(SELECT result#>>'{history_payload,closure,balance,raw}' FROM scenarios WHERE id=(SELECT result->'versions'->>'2026-07/principal' FROM scenarios WHERE id='master-history-source')));""";return json.loads(ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d '+database+' -At -c '+shlex.quote(q)).strip())
assert exists(BACKUP) and exists(STAGE) and ssh(PG+'psql -h '+SOCK+' -U mgs_pg -d postgres -At -c '+shlex.quote("SELECT 1 FROM pg_database WHERE datname='"+DB+"'")).strip()=='1';assert query_summary(DB)['cutoffs'] in (0,17)
ssh('sudo -n -u mgs_pg tar -xzf - -C '+shlex.quote(STAGE),bundle(),timeout=180)
for f,h in new.items():assert rh(STAGE+'/'+f,'mgs_pg')==h
policy=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/current-policy-cli.mjs '+DB,timeout=600).strip());assert policy['pass'] and policy['updated'] in (0,17)
history=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/history-source-cli.mjs '+DB+' '+AUTH,payload,timeout=600).strip());assert history['pass'] and history['verified']==6
repeat_policy=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/current-policy-cli.mjs '+DB,timeout=600).strip());repeat_history=json.loads(ssh('sudo -n -u mgs_pg '+STAGE+'/node '+STAGE+'/history-source-cli.mjs '+DB+' '+AUTH,payload,timeout=600).strip());assert not repeat_policy['changed'] and not repeat_history['changed'];summary=query_summary(DB);assert summary['cutoffs']==17 and summary['inactive_sites']==48 and summary['sep_realized']['cutoff_date']=='2026-09-09' and round(float(summary['july_balance']),2)==-1090.05
before_files=remote_hashes();before_db=dbcheck('mgs_finance');out={'pass':True,'resumed_after_stage_tolerance_fix':True,'before_files':before_files,'new_files':new,'before_db':before_db,'backup':BACKUP,'backup_code_sha256':rh(BACKUP+'/code-before.tar.gz','zeus'),'backup_db_sha256':rh(BACKUP+'/mgs_finance-before.dump','zeus'),'stage':STAGE,'stage_database':DB,'policy':policy,'policy_stage_applied':17,'history':{k:v for k,v in history.items() if k!='versions'},'summary':summary,'idempotent':True,'services':ssh('systemctl is-active mgs-postgresql18 mgs-finance-dash mgs-finance-dash.socket').split(),'production_writes':0};assert out['services']==['active']*3;(STATE/'prepared.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'pass':True,'policy_periods':policy['updated'],'history_docs':history['verified'],'july_balance':summary['july_balance'],'sep_realized':summary['sep_realized']['profit'],'sep_projection_half':summary['sep_projection']['half_usd'],'backup_db_sha256':out['backup_db_sha256']}))
