#!/usr/bin/env python3
"""Build a deduplicated read-only copy/clean queue for UPLOAD_CANVAS creatives.

Input: organization proposal CSV generated by ares-propose-creative-organization.py.
Output: queue CSV, skipped duplicate CSV and summary JSON.
No Drive writes and no metadata cleaning are executed by this script.
"""
from __future__ import annotations

import argparse
import collections
import csv
import datetime as dt
import hashlib
import json
import re
from pathlib import Path

CONF_SCORE = {"high": 30, "medium": 20, "low": 10}
VERTICAL_SCORE = {"JOBS": 40, "CC": 35, "CC_REVIEW": 20, "REVIEW": 5}
FORMAT_SCORE = {"IMG": 10, "VID": 10, "ZIP": -20, "OTHER": -20}


def safe_name(name: str) -> str:
    stem = name.strip().replace("/", "-").replace("\\", "-")
    stem = re.sub(r"\s+", " ", stem)
    return stem[:180]


def row_key(row: dict[str, str]) -> str:
    checksum = row.get("md5_checksum") or ""
    if checksum:
        return "md5:" + checksum
    return "drive:" + row["drive_id"]


def score(row: dict[str, str]) -> int:
    s = 0
    s += CONF_SCORE.get(row.get("proposal_confidence", "low"), 0)
    s += VERTICAL_SCORE.get(row.get("vertical_proposed", "REVIEW"), 0)
    s += FORMAT_SCORE.get(row.get("format", "OTHER"), -10)
    # Prefer already-structured local organized export when content is identical.
    if row.get("source_top_folder") == "organized":
        s += 8
    # Prefer files with clear technical metadata.
    if row.get("placement_fit") not in {"", "UNKNOWN"}:
        s += 4
    if row.get("language_guess") not in {"", "UNKNOWN"}:
        s += 4
    # Keep ZIP/manual-review behind media files.
    if row.get("format") in {"ZIP", "OTHER"}:
        s -= 50
    return s


def status_for(row: dict[str, str]) -> str:
    if row.get("format") not in {"IMG", "VID"}:
        return "00_REVIEW"
    if row.get("proposal_confidence") == "low" or row.get("vertical_proposed") == "CC_REVIEW":
        # CC_REVIEW is still not campaign-ready; folder means review required.
        return "00_REVIEW" if row.get("proposal_confidence") == "low" else "01_READY_CANDIDATE"
    return "01_READY_CANDIDATE"


def destination(row: dict[str, str]) -> str:
    operation = row.get("operation_proposed") or "REVIEW"
    fmt = row.get("format") if row.get("format") in {"IMG", "VID"} else "OTHER"
    placement = row.get("placement_fit") or "UNKNOWN"
    if placement not in {"FEED", "STORY", "LANDSCAPE"}:
        placement = "UNKNOWN"
    lang = row.get("language_guess") or "UNKNOWN"
    if lang not in {"EN", "ES", "DE", "PT", "FR", "TR"}:
        lang = "UNKNOWN"
    status = status_for(row)
    return f"MGS-CRIATIVOS/{operation}/{fmt}/{placement}/{lang}/{status}"


def action_for(row: dict[str, str]) -> str:
    if row.get("format") not in {"IMG", "VID"}:
        return "MANUAL_REVIEW_NO_CLEAN"
    return "CLEAN_METADATA_THEN_COPY_KEEP_RAW"


def build(rows: list[dict[str, str]]) -> tuple[list[dict[str, str]], list[dict[str, str]], dict[str, object]]:
    groups: dict[str, list[dict[str, str]]] = collections.defaultdict(list)
    for row in rows:
        groups[row_key(row)].append(row)

    queue: list[dict[str, str]] = []
    skipped: list[dict[str, str]] = []
    destination_names: dict[str, int] = collections.Counter()

    for key, items in groups.items():
        ranked = sorted(items, key=score, reverse=True)
        canonical = ranked[0]
        dest = destination(canonical)
        filename = safe_name(canonical["original_filename"])
        collision_key = dest + "/" + filename
        destination_names[collision_key] += 1
        if destination_names[collision_key] > 1:
            # Avoid future Drive name collision while still preserving original name in inventory.
            p = Path(filename)
            suffix = f"__dupname{destination_names[collision_key]:03d}"
            filename = f"{p.stem}{suffix}{p.suffix}"

        queue.append(
            {
                "queue_id": hashlib.sha256(key.encode()).hexdigest()[:16],
                "dedup_key": key,
                "duplicate_count": str(len(items)),
                "source_drive_id": canonical["drive_id"],
                "source_relative_path": canonical["relative_path"],
                "source_top_folder": canonical["source_top_folder"],
                "original_filename": canonical["original_filename"],
                "destination_folder": dest,
                "destination_filename": filename,
                "vertical_proposed": canonical["vertical_proposed"],
                "operation_proposed": canonical["operation_proposed"],
                "format": canonical["format"],
                "placement_fit": canonical["placement_fit"],
                "language_guess": canonical["language_guess"],
                "proposal_confidence": canonical["proposal_confidence"],
                "proposal_reason": canonical["proposal_reason"],
                "width": canonical.get("width", ""),
                "height": canonical.get("height", ""),
                "duration_ms": canonical.get("duration_ms", ""),
                "size_bytes": canonical.get("size_bytes", ""),
                "md5_checksum": canonical.get("md5_checksum", ""),
                "queue_action": action_for(canonical),
                "raw_policy": "KEEP_UPLOAD_CANVAS_UNCHANGED",
                "metadata_status": "PENDING_CLEAN" if canonical.get("format") in {"IMG", "VID"} else "NOT_APPLICABLE",
                "drive_write_status": "NOT_EXECUTED",
            }
        )
        for duplicate in ranked[1:]:
            skipped.append(
                {
                    "dedup_key": key,
                    "kept_drive_id": canonical["drive_id"],
                    "skipped_drive_id": duplicate["drive_id"],
                    "kept_relative_path": canonical["relative_path"],
                    "skipped_relative_path": duplicate["relative_path"],
                    "reason": "DUPLICATE_MD5_OR_SAME_KEY",
                    "kept_score": str(score(canonical)),
                    "skipped_score": str(score(duplicate)),
                }
            )

    summary = summarize(queue, skipped, len(rows), len(groups))
    return queue, skipped, summary


def summarize(queue: list[dict[str, str]], skipped: list[dict[str, str]], input_rows: int, groups: int) -> dict[str, object]:
    by_dest = collections.Counter(q["destination_folder"] for q in queue)
    by_vertical = collections.Counter(q["vertical_proposed"] for q in queue)
    by_action = collections.Counter(q["queue_action"] for q in queue)
    by_format = collections.Counter(q["format"] for q in queue)
    by_conf = collections.Counter(q["proposal_confidence"] for q in queue)
    by_lang = collections.Counter(q["language_guess"] for q in queue)
    by_placement = collections.Counter(q["placement_fit"] for q in queue)
    return {
        "generated_at_utc": dt.datetime.now(dt.UTC).isoformat(),
        "input_rows": input_rows,
        "dedup_groups": groups,
        "queue_rows": len(queue),
        "skipped_duplicate_rows": len(skipped),
        "by_vertical": dict(by_vertical.most_common()),
        "by_format": dict(by_format.most_common()),
        "by_placement": dict(by_placement.most_common()),
        "by_language": dict(by_lang.most_common()),
        "by_confidence": dict(by_conf.most_common()),
        "by_action": dict(by_action.most_common()),
        "by_destination_top30": dict(by_dest.most_common(30)),
    }


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("proposal_csv")
    ap.add_argument("--out-dir", default="/root/mgs-agent/data/ares/creative-inventory")
    args = ap.parse_args()

    rows = list(csv.DictReader(open(args.proposal_csv, encoding="utf-8")))
    queue, skipped, summary = build(rows)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
    queue_path = out_dir / f"upload-canvas-dedup-copy-queue-{stamp}.csv"
    skipped_path = out_dir / f"upload-canvas-dedup-skipped-{stamp}.csv"
    summary_path = out_dir / f"upload-canvas-dedup-copy-queue-summary-{stamp}.json"
    write_csv(queue_path, queue)
    write_csv(skipped_path, skipped)
    summary["files"] = {
        "queue_csv": str(queue_path),
        "skipped_duplicates_csv": str(skipped_path),
        "summary_json": str(summary_path),
    }
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
