#!/usr/bin/env python3
"""OCR-assisted classifier for Ares video timeline sheets.

Reads the manifest generated by ares-drive-video-frame-sampler.py and creates a
read-only naming proposal CSV. This is a conservative first pass: OCR drives
language/country/angle; visual-only fields that OCR cannot prove are marked for
review unless deterministic from dimensions/placement.
"""
from __future__ import annotations

import argparse
import collections
import csv
import datetime as dt
import hashlib
import json
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from PIL import Image, ImageEnhance, ImageOps

ANGLE_PATTERNS: list[tuple[str, list[str]]] = [
    ("APROBACION", [r"APPROV", r"APROB", r"APROBAD", r"APPROVED FOR YOU", r"PRE.?APPROV"]),
    ("LIMITE_ALTO", [r"LIMIT", r"LIMITE", r"LIMIT FROM", r"UP TO", r"HASTA", r"\$\s?\d", r"MXN", r"USD"]),
    ("SIN_VERIFICACION", [r"NO CREDIT CHECK", r"SIN VERIFIC", r"NO VERIFICATION", r"NO CHECK", r"OHNE.*PRUF"]),
    ("CASHBACK", [r"CASH\s?BACK", r"CASHBACK"]),
    ("RECOMPENSAS", [r"BONUS", r"REWARD", r"RECOMPEN", r"POINTS", r"PUNTOS", r"MILES", r"OFFER WORTH"]),
    ("URGENCIA", [r"DON.?T WAIT", r"URGENT", r"URGENTE", r"24H", r"LIMITED TIME", r"LAST CHANCE", r"QUEDAN", r"HEUTE"]),
    ("COMPARACION", [r"COMPARE", r"COMPAR", r"BEST CARD", r"MEJORES", r"CHOICE", r"CHOOSE"]),
    ("WALLET", [r"WALLET", r"CARTERA", r"PURCHASE", r"PAYMENT", r"SHOP", r"KAUF"]),
]

LANG_MARKERS = {
    "ES": [r"TARJETA", r"CREDITO", r"APROBADA", r"APROBACION", r"SOLICITA", r"AHORA", r"QUEDAN", r"LIMITE", r"SIN ", r"PARA TI"],
    "EN": [r"CREDIT", r"CARD", r"APPROVED", r"LIMIT", r"OFFER", r"APPLY", r"DON.?T", r"BONUS", r"REWARD", r"FOR YOU"],
    "DE": [r"KREDIT", r"KARTE", r"GENEHM", r"ANGEBOT", r"JETZT", r"FUR", r"LIMIT", r"OHNE", r"BONUS"],
}


def norm(text: str) -> str:
    text = text.upper()
    replacements = {"Á":"A","À":"A","Ã":"A","Â":"A","É":"E","Ê":"E","Í":"I","Ó":"O","Ô":"O","Õ":"O","Ú":"U","Ç":"C","Ü":"U","Ö":"O","Ä":"A","ß":"SS"}
    for a,b in replacements.items():
        text=text.replace(a,b)
    return re.sub(r"\s+", " ", text)


def preprocess(src: Path, dst: Path) -> None:
    img = Image.open(src).convert("L")
    # Normalize for OCR without creating huge temporary images.
    max_side = 1600
    scale = min(1.5, max_side / max(img.width, img.height))
    if scale != 1:
        img = img.resize((max(1, int(img.width * scale)), max(1, int(img.height * scale))))
    img = ImageOps.autocontrast(img)
    img = ImageEnhance.Contrast(img).enhance(1.6)
    img.save(dst)


def ocr_image(path: Path, timeout: int = 20) -> str:
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp_path = Path(tmp.name)
    try:
        preprocess(path, tmp_path)
        try:
            proc = subprocess.run(
                ["tesseract", str(tmp_path), "stdout", "-l", "eng+spa+deu", "--psm", "11"],
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
                timeout=timeout,
                check=False,
            )
            return proc.stdout or ""
        except subprocess.TimeoutExpired:
            return ""
    finally:
        try:
            tmp_path.unlink()
        except FileNotFoundError:
            pass


def score_language(text: str, fallback: str) -> tuple[str, dict[str, int]]:
    t = norm(text)
    scores: dict[str, int] = {}
    for lang, patterns in LANG_MARKERS.items():
        s = 0
        for pat in patterns:
            s += 2 if re.search(pat, t) else 0
        scores[lang] = s
    best, best_score = max(scores.items(), key=lambda kv: kv[1])
    if best_score == 0:
        return fallback or "UNKNOWN", scores
    # if tie, use fallback if tied
    tied = [k for k,v in scores.items() if v == best_score]
    if fallback in tied:
        return fallback, scores
    return best, scores


def classify_angle(text: str) -> tuple[str, int, list[str]]:
    t = norm(text)
    hits: list[tuple[str,int,list[str]]] = []
    for angle, patterns in ANGLE_PATTERNS:
        matched = [pat for pat in patterns if re.search(pat, t)]
        if matched:
            hits.append((angle, len(matched), matched[:5]))
    if not hits:
        return "UNKNOWN", 0, []
    # Priority: approval before limit if both exist and approval text is present;
    # otherwise highest match count.
    hits.sort(key=lambda x: (1 if x[0] == "APROBACION" else 0, x[1]), reverse=True)
    return hits[0][0], hits[0][1], hits[0][2]


def country_from_text_lang(text: str, lang: str, fallback_name: str) -> tuple[str, str]:
    t = norm(text + " " + fallback_name)
    if re.search(r"\bMXN\b|\bMEXICO\b|\bMX\b", t):
        return "MX", "currency/name evidence"
    if re.search(r"\$|USD|UNITED STATES|\bUS\b|\bUSA\b", t) and lang == "EN":
        return "US", "dollar + EN"
    if lang == "DE":
        return "DE", "language fallback"
    if lang == "ES":
        return "US", "Spanish operation fallback"
    if lang == "EN":
        return "US", "English operation fallback"
    return "UNKNOWN", "insufficient evidence"


def orientation_from_placement(placement: str) -> str:
    if placement == "STORY":
        return "VERTICAL"
    if placement in {"FEED", "LANDSCAPE"}:
        return "HORIZONTAL"
    return "REVIEW"


def p_orient(person: str, orientation: str) -> str:
    if orientation == "VERTICAL" and person == "PERSON": return "PV"
    if orientation == "HORIZONTAL" and person == "PERSON": return "PH"
    if orientation == "VERTICAL" and person == "NO_PERSON": return "NV"
    if orientation == "HORIZONTAL" and person == "NO_PERSON": return "NH"
    return "REVIEW"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest_json")
    ap.add_argument("--out-dir", default="/root/mgs-agent/data/ares/creative-inventory/video-classification")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    manifest = json.loads(Path(args.manifest_json).read_text(encoding="utf-8"))
    items = manifest["items"][: args.limit or None]
    stamp = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
    out_dir = Path(args.out_dir) / stamp
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for idx, item in enumerate(items, 1):
        frame_texts = []
        for frame in item.get("frames", []):
            frame_texts.append(ocr_image(Path(frame)))
        text = "\n".join(frame_texts)
        text_norm = norm(text)
        lang, lang_scores = score_language(text, item.get("language_guess") or "UNKNOWN")
        angle, angle_score, angle_hits = classify_angle(text)
        country, country_reason = country_from_text_lang(text, lang, item.get("original_filename") or "")
        orientation = orientation_from_placement(item.get("placement_fit") or "UNKNOWN")
        # OCR cannot reliably detect hands/people. Conservative default: no final person proof.
        # Most card templates are no-person; flag for visual review if confidence is not high.
        person = "NO_PERSON"
        porient = p_orient(person, orientation)
        confidence = "high" if angle != "UNKNOWN" and lang != "UNKNOWN" and porient != "REVIEW" and angle_score >= 1 else "low"
        notes = []
        if item.get("language_guess") and item.get("language_guess") != lang:
            notes.append(f"lang corrected from {item.get('language_guess')} by OCR")
        if angle == "UNKNOWN":
            notes.append("angle not detected by OCR")
        if porient == "REVIEW":
            notes.append("placement/orientation review")
        notes.append("person default NO_PERSON requires visual audit before Drive rename")
        ext = Path(item.get("original_filename") or "video.mp4").suffix.lower() or ".mp4"
        variant = "01"
        proposed = f"CC_{country}_{lang}_VID_{angle}_{porient}_{variant}{ext}" if porient != "REVIEW" and country != "UNKNOWN" and lang != "UNKNOWN" else "REVIEW"
        rows.append({
            "idx": idx,
            "current_filename": item.get("original_filename", ""),
            "relative_path": item.get("relative_path", ""),
            "format": "VID",
            "visible_lang_ocr": lang,
            "language_guess": item.get("language_guess", ""),
            "country_proposed": country,
            "country_reason": country_reason,
            "vertical": "CC",
            "angle_proposed": angle,
            "angle_score": angle_score,
            "angle_hits": ";".join(angle_hits),
            "person": person,
            "orientation_mgs": orientation,
            "p_orient": porient,
            "variant": variant,
            "proposed_filename_base": proposed,
            "confidence": confidence,
            "needs_visual_audit": "yes" if "visual audit" in " ".join(notes) or confidence != "high" else "no",
            "ocr_text_excerpt": text_norm[:500],
            "sheet": item.get("sheet", ""),
            "notes": " | ".join(notes),
        })
    # Resolve duplicate proposed names by assigning sequence within proposed base group.
    counters: dict[str,int] = collections.Counter()
    for r in rows:
        base = r["proposed_filename_base"]
        if base == "REVIEW":
            r["proposed_filename"] = "REVIEW"
            continue
        stem = Path(base).stem
        ext = Path(base).suffix
        key = re.sub(r"_\d{2}$", "", stem)
        counters[key] += 1
        r["variant"] = f"{counters[key]:02d}"
        r["proposed_filename"] = f"{key}_{r['variant']}{ext}"

    csv_path = out_dir / "video-naming-proposal-ocr.csv"
    json_path = out_dir / "video-naming-proposal-summary.json"
    fields = list(rows[0].keys()) if rows else []
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader(); w.writerows(rows)
    summary = {
        "generated_at_utc": dt.datetime.now(dt.UTC).isoformat(),
        "source_manifest": args.manifest_json,
        "rows": len(rows),
        "csv": str(csv_path),
        "by_confidence": dict(collections.Counter(r["confidence"] for r in rows)),
        "by_language": dict(collections.Counter(r["visible_lang_ocr"] for r in rows)),
        "by_country": dict(collections.Counter(r["country_proposed"] for r in rows)),
        "by_angle": dict(collections.Counter(r["angle_proposed"] for r in rows)),
        "by_p_orient": dict(collections.Counter(r["p_orient"] for r in rows)),
        "needs_visual_audit": sum(1 for r in rows if r["needs_visual_audit"] == "yes"),
    }
    json_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
