#!/usr/bin/env python3
"""mgs-rec-p1-orchestrator.py — REC+P1 operation coordinator.

Business model: one REC+P1 request returns one paired deliverable.
Technical model: REC and P1 are generated by separate runners, with minimal handoff.

This orchestrator does not generate article prose and does not consult editorial cache.
"""
from __future__ import annotations

import argparse
import html as html_lib
import json
import re
import subprocess
import sys
import time
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import urljoin, urlparse

ROOT = Path("/root/mgs-agent")
REC_RUNNER = ROOT / "scripts/mgs-rec-runner.py"
P1_RUNNER = ROOT / "scripts/mgs-p1-runner.py"
CONTRACT_REC = ROOT / "skills/content-generate-rec-p1/contracts/cc-rec.md"
CONTRACT_P1 = ROOT / "skills/content-generate-rec-p1/contracts/cc-p1.md"


class OrchestratorError(Exception):
    pass


def run_json(cmd: List[str], *, timeout: int = 1800) -> Dict[str, Any]:
    p = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    raw = (p.stdout or p.stderr or "").strip()
    try:
        data = json.loads(raw or "{}")
    except Exception as e:
        raise OrchestratorError(
            "Command did not return JSON: "
            + " ".join(cmd)
            + f"\nrc={p.returncode}\nstdout={(p.stdout or '')[:1600]}\nstderr={(p.stderr or '')[:1600]}\nerror={e}"
        )
    if p.returncode != 0:
        data.setdefault("ok", False)
        data.setdefault("success", False)
        data.setdefault("returncode", p.returncode)
    return data


def okish(data: Dict[str, Any]) -> bool:
    return bool(data.get("success") is True or data.get("ok") is True)


def site_domain_from_url(url: str) -> str:
    parsed = urlparse(url)
    return parsed.netloc


def fetch_html(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 MGS-Orchestrator/1.0"})
    with urllib.request.urlopen(req, timeout=25) as resp:
        return resp.read(600000).decode(errors="ignore")


def extract_links(html: str, base_url: str) -> List[Dict[str, str]]:
    links: List[Dict[str, str]] = []
    for m in re.finditer(r"<a\b[^>]*href=[\"']([^\"']+)[\"'][^>]*>(.*?)</a>", html, flags=re.I | re.S):
        href = html_lib.unescape(m.group(1).strip())
        if not href or href.startswith(("#", "mailto:", "tel:", "javascript:")):
            continue
        text = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", m.group(2))).strip()
        links.append({"url": urljoin(base_url, href), "text": html_lib.unescape(text)})
    return links


def discover_reference_p1_url(reference_rec_url: str, rec_html: str) -> str:
    base = urlparse(reference_rec_url)
    base_host = base.netloc.lower()
    current_path = base.path.rstrip("/")
    candidates: List[tuple[int, str, str]] = []
    for link in extract_links(rec_html, reference_rec_url):
        parsed = urlparse(link["url"])
        if parsed.scheme not in {"http", "https"} or parsed.netloc.lower() != base_host:
            continue
        path = parsed.path.rstrip("/")
        if not path or path == current_path:
            continue
        hay = (path + " " + link.get("text", "")).lower()
        score = 0
        for token in ("apply", "how-to-apply", "solicitar", "p1", "continue", "learn-more", "more", "offer"):
            if token in hay:
                score += 2
        if "rec" in hay:
            score -= 1
        if score > 0:
            candidates.append((score, link["url"], link.get("text", "")))
    if not candidates:
        raise OrchestratorError("reference_p1_discovery_failed: REC reference has no clear internal P1/apply link; ask for the P1 reference URL or final offer URL")
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def discover_final_offer_url(reference_p1_url: str, p1_html: str) -> str:
    p1_host = urlparse(reference_p1_url).netloc.lower()
    candidates: List[tuple[int, str, str]] = []
    for link in extract_links(p1_html, reference_p1_url):
        parsed = urlparse(link["url"])
        if parsed.scheme not in {"http", "https"}:
            continue
        hay = (parsed.netloc + " " + parsed.path + " " + link.get("text", "")).lower()
        if parsed.netloc.lower() == p1_host:
            continue
        if any(bad in hay for bad in ("facebook", "twitter", "instagram", "linkedin", "pinterest", "whatsapp", "mailto", "privacy", "terms")):
            continue
        score = 1
        for token in ("apply", "solicitar", "request", "get", "offer", "card", "credit", "bank", "issuer", "redirect"):
            if token in hay:
                score += 2
        candidates.append((score, link["url"], link.get("text", "")))
    if not candidates:
        raise OrchestratorError("final_offer_discovery_failed: reference P1 has no clear external CTA/offer link; ask for the final offer URL")
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def discover_reference_chain(reference_rec_url: str) -> Dict[str, str]:
    rec_html = fetch_html(reference_rec_url)
    reference_p1_url = discover_reference_p1_url(reference_rec_url, rec_html)
    p1_html = fetch_html(reference_p1_url)
    final_offer_url = discover_final_offer_url(reference_p1_url, p1_html)
    return {
        "reference_rec_url": reference_rec_url,
        "reference_p1_url": reference_p1_url,
        "final_offer_url": final_offer_url,
    }


def rec_handoff_url(rec: Dict[str, Any]) -> str:
    """Return minimal technical REC reference for P1 runner.

    P1 runner can fetch private/draft REC content when URL contains ?p=<post_id>.
    This avoids handing P1 REC body/prose through the orchestrator.
    """
    post_id = rec.get("post_id")
    public_url = rec.get("public_url") or ""
    if post_id and public_url:
        domain = site_domain_from_url(public_url)
        if domain:
            return f"https://{domain}/?p={post_id}"
    if public_url:
        return public_url
    raise OrchestratorError("REC result missing public_url/post_id; cannot hand off to P1")


def featured_ref_from_result(result: Dict[str, Any], article_type: str) -> Dict[str, Any]:
    """Extract the published featured-media reference from REC/P1 runner JSON."""
    if article_type == "rec":
        featured = (result.get("images") or {}).get("featured") or {}
        return {
            "id": result.get("featured_id") or featured.get("id"),
            "url": result.get("featured_url") or featured.get("source_url") or featured.get("url"),
        }
    featured = ((result.get("images") or {}).get("featured") or {})
    post = result.get("post") or {}
    return {
        "id": featured.get("id") or post.get("featured_media"),
        "url": featured.get("source_url") or featured.get("url"),
    }


def validate_featured_image_separation(rec: Dict[str, Any], p1: Dict[str, Any]) -> Dict[str, Any]:
    """REC+P1 must not reuse the same featured image/media."""
    rec_ref = featured_ref_from_result(rec, "rec")
    p1_ref = featured_ref_from_result(p1, "p1")
    rec_id, p1_id = str(rec_ref.get("id") or ""), str(p1_ref.get("id") or "")
    rec_url, p1_url = str(rec_ref.get("url") or ""), str(p1_ref.get("url") or "")
    same_id = bool(rec_id and p1_id and rec_id == p1_id)
    same_url = bool(rec_url and p1_url and rec_url == p1_url)
    ok = bool(rec_id and p1_id and rec_url and p1_url and not same_id and not same_url)
    detail = {
        "ok": ok,
        "rec_featured_id": rec_ref.get("id"),
        "p1_featured_id": p1_ref.get("id"),
        "rec_featured_url": rec_ref.get("url"),
        "p1_featured_url": p1_ref.get("url"),
        "same_id": same_id,
        "same_url": same_url,
        "rule": "REC and P1 featured images must use distinct media IDs and URLs",
    }
    if not ok:
        raise OrchestratorError(f"rec_p1_featured_image_not_distinct: {json.dumps(detail, ensure_ascii=False)}")
    return detail


def build_rec_cmd(args: argparse.Namespace) -> List[str]:
    cmd = [
        str(REC_RUNNER),
        "--site", args.site,
        "--card", args.card,
        "--status", args.status,
        "--source-url", args.official_url,
        "--article-url", args.reference_rec_url or args.article_url,
    ]
    if args.lang:
        cmd += ["--lang", args.lang]
        if args.allow_language_override:
            cmd.append("--allow-language-override")
    if args.card_image_url:
        cmd += ["--card-image-url", args.card_image_url]
    if args.annual_fee:
        cmd += ["--annual-fee", args.annual_fee]
    if args.apr:
        cmd += ["--apr", args.apr]
    for benefit in args.benefit:
        cmd += ["--benefit", benefit]
    for competitor in args.competitor:
        cmd += ["--competitor", competitor]
    if args.allow_disambiguation:
        cmd.append("--allow-disambiguation")
    if args.dry_run:
        cmd.append("--dry-run")
    return cmd


def build_p1_cmd(args: argparse.Namespace, rec_url: str) -> List[str]:
    cmd = [
        str(P1_RUNNER),
        "--site", args.site,
        "--rec-url", rec_url,
        "--status", args.status,
        "--official-url", args.official_url,
        "--article-url", args.reference_p1_url or args.article_url,
        "--card", args.card,
    ]
    if args.lang:
        cmd += ["--lang", args.lang]
        if args.allow_language_override:
            cmd.append("--allow-language-override")
    if args.annual_fee:
        cmd += ["--annual-fee", args.annual_fee]
    if args.apr:
        cmd += ["--apr", args.apr]
    for benefit in args.benefit:
        cmd += ["--benefit", benefit]
    if args.dry_run:
        cmd.append("--dry-run")
    return cmd


def official_product_preflight(card_name: str, official_url: str) -> None:
    """Block obvious card ↔ official URL mismatch before any publish attempt.

    Conservative after the Nationwide incident: if the URL path advertises a
    different product type (for example `purchase-credit-card`) that is not in
    the requested card name, require the corrected official URL before running.
    """
    parsed = urlparse(official_url)
    path_tokens = set(re.findall(r"[a-z0-9]+", parsed.path.lower()))
    name_l = card_name.lower()
    product_terms = {
        "purchase": "purchase",
        "cashback": "cashback",
        "reward": "reward",
        "rewards": "rewards",
        "travel": "travel",
        "student": "student",
        "business": "business",
    }
    mismatches = []
    for token, phrase in product_terms.items():
        if token in path_tokens and phrase not in name_l:
            mismatches.append(f"url_path_contains_{token}_but_card_name_not_{phrase}")
    if mismatches:
        raise OrchestratorError(
            "official_url_product_mismatch: requested card and official URL look inconsistent; "
            f"card={card_name!r} url={official_url!r} reasons={mismatches}. "
            "Stop and ask for the corrected official product URL before publishing."
        )
    try:
        req = urllib.request.Request(official_url, headers={"User-Agent": "Mozilla/5.0 MGS-Orchestrator/1.0"})
        with urllib.request.urlopen(req, timeout=20) as resp:
            html = resp.read(250000).decode(errors="ignore")
        title_m = re.search(r"<title[^>]*>(.*?)</title>", html, flags=re.I | re.S)
        title = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", title_m.group(1) if title_m else "")).strip().lower()
        if title:
            distinctive = [w for w in re.findall(r"[a-z0-9]+", name_l) if w not in {"credit", "card", "the", "and", "uk"}]
            # Include hostname so issuer tokens present in the official domain
            # (e.g. tescobank.com) do not create a false mismatch when the
            # page title is a generic product name.
            title_and_path = title + " " + parsed.netloc.lower().replace("-", " ") + " " + parsed.path.lower().replace("-", " ")
            missing = [w for w in distinctive if w not in title_and_path]
            if len(missing) >= max(2, len(distinctive) // 2):
                raise OrchestratorError(
                    "official_url_title_mismatch: official page title/path does not match enough requested card terms; "
                    f"card={card_name!r} title={title!r} missing_terms={missing}. Stop and confirm URL."
                )
    except OrchestratorError:
        raise
    except Exception as e:
        raise OrchestratorError(f"official_url_preflight_fetch_failed: {official_url} error={e}")


def validate_contract_preflight(args: argparse.Namespace) -> List[str]:
    warnings: List[str] = []
    if not CONTRACT_REC.exists():
        raise OrchestratorError(f"Missing active REC editorial contract: {CONTRACT_REC}")
    if not CONTRACT_P1.exists():
        raise OrchestratorError(f"Missing active P1 editorial contract: {CONTRACT_P1}")
    if not (args.reference_rec_url or args.article_url):
        raise OrchestratorError("--reference-rec-url is required for normal REC+P1 production. Atena reads the reference REC, discovers its P1, and extracts the final offer CTA. Legacy --article-url remains only for direct/debug rewrite input.")
    if not args.official_url:
        raise OrchestratorError("final offer URL missing: provide --official-url/--offer-url explicitly or pass --reference-rec-url so the orchestrator can extract it from the reference P1")
    if not args.reference_rec_url:
        official_product_preflight(args.card, args.official_url)
    if args.status == "publish" and not args.card_image_url:
        raise OrchestratorError(
            "--card-image-url is required for publish. If the image is missing/invalid, stop and ask Raquel/Rodolfo for a correct card image; automatic image fallback is disabled for production."
        )
    if args.status == "publish" and args.dry_run:
        warnings.append("dry_run_requested_with_publish_status: no WordPress publish will occur")
    return warnings


def main() -> int:
    ap = argparse.ArgumentParser(description="Coordinate REC+P1 as one operation with separate runners")
    ap.add_argument("--site", required=True)
    ap.add_argument("--card", required=True)
    ap.add_argument("--reference-rec-url", default="", help="Normal input: REC reference URL. The orchestrator discovers the linked reference P1 and extracts its final offer CTA.")
    ap.add_argument("--reference-p1-url", default="", help="Optional override when the reference P1 cannot be discovered from the REC reference.")
    ap.add_argument("--official-url", "--offer-url", dest="official_url", default="", help="Optional override for the final P1 CTA/offer URL. Normally extracted from the reference P1.")
    ap.add_argument("--article-url", default="", help="Legacy/debug direct article-base URL. Normal production should use --reference-rec-url.")
    ap.add_argument("--status", choices=["draft", "publish"], default="draft")
    ap.add_argument("--card-image-url", default="")
    ap.add_argument("--annual-fee", default="")
    ap.add_argument("--apr", default="")
    ap.add_argument("--benefit", action="append", default=[])
    ap.add_argument("--competitor", action="append", default=[])
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--allow-disambiguation", action="store_true")
    ap.add_argument("--timeout", type=int, default=2400)
    ap.add_argument("--lang", default="", help="Debug-only language override. Production language comes from site.language.")
    ap.add_argument("--allow-language-override", action="store_true", help="Allow --lang in dry-run/draft debug. Publish aborts if it conflicts with site.language.")
    args = ap.parse_args()

    started = time.time()
    steps: List[str] = []
    timings: Dict[str, float] = {}
    warnings: List[str] = []
    result: Dict[str, Any] = {
        "ok": False,
        "runner": "mgs-rec-p1-orchestrator",
        "site": args.site,
        "card": args.card,
        "status_requested": args.status,
        "dry_run": args.dry_run,
        "official_url": args.official_url,
        "policy": {
            "editorial_cache": "disabled",
            "contract_rec": str(CONTRACT_REC),
            "contract_p1": str(CONTRACT_P1),
            "rec_p1_model": "one operation, two separate generations",
        },
    }

    try:
        if args.lang and not args.allow_language_override:
            raise OrchestratorError("--lang is debug-only. Use site.language for production, or pass --allow-language-override for dry-run/draft debugging.")
        if args.reference_rec_url:
            t = time.time()
            if args.reference_p1_url:
                p1_html = fetch_html(args.reference_p1_url)
                if not args.official_url:
                    args.official_url = discover_final_offer_url(args.reference_p1_url, p1_html)
                reference_chain = {
                    "reference_rec_url": args.reference_rec_url,
                    "reference_p1_url": args.reference_p1_url,
                    "final_offer_url": args.official_url,
                    "p1_override": True,
                }
            else:
                reference_chain = discover_reference_chain(args.reference_rec_url)
                args.reference_p1_url = reference_chain["reference_p1_url"]
                if not args.official_url:
                    args.official_url = reference_chain["final_offer_url"]
            timings["reference_chain_discovery_sec"] = round(time.time() - t, 3)
            steps.append("reference_chain_discovered")
            result["reference_chain"] = reference_chain
            result["official_url"] = args.official_url
        warnings.extend(validate_contract_preflight(args))
        steps.append("contract_preflight_passed")

        rec_cmd = build_rec_cmd(args)
        t = time.time()
        rec = run_json(rec_cmd, timeout=args.timeout)
        timings["rec_runner_sec"] = round(time.time() - t, 3)
        steps.append("rec_runner_completed")
        result["rec"] = rec
        if not okish(rec):
            raise OrchestratorError(f"REC runner failed; P1 not started. error={rec.get('error') or rec.get('status_detail') or rec}")

        if args.dry_run:
            warnings.append("dry_run: P1 runner skipped because REC was not published/created for authenticated handoff")
            result.update({
                "ok": True,
                "status_detail": "dry_run_rec_validated_p1_skipped",
                "steps": steps,
                "warnings": warnings,
                "duration_sec": round(time.time() - started, 3),
                "timings_sec": timings,
                "handoff": {
                    "allowed_fields": ["card_name", "card_slug", "rec_post_id", "rec_url", "official_url", "validated_card_image_id/url"],
                    "forbidden_fields": ["REC body", "REC opening", "REC benefit prose", "REC descriptor/tag", "card-cache data"],
                },
            })
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return 0

        rec_url = rec_handoff_url(rec)
        steps.append("minimal_rec_handoff_prepared")

        p1_cmd = build_p1_cmd(args, rec_url)
        t = time.time()
        p1 = run_json(p1_cmd, timeout=args.timeout)
        timings["p1_runner_sec"] = round(time.time() - t, 3)
        steps.append("p1_runner_completed")
        result["p1"] = p1
        if not okish(p1):
            raise OrchestratorError(f"P1 runner failed after REC success. error={p1.get('error') or p1.get('status_detail') or p1}")

        rec_public_url = rec.get("public_url")
        p1_post = p1.get("post") or {}
        p1_url = p1_post.get("link")
        featured_separation = validate_featured_image_separation(rec, p1)
        validation = {
            "rec_ok": True,
            "p1_ok": True,
            "rec_to_p1_checked_by_p1_runner": bool((p1.get("rec_source") or {}).get("url")),
            "p1_to_official_url": p1.get("official_url") == args.official_url,
            "no_editorial_cache": True,
            "featured_image_separation": featured_separation,
        }
        steps.append("featured_image_separation_validated")
        steps.append("pair_validated")
        result.update({
            "ok": True,
            "status_detail": "fully_validated_pair",
            "steps": steps,
            "warnings": warnings,
            "duration_sec": round(time.time() - started, 3),
            "timings_sec": timings,
            "pair": {
                "rec_url": rec_public_url,
                "p1_url": p1_url,
                "official_url": args.official_url,
                "rec_post_id": rec.get("post_id"),
                "p1_post_id": p1_post.get("id"),
            },
            "validation": validation,
            "handoff": {
                "rec_url_used_for_p1": rec_url,
                "passed_prose": False,
                "passed_cache_data": False,
            },
        })
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0

    except Exception as e:
        result.update({
            "ok": False,
            "error": str(e),
            "steps": steps,
            "warnings": warnings,
            "duration_sec": round(time.time() - started, 3),
            "timings_sec": timings,
        })
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
