#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,shutil
from pathlib import Path
B=Path('/root/mgs-agent/backups/meta-app-b0044-to-b0045-cutover-20260903-122500');B.mkdir(parents=True,exist_ok=False)
files={'meta-app-registry.json.before':Path('/root/mgs-agent/data/meta-app-registry.json'),'meta-app-role-monitor-state.json.before':Path('/root/mgs-agent/data/meta-app-role-monitor-state.json'),'meta-app-role-identity-baseline.json.before':Path('/root/mgs-agent/data/meta-app-role-identity-baseline.json'),'meta-app-role-alert-pause.json.before':Path('/root/mgs-agent/data/meta-app-role-alert-pause.json'),'agent-checkpoints.json.before':Path('/root/mgs-agent/data/agent-checkpoints.json'),'knowledge-registry.json.before':Path('/root/mgs-agent/data/knowledge-registry.json'),'infra-inventory.json.before':Path('/root/mgs-agent/data/infra-inventory.json'),'route-pack-05.runtime.before':Path('/root/.hermes/profiles/zeus/skills/growth/meta-app-rate-limit-monitor/references/route-pack-05.md'),'route-pack-05.mirror.before':Path('/root/mgs-agent/profiles/zeus-skills/growth/meta-app-rate-limit-monitor/references/route-pack-05.md'),'meta-app-roles-watch.sh.before':Path('/root/.hermes/profiles/zeus/scripts/meta-app-roles-watch.sh')}
for dst,src in files.items():assert src.exists();shutil.copy2(src,B/dst)
reg=json.loads(files['meta-app-registry.json.before'].read_text());hit=[x for x in reg['apps'] if x.get('app')=='B004-4'];assert len(hit)==1 and not any(x.get('app')=='B004-5' for x in reg['apps']);hit[0].update({'app':'B004-5','channel_id':'1521251334496456815','channel_name':'b004-3-app-status','admin':'Heloisa Barbosa Almeida','onepassword_item_title':'BOT B004-5 Token - Heloisa Barbosa Almeida','expected_sheet_roles':11});reg.update({'updated_by':'zeus','authorized_by':'Rodolfo Mattei','source_message_id':'1545107187972440064'});(B/'meta-app-registry.canary.json').write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n')
script=files['meta-app-roles-watch.sh.before'].read_text();old="REGISTRY_PATH = Path('/root/mgs-agent/data/meta-app-registry.json')";assert script.count(old)==1;script=script.replace(old,f"REGISTRY_PATH = Path('{B}/meta-app-registry.canary.json')",1);lock='LOCK_FILE="/var/lock/meta-app-roles-watch.lock"';assert script.count(lock)==1;script=script.replace(lock,'LOCK_FILE="/var/lock/meta-app-roles-watch-b0045-canary.lock"',1);(B/'meta-app-roles-watch.canary.sh').write_text(script)
(B/'meta-app-role-monitor-state.canary.json').write_text('{"apps": {}}\n');pause={'version':4,'mode':'manual','apps':['B004-5'],'monitor_apps':[],'timezone':'America/New_York','requested_by':'Rodolfo Mattei','source_message_id':'1545107187972440064','reason':'isolated B004-5 cutover canary alert containment'};(B/'meta-app-role-alert-pause.canary.json').write_text(json.dumps(pause,ensure_ascii=False,indent=2)+'\n')
lines=[]
for p in sorted(B.iterdir(),key=lambda x:x.name):
 if p.is_file() and p.name!='SHA256SUMS':lines.append(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}')
(B/'SHA256SUMS').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':'prepared','backup':str(B),'files':len(files),'canary_app':'B004-5'},ensure_ascii=False))
