import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {planApiAccounts,prepareApiCollection} from '../api-spend-accounts.mjs';import {sourceReconciliationTolerance} from '../media-spend.mjs';
const D=new URL('../private/spend-placement-1547012165150711858/',import.meta.url),w=JSON.parse(fs.readFileSync(new URL('baseline-workspace.json',D))),registry=JSON.parse(fs.readFileSync(new URL('baseline-accounts.json',D))),source=JSON.parse(fs.readFileSync(new URL('api-first/collection.json',D))),state={id:w.id,result:{domain:w.domain}},copy=x=>structuredClone(x);
test('API-first sees34 Meta positive accounts independent of80 registered',()=>{assert.equal(source.accounts.filter(x=>x.platform==='meta').length,34);assert.equal(registry.accounts.filter(x=>(x.platform||'meta')==='meta').length,80);assert.equal(source.discovered_count,350);});
test('Meta daily versus aggregate tolerance uses explicit bounded source rounding evidence',()=>{assert.equal(sourceReconciliationTolerance({platform:'meta',reconciliation_tolerance:'0.06'}),60000n);assert.equal(sourceReconciliationTolerance({platform:'meta'}),10000n);assert.equal(sourceReconciliationTolerance({platform:'google',reconciliation_tolerance:'0.06'}),0n);assert.throws(()=>sourceReconciliationTolerance({platform:'meta',reconciliation_tolerance:'0.17'}));const zero=prepareApiCollection(source,registry,{created:[],bound:[],blocked:[]}).accounts.find(x=>x.aggregate_total==='0'&&x.daily.every(d=>d.source_row===false));assert.equal(zero?.reconciliation_tolerance,'0');});
test('six missing Meta accounts register to unambiguous existing site/country',()=>{const p=planApiAccounts(state,registry,source);assert.equal(p.created.length,6);assert.equal(p.created.filter(x=>x.site==='Yolokfx').length,5);assert.equal(p.created.filter(x=>x.site==='Vizioid').length,1);assert.ok(p.created.every(x=>x.country==='US'));assert.equal(p.bound.length,1);assert.equal(p.bound[0].site,'GamingAdx');assert.ok(p.blocked.some(x=>x.name==='Mattei 1'));});
test('registration and binding are idempotent and preserve explicit existing sites',()=>{const p=planApiAccounts(state,registry,source),next={...registry,accounts:p.accounts};const again=planApiAccounts(state,next,source);assert.equal(again.created.length,0);assert.equal(again.bound.length,0);for(const a of registry.accounts.filter(a=>a.sites.length))assert.deepEqual(p.accounts.find(x=>x.id===a.id).bindings,a.bindings);});
test('unknown or ambiguous site and country never create a registration',()=>{for(const name of ['Unrecognized-US-CC-EN-01','Vizioid-ZZ-CC-EN-01']){const s=copy(source);s.accounts=[{...s.accounts.find(x=>x.name==='Vizioid-US-SHEIN-EN-01-G002'),name}];const p=planApiAccounts(state,registry,s);assert.equal(p.created.length,0);assert.equal(p.blocked.length,1);}});
test('API source errors never become new accounts',()=>{const s=copy(source);s.accounts=s.accounts.map(a=>({...a,status:'error'}));assert.equal(planApiAccounts(state,registry,s).created.length,0);});
test('prepared collection includes new spending accounts and only verified zeros',()=>{const p=planApiAccounts(state,registry,source),d={...registry,accounts:p.accounts},c=prepareApiCollection(source,d,p);assert.equal(c.accounts.length,88);assert.equal(c.registry_revision,registry.revision);for(const a of p.created)assert.ok(c.accounts.some(x=>x.id===a.id));assert.ok(c.missing_accounts.every(x=>!d.accounts.some(a=>a.id===x.account_id)));});
