import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {randomUUID} from 'node:crypto';import fs from 'node:fs/promises';import vm from 'node:vm';
import {openDatabase,initialize,root} from '../storage.mjs';import {createApp} from '../server.mjs';
test('profit and ROI color boundaries, including minus 15 and zero',async()=>{const source=(await fs.readFile(path.join(root,'public/app.js'),'utf8')).split("document.addEventListener('click'")[0];const ctx=vm.createContext({Intl});vm.runInContext(source,ctx);vm.runInContext('data={fx:5}',ctx);for(const [v,color] of [[-0.15001,'negative'],[-0.15,'warning'],[-0.01,'warning'],[0,'warning'],[0.00001,'positive']])assert.match(vm.runInContext(`roi(${v})`,ctx),new RegExp(color));assert.equal(vm.runInContext("roi('')",ctx),'—');assert.match(vm.runInContext('num(1,true)',ctx),/positive/);assert.doesNotMatch(vm.runInContext('num(0,true)',ctx),/positive/);});
test('monthly site registry CRUD, allocation, taxes/revshare, new-site daily entries and audit',{timeout:360000},async()=>{
 const dir=path.join(root,'private/catalog-test-'+randomUUID()),db=await openDatabase(dir);await initialize(db);const server=(await createApp(db)).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const get=async p=>{const r=await fetch(base+p);assert.equal(r.status,200);return r.json();};const post=async(p,b,code=200)=>{const r=await fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();assert.equal(r.status,code,JSON.stringify(d));return d;};const mutate=async(p,b,code=200)=>{const w=await get('/api/workspace');return post('/api/scenarios/'+w.id+'/'+p,{revision:w.revision,...b},code);};
 try{
  const baseline=await get('/api/scenarios/baseline');let w=await get('/api/workspace');assert.equal(w.sites.length,41);assert.equal(w.sites.reduce((a,s)=>a+s.units,0),43);assert.equal(w.period.id,'2026-08');assert.equal(w.period.other_periods_open,true);
  await post('/api/workspace/open',{});const name='TEST registered CAD site';const form={name,status:'ATIVO',countries:['US'],manager:'nicolas',partner:'JBF',currency:'CAD'};
  await mutate('sites',{...form,countries:['US','US']},400);await mutate('sites',{...form,manager:''},400);await mutate('sites',form);w=await get('/api/workspace');const site=w.sites.find(s=>s.name===name);assert.ok(site.new);assert.equal(w.domain.facts.filter(f=>f.site===name).length,31);assert.equal(w.domain.allocation.active_units,31);
  const entry={site:name,partner:'JBF',manager:'nicolas',country:'US',date:'2026-08-01',currency:'CAD',gross:'1000',spend:'10',invalid_rate:'0',share_rate:'0',tax_rate:'0',quotes:{USDBRL:'1',USDCAD:'1',GBPUSD:'1'}};
  await mutate('entries',{...entry,manager:'joe'},400);await mutate('entries',entry);w=await get('/api/workspace');let fact=w.domain.facts.find(f=>f.site===name&&!f.native_placeholder);assert.ok(Math.abs(Number(fact.gross)-1000/Number(w.rates.find(r=>r.source==='H1').value))<1e-7);assert.equal(w.domain.facts.filter(f=>f.site===name).length,31);
  await mutate('rates',{key:'principal|Agosto 2026|C1',value:'0.06',mode:'fixed',status:'confirmed'});await mutate('rates',{key:'principal|Agosto 2026|D1',value:'0.12',mode:'fixed',status:'confirmed'});w=await get('/api/workspace');fact=w.domain.facts.find(f=>f.site===name&&!f.native_placeholder);assert.equal(Number(fact.tax_rate),0.06);assert.equal(Number(fact.share_rate),0.12);const special=w.domain.facts.filter(f=>f.rate_source?.share==='EW82');assert.ok(special.length>0);assert.ok(special.every(f=>Number(f.share_rate)===0.05));
  const gross=fact.gross;await mutate('sites',{target:site.id,status:'INATIVO'});w=await get('/api/workspace');assert.equal(w.domain.facts.find(f=>f.site===name&&!f.native_placeholder).gross,gross);assert.equal(Number(w.domain.segments.find(s=>s.site===name).expenses),0);
  const egg=w.sites.find(s=>s.name==='Eggbev');await mutate('sites',{target:egg.id,status:'INATIVO'});w=await get('/api/workspace');assert.equal(w.domain.allocation.active_units,29);assert.equal(Number(w.domain.segments.find(s=>s.site==='Eggbev').expenses),0);
  const before=Number(w.domain.cash.company_expenses);await mutate('expenses',{category:'company',label:'TEST allocation extra',amount:'60',currency:'USD',status:'A conferir'});w=await get('/api/workspace');assert.ok(Math.abs(Number(w.domain.cash.company_expenses)-before+60)<1e-7);assert.ok(Math.abs(w.domain.segments.reduce((a,s)=>a+Number(s.expenses),0)-Number(w.domain.cash.company_expenses))<1e-7);
  assert.deepEqual((await get('/api/scenarios/baseline')).domain.cash,baseline.domain.cash);const audit=await get('/api/scenarios/'+w.id+'/audit');assert.ok(audit.some(a=>a.action==='SITE_REGISTERED'));assert.ok(audit.some(a=>a.action==='SITE_STATUS_CHANGED'));
  await fs.writeFile(path.join(root,'private/ui-catalog-1546169687346249728/catalog-api-evidence.json'),JSON.stringify({pass:true,database:dir,sites_before:41,units_before:43,new_site:true,active_inactive_preserves_history:true,allocation_reconciles:true,monthly_rates:true,m2_exception_preserved:true,baseline_preserved:true,production_writes:0}));
 }finally{await new Promise(r=>server.close(r));await db.close();}
});
