import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
const src=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');
test('edited expenses do not show the removed adjustment caption',()=>{assert.ok(!src.includes('Valor ajustado na dash'));assert.ok(src.includes('Remuneração automática · fórmula do gestor'));assert.ok(src.includes('Despesa extra'));});
function helpers(period='2026-09'){const box={currentPeriod:period};vm.createContext(box);vm.runInContext(src.split('\n').filter(x=>x.startsWith('function expenseDisplayName')||x.startsWith('function expenseOrder')).join('\n'),box);return box;}
test('company order follows source IDs, not alphabet; SB names retained',()=>{const h=helpers(),rows=[{id:'company|143',category:'company',label:'JBF Wire Fee:'},{id:'company|114',category:'company',label:'ChatGPT Pro:'},{id:'company|100',category:'company',label:'Servidor Sites + Server Bot:'}];assert.deepEqual(rows.sort(h.expenseOrder).map(x=>x.id),['company|100','company|114','company|143']);assert.equal(h.expenseDisplayName(rows[2].label),'SB Wire Fee:');});
test('all 44 IDs retain their source order in all 17 target periods',()=>{for(let y=2026;y<=2027;y++)for(let m=y===2026?8:1;m<=12;m++){const h=helpers(`${y}-${String(m).padStart(2,'0')}`),rows=Array.from({length:44},(_,i)=>({id:`company|${143-i}`,category:'company',label:`label-${i}`}));assert.deepEqual(rows.sort(h.expenseOrder).map(x=>x.id),Array.from({length:44},(_,i)=>`company|${100+i}`));}});
test('new company entries follow preserved source catalog without dropping rows',()=>{const h=helpers(),rows=[{id:'extra-1',category:'company',label:'A novo'},{id:'company|143',category:'company',label:'JBF Wire Fee:'}];assert.equal(rows.sort(h.expenseOrder)[0].id,'company|143');assert.equal(rows.length,2);});
test('personnel and closed history retain alphabetical behavior',()=>{for(const [period,category] of [['2026-09','personnel'],['2026-07','company']]){const h=helpers(period),rows=[{id:'company|100',category,label:'Zulu'},{id:'company|143',category,label:'Alpha'}];assert.equal(rows.sort(h.expenseOrder)[0].label,'Alpha');}});
function versionHelpers(){const box={};vm.createContext(box);vm.runInContext(src.split('\n').filter(x=>x.startsWith('function expenseEditVersion')).join('\n'),box);return box;}
const expenseSnapshot=()=>({id:'workspace-2026-09',period:{id:'2026-09'},state:'draft',revision:831,domain:{expenses:[{id:'company|121',label:'SMS Funnel:',category:'company',edit_amount:'95000',edit_currency:'BRL',usd:'-18437',brl:'-95000',status:'A conferir',checked_on:null,archived:false}]},additions:[{kind:'expense',id:'company|121',target:'company|121',amount:'95000',currency:'BRL'}]});
test('expense edit version ignores only converted totals and unrelated monthly updates',()=>{const h=versionHelpers(),a=expenseSnapshot(),b=structuredClone(a);b.revision++;b.domain.expenses[0].usd='-18300';b.domain.expenses[0].brl='-95000.00';b.additions.push({kind:'rate',id:'FX',value:'5.2'});assert.equal(h.expenseEditVersion(a,'company|121'),h.expenseEditVersion(b,'company|121'));});
test('expense edit version detects amount currency review label dates archive and source changes',()=>{const h=versionHelpers(),a=expenseSnapshot(),v=h.expenseEditVersion(a,'company|121');for(const change of [{edit_amount:'96000'},{edit_currency:'USD'},{status:'Conferido'},{checked_on:'2026-09-30'},{label:'Outra'},{charges:[{id:'a',date:'2026-09-01',amount:'95000'}]},{archived:true}]){const b=structuredClone(a);Object.assign(b.domain.expenses[0],change);assert.notEqual(v,h.expenseEditVersion(b,'company|121'));}const b=structuredClone(a);b.additions[0].amount='96000';assert.notEqual(v,h.expenseEditVersion(b,'company|121'));});
test('expense edit version is order independent and missing target fails closed',()=>{const h=versionHelpers(),a=expenseSnapshot(),b=structuredClone(a);b.domain.expenses[0]=Object.fromEntries(Object.entries(b.domain.expenses[0]).reverse());assert.equal(h.expenseEditVersion(a,'company|121'),h.expenseEditVersion(b,'company|121'));b.domain.expenses=[];assert.equal(h.expenseEditVersion(b,'company|121'),null);assert.equal(h.expenseEditVersion(a,'missing'),null);});
