import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/financial-summary.js',import.meta.url),'utf8');const ctx={};vm.createContext(ctx);vm.runInContext(source,ctx);
const projectionFixture=()=>({period:{id:'2026-10',days:31},domain:{realized:{elapsed_days:2,gross:200,invalid:-2,net:178.2,tax:-8.91,direct_expense:-12,spend:-80},cash:{company_expenses:-310,personnel:-155,direct_expenses:-999},projection:{state:'in_progress',half_usd:366.4975}}});
test('composition estimated columns start in October and remain standard beyond registered years',()=>{const d=projectionFixture();for(const p of ['2026-08','2026-09','2026-00','2026-13','2026-1','bad']){d.period.id=p;assert.equal(ctx.compositionEstimates(d),null);}for(const p of ['2026-10','2026-11','2026-12','2027-01','2028-02','2035-12']){d.period.id=p;assert.equal(ctx.compositionEstimates(d).length,12);}});
test('composition uses completed days, fixed costs once and exact existing engine projection',()=>{const d=projectionFixture(),before=JSON.stringify(d),r=ctx.compositionEstimates(d);assert.equal(r[0],3100);assert.equal(r[1],-31);assert.ok(Math.abs(r[2]+306.9)<1e-9);assert.equal(r[5],-186);assert.equal(r[6],-310);assert.equal(r[7],-155);assert.equal(r[8],-1240);assert.equal(r[9],d.domain.projection.half_usd*2);assert.ok(Math.abs(r[0]+r[1]+r[2]+r[4]+r[5]+r[6]+r[7]+r[8]-r[9])<1e-9);assert.equal(r[10],r[11]);assert.equal(JSON.stringify(d),before);});
test('composition no completed days or future period never fabricates forecast zero',()=>{for(const [days,state,value] of [[0,'in_progress',null],[0,'planned',null],[32,'in_progress',1],[2,'planned',1]]){const d=projectionFixture();d.domain.realized.elapsed_days=days;d.domain.projection.state=state;d.domain.projection.half_usd=value;assert.ok(ctx.compositionEstimates(d).every(x=>x===null));}});
test('composition closed month and negative results preserve signs',()=>{const d=projectionFixture();d.domain.realized.elapsed_days=31;d.domain.projection.state='closed';d.domain.projection.half_usd=-194.855;const r=ctx.compositionEstimates(d);assert.equal(r[0],200);assert.equal(r[5],-12);assert.equal(r[6],-310);assert.equal(r[10],-194.855);});
test('Gross -> deductions -> final net and Sheet-style ROI, no double invalid',()=>{const r=ctx.financialTotals([{gross:1000,invalid:-10,net:891,tax:-44.55,spend:-500}],-100,-50);assert.equal(r.revshare,-99);assert.ok(Math.abs(r.profit-196.45)<1e-10);assert.equal(r.roi_gross,1);assert.ok(Math.abs(r.roi_net-(891/694.55-1))<1e-10);assert.equal(ctx.financialTotals([]).roi_net,'');});
test('direct SMS expense is separate from media and still reduces profit',()=>{const r=ctx.financialTotals([{gross:100,invalid:0,net:90,tax:-5,spend:-40},{gross:0,invalid:0,net:0,tax:0,spend:0,direct_expense:-12}]);assert.equal(r.spend,-40);assert.equal(r.direct_expenses,-12);assert.equal(r.profit,33);});

test('Company totals equal sum of daily final net; monthly ROI not average',()=>{const facts=[{gross:100,invalid:-1,net:89.1,tax:-4.455,spend:-40},{gross:200,invalid:-2,net:178.2,tax:-8.91,spend:-90}];const a=ctx.financialTotals(facts,-20,-10),b=ctx.financialTotals([facts[0]],-10,-5),c=ctx.financialTotals([facts[1]],-10,-5);assert.ok(Math.abs(a.profit-b.profit-c.profit)<1e-10);assert.equal(a.roi_gross,300/130-1);});
test('daily realized rows stop at explicit cutoff and accrue fixed costs only through it',()=>{const data={period:{id:'2026-09',days:30},domain:{facts:[{id:'d1',site:'A',date:'2026-09-01',gross:100,invalid:-1,net:89.1,tax:-4.455,spend:-40},{id:'d10',site:'A',date:'2026-09-10',gross:1000,invalid:-10,net:891,tax:-44.55,spend:-400}],segments:[{site:'A',expenses:-300}],cash:{company_expenses:-300,personnel:-150},realized:{cutoff_date:'2026-09-09',elapsed_days:9}},model:{facts:{}},additions:[]},rows=ctx.financialRows(data);assert.equal(rows.length,31);assert.equal(rows[9].gross,0);assert.equal(rows[9].general,0);assert.equal(rows[9].staff,0);const total=rows.at(-1);assert.equal(total.date,'TOTAL REALIZADO');assert.equal(total.gross,100);assert.equal(total.general,-90);assert.equal(total.staff,-45);assert.equal(total.elapsed_days,9);});
test('confirmed partial GAM day includes daily fixed costs without entering realized totals',()=>{const data={period:{id:'2026-09',days:30},domain:{facts:[{id:'d1',site:'A',date:'2026-09-01',gross:100,invalid:-1,net:89.1,tax:-4.455,spend:-40},{id:'staged',site:'A',date:'2026-09-10',gross:1000,invalid:-10,net:891,tax:-44.55,spend:-400}],segments:[{site:'A',expenses:-300}],cash:{company_expenses:-300,personnel:-150},realized:{cutoff_date:'2026-09-09',elapsed_days:9}},model:{facts:{}},additions:[{id:'staged',source_import_type:'gam_email_daily',date:'2026-09-10',currency:'USD',gross:'1000'}]},rows=ctx.financialRows(data);assert.equal(rows[9].staged,true);assert.equal(rows[9].gross,1000);assert.equal(rows[9].spend,-400);assert.equal(rows[9].general,-10);assert.equal(rows[9].staff,-5);assert.equal(rows[9].profit,891-44.55-400-10-5);assert.equal(rows[10].general,0);assert.equal(rows[10].staff,0);const siteRows=ctx.financialRows(data,'A');assert.equal(siteRows[9].general,-10);assert.equal(siteRows[9].staff,0);const total=rows.at(-1);assert.equal(total.gross,100);assert.equal(total.spend,-40);assert.equal(total.general,-90);assert.equal(total.staff,-45);});
