import test from 'node:test';import assert from 'node:assert/strict';import {cents,ledgerSummary,mayRequest,partnerCanRead,paymentExchangeIndicators} from '../finance-ops.mjs';import {managerView} from '../manager-view.mjs';
test('monetary cents are exact, half-up and signed',()=>{assert.equal(cents('0.7133221368276281'),71);assert.equal(cents('-10.005'),-1001);assert.equal(cents('1.005'),101);assert.throws(()=>cents('NaN'));});
test('ledger: fifty percent plus carry, reimbursement minus payment; no company expense mutation',()=>{const periods=[{period:'2026-08',due:10000},{period:'2026-09',due:5000}],entries=[{period:'2026-08',kind:'adjustment',direction:1,amount_cents:2000},{period:'2026-08',kind:'payment',direction:-1,amount_cents:8000}];const r=ledgerSummary(periods,entries,71,'2026-09');assert.equal(r.previous,4071);assert.equal(r.balance,9071);assert.equal(r.due,5000);assert.equal(ledgerSummary(periods,entries,71,'2026-08').balance,4071);});
test('proposal target allowlist fails closed',()=>{assert.equal(mayRequest('/api/scenarios/workspace-2026-08/expenses'),true);assert.equal(mayRequest('/api/finance/users'),false);assert.equal(mayRequest('/api/finance/users/nicolas/credential'),false);assert.equal(mayRequest('/api/auth/login'),false);assert.equal(mayRequest('/api/finance/approvals/x/approve'),false);});
test('partner reads the requested Geizian areas but not administration',()=>{for(const url of ['/api/workspace','/api/ad-accounts','/api/manager-workspace','/api/finance/ledger','/api/finance/profile'])assert.equal(partnerCanRead(url),true,url);for(const url of ['/api/finance/users','/api/finance/approvals','/api/finance/activity','/api/scenarios/workspace-2026-09/audit'])assert.equal(partnerCanRead(url),false,url);});
test('Nicolas projection returns only his live engine values, never entire shared site/global cash',()=>{const s={revision:4,result:{results:{'nicolas|Agosto 2026|C22':{actual:123},'joe|Agosto 2026|C22':{actual:999}},domain:{cash:{secret:987},managers:[{manager:'nicolas',row:2,profit:123},{manager:'joe',row:2,profit:999}],expenses:[]}}};const src=[{book:'nicolas',sheet:'Agosto 2026',cell:'B20',input:'Eggbev CAD US'},{book:'nicolas',sheet:'Agosto 2026',cell:'C20',input:'GROSS USD'}];const v=managerView(s,src,'2026-08');assert.equal(v.blocks[0].rows[0].values[1],123);assert.equal(v.blocks[0].rows.length,31);assert.equal(v.summaries.length,1);assert.equal(v.source,'dash');assert.ok(!JSON.stringify(v).includes('999'));assert.ok(!('cash' in v));});
test('Payments month list filters reference for every role and payee without changing carry',async()=>{
 const fs=await import('node:fs/promises'),vm=await import('node:vm');const source=await fs.readFile(new URL('../public/operations.js',import.meta.url),'utf8');
 for(const role of ['owner','partner','manager'])for(const counterparty of ['geizian','personnel|154','personnel|155','personnel|TEST']){
  const nodes=new Map(),document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,{});return nodes.get(s);},querySelectorAll:()=>[]};const ctx=vm.createContext({Intl,URLSearchParams,location:{search:'?view=payments'},document});
  vm.runInContext(source.slice(0,source.indexOf("$('#cancel').onclick=")),ctx);
  for(const month of ['2026-08','2026-09','2026-11','2027-01']){
   const entries=[{id:'a',period:'2026-08',effective_date:'2026-09-18',description:'TEST AUGUST',kind:'adjustment',direction:1,amount_cents:6000},{id:'b',period:'2026-09',effective_date:'2026-09-20',description:'TEST SEPTEMBER',kind:'payment',direction:-1,amount_cents:2000},{id:'v',period:month,effective_date:'2026-09-20',description:'TEST VOID',kind:'adjustment',direction:1,amount_cents:100,voided_at:'2026-09-20'}];
   const data={period:month,counterparty,party:{id:counterparty,label:counterparty},parties:[{id:counterparty,label:counterparty}],entries,previous:12345,due:8000,movement:0,balance:20345,status:'Parcial'};
   ctx.fixture=structuredClone(data);ctx.user={role};vm.runInContext('me=user;state=fixture;paymentsView()',ctx);const html=nodes.get('#content').innerHTML;
   for(const e of entries)assert.equal(html.includes(e.description),!e.voided_at&&e.period===month,`${role}/${counterparty}/${month}/${e.id}`);
   assert.deepEqual(ctx.fixture,data,'renderer does not mutate financial data');assert.match(html,/123,45/);assert.match(html,/203,45/);
   if(!entries.some(e=>!e.voided_at&&e.period===month))assert.match(html,/Nenhum lançamento neste mês/);
   assert.equal(html.includes('data-ledger-edit='),role!=='manager'&&entries.some(e=>!e.voided_at&&e.period===month));
  }
 }
});
test('engine scientific decimals convert to cents exactly including rollover zero',()=>{
 for(const x of ['0E-30','-0E-40','0e+12','0.000E-100'])assert.equal(cents(x),0);
 for(const [v,want] of [['1.005E+0',101],['-1.005e0',-101],['1231019E-2',1231019],['5e-3',1],['4.999e-3',0],['1e-40',0],['999999999.995',100000000000],['1e9',100000000000],['0001.005e0',101],['-0.0049e0',0]])assert.equal(cents(v),want,v);
 for(const x of ['NaN','Infinity','1e','1e10001','1e309','1.000000001e9','1e-10001','1.2.3','123,45'])assert.throws(()=>cents(x),undefined,x);
});
test('failed month load clears previous ledger and later successful load clears error',async()=>{
 const fs=await import('node:fs/promises'),vm=await import('node:vm');const source=await fs.readFile(new URL('../public/operations.js',import.meta.url),'utf8'),nodes=new Map();
 const document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',insertAdjacentHTML(){}});return nodes.get(s);},querySelectorAll:()=>[]};
 const ctx=vm.createContext({Intl,URLSearchParams,location:{search:'?view=payments'},document,window:{MGSNavigation:{setPeriod(){}}}});vm.runInContext(source.slice(0,source.indexOf("$('#cancel').onclick=")),ctx);
 vm.runInContext("me={role:'owner'};period='2026-10';state={period:'2026-09'};$('#content').innerHTML='PREVIOUS SEPTEMBER PAYMENT';api=async()=>{throw Error('Valor monetário inválido')}",ctx);
 await assert.rejects(vm.runInContext('load()',ctx),/Valor monetário inválido/);assert.ok(!nodes.get('#content').innerHTML.includes('PREVIOUS SEPTEMBER PAYMENT'));assert.equal(vm.runInContext('state',ctx),null);
 vm.runInContext("$('#message').textContent='Valor monetário inválido';api=async()=>({period:'2026-10'});paymentsView=()=>{$('#content').innerHTML='OCTOBER'}",ctx);await vm.runInContext('load()',ctx);assert.equal(nodes.get('#message').textContent,'');assert.equal(nodes.get('#content').innerHTML,'OCTOBER');
});
test('out-of-order month responses cannot replace the latest selection',async()=>{
 const fs=await import('node:fs/promises'),vm=await import('node:vm');const source=await fs.readFile(new URL('../public/operations.js',import.meta.url),'utf8'),nodes=new Map(),pending=[];
 const document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',insertAdjacentHTML(){}});return nodes.get(s);},querySelectorAll:()=>[]};
 const ctx=vm.createContext({Intl,URLSearchParams,location:{search:'?view=payments'},document,window:{MGSNavigation:{setPeriod(){}}},request:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))});vm.runInContext(source.slice(0,source.indexOf("$('#cancel').onclick=")),ctx);
 vm.runInContext("me={role:'owner'};api=request;paymentsView=()=>{$('#content').innerHTML=state.period};period='2026-09'",ctx);const first=vm.runInContext('load()',ctx);vm.runInContext("period='2026-10'",ctx);const second=vm.runInContext('load()',ctx);
 pending[1].resolve({period:'2026-10'});await second;pending[0].resolve({period:'2026-09'});await first;assert.equal(nodes.get('#content').innerHTML,'2026-10');assert.equal(vm.runInContext('state.period',ctx),'2026-10');
});
const fxKeys=['principal|CAIXA SINTETICO|J2','principal|Agosto 2026|H1','principal|Agosto 2026|I1'];
test('all 17 workspaces resolve payment confirmation per currency, not month age',()=>{for(let offset=0;offset<17;offset++){const period=new Date(Date.UTC(2026,7+offset,1)).toISOString().slice(0,7);const selected={id:'workspace-'+period,fx:'5.08',fx_cad:'1.41708',fx_gbp:'1.3357',rate_settings:fxKeys.map(key=>({kind:'rate',key,mode:'fixed',status:'confirmed'}))};let out=paymentExchangeIndicators(selected);assert.equal(out.status,'Confirmado',period);assert.deepEqual(out.exchange_rates.map(r=>r.status),['Confirmado','Confirmado','Confirmado']);assert.deepEqual(out.exchange_rates.map(r=>r.value),['5.08','1.41708','1.3357']);selected.rate_settings[1].status='provisional';out=paymentExchangeIndicators(selected);assert.equal(out.status,'Parcialmente confirmado');assert.deepEqual(out.exchange_rates.map(r=>r.status),['Confirmado','Provisório','Confirmado']);}});
test('missing confirmation and automatic rates fail closed as provisional',()=>{const s={fx:'5',fx_cad:'1.4',fx_gbp:'1.3'};assert.equal(paymentExchangeIndicators(s).status,'Provisório');s.rate_settings=fxKeys.map(key=>({key,mode:'auto',status:'confirmed'}));assert.ok(paymentExchangeIndicators(s).exchange_rates.every(x=>x.status==='Provisório'));});
test('Payments renderer uses individual status and retains frozen history',async()=>{const fs=await import('node:fs/promises'),vm=await import('node:vm');const source=await fs.readFile(new URL('../public/operations.js',import.meta.url),'utf8');const ctx=vm.createContext({Intl});vm.runInContext(source.slice(0,source.indexOf('let me,view=')),ctx);const out=vm.runInContext(`paymentIndicators({status:'Parcialmente confirmado',source_note:'Estados individuais',exchange_rates:[{label:'USD',value:5,status:'Confirmado'},{label:'CAD',value:1.4,status:'Provisório'}]})`,ctx);assert.match(out,/>Confirmado</);assert.match(out,/>Provisório</);assert.match(vm.runInContext(`paymentIndicators({status:'Fechado',exchange_rates:[{label:'USD',value:5}]})`,ctx),/>Fechado</);});
