import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,scryptSync} from 'node:crypto';import {request} from 'node:http';import {openPostgres,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const database='mgs_finance_history_ui_1546896342805123125',dir=path.join(root,'private/history-import-1546884731436671056');const db=await openPostgres({database,user:'mgs_pg',options:'-c role=mgsfinance -c timezone=UTC -c statement_timeout=60000'});let server;
try{
 const initial=(await db.query("SELECT id,md5(result::text) h,md5(overrides::text) o,md5(additions::text) a,revision FROM scenarios ORDER BY id")).rows;
 const password=randomUUID()+'-ISOLATED',salt=randomUUID(),config={username:'rodolfo',salt,hash:scryptSync(password,salt,64).toString('hex'),origin:'https://dash.mgsdigitalcorp.com'};server=(await createApp(db,{auth:config})).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 function call(url,body,h={},expected=200){return new Promise((resolve,reject)=>{const req=request({hostname:'127.0.0.1',port:server.address().port,path:url,method:body===undefined?'GET':'POST',headers:{Host:'dash.mgsdigitalcorp.com',...(body===undefined?{}:{'Content-Type':'application/json',Origin:config.origin}),...h}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{try{let data;try{data=JSON.parse(s);}catch{}assert.equal(res.statusCode,expected,url+' '+s.slice(0,200));resolve({data,headers:res.headers});}catch(e){reject(e);}})});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
 async function login(username,pw){const r=await call('/api/auth/login',{username,password:pw});const h={Cookie:r.headers['set-cookie'][0].split(';')[0]},me=(await call('/api/auth/me',undefined,h)).data;return {...h,'X-CSRF-Token':me.csrf};}
 const owner=await login('rodolfo',password),build=JSON.parse(await fs.readFile(path.join(dir,'built.json'),'utf8'));let cells=0,denied=0,current=0;const monthly=[];const periods=(await call('/api/periods',undefined,owner)).data;assert.equal(periods.length,24);assert.equal(periods.filter(p=>p.historical).length,7);
 for(const m of build.manifest){const key=m.book==='george'?'icaro':m.book;const d=(await call('/api/history?period='+m.period+'&book='+key,undefined,owner)).data;const expected=JSON.parse(await fs.readFile(path.join(dir,'payloads',m.file),'utf8'));assert.deepEqual(d.cells,expected.cells);cells+=d.cells.length;monthly.push({book:m.book,period:m.period,cells:d.cells.length,pass:true});if(m.book==='principal'){assert.deepEqual(d.closure,expected.closure);assert.deepEqual(d.caixa,expected.caixa);await call('/api/scenarios/workspace-'+m.period+'/inputs',{revision:0,key:'bad',value:'0'},owner,409);denied++;await call('/api/finance/ledger',{period:m.period},owner,409);denied++;}}
 assert.equal(cells,build.cells);
 for(const key of ['nicolas','joe','isliago','kelly','icaro']){
  const username='hist_'+key+'_'+randomUUID().slice(0,6),pw=randomUUID()+'-ISOLATED';await call('/api/finance/users',{username,display_name:'ISOLATED '+key,role:'manager',manager_key:key,email:'',phone:'',discord_id:''},owner,201);await call('/api/finance/users/'+username+'/credential',{password:pw,revision:0},owner);const h=await login(username,pw);
  for(const month of periods.filter(p=>p.historical)){
   const own=(await call('/api/history?period='+month.id,undefined,h)).data;assert.equal(own.manager,key);assert.ok(!own.closure&&!own.payroll&&!own.caixa);assert.ok(own.remuneration.length);const other=key==='joe'?'kelly':'joe';for(const book of ['principal',other,'george','caixa']){await call('/api/history?period='+month.id+'&book='+book,undefined,h,403);denied++;}
   await call('/api/history?period='+month.id,{},h,409);denied++;
   const managed=(await call('/api/manager-workspace?period='+month.id,undefined,h)).data;assert.deepEqual(managed,own);
  }
  for(const month of periods.filter(p=>!p.historical)){const own=(await call('/api/manager-workspace?period='+month.id,undefined,h)).data;assert.equal(own.manager,key);assert.ok(own.blocks.length);current++;}
  for(const url of ['/api/workspace','/api/cells','/api/scenarios','/api/finance/users']){await call(url,undefined,h,403);denied++;}
  const legacy=await call('/history',undefined,h,302);assert.ok(legacy.headers.location.startsWith('/operations?view=manager'));await call('/history-dashboard.js',undefined,h);await call('/history-operations.js',undefined,h);await call('/api/auth/logout',{},h);await call('/api/history',undefined,h,401);denied++;
 }
 const aug=(await call('/api/finance/ledger?period=2026-08',undefined,owner)).data,sep=(await call('/api/finance/ledger?period=2026-09',undefined,owner)).data;assert.equal(aug.opening,71);assert.equal(aug.opening_source.period,'2026-07');assert.equal(aug.opening_source.reference,'F132');assert.equal(aug.opening_source.source,'dash-frozen-snapshot');assert.equal(sep.previous,aug.balance);
 for(const q of ["UPDATE finance_history SET authority=authority WHERE period='2026-07'", "DELETE FROM finance_history WHERE period='2026-07'", "INSERT INTO finance_history SELECT * FROM finance_history WHERE period='2026-07'"]){await assert.rejects(db.query(q),e=>e.code==='42501');denied++;}
 assert.deepEqual((await db.query("SELECT id,md5(result::text) h,md5(overrides::text) o,md5(additions::text) a,revision FROM scenarios ORDER BY id")).rows,initial);
 const proof={pass:true,tabs:monthly.length,cells,monthly,denied,current_manager_months:current,july_to_august:aug.opening_source,august_opening_cents:aug.opening,september_previous_cents:sep.previous,august_balance_cents:aug.balance,existing_scenarios_unchanged:true};await fs.writeFile(path.join(root,'private/history-ui-1546894693135028234/stage-pg.json'),JSON.stringify(proof));console.log(JSON.stringify({...proof,monthly:undefined}));
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}
