import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,scryptSync} from 'node:crypto';import {request} from 'node:http';import vm from 'node:vm';import {openPostgres,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const database=process.env.FINANCE_NAVIGATION_DATABASE;assert.equal(database,'mgs_finance_usability_1546729477319696405');const db=await openPostgres({database,user:'mgs_pg',options:'-c role=mgsfinance -c timezone=UTC -c statement_timeout=60000'});let server;
try{
 const initial=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.equal(initial.filter(x=>x.id.startsWith('workspace-')).length,17);
 const password=randomUUID()+'-ISOLATED',salt=randomUUID(),config={username:'rodolfo',salt,hash:scryptSync(password,salt,64).toString('hex'),origin:'https://dash.mgsdigitalcorp.com'};server=(await createApp(db,{auth:config})).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 function call(url,body,h={},expected=200){return new Promise((resolve,reject)=>{const req=request({hostname:'127.0.0.1',port:server.address().port,path:url,method:body===undefined?'GET':'POST',headers:{Host:'dash.mgsdigitalcorp.com',...(body===undefined?{}:{'Content-Type':'application/json',Origin:config.origin}),...h}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{try{let data;try{data=JSON.parse(s);}catch{}assert.equal(res.statusCode,expected,url+' '+JSON.stringify(data));resolve({data,headers:res.headers});}catch(e){reject(e);}})});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
 async function login(username,pw){const r=await call('/api/auth/login',{username,password:pw});const h={Cookie:r.headers['set-cookie'][0].split(';')[0]},me=(await call('/api/auth/me',undefined,h)).data;return {...h,'X-CSRF-Token':me.csrf};}
 const owner=await login('rodolfo',password),periods=(await call('/api/periods',undefined,owner)).data,results=[];assert.equal(periods.length,17);const ledgerBefore=(await db.query("SELECT id,md5(to_jsonb(finance_ledger)::text) hash FROM finance_ledger ORDER BY id")).rows;
 for(const p of periods){const w=(await call('/api/workspace?period='+p.id,undefined,owner)).data,rows=w.domain.expenses.filter(e=>e.category==='personnel'&&e.label.toLowerCase().includes('jislaine'));assert.equal(rows.length,1);const e=rows[0];assert.equal(e.id,'personnel|157');assert.ok([1500,3000].includes(Math.abs(Number(e.brl))));const others=w.domain.expenses.filter(x=>x.id!==e.id);if(Math.abs(Number(e.brl))===1500)await call('/api/scenarios/'+w.id+'/expenses',{revision:w.revision,period:p.id,target:e.id,category:'personnel',label:e.label,amount:'3000',currency:'BRL',status:e.status,checked_on:e.checked_on,activity:e.activity},owner);const after=(await call('/api/workspace?period='+p.id,undefined,owner)).data,n=after.domain.expenses.find(x=>x.id===e.id);assert.equal(Math.abs(Number(n.brl)),3000);const normalize=rows=>rows.map(x=>({...x,brl:Number(x.brl),usd:Number(x.usd)}));assert.deepEqual(normalize(after.domain.expenses.filter(x=>x.id!==e.id)),normalize(others));for(const k of ['gross','spend','net','tax','company_expenses'])assert.equal(Number(after.domain.cash[k]),Number(w.domain.cash[k]));assert.ok(Math.abs(Number(after.domain.cash.profit)-Number(w.domain.cash.profit)+(3000-Math.abs(Number(e.brl)))/Number(w.fx))<1e-6);results.push({period:p.id,pass:true,before:1500,after:3000,other_staff_unchanged:true});await fs.writeFile(path.join(root,'private/jislaine-stage-months.json'),JSON.stringify(results));}
 assert.deepEqual((await db.query("SELECT id,md5(to_jsonb(finance_ledger)::text) hash FROM finance_ledger ORDER BY id")).rows,ledgerBefore);const out={pass:true,months:results.length,ledger_unchanged:true,other_staff_unchanged:true,production_writes:0};await fs.writeFile(path.join(root,'private/jislaine-stage.json'),JSON.stringify(out));console.log(JSON.stringify(out));
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}
