import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {planSpend,micros,decimal} from '../media-spend.mjs';
const D=new URL('../private/spend-import-1546991137171181578/',import.meta.url),s=JSON.parse(fs.readFileSync(new URL('snapshot.json',D))),model=JSON.parse(fs.readFileSync(new URL('../private/ui-model.json',import.meta.url))),c=JSON.parse(fs.readFileSync(new URL('collection/collection.json',D)));const plan=()=>planSpend(s.scenario,s.registry,model,c);
test('exact source money and Google micros',()=>{assert.equal(decimal(micros('26938.430287')),'26938.430287');for(const x of ['NaN','-1','1e2','1.0000001'])assert.throws(()=>micros(x));});
test('all82 accounts and574 unique account days; do not allocate ambiguous fields',()=>{const p=plan();assert.equal(p.entries.length,574);assert.equal(new Set(p.entries.map(r=>r.platform+'|'+r.account_id+'|'+r.date)).size,574);assert.equal(p.summary.recorded_accounts,82);assert.ok(p.entries.filter(r=>r.account_id==='3188620887977617').every(r=>r.status==='ambiguous_mapping'));assert.ok(p.entries.filter(r=>r.platform==='google').every(r=>r.status==='missing_mapping'));assert.ok(p.changes.length>0&&p.changes.every(r=>r.date>='2026-09-01'&&r.date<='2026-09-07'));});
test('exact existing source link wins over generic virtual country fields',()=>{const p=plan(),r=p.entries.find(r=>r.account_id==='311204101516831'&&r.date==='2026-09-01');assert.equal(r.target_key,'principal|Agosto 2026|BF46');assert.equal(r.status,'applied');});
test('idempotent replay cannot double spend or change fields',()=>{const p=plan(),state={...s.scenario,overrides:p.overrides,additions:p.additions};const q=planSpend(state,s.registry,model,c,p.entries);assert.equal(q.changes.length,0);assert.deepEqual(q.entries,p.entries);assert.deepEqual(q.overrides,p.overrides);});
test('manual later edit is preserved and explicitly reported',()=>{const p=plan(),change=p.changes[0],state=structuredClone(s.scenario);state.overrides={...p.overrides,[change.key]:'12345.67'};const q=planSpend(state,s.registry,model,c,p.entries);assert.equal(q.overrides[change.key],'12345.67');assert.ok(q.entries.some(r=>r.target_key===change.key&&r.status==='manual_conflict'));});
test('account source failure does not replace stored records with zero',()=>{const p=plan(),broken=structuredClone(c),a=broken.accounts.find(a=>a.daily.some(r=>micros(r.amount)>0n));a.status='error';a.error='fixture failure';delete a.daily;const q=planSpend({...s.scenario,overrides:p.overrides,additions:p.additions},s.registry,model,broken,p.entries);assert.deepEqual(q.entries.filter(r=>r.account_id===a.id),p.entries.filter(r=>r.account_id===a.id));});
test('future historical and mismatched registry/window rejected',()=>{for(const changes of [{period:'2026-07'},{since:'2026-08-31'},{registry_revision:-1},{until:'2026-09-09'}])assert.throws(()=>planSpend(s.scenario,s.registry,model,{...c,...changes}));});
