import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,scryptSync} from 'node:crypto';import {request} from 'node:http';import vm from 'node:vm';import {openPostgres,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const database=process.env.FINANCE_NAVIGATION_DATABASE;assert.equal(database,'mgs_finance_navigation_1546682010066489394');const db=await openPostgres({database,user:'mgs_pg',options:'-c role=mgsfinance -c timezone=UTC -c statement_timeout=60000'});let server;
try{
 const initial=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.equal(initial.filter(x=>x.id.startsWith('workspace-')).length,17);
 const password=randomUUID()+'-ISOLATED',salt=randomUUID(),config={username:'rodolfo',salt,hash:scryptSync(password,salt,64).toString('hex'),origin:'https://dash.mgsdigitalcorp.com'};server=(await createApp(db,{auth:config})).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 function call(url,body,h={},expected=200){return new Promise((resolve,reject)=>{const req=request({hostname:'127.0.0.1',port:server.address().port,path:url,method:body===undefined?'GET':'POST',headers:{Host:'dash.mgsdigitalcorp.com',...(body===undefined?{}:{'Content-Type':'application/json',Origin:config.origin}),...h}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{try{let data;try{data=JSON.parse(s);}catch{}assert.equal(res.statusCode,expected,url+' '+JSON.stringify(data));resolve({data,headers:res.headers});}catch(e){reject(e);}})});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
 async function login(username,pw){const r=await call('/api/auth/login',{username,password:pw});const h={Cookie:r.headers['set-cookie'][0].split(';')[0]},me=(await call('/api/auth/me',undefined,h)).data;return {...h,'X-CSRF-Token':me.csrf};}
 const owner=await login('rodolfo',password);const pw=randomUUID()+'-ISOLATED';for(const [username,role]of [['test_geizian','partner'],['test_nicolas','manager']]){await call('/api/finance/users',{username,display_name:username,role,manager_key:role==='manager'?'nicolas':null},owner,201);await call('/api/finance/users/'+username+'/credential',{password:pw,revision:0},owner);}
 await call('/api/finance/users',{username:'test_joe',display_name:'Not authorized pilot',role:'manager',manager_key:'joe'},owner,400);
 const partner=await login('test_geizian',pw),manager=await login('test_nicolas',pw);
 for(const url of ['/api/workspace','/api/cells','/api/catalog','/api/ad-accounts','/api/scenarios','/api/finance/users','/api/finance/activity','/api/finance/approvals','/api/scenarios/workspace-2026-08/audit','/api/finance/ledger?counterparty=geizian'])await call(url,undefined,manager,403);
 await call('/api/finance/activity',undefined,partner,403);await call('/api/scenarios/workspace-2026-08/audit',undefined,partner,403);await call('/api/finance/users/test_nicolas/credential',{password:randomUUID(),revision:1},partner,403);await call('/api/meta-account-lookups',{id:'bad'},partner,400);
 const scope=(await call('/api/manager-workspace?period=2026-08',undefined,manager)).data;assert.equal(scope.manager,'nicolas');assert.equal(scope.source,'dash');assert.ok(scope.blocks.length>0);assert.ok(scope.remuneration.length);assert.ok(!('cash' in scope));assert.ok(scope.summaries.every(x=>!('manager' in x)));assert.ok(!('results' in scope));const ownLedger=(await call('/api/finance/ledger?period=2026-08',undefined,manager)).data;assert.ok(ownLedger.parties.every(x=>x.manager==='nicolas'));
 let w=(await call('/api/workspace?period=2026-08',undefined,owner)).data;const ctx=vm.createContext({});vm.runInContext(await fs.readFile(path.join(root,'public/financial-summary.js'),'utf8'),ctx);ctx.workspace=w;const summaries=vm.runInContext('financialRows(workspace)',ctx),total=summaries.at(-1);for(const k of ['gross','invalid','net','tax','spend','profit'])assert.ok(Math.abs(total[k]-Number(w.domain.cash[k]))<1e-6,k);assert.ok(Math.abs(summaries.slice(0,-1).reduce((s,r)=>s+r.profit,0)-total.profit)<1e-6);assert.ok(total.origins.CAD>0&&total.origins.USD>0);const cad=Number(w.rates.find(r=>r.key==='principal|Agosto 2026|H1').value),gbp=Number(w.rates.find(r=>r.key==='principal|Agosto 2026|I1').value);assert.ok(Math.abs((total.origins.USD||0)+(total.origins.CAD||0)/cad+(total.origins.GBP||0)*gbp+(total.origins.BRL||0)/Number(w.fx)-total.gross)<1e-4,'Original-currency bridge must reconcile');const egg=vm.runInContext("financialRows(workspace,'Eggbev')",ctx).at(-1);assert.ok(Math.abs(egg.gross-w.domain.facts.filter(f=>f.site==='Eggbev').reduce((s,f)=>s+Number(f.gross||0),0))<1e-6);
 const before=w.revision,e=w.domain.expenses.find(e=>e.id==='company|113'),target='/api/scenarios/'+w.id+'/expenses',body={target:e.id,category:'company',label:e.label,amount:'101',currency:'BRL',status:'A conferir',checked_on:null,period:'2026-08',revision:before};const proposal=(await call(target,body,partner,202)).data;assert.equal(proposal.pending,true);assert.equal((await call('/api/workspace?period=2026-08',undefined,owner)).data.revision,before);
 await call(target,{}, {...owner,'X-Finance-Approval':proposal.request_id});const approval=(await call('/api/finance/approvals',undefined,owner)).data.find(a=>a.id===proposal.request_id);assert.equal(approval.status,'approved');w=(await call('/api/workspace?period=2026-08',undefined,owner)).data;assert.equal(Number(w.domain.expenses.find(e=>e.id==='company|113').edit_amount),101);await call(target,{}, {...owner,'X-Finance-Approval':proposal.request_id},409);
 const reject=(await call(target,{...body,amount:'102',revision:w.revision},partner,202)).data;await call('/api/finance/approvals/'+reject.request_id+'/reject',{reason:'TEST ISOLATED reject'},owner);assert.equal((await call('/api/workspace?period=2026-08',undefined,owner)).data.revision,w.revision);
 const oldLedger=(await call('/api/finance/ledger?period=2026-08',undefined,owner)).data;assert.equal(oldLedger.opening,71);assert.equal(oldLedger.entries.length,0);const id=randomUUID(),entry={id,counterparty:'geizian',period:'2026-08',date:'2026-09-07',kind:'payment',direction:-1,amount:'20.00',description:'ISOLATED PAYMENT TEST'};const p=(await call('/api/finance/ledger',entry,partner,202)).data;assert.equal((await call('/api/finance/ledger?period=2026-08',undefined,owner)).data.entries.length,0);await call('/api/finance/ledger',{}, {...owner,'X-Finance-Approval':p.request_id},201);const after=(await call('/api/finance/ledger?period=2026-08',undefined,owner)).data;assert.equal(after.balance,oldLedger.balance-2000);assert.equal(after.entries.length,1);assert.equal((await call('/api/workspace?period=2026-08',undefined,owner)).data.revision,w.revision);await call('/api/finance/ledger',entry,owner,409);await call('/api/finance/ledger/'+id+'/void',{reason:'ISOLATED reversal'},owner);assert.equal((await call('/api/finance/ledger?period=2026-08',undefined,owner)).data.balance,oldLedger.balance);
 const sept=(await call('/api/finance/ledger?period=2026-09',undefined,owner)).data;assert.equal(sept.previous,oldLedger.balance);
 const history=(await call('/api/finance/activity',undefined,owner)).data;assert.ok(history.rows.some(x=>x.action==='PROPOSAL_APPROVED'));assert.ok(history.rows.some(x=>x.action==='LEDGER_ENTRY_RECORDED'));assert.ok(!JSON.stringify(history).includes(pw));const users=(await call('/api/finance/users',undefined,owner)).data;assert.ok(!JSON.stringify(users).includes('password_hash'));const n=users.find(u=>u.username==='test_nicolas');await call('/api/finance/users/test_nicolas',{enabled:false,revision:n.revision},owner);await call('/api/auth/me',undefined,manager,401);
 const usersNow=(await call('/api/finance/users',undefined,owner)).data,profileUser=usersNow.find(x=>x.username==='test_nicolas');const profile={display_name:'Nicolas QA isolated',email:'qa@example.com',phone:'+55 (11) 99999-9999',discord_id:'344196393512075265',revision:profileUser.revision};await call('/api/finance/users/test_nicolas',profile,owner);const rb=(await call('/api/finance/users',undefined,owner)).data.find(x=>x.username==='test_nicolas');for(const k of ['display_name','email','phone','discord_id'])assert.equal(rb[k],profile[k]);assert.equal(rb.enabled,false);assert.equal(rb.role,'manager');await call('/api/finance/users/test_nicolas',profile,owner,409);await call('/api/finance/users/test_nicolas',{...profile,revision:rb.revision,email:'invalid'},owner,400);
 const proposalProfile=(await call('/api/finance/users/test_nicolas',{...profile,display_name:'Proposed contact',revision:rb.revision},partner,202)).data;assert.equal((await call('/api/finance/users',undefined,owner)).data.find(x=>x.username==='test_nicolas').display_name,profile.display_name);await call('/api/finance/users/test_nicolas',{}, {...owner,'X-Finance-Approval':proposalProfile.request_id});assert.equal((await call('/api/finance/users',undefined,owner)).data.find(x=>x.username==='test_nicolas').display_name,'Proposed contact');
 for(const file of ['/navigation.js','/navigation.css'])await call(file,undefined,await login('test_geizian',pw));
 const final=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.deepEqual(final.filter(x=>x.id!=='workspace-2026-08'),initial.filter(x=>x.id!=='workspace-2026-08'));const out={pass:true,profile_edit_readback:true,stale_profile_rejected:true,partner_profile_gated:true,database,periods:17,nicolas_blocks:scope.blocks.length,nicolas_isolated:true,manager_api_denials:10,owner_only_activity:true,partner_no_direct_writes:true,approval_atomic_once:true,rejection_no_financial_effect:true,ledger_no_double_expense:true,carry_forward:true,credential_redaction:true,session_revocation:true,company_and_site_summary:true,baseline_preserved:true,production_test_writes:0};await fs.writeFile(path.join(root,'private/payments-test-readback.json'),JSON.stringify(out,null,2));await fs.writeFile(path.join(root,'private/payments-nicolas-scope.json'),JSON.stringify(scope));console.log(JSON.stringify(out));
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}
