import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {openDatabase,root} from '../storage.mjs';import {createApp} from '../server.mjs';import {networkRules} from '../networks.mjs';
const published=process.env.FINANCE_PUBLIC==='1',dir=path.join(root,'private/networks-1546579646227943506');let browser,db,server;
try{
 let base='https://dash.mgsdigitalcorp.com',credential;
 if(published){const chunks=[];for await(const c of process.stdin)chunks.push(c);credential=JSON.parse(Buffer.concat(chunks).toString());}
 else{db=await openDatabase(path.join(dir,'isolated-pglite'));server=(await createApp(db)).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;}
 browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);
 await page.goto(base);if(published){await page.waitForURL('**/login');await page.locator('#username').fill(credential.username);await page.locator('#password').fill(credential.password);await page.locator('button[type=submit]').click();}await page.waitForSelector('.cards');
 const get=async p=>{const r=await context.request.get(base+p);assert.equal(r.status(),200);return r.json();},nav=async v=>{if(await page.locator('#adminNav').isHidden())await page.locator('#nav [data-view=admin]').click();await page.locator('#adminNav [data-view='+v+']').click();};
 const periods=await get('/api/periods'),checks=[];assert.equal(periods.length,17);
 for(const p of periods){const w=await get('/api/workspace?period='+p.id);assert.equal(w.sites.length,41);assert.equal(w.rates.length,11);for(const label of ['Imposto','Revshare Geral','USD → BRL','GBP → USD · YMonetize','Preço por Artigo','Inválidos SB Rede1','Inválidos SB Rede2'])assert.ok(w.rates.some(r=>r.label===label));assert.equal(Number(w.rates.find(r=>r.key===networkRules.rede2_key).value),.004104);for(const s of w.sites){assert.ok(networkRules.networks[s.network]);if(networkRules.explicit_sites[s.name])assert.equal(s.network,networkRules.explicit_sites[s.name]);}const people=w.domain.expenses.filter(e=>e.category==='personnel'&&e.label);assert.equal(people.length,12);assert.ok(people.every(e=>e.payroll_rule==='monthly-v1'));if(p.id!=='2026-08')assert.ok(w.domain.expenses.every(e=>e.status==='A conferir'&&!e.checked_on));checks.push({period:p.id,sites:w.sites.length,rates:w.rates.length,employees:people.length,pass:true});}
 for(const width of [390,768,1440]){
  await page.setViewportSize({width,height:1000});
  for(const period of ['2026-08','2026-09','2027-12']){
   await page.locator('#period').selectOption(period);await page.waitForFunction(p=>document.querySelector('#period').value===p&&!document.querySelector('#period').disabled,period);
   await nav('rates');assert.ok(!(await page.locator('#content th').allTextContents()).includes('Origem'));assert.ok(!(await page.locator('#content').innerText()).includes('JBF'));
   await nav('sites');const target=page.locator('#content tbody tr').filter({hasText:'AmazingXJobs'});assert.ok((await target.innerText()).includes('Ymonetize'));await target.locator('button').click();assert.ok((await page.locator('#editorTitle').innerText()).includes(periods.find(p=>p.id===period).label),'Site editor must show selected month');assert.equal(await page.locator('#siteNetwork option').count(),5);assert.equal(await page.locator('#siteNetwork').inputValue(),'Ymonetize');await page.locator('#editor [data-close]').first().click();
   await nav('accounts');assert.ok(!(await page.locator('#content th').allTextContents()).includes('Origem'));await page.locator('[data-account-edit]').first().click();assert.equal(await page.locator('input[name=sites][type=checkbox]').count(),41);assert.equal(await page.locator('input[name=timezone]').count(),1);assert.equal(await page.locator('select[multiple]').count(),0);await page.locator('#editor [data-close]').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
   await nav('personnel');assert.equal(await page.locator('#content tbody tr').count(),12);assert.ok((await page.locator('#content').innerText()).includes('Atividade'));
  }
 }
 if(!published){
  await page.setViewportSize({width:1440,height:1000});await nav('accounts');const accounts=(await get('/api/ad-accounts?period=2027-12')).accounts;const first=accounts.slice().sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))[0];await page.locator('[data-account-edit="'+first.id+'"]').click();const oldTZ=await page.locator('[name=timezone]').inputValue();await page.locator('[name=timezone]').fill('America/Sao_Paulo');const other=page.locator('[name=sites]').filter({visible:true});const box=page.locator('[name=sites][value="Eggbev"]');const oldChecked=await box.isChecked();await box.setChecked(!oldChecked);await page.locator('#save').click();await page.waitForFunction(()=>!document.querySelector('#editor').open,null,{timeout:90000});let a=(await get('/api/ad-accounts?period=2027-12')).accounts.find(x=>x.id===first.id);assert.equal(a.timezone,'America/Sao_Paulo');assert.equal(a.sites.includes('Eggbev'),!oldChecked);await page.locator('[data-account-edit="'+first.id+'"]').click();await page.locator('[name=timezone]').fill(oldTZ);await page.locator('[name=sites][value="Eggbev"]').setChecked(oldChecked);await page.locator('#save').click();await page.waitForFunction(()=>!document.querySelector('#editor').open,null,{timeout:90000});
  await nav('sites');const row=page.locator('#content tbody tr').filter({hasText:'AmazingXJobs'});await row.locator('button').click();await page.locator('#siteNetwork').selectOption('SB Rede1');await page.locator('#save').click();await page.waitForFunction(()=>!document.querySelector('#editor').open,null,{timeout:90000});assert.equal((await get('/api/workspace?period=2027-12')).sites.find(s=>s.name==='AmazingXJobs').network,'SB Rede1');await row.locator('button').click();await page.locator('#siteNetwork').selectOption('Ymonetize');await page.locator('#save').click();await page.waitForFunction(()=>!document.querySelector('#editor').open,null,{timeout:90000});
 }
 assert.equal(errors.length,0,errors.join(';'));await fs.writeFile(path.join(dir,published?'public-browser.json':'local-browser.json'),JSON.stringify({pass:true,published,periods:checks,viewports:[390,768,1440],local_write_readback:!published,js_errors:0,production_test_writes:0},null,2));console.log(JSON.stringify({pass:true,published,periods:checks.length,js_errors:0}));
}catch(e){console.log(JSON.stringify({pass:false,published,error:e.message.slice(0,1500)}));process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}
