import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {openPostgres,root,scenario} from '../storage.mjs';import {createApp} from '../server.mjs';
const database=process.env.FINANCE_ORIGIN_DATABASE;assert.equal(database,'mgs_finance_origin_1546618148571058266');const db=await openPostgres({database,user:'mgs_pg',options:'-c role=mgsfinance -c timezone=UTC -c statement_timeout=60000'});let server;
try{
 const initial=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.equal(initial.filter(x=>x.id.startsWith('workspace-')).length,17);
 server=(await createApp(db)).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,get=async p=>{const r=await fetch(base+p);assert.equal(r.status,200);return r.json();},post=async(p,b,status=200)=>{const r=await fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;};
 const proof=JSON.parse(await fs.readFile(path.join(root,'private/meta-probe.json'),'utf8')),id=proof.account.account_id,accounts=await get('/api/ad-accounts?period=2026-09');assert.ok(!accounts.accounts.some(a=>a.id===id));
 await post('/api/meta-account-lookups',{id:'act_'+id},400);await post('/api/ad-accounts',{id,name:'UNVERIFIED',currency:'USD',timezone:'UTC',sites:['Eggbev'],period:'2026-09',revision:accounts.revision,edit:false},400);
 let lookup=await post('/api/meta-account-lookups',{id},202);const start=Date.now();while(lookup.status==='pending'&&Date.now()-start<115000){await new Promise(r=>setTimeout(r,1000));lookup=await get('/api/meta-account-lookups/'+lookup.request_id);}assert.equal(lookup.status,'ready',JSON.stringify(lookup));assert.equal(lookup.name,proof.account.name);assert.equal(lookup.currency,proof.account.currency);assert.equal(lookup.timezone,proof.account.timezone);
 await post('/api/ad-accounts',{id,lookup_id:lookup.request_id,name:'CLIENT MUST NOT OVERRIDE',currency:'GBP',timezone:'Pacific/Honolulu',sites:['Eggbev','FinanceTopFeed'],period:'2026-09',revision:accounts.revision,edit:false});const saved=(await get('/api/ad-accounts?period=2026-09')).accounts.find(a=>a.id===id);assert.equal(saved.name,lookup.name);assert.equal(saved.currency,lookup.currency);assert.equal(saved.timezone,lookup.timezone);assert.deepEqual(saved.sites,['Eggbev','FinanceTopFeed']);assert.deepEqual((await get('/api/ad-accounts?period=2026-08')).accounts.find(a=>a.id===id).sites,[]);
 let w=await get('/api/workspace?period=2026-08');const save=async(action,payload)=>{await post('/api/scenarios/'+w.id+'/'+action,{...payload,period:'2026-08',revision:w.revision});w=await get('/api/workspace?period=2026-08');};
 const oldPeople=w.domain.expenses.filter(e=>e.category==='personnel').map(e=>({id:e.id,status:e.status,checked_on:e.checked_on,activity:e.activity}));
 for(const [target,amount] of [['company|113','100'],['personnel|155','2000']]){const e=w.domain.expenses.find(x=>x.id===target);await save('expenses',{target,category:e.category,label:e.label,amount,currency:'BRL',status:e.status==='Conferido'?'Conferido':'A conferir',checked_on:e.checked_on||null,...(e.category==='personnel'?{activity:e.activity||'ATIVO'}:{})});const after=w.domain.expenses.find(x=>x.id===target);assert.equal(after.edit_currency,'BRL');assert.equal(Number(after.edit_amount),Number(amount));assert.ok(Math.abs(Number(after.brl)+Number(amount))<1e-8);}
 const fxKey=w.rates.find(r=>r.source==='F1').key;for(const fx of ['5','4']){await save('rates',{key:fxKey,value:fx,mode:'fixed',status:'provisional'});for(const [id,amount] of [['company|113',100],['personnel|155',2000]]){const e=w.domain.expenses.find(x=>x.id===id);assert.ok(Math.abs(Number(e.brl)+amount)<1e-8);assert.ok(Math.abs(Number(e.usd)+amount/Number(fx))<1e-8);}const usd=w.domain.expenses.find(x=>x.id==='company|114');assert.equal(Number(usd.usd),-200);assert.equal(Number(usd.brl),-200*Number(fx));}
 const q=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.deepEqual(q.filter(x=>!['workspace-2026-08','master-ad-accounts'].includes(x.id)),initial.filter(x=>!['workspace-2026-08','master-ad-accounts'].includes(x.id)));assert.ok(w.domain.expenses.filter(e=>e.mode==='COMMISSION_FLOOR').every(e=>!e.edit_amount));
 const out={pass:true,database,periods_preserved:16,baseline_preserved:true,real_meta_queue:true,registered_id:id,meta_fields_locked:true,monthly_sites:true,brl_origin_and_fx_recalculation:true,usd_origin_preserved:true,fixed_payroll_original:true,commissions_not_overridden:true,production_financial_test_writes:0};await fs.writeFile(path.join(root,'private/origin-test-readback.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out));
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}
