import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {root} from '../storage.mjs';
const dir=path.join(root,'private/origin-1546618148571058266'),base='https://dash.mgsdigitalcorp.com';let browser;
try{
 const chunks=[];for await(const c of process.stdin)chunks.push(c);const credential=JSON.parse(Buffer.concat(chunks).toString());
 browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);
 await page.goto(base);await page.waitForURL('**/login');assert.equal(await page.locator('.official-logo').getAttribute('alt'),'MGS Digital Corp');assert.ok(await page.locator('.official-logo').evaluate(i=>i.complete&&i.naturalWidth>0));
 const assets=[];for(const name of ['mgs-logo.png','favicon.ico','favicon-32.png','apple-touch-icon.png']){const r=await context.request.get(base+'/'+name);assert.equal(r.status(),200);assert.equal(createHash('sha256').update(await r.body()).digest('hex'),createHash('sha256').update(await fs.readFile(path.join(root,'public',name))).digest('hex'));assets.push(name);}assert.equal((await context.request.get(base+'/api/ad-accounts')).status(),401);
 await page.locator('#username').fill(credential.username);await page.locator('#password').fill(credential.password);await page.locator('button[type=submit]').click();await page.waitForSelector('.cards');
 const get=async p=>{const r=await context.request.get(base+p);assert.equal(r.status(),200);return r.json();},periods=await get('/api/periods'),checks=[];assert.equal(periods.length,17);
 for(const period of periods){await page.locator('#period').selectOption(period.id);await page.waitForFunction(p=>document.querySelector('#period').value===p&&!document.querySelector('#period').disabled,period.id);await page.locator('#nav [data-view=admin]').click();await page.locator('#adminNav [data-view=sites]').click();const w=await get('/api/workspace?period='+period.id),site=w.sites.find(s=>s.name==='FinanceTopFeed');assert.ok(site);assert.equal(w.sites.length,41);const row=page.locator('[data-site-edit="'+site.id+'"]').locator('..').locator('..');assert.equal((await row.locator('td').first().innerText()).trim(),'Topfeed Finance');await row.locator('button').click();assert.equal(await page.locator('#editorBody strong').innerText(),'Topfeed Finance');await page.locator('#editor [data-close]').first().click();checks.push({period:period.id,sites:41,canonical:site.name,display:'Topfeed Finance',pass:true});}
 await page.locator('#period').selectOption('2026-08');await page.waitForFunction(()=>!document.querySelector('#period').disabled);const w=await get('/api/workspace?period=2026-08'),expenseChecks=[];
 for(const category of ['company','personnel']){await page.locator('#adminNav [data-view='+category+']').click();for(const e of w.domain.expenses.filter(x=>x.category===category&&x.label&&!x.archived)){const button=page.locator('[data-expense="'+e.id+'"]');if(!await button.count())throw Error('Missing expense editor '+e.id);await button.click();if(e.mode==='COMMISSION_FLOOR'){assert.equal(await page.locator('#expenseAmount').count(),0);expenseChecks.push({id:e.id,automatic:true,pass:true});}else{const currency=e.edit_currency||(e.mode==='UNIT_COST_DIVISOR'?'UNITS':e.mode),amount=Math.abs(Number(e.edit_amount??e.input??0));assert.equal(Number((await page.locator('#expenseAmount').inputValue()).replace(',','.')),amount,e.id);assert.equal(await page.locator('#expenseCurrency').inputValue(),currency,e.id);expenseChecks.push({id:e.id,amount,currency,pass:true});}await page.locator('#editor [data-close]').first().click();}}
 const chat=expenseChecks.find(e=>e.id==='company|113');assert.equal(chat.amount,100);assert.equal(chat.currency,'BRL');assert.equal(expenseChecks.find(e=>e.id==='personnel|155').currency,'BRL');
 await page.locator('#adminNav [data-view=accounts]').click();await page.locator('#addAccount').click();assert.equal(await page.locator('select[name=candidate]').count(),0);for(const k of ['name','currency','timezone'])assert.notEqual(await page.locator('#editorForm [name='+k+']').getAttribute('readonly'),null);assert.ok(await page.locator('#save').isDisabled());
 const proof=JSON.parse(await fs.readFile(path.join(dir,'meta-probe.json'),'utf8')),start=Date.now();await page.locator('#editorForm [name=id]').fill(proof.account.account_id);await page.waitForFunction(()=>document.querySelector('#lookupStatus')?.textContent.includes('Dados confirmados'),null,{timeout:120000});const lookupMs=Date.now()-start;for(const k of ['name','currency','timezone'])assert.equal(await page.locator('#editorForm [name='+k+']').inputValue(),proof.account[k]);const canonicalBox=page.locator('input[name=sites][value=FinanceTopFeed]');assert.equal(await canonicalBox.count(),1);assert.ok((await canonicalBox.locator('..').innerText()).includes('Topfeed Finance'));await page.locator('#editor [data-close]').first().click();
 for(const width of [390,1440]){await page.setViewportSize({width,height:1000});await page.locator('#adminNav [data-view=company]').click();await page.locator('[data-expense="company|113"]').click();assert.equal(await page.locator('#expenseAmount').inputValue(),'100');assert.equal(await page.locator('#expenseCurrency').inputValue(),'BRL');await page.screenshot({path:path.join(dir,'expense-original-'+width+'.png')});await page.locator('#editor [data-close]').first().click();}
 assert.equal(errors.length,0);const out={pass:true,published:true,periods:checks,expense_editors:expenseChecks,assets,logo_original:true,live_bm_form:true,meta_account_id:proof.account.account_id,lookup_ms:lookupMs,readonly_metadata:true,viewports:[390,1440],js_errors:0,production_financial_test_writes:0};await fs.writeFile(path.join(dir,'public-browser.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({pass:true,published:true,periods:checks.length,expense_editors:expenseChecks.length,logo_favicon:true,live_bm_form:true,lookup_ms:lookupMs,js_errors:0}));
}catch(e){console.log(JSON.stringify({pass:false,error:e.message.slice(0,1500)}));process.exitCode=1;}finally{await browser?.close();}
