import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {openDatabase,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const published=process.env.FINANCE_PUBLIC==='1',dir=path.join(root,'private/ui-periods-1546184035921829938');let browser,db,server,stage='startup';
try{let base='https://dash.mgsdigitalcorp.com',credential;if(published){const chunks=[];for await(const c of process.stdin)chunks.push(c);credential=JSON.parse(Buffer.concat(chunks).toString());}else{const e=JSON.parse(await fs.readFile(path.join(dir,'periods-api-evidence.json')));db=await openDatabase(e.directory);server=(await createApp(db)).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;}
 browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const get=async p=>(await context.request.get(base+p)).json(),saved=()=>page.waitForFunction(()=>!document.querySelector('#editor').open,{timeout:90000});
 await page.goto(base);if(published){await page.waitForURL('**/login');await page.locator('#username').fill(credential.username);await page.locator('#password').fill(credential.password);await page.locator('button[type=submit]').click();}await page.waitForSelector('.cards');assert.equal(await page.locator('#period option').count(),17);
 const select=async(id,inner=false)=>{await page.locator(inner?'[data-period-control]':'#period').selectOption(id);await page.waitForFunction(id=>document.querySelector('#period').value===id&&!document.querySelector('#period').disabled,id);};
 stage='groups';let w=await get('/api/workspace?period=2026-08');await page.locator('#nav [data-view=movement]').click();for(const status of ['ATIVO','INATIVO'])assert.equal(await page.locator(`[data-site-status=${status}] tbody tr`).count(),w.sites.filter(s=>s.status===status).length);await page.screenshot({path:path.join(dir,(published?'public':'local')+'-site-groups.png'),fullPage:true});
 stage='rates';await page.locator('#nav [data-view=admin]').click();await page.locator('#adminNav [data-view=rates]').click();assert.equal(await page.locator('[data-monthly-rates] tbody tr').count(),10);assert.equal(await page.locator('.rategrid,.ratecard').count(),0);await select('2026-09',true);assert.match(await page.locator('#subtitle').innerText(),/Setembro 2026/);await page.locator('[data-rate="principal|Agosto 2026|C1"]').click();if(!published){await page.locator('#rateValue').fill('7');await page.locator('#save').click();await saved();assert.equal(Number((await get('/api/workspace?period=2026-09')).rates.find(r=>r.source==='C1').value),0.07);assert.equal(Number((await get('/api/workspace?period=2026-08')).rates.find(r=>r.source==='C1').value),Number(w.rates.find(r=>r.source==='C1').value));}else await page.locator('#editor [data-close]').first().click();await page.screenshot({path:path.join(dir,(published?'public':'local')+'-compact-rates.png'),fullPage:true});
 stage='month-calendar';for(const period of ['2027-02','2027-12','2026-08']){await select(period);assert.ok((await page.locator('#subtitle').innerText()).includes((await get('/api/workspace?period='+period)).period.label));}
 stage='accounts';await select('2027-02');await page.locator('#adminNav [data-view=accounts]').click();const accounts=(await get('/api/ad-accounts?period=2027-02')).accounts;assert.equal(await page.locator('[data-account-table] tbody tr').count(),accounts.length);await page.locator('#addAccount').click();assert.ok(await page.locator('[name=sites] option').count()>=41);
 if(!published){await page.locator('[name=id]').fill('900000000000002');await page.locator('[name=name]').fill('TEST browser GBP account');await page.locator('[name=currency]').selectOption('GBP');await page.locator('[name=sites]').selectOption('Eggbev');await page.locator('#save').click();await saved();await page.locator('[data-account-edit="900000000000002"]').click();await page.locator('[name=name]').fill('TEST browser renamed GBP');await page.locator('#save').click();await saved();assert.equal((await get('/api/ad-accounts?period=2027-02')).accounts.find(a=>a.id==='900000000000002').name,'TEST browser renamed GBP');}else await page.locator('#editor [data-close]').first().click();await page.screenshot({path:path.join(dir,(published?'public':'local')+'-accounts.png'),fullPage:true});
 stage='account-daily';await page.locator('#nav [data-view=movement]').click();await page.locator('button[data-site=Eggbev]').first().click();await page.locator('[data-jump-country=US]').click();assert.equal(await page.locator('.country-block[data-country=US] [data-edit-fact]').count(),28);await page.locator('.country-block[data-country=US] [data-edit-fact]').first().click();assert.ok(await page.locator('[data-input-key]').count()>0);
 if(!published){const input=page.locator('[data-input-key^="account|900000000000002|"]');await input.fill('10');await page.locator('#save').click();await saved();const check=await get('/api/workspace?period=2027-02'),f=check.domain.facts.find(f=>f.id==='eggbev-principal|US|1');assert.ok(Math.abs(Number(f.spend)+10*Number(check.rates.find(r=>r.source==='I1').value))<1e-8);}else await page.locator('#editor [data-close]').first().click();
 stage='mobile';for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});await page.locator('#nav [data-view=admin]').click();for(const view of ['rates','accounts','sites']){await page.locator(`#adminNav [data-view=${view}]`).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'overflow '+view+' '+width);}}assert.equal(errors.length,0,errors.join(';'));
 await fs.writeFile(path.join(dir,(published?'public':'local')+'-periods-browser-evidence.json'),JSON.stringify({pass:true,published,months:17,calendar_28_verified:true,compact_monthly_rates:true,active_inactive_groups:true,accounts_readback:true,local_crud:!published,public_financial_test_writes:0}));console.log(JSON.stringify({pass:true,published,stage}));
}catch(e){console.log(JSON.stringify({pass:false,published,stage,error:e.message.slice(0,1500)}));process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}
