import test from 'node:test';
import assert from 'node:assert/strict';
import {buildSimpleReview,revenueDeductions,conferenceRates} from '../simple-review.mjs';
test('conference rates use selected saved result, with independent fixed confirmations',()=>{const s=base(),key='principal|Agosto 2026|H1';s.result.results={[key]:{actual:'1.41708'}};s.overrides[key]='1.4';s.additions=[{kind:'rate',key,mode:'fixed',status:'confirmed',value:'1.4'}];const before=JSON.stringify(s),rs=conferenceRates(s);assert.equal(rs.length,8);assert.equal(rs.find(r=>r.key===key).value,'1.41708');assert.equal(rs.find(r=>r.key===key).status,'confirmed');assert.equal(rs.find(r=>r.source==='J1').value,null);assert.equal(rs.find(r=>r.source==='J1').status,'provisional');assert.equal(JSON.stringify(s),before);});
test('automatic and absent metadata never inherit confirmation; future month stays independent',()=>{const a=base('2026-08'),b=base('2026-10'),key='principal|Agosto 2026|H1';a.overrides[key]='1.41708';a.additions=[{kind:'rate',key,mode:'auto',status:'confirmed'}];assert.equal(conferenceRates(a).find(r=>r.key===key).status,'provisional');assert.equal(conferenceRates(b).find(r=>r.key===key).value,null);});
test('confirmed invalid zero is not confused with missing',()=>{const s=base(),key='principal|Agosto 2026|J1';s.overrides[key]='0';s.additions=[{kind:'rate',key,mode:'fixed',status:'confirmed'}];assert.equal(conferenceRates(s).find(r=>r.key===key).value,'0');assert.equal(conferenceRates(s).find(r=>r.key===key).status,'confirmed');});
const base=(p='2026-09')=>({id:'workspace-'+p,revision:1,overrides:{},additions:[],result:{domain:{facts:[],realized:{cutoff_date:null}}}});
const options={model:{facts:{},inputs:{}},source:[],accounts:{accounts:[],slots:[]}};
function add(s,{id='a',currency='CAD',gross='10',partner='SB Rede1',components=[]}={}){s.additions.push({id,date:s.id.slice(10)+'-01',site:'Example',currency,gross,partner,source_components:components});s.result.domain.facts.push({id,date:s.id.slice(10)+'-01',site:'Example',partner,native_addition:true,gross_origins:{[currency]:gross},gross:'5',spend:'0'});}
test('six items only; empty month is not a reconciled zero',()=>{const r=buildSimpleReview(base(),options);assert.equal(r.items.length,6);assert.deepEqual(r.items.map(x=>x.id),['rede1','rede2','av','m2','facebook','google']);assert.ok(r.items.every(x=>x.totals.length===0));assert.equal(r.financial_writes,0);assert.equal(r.external_reconciled,false);});
test('original CAD never adds converted USD and four networks remain separate',()=>{const s=base();add(s);add(s,{id:'b',currency:'USD',gross:'20',partner:'SB Rede2'});add(s,{id:'c',currency:'USD',gross:'30',components:[{network:'AV',currency:'USD',gross:'30'}]});add(s,{id:'d',currency:'USD',gross:'40',partner:'M2'});const before=JSON.stringify(s),r=buildSimpleReview(s,options);assert.deepEqual(r.items.slice(0,4).map(x=>Number(x.totals[0].value)),[10,20,30,40]);assert.equal(JSON.stringify(s),before);});
test('unidentified USD under Rede1 is not guessed to be AV',()=>{const s=base();add(s,{currency:'USD'});const r=buildSimpleReview(s,options);assert.equal(r.items.find(x=>x.id==='av').totals.length,0);assert.equal(r.unclassified.length,1);});
test('superseded legacy gross not counted twice',()=>{const s=base();add(s);s.result.domain.facts[0].revenue_superseded=true;assert.equal(buildSimpleReview(s,options).items[0].totals.length,0);});
test('date from another month fails closed, not silently grouped',()=>{const s=base();add(s);s.result.domain.facts[0].date='2026-10-01';assert.throws(()=>buildSimpleReview(s,options),/competência/);});
test('component/current mismatch is explicit, never manufactures network attribution',()=>{const s=base();add(s,{currency:'USD',gross:'12',components:[{network:'AV',currency:'USD',gross:'10'},{network:'M2',currency:'USD',gross:'1'}]});const r=buildSimpleReview(s,options);assert.equal(r.unclassified.length,1);assert.ok(r.items.slice(0,4).every(x=>x.totals.length===0));});
function finc(s,{native=false,day='01',known=true}={}){add(s,{id:native?'gam-email-2026-09-'+day+'-abcdef123456|fincgriffin|US|g002-d|USD':'fincgriffin-principal|US|'+Number(day),currency:'USD',gross:'12.34'});const a=s.additions[0],f=s.result.domain.facts[0];for(const row of [a,f]){row.site='Fincgriffin';row.date=s.id.slice(10)+'-'+day;}if(native){Object.assign(a,{source_import_type:known?'gam_email_daily':'manual',source_import_id:'gam-email-2026-09-'+day+'-abcdef123456',source_hashes:{usd:'a'.repeat(64)},source_bundle_sha256:'b'.repeat(64)});}else{s.additions=[];delete f.native_addition;}return s;}
test('approved September Fincgriffin legacy USD belongs to Rede2 without changing inputs',()=>{const s=finc(base()),before=JSON.stringify(s),r=buildSimpleReview(s,options);assert.equal(r.items[1].totals[0]?.value,'12.340000000000000000');assert.equal(r.unclassified.length,0);assert.equal(JSON.stringify(s),before);});
test('Fincgriffin verified GAM email USD uses report network, not catalog partner',()=>{const s=finc(base(),{native:true,day:'20'}),r=buildSimpleReview(s,options);assert.equal(r.items[1].totals[0]?.value,'12.340000000000000000');assert.equal(r.unclassified.length,0);});
test('Fincgriffin routing leaves other periods and unknown sources pending',()=>{for(const s of [finc(base('2026-08')),finc(base('2026-10')),finc(base(),{native:true,day:'20',known:false}),finc(base(),{day:'10'})]){const r=buildSimpleReview(s,options);assert.equal(r.items[1].totals.length,0);assert.equal(r.unclassified.length,1);}});
test('explicit Fincgriffin component network wins over compatibility fallback',()=>{const s=finc(base(),{native:true,day:'20'});s.additions[0].source_components=[{network:'AV',currency:'USD',gross:'12.34'}];const r=buildSimpleReview(s,options);assert.equal(r.items[2].totals[0].value,'12.340000000000000000');assert.equal(r.items[1].totals.length,0);});
test('September remains byte identical when October snapshot gains activity',()=>{const a=base(),b=base('2026-10');add(a);const before=JSON.stringify(buildSimpleReview(a,options));add(b,{gross:'900'});buildSimpleReview(b,options);assert.equal(JSON.stringify(buildSimpleReview(a,options)),before);});
test('M2 deductions use saved results and reach 4284.08 without current-rate override',()=>{const s=base('2026-08');add(s,{currency:'USD',gross:'4611.87',partner:'M2'});Object.assign(s.result.domain.facts[0],{gross:'4611.87',invalid:'-102.312105188481',net:'4284.08000007094305',invalid_rate:'.99',share_rate:'.99'});const before=JSON.stringify(s),r=buildSimpleReview(s,options),b=r.items[3].breakdown[0];assert.equal(b.status,'ready');assert.equal(Number(b.net).toFixed(2),'4284.08');assert.equal(Number(b.invalid).toFixed(2),'-102.31');assert.equal(Number(b.revshare).toFixed(2),'-225.48');assert.deepEqual(r.items[3].sites[0].breakdown[0],b);assert.equal(JSON.stringify(s),before);});
test('all four revenue cards carry native-currency deductions, ad-spend cards do not',()=>{const s=base();for(const [id,partner,currency] of [['a','SB Rede1','CAD'],['b','SB Rede2','USD'],['c','AV','USD'],['d','M2','USD']]){add(s,{id,partner,currency,gross:'100'});Object.assign(s.result.domain.facts.at(-1),{gross:'50',invalid:'-5',net:'40'});}const r=buildSimpleReview(s,options);for(const x of r.items.slice(0,4)){assert.equal(x.breakdown[0].currency,x.currency);assert.equal(Number(x.breakdown[0].invalid),-10);assert.equal(Number(x.breakdown[0].revshare),-10);assert.equal(Number(x.breakdown[0].net),80);}for(const x of r.items.slice(4))assert.equal(x.breakdown,undefined);});
test('mixed source networks split existing deductions once without guessing a new rate',()=>{const s=base();add(s,{currency:'USD',gross:'100',components:[{network:'AV',currency:'USD',gross:'30'},{network:'SB Rede2',currency:'USD',gross:'70'}]});Object.assign(s.result.domain.facts[0],{gross:'100',invalid:'-10',net:'81'});const r=buildSimpleReview(s,options);assert.equal(Number(r.items[2].breakdown[0].net),24.3);assert.equal(Number(r.items[1].breakdown[0].net),56.7);assert.equal(r.items[2].breakdown[0].currency,'USD');});
test('missing saved discounts are pending, not a zero deduction',()=>{const s=base();add(s);const r=buildSimpleReview(s,options),b=r.items[0].breakdown[0];assert.equal(b.status,'pending');assert.equal(b.net,null);assert.equal(b.invalid,null);assert.equal(b.revshare,null);assert.equal(b.pending_entries,1);});
test('confirmed zeros, negative adjustment and invalid values remain distinct',()=>{assert.deepEqual(revenueDeductions('0',{gross:'0',invalid:'0',net:'0'}),{invalid:'0.000000000000000000',revshare:'0.000000000000000000',net:'0.000000000000000000'});assert.equal(revenueDeductions('10',{gross:'0',invalid:'0',net:'0'}),null);assert.equal(revenueDeductions('10',{gross:'NaN',invalid:'0',net:'0'}),null);assert.equal(Number(revenueDeductions('-10',{gross:'-10',invalid:'1',net:'-8.1'}).revshare),.9);});
test('monthly adjustment remains monthly and CAD/USD original components are separate',()=>{const s=base('2026-08');add(s,{currency:'CAD',gross:'100'});Object.assign(s.additions[0],{kind:'monthly_gross_adjustment',period:'2026-08',date:'2026-08'});Object.assign(s.result.domain.facts[0],{date:'2026-08',gross:'100',invalid:'-10',net:'81',gross_origins:{CAD:'100',USD:'50'}});s.additions[0].source_components=[{network:'SB Rede1',currency:'CAD',gross:'100'},{network:'AV',currency:'USD',gross:'50'}];const r=buildSimpleReview(s,options);assert.equal(Number(r.items[0].breakdown[0].net),81);assert.equal(Number(r.items[2].breakdown[0].net),40.5);assert.equal(r.unclassified.length,0);});
