import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {openDatabase,initialize,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const published=process.env.FINANCE_PUBLIC==='1',dir=process.env.FINANCE_EVIDENCE_DIR||path.join(root,'private/ui-periods-1546184035921829938');await fs.mkdir(dir,{recursive:true});let db,server,browser,stage='init';
try{
 let base='https://dash.mgsdigitalcorp.com',credential;
 if(published){const chunks=[];for await(const c of process.stdin)chunks.push(c);credential=JSON.parse(Buffer.concat(chunks));}
 else{db=await openDatabase(path.join(root,'private/sync-browser-'+randomUUID()));await initialize(db);server=(await createApp(db)).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;}
 browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const a=await ctx.newPage(),b=await ctx.newPage();const errors=[];for(const p of [a,b])p.on('pageerror',e=>errors.push(e.name));
 stage='login';await a.goto(base+'/');if(published){await a.waitForURL('**/login');await a.locator('#username').fill(credential.username);await a.locator('#password').fill(credential.password);await a.locator('button[type=submit]').click();}await a.waitForSelector('.cards');
 await b.clock.install();await b.goto(base+'/');await b.waitForSelector('.cards');
 stage='manual refresh';const before=await (await ctx.request.get(base+'/api/workspace')).json();const manual=a.waitForResponse(r=>new URL(r.url()).pathname==='/api/workspace'&&r.request().method()==='GET');await a.locator('#refresh').click();const response=await manual;assert.equal(response.status(),200);const loaded=await response.json();assert.equal(loaded.id,before.id);await a.waitForFunction(()=>document.querySelector('#sync').textContent==='Dados carregados');
 let mutation=false,changedId=null;
 if(!published){stage='two-screen write isolated';await ctx.request.post(base+'/api/workspace/open',{data:{}});let w=await (await ctx.request.get(base+'/api/workspace')).json();let r=await ctx.request.post(base+'/api/scenarios/'+w.id+'/expenses',{data:{revision:w.revision,category:'company',label:'TEST two-screen refresh only',amount:'1',currency:'USD',status:'A conferir'}});assert.equal(r.status(),200);w=await (await ctx.request.get(base+'/api/workspace')).json();changedId=w.domain.expenses.find(e=>e.label==='TEST two-screen refresh only').id;mutation=true;assert.equal(await b.evaluate(()=>data.domain.expenses.some(e=>e.label==='TEST two-screen refresh only')),false);}
 stage='automatic timer';const automatic=b.waitForResponse(r=>new URL(r.url()).pathname==='/api/workspace'&&r.request().method()==='GET');await b.clock.fastForward(300001);assert.equal((await automatic).status(),200);await b.waitForFunction(()=>document.querySelector('#sync').textContent==='Dados carregados');if(mutation)await b.waitForFunction(id=>data.domain.expenses.some(e=>e.id===id),changedId);
 stage='editing guard';await b.locator('#nav [data-view="admin"]').click();await b.locator('#adminNav [data-view="company"]').click();await b.locator('#addExpense').click();await b.locator('#expenseLabel').fill('TEST unsaved only');let reads=0;const watch=r=>{if(new URL(r.url()).pathname==='/api/workspace')reads++;};b.on('request',watch);await b.clock.fastForward(300001);await b.waitForTimeout(100);assert.equal(reads,0);assert.equal(await b.locator('#expenseLabel').inputValue(),'TEST unsaved only');await b.locator('#editor [data-close]').first().click();
 const resumed=b.waitForResponse(r=>new URL(r.url()).pathname==='/api/workspace'&&r.request().method()==='GET');await b.clock.fastForward(300001);assert.equal((await resumed).status(),200);b.off('request',watch);
 assert.equal(errors.length,0);const out={pass:true,published,manual_get_status:response.status(),manual_reads_server_not_google:true,automatic_interval_ms:300000,timer_accelerated_with_playwright:true,other_screen_change_observed:mutation,editing_pauses_auto_refresh:true,resumes_after_editor:true,public_financial_writes:0,js_errors:0,revision:loaded.revision,quote_sync:loaded.quote_sync,fx:loaded.fx};await fs.writeFile(path.join(dir,published?'public-sync-evidence.json':'local-sync-evidence.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out));
 if(published){await a.locator('#logout').click();await a.waitForURL('**/login');}
}catch(e){console.log(JSON.stringify({pass:false,published,stage,error:published?e.name:e.message.slice(0,500)}));process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}
