import unittest,tempfile,pathlib,shutil,json,subprocess,uuid,datetime
ROOT=pathlib.Path(__file__).resolve().parents[1]
class HistoryQueueTransport(unittest.TestCase):
 def test_history_pending_and_ready_readback(self):
  with tempfile.TemporaryDirectory() as td:
   root=pathlib.Path(td);(root/'deploy').mkdir();(root/'private/meta-account-lookups').mkdir(parents=True);shutil.copy2(ROOT/'deploy/meta-lookup-queue.py',root/'deploy/meta-lookup-queue.py');rid=str(uuid.uuid4());row={'request_id':rid,'account_id':'202607','platform':'history','period':'2026-07','actor':'rodolfo','status':'pending','requested_at':datetime.datetime.now(datetime.timezone.utc).isoformat()};p=root/'private/meta-account-lookups'/(rid+'.json');p.write_text(json.dumps(row));wait=subprocess.run(['python3',str(root/'deploy/meta-lookup-queue.py'),'wait'],capture_output=True,text=True,timeout=5,check=True);queued=json.loads(wait.stdout);self.assertEqual(queued[0]['period'],'2026-07');self.assertEqual(queued[0]['actor'],'rodolfo');ready={**queued[0],'status':'ready','updated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'captured_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'changed':False,'documents':6,'policy_correction':{'authority':'1547697182948458611','currency':'CAD'}};done=subprocess.run(['python3',str(root/'deploy/meta-lookup-queue.py'),'complete'],input=json.dumps([ready]),capture_output=True,text=True,timeout=5,check=True);self.assertTrue(json.loads(done.stdout)['readback']);saved=json.loads(p.read_text());self.assertEqual(saved['documents'],6);self.assertEqual(saved['policy_correction']['currency'],'CAD')
 def test_already_cad_has_queue_proof_without_recalculating_or_mutating_source(self):
  from unittest.mock import patch
  from copy import deepcopy
  from history_policy import apply_july_sb_tech_cad
  books=['principal','joe','nicolas','isliago','kelly','george'];docs=[{'book':b,'period':'2026-07','source_id':b,'cells':[{'value':42}],'source_sha256':'preserved','source':'original-monthly-tab'} for b in books]
  raw={b:[] for b in books};raw['principal']=[{'a1':'N140','userEnteredValue':{'formulaValue':'=SUM(Q140/$H$1)*-1'},'effectiveValue':{'numberValue':-448.01047977730474}},{'a1':'Q140','userEnteredValue':{'numberValue':629.28},'effectiveValue':{'numberValue':629.28}},{'a1':'H1','userEnteredValue':{'numberValue':1.40461},'effectiveValue':{'numberValue':1.40461}}];before=deepcopy(docs)
  with patch('history_policy.export',side_effect=AssertionError('already-correct source must not recalculate')):out,proof=apply_july_sb_tech_cad(docs,raw)
  self.assertEqual(docs,before);self.assertFalse(proof['applied']);self.assertEqual(proof['reason'],'source_already_cad')
  p=next(d for d in out if d['book']=='principal');self.assertEqual(p['correction']['authority'],'1547697182948458611');self.assertEqual(p['correction']['currency'],'CAD');self.assertTrue(p['correction']['source_already_cad'])
  for old,new in zip(docs,out):self.assertEqual(old['cells'],new['cells']);self.assertEqual(old['source_sha256'],new['source_sha256']);self.assertEqual(old['source'],new['source'])
  with tempfile.TemporaryDirectory() as td:
   root=pathlib.Path(td);(root/'deploy').mkdir();(root/'private/meta-account-lookups').mkdir(parents=True);shutil.copy2(ROOT/'deploy/meta-lookup-queue.py',root/'deploy/meta-lookup-queue.py');rid=str(uuid.uuid4());row={'request_id':rid,'account_id':'202607','platform':'history','period':'2026-07','actor':'rodolfo','status':'pending','requested_at':datetime.datetime.now(datetime.timezone.utc).isoformat()};file=root/'private/meta-account-lookups'/(rid+'.json');file.write_text(json.dumps(row));ready={**row,'status':'ready','updated_at':row['requested_at'],'captured_at':row['requested_at'],'changed':False,'documents':6,'policy_correction':p['correction']};r=subprocess.run(['python3',str(root/'deploy/meta-lookup-queue.py'),'complete'],input=json.dumps([ready]),text=True,capture_output=True,check=True,timeout=5);self.assertTrue(json.loads(r.stdout)['readback']);self.assertEqual(json.loads(file.read_text())['status'],'ready')
if __name__=='__main__':unittest.main()
