import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {openDatabase,initialize,root} from '../storage.mjs';import {createApp} from '../server.mjs';
let browser,db,server,stage='startup';const published=process.env.FINANCE_PUBLIC==='1';const dir=process.env.FINANCE_EVIDENCE_DIR||path.join(root,'private/ui-periods-1546184035921829938');await fs.mkdir(dir,{recursive:true});
try{
 let base='https://dash.mgsdigitalcorp.com',credential;
 if(published){const chunks=[];for await(const c of process.stdin)chunks.push(c);credential=JSON.parse(Buffer.concat(chunks).toString());}
 else{db=await openDatabase(path.join(root,'private/ui-browser-'+randomUUID()));await initialize(db);const app=await createApp(db);server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;}
 browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const saved=()=>page.waitForFunction(()=>!document.querySelector('#editor').open,{timeout:90000});
 stage='login';await page.goto(base+'/');if(published){await page.waitForURL('**/login');await page.locator('#username').fill(credential.username);await page.locator('#password').fill(credential.password);await page.locator('button[type=submit]').click();}
 await page.waitForSelector('.cards');assert.equal(await page.locator('#nav > button').count(),3);assert.equal(await page.getByText('Criar cenário',{exact:true}).count(),0);assert.equal(await page.getByText('Reconciliação da captura',{exact:true}).count(),0);assert.equal(await page.locator('.cards').count(),1);
 const initial=await (await context.request.get(base+'/api/workspace')).json();assert.match(await page.locator('.cards').innerText(),new RegExp(Number(initial.domain.cash.half_brl).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));

 stage='summary-review-acceptance';
 assert.equal(await page.locator('#content > section').first().getAttribute('class'),'quote-strip');assert.ok((await page.locator('.quote-strip').boundingBox()).height<150);
 const countryRows=await page.locator('[data-summary-country]').allTextContents();assert.deepEqual(countryRows.sort(),[...new Set(initial.domain.facts.map(f=>f.country))].sort());
 for(const c of countryRows){const facts=initial.domain.facts.filter(f=>f.country===c),tr=page.locator(`[data-summary-country="${c}"]`).locator('..').locator('..');for(const [i,k] of ['gross','invalid','net','tax','spend','profit'].entries()){const value=facts.reduce((a,f)=>a+Number(f[k]||0),0);const usd=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD'}).format(value);assert.equal(await tr.locator('td').nth(i+1).locator('.number').innerText(),usd);}}
assert.equal(await page.getByText('Alterações ficam na dash. A planilha não é modificada.',{exact:true}).count(),0);
 assert.equal(await page.locator('.quote-strip .quote-item').count(),initial.rates.filter(r=>r.type==='fx'||r.type==='invalid').length);
 assert.equal(await page.locator('.quote-strip [data-rate], .summary-expenses button, .summary-expenses input, .summary-expenses select').count(),0);
 for(const category of ['company','personnel']){const expected=initial.domain.expenses.filter(e=>e.category===category&&e.label&&!e.archived);const rows=page.locator(`[data-summary-expenses="${category}"] tbody tr`);assert.equal(await rows.count(),expected.length+1);for(let i=0;i<expected.length;i++){const cells=await rows.nth(i).locator('td').allTextContents();assert.equal(cells[0],expected[i].label);assert.equal(cells[1],new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD'}).format(Math.abs(Number(expected[i].usd))));assert.equal(cells[2],new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Math.abs(Number(expected[i].brl))));}}
 stage='country-block-acceptance';const ordered=await page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Composição financeira',exact:true})}).locator('tbody tr td:first-child').allTextContents();assert.deepEqual(ordered.slice(0,2),['Receita gross','Inválidos']);
 await page.locator('#nav [data-view="movement"]').click();
 const listed=await page.locator('#movementRows tbody tr td:first-child button').evaluateAll(es=>es.map(e=>({site:e.dataset.site,text:e.textContent})));
 const family=x=>{const parts=x.text.split('.');return parts.length>1?parts.slice(-2).join('.'):x.site.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();};
 for(let i=1;i<listed.length;i++)if(initial.sites.find(s=>s.name===listed[i-1].site).status===initial.sites.find(s=>s.name===listed[i].site).status)assert.ok(family(listed[i-1]).localeCompare(family(listed[i]),'pt-BR',{sensitivity:'base'})<=0,'family order');
 for(const [parent,child] of [['Eggbev','Eggbev Finanzas'],['Lyzmo','Lyzmo Finanzas'],['Ducapes','Ducapes Finance']]){const i=listed.findIndex(x=>x.site===parent),j=listed.findIndex(x=>x.site===child);if(i>=0&&j>=0&&initial.sites.find(s=>s.name===parent).status===initial.sites.find(s=>s.name===child).status)assert.equal(j,i+1,parent);}
 const filters=await page.locator('#managerFilter').innerText();assert.match(filters,/MGS/);assert.doesNotMatch(filters,/NAO_MAPEADO|Geizian|g002/i);await page.locator('#managerFilter').selectOption('MGS');assert.ok(await page.locator('#movementRows tbody tr').count()>0);await page.locator('#managerFilter').selectOption('');
 await page.locator('button[data-site="Eggbev"]').first().click();
 const egg=initial.domain.facts.filter(f=>f.site==='Eggbev');
 const expense=initial.domain.segments.filter(s=>s.site==='Eggbev').reduce((a,s)=>a+Number(s.expenses),0);assert.equal(await page.locator('[data-expense-total]').innerText(),new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD'}).format(expense));assert.equal(await page.locator('[data-expense-total]').count(),1);assert.equal(await page.locator('[data-site-consolidation] tbody tr').count(),new Set(egg.map(f=>f.country)).size+1);
assert.equal(await page.locator('.country-block').count(),new Set(egg.map(f=>f.country)).size);assert.equal(await page.locator('[data-edit-fact]').count(),egg.length);
 assert.equal(await page.locator('.country-block[open]').count(),0);
 const countryLink=page.locator('[data-jump-country="US"]');await countryLink.click();assert.equal(await page.locator('.country-block[data-country="US"]').evaluate(e=>e.open),true);await page.locator('.country-block[data-country="US"] > summary').click();
 const summary=page.locator('.country-heading').first();await summary.click();assert.equal(await page.locator('.country-block[open]').count(),1);await summary.click();assert.equal(await page.locator('.country-block[open]').count(),0);await summary.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.country-block[open]').count(),1);
 for(const summary of await page.locator('.country-block > summary').all())if(!await summary.evaluate(e=>e.parentElement.open))await summary.click();
 assert.match(await page.locator('#movementRows').innerText(),/Gross CAD/);assert.match(await page.locator('#movementRows').innerText(),/ROI net/);assert.match(await page.locator('[data-site-consolidation]').innerText(),/Consolidado ·/);
 const ids=await page.locator('[data-edit-fact]').evaluateAll(es=>es.map(e=>e.dataset.editFact));assert.deepEqual([...ids].sort(),egg.map(f=>f.id).sort());
 // Raw source revenue must reconcile to normalized gross, never inferred from net.
 for(const f of egg){const raw=(initial.model.facts[f.id]?.gross||[]).map(k=>initial.model.inputs[k]);const converted=raw.reduce((s,x)=>s+Number(x.value||0)/(x.currency==='CAD'&&!(x.book==='principal'&&x.source===f.source.gross)?Number(initial.rates.find(r=>r.source==='H1').value):1),0);assert.ok(Math.abs(converted-Number(f.gross||0))<1e-7,'source gross '+f.id);}
 await page.locator('#countryFilter').selectOption('GB');assert.equal(await page.locator('.country-block').count(),1);assert.equal(await page.locator('[data-edit-fact]').count(),egg.filter(f=>f.country==='GB').length);await page.locator('#countryFilter').selectOption('');
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'country overflow '+width);
 const sc=page.locator('[data-site-consolidation] .scroll');await sc.evaluate(e=>e.scrollLeft=e.scrollWidth);assert.ok(await sc.evaluate(e=>{const a=e.getBoundingClientRect(),z=e.querySelector('tr:last-child td:last-child').getBoundingClientRect();return z.right<=a.right+2&&z.left>=a.left;}),'last ROI accessible');await sc.evaluate(e=>e.scrollLeft=0);}
 await page.setViewportSize({width:1440,height:1000});await page.locator('#nav [data-view="overview"]').click();
 const screenshots=[];const snap=async name=>{const p=path.join(dir,(published?'public-':'local-')+name+'.png');await page.screenshot({path:p,fullPage:true});screenshots.push(p);};await snap('overview');
 stage='domain-search';await page.locator('#nav [data-view="movement"]').click();await page.locator('#siteSearch').fill('eggbev.com');assert.ok(await page.locator('tbody tr').count()>=1);assert.ok(await page.locator('tbody tr').count()<10);await page.locator('button[data-site="Eggbev"]').first().click();assert.equal(await page.getByRole('heading',{name:'Gastos e despesas do site',exact:true}).count(),0);assert.ok(await page.locator('[data-site-consolidation]').evaluate(e=>e.nextElementSibling.hasAttribute('data-manager-results')));assert.ok(await page.locator('[data-manager-results]').evaluate(e=>Boolean(e.compareDocumentPosition(document.querySelector('#movementRows'))&Node.DOCUMENT_POSITION_FOLLOWING)));await snap('site');
 stage='movement-return';await page.locator('#countryFilter').selectOption('US');await page.locator('#nav [data-view="movement"]').click();assert.equal(await page.locator('#title').innerText(),'Movimento do mês');assert.equal(await page.locator('.country-block').count(),0);assert.equal(await page.locator('#countryFilter').inputValue(),'');assert.equal(await page.locator('#siteSearch').inputValue(),'');await page.locator('button[data-site="Eggbev"]').first().click();assert.equal(await page.locator('.country-block[open]').count(),0);
 stage='daily-editor';await page.locator('.country-heading').first().click();await page.locator('[data-edit-fact]').first().click();assert.ok(await page.locator('[data-input-key]').count()>=2);assert.match(await page.locator('#editorBody').innerText(),/Gastos das contas/);assert.match(await page.locator('#editorBody .editgroup').first().innerText(),/USD/);
 if(!published){const input=page.locator('[data-input-key]').first();const key=await input.getAttribute('data-input-key');const prior=await input.inputValue();const value=Number(prior.replace(',','.'))+1;await input.fill(String(value));await page.locator('#save').click();await saved();const after=await (await context.request.get(base+'/api/workspace')).json();assert.equal(Number(after.model.inputs[key].value),value);}
 else await page.locator('#editor [data-close]').first().click();
 stage='site-catalog';await page.locator('#nav [data-view="admin"]').click();await page.locator('#adminNav [data-view="sites"]').click();assert.equal(await page.locator('[data-site-edit]').count(),initial.sites.length);await page.locator('[data-site-edit]').first().click();assert.equal(await page.locator('#siteStatus option').count(),2);await page.locator('#editor [data-close]').first().click();await page.locator('#addSite').click();assert.ok(await page.locator('#siteCountries').isVisible());
 if(!published){await page.locator('#siteName').fill('TEST browser native site');await page.locator('#siteCountries').fill('US');await page.locator('#siteManager').selectOption('nicolas');await page.locator('#sitePartner').selectOption('JBF');await page.locator('#siteCurrency').selectOption('CAD');await page.locator('#save').click();await saved();let w=await (await context.request.get(base+'/api/workspace')).json();const site=w.sites.find(s=>s.name==='TEST browser native site');assert.ok(site);await page.locator(`[data-site-edit="${site.id}"]`).click();await page.locator('#siteStatus').selectOption('INATIVO');await page.locator('#save').click();await saved();await page.locator('#nav [data-view="movement"]').click();await page.locator('button[data-site="TEST browser native site"]').first().click();await page.locator('[data-jump-country="US"]').click();await page.locator('[data-edit-fact]').first().click();assert.match(await page.locator('#editorBody').innerText(),/CAD/);assert.match(await page.locator('#editorBody').innerText(),/nicolas/);await page.locator('[data-input-key^="nativegross|"]').fill('10');await page.locator('[data-input-key^="nativespend|"]').fill('1');await page.locator('#save').click();await saved();w=await (await context.request.get(base+'/api/workspace')).json();assert.equal(w.domain.facts.filter(f=>f.site===site.name).length,31);assert.equal(w.sites.find(s=>s.id===site.id).status,'INATIVO');assert.equal(Number(w.domain.segments.find(s=>s.site===site.name).expenses),0);assert.ok(w.domain.facts.some(f=>f.site===site.name&&Number(f.gross)>0));}
 else await page.locator('#editor [data-close]').first().click();
 stage='company';await page.locator('#nav [data-view="admin"]').click();await page.locator('#adminNav [data-view="company"]').click();assert.match(await page.locator('thead').innerText(),/Despesa Tipo/);assert.match(await page.locator('thead').innerText(),/Status/);await page.locator('#addExpense').click();
 assert.deepEqual(await page.locator('#expenseStatus option').allTextContents(),['A conferir','Conferido']);assert.equal(await page.locator('#expenseDateField').isVisible(),false);await page.locator('#expenseStatus').selectOption('Conferido');assert.equal(await page.locator('#expenseDateField').isVisible(),true);assert.equal(await page.locator('#expenseCheckedOn').evaluate(e=>e.required&&!e.checkValidity()),true);await page.locator('#expenseStatus').selectOption('A conferir');assert.equal(await page.locator('#expenseDateField').isVisible(),false);
 if(!published){await page.locator('#expenseLabel').fill('TEST browser expense only');await page.locator('#expenseAmount').fill('12,50');await page.locator('#expenseCurrency').selectOption('BRL');await page.locator('#expenseStatus').selectOption('Conferido');await page.locator('#expenseCheckedOn').fill('2026-09-08');await page.locator('#save').click();await saved();let row=page.locator('tbody tr').filter({hasText:'TEST browser expense only'});assert.equal(await row.count(),1);assert.match(await row.innerText(),/12,50/);await row.locator('[data-expense]').click();assert.equal(await page.locator('#expenseCheckedOn').inputValue(),'2026-09-08');await page.locator('#expenseAmount').fill('15');await page.locator('#save').click();await saved();row=page.locator('tbody tr').filter({hasText:'TEST browser expense only'});await row.locator('[data-archive]').click();await page.locator('#save').click();await saved();assert.equal(await page.locator('tbody tr').filter({hasText:'TEST browser expense only'}).count(),0);await page.locator('summary').click();await page.locator('[data-restore]').last().click();assert.equal(Number(await page.locator('#expenseAmount').inputValue()),15);await page.locator('#save').click();await saved();}
 else await page.locator('#editor [data-close]').first().click();await snap('expenses');
 stage='payroll';await page.locator('#adminNav [data-view="personnel"]').click();const auto=page.locator('tbody tr').filter({hasText:'Remuneração automática'}).first();await auto.locator('[data-expense]').click();assert.equal(await page.locator('#expenseAmount').count(),0);await page.locator('#editor [data-close]').first().click();
 stage='rates';await page.locator('#adminNav [data-view="rates"]').click();assert.equal(await page.locator('[data-monthly-rates] tbody tr').count(),10);await page.locator('[data-rate="principal|CAIXA SINTETICO|J2"]').click();assert.equal(await page.locator('#rateMode option').count(),2);await page.locator('#rateMode').selectOption('fixed');await page.locator('#rateValue').fill('5,1');await page.locator('#rateStatus').selectOption('confirmed');
 if(!published){await page.locator('#save').click();await saved();const w=await (await context.request.get(base+'/api/workspace')).json();assert.equal(Number(w.fx),5.1);assert.equal(w.rates.find(x=>x.source==='F1 → Caixa J2').mode,'fixed');}
 else await page.locator('#editor [data-close]').first().click();await snap('rates');
 stage='mobile';const views=['overview','movement','admin','sites','company','personnel','rates'];for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const view of views){if(['sites','company','personnel','rates'].includes(view))await page.locator('#nav [data-view="admin"]').click();await page.locator('#nav [data-view="'+view+'"]').click();await page.waitForTimeout(60);
 if(view==='overview'){
  for(const selector of ['[data-country-summary]','.summary-expenses > div']){for(const panel of await page.locator(selector).all()){assert.ok(await panel.evaluate(e=>{const s=e.querySelector('.scroll').getBoundingClientRect(),note=e.querySelector('.block-scroll-note').getBoundingClientRect();return note.top>=s.bottom-1;}),'note does not overlay data');}}
  const scroll=page.locator('[data-country-summary] .scroll');await scroll.evaluate(e=>{e.scrollTop=e.scrollHeight;e.scrollLeft=e.scrollWidth;});assert.ok(await scroll.evaluate(e=>{const box=e.getBoundingClientRect(),cell=e.querySelector('tr:last-child td:last-child').getBoundingClientRect();return cell.right<=box.right+2&&cell.bottom<=box.bottom+2;}),'country total and last ROI reachable');await scroll.evaluate(e=>{e.scrollTop=0;e.scrollLeft=0;});
  const strip=page.locator('.quote-strip-scroll');await strip.evaluate(e=>e.scrollLeft=e.scrollWidth);assert.ok(await strip.evaluate(e=>e.lastElementChild.getBoundingClientRect().right<=e.getBoundingClientRect().right+2));await strip.evaluate(e=>e.scrollLeft=0);
 }
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'overflow '+width+' '+view);}}
 await page.setViewportSize({width:390,height:844});await page.locator('#nav [data-view="overview"]').click();await snap('mobile');
 stage='security';if(published){const c=(await context.cookies()).find(c=>c.name==='__Host-mgs_finance');assert.ok(c?.secure&&c.httpOnly&&c.sameSite==='Strict');assert.equal((await context.request.get(base+'/private/source.json')).status(),404);assert.equal((await context.request.post(base+'/api/auth/logout',{headers:{Origin:base},data:{}})).status(),403);await page.setViewportSize({width:1440,height:1000});await page.locator('#logout').click();await page.waitForURL('**/login');assert.equal((await context.request.get(base+'/api/workspace')).status(),401);}
 assert.equal(errors.length,0,errors.join(';'));const out={pass:true,published,views,widths:[390,768,1440],js_errors:errors.length,desktop_mobile_overflow:false,local_crud:!published,public_financial_writes:0,screenshots};await fs.writeFile(path.join(dir,published?'public-browser-evidence.json':'local-browser-evidence.json'),JSON.stringify(out));console.log(JSON.stringify(out));
}catch(e){console.log(JSON.stringify({pass:false,published,stage,error:published?e.name:e.message.slice(0,600)}));process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}
