import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../public/financial-summary.js',import.meta.url),'utf8')+'\n'+fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').split("document.addEventListener('click'")[0];
const domain=JSON.parse(fs.readFileSync(new URL('../private/domain.json',import.meta.url)));
const model=JSON.parse(fs.readFileSync(new URL('../private/ui-model.json',import.meta.url)));
domain.expenses=[{id:'TEST-company',category:'company',label:'TEST expense',usd:-10,brl:-50,status:'A conferir'},{id:'TEST-personnel',category:'personnel',label:'TEST payroll',usd:-20,brl:-100,status:'Conferido',checked_on:'2026-09-08'}];
const fixture={domain,model,period:{id:"2026-08",days:31},fx:5,additions:[],rates:[]}; // Fixed FX here is a test fixture only.
function ui(){const ctx=vm.createContext({Intl,console});vm.runInContext(source,ctx);ctx.fixture=structuredClone(fixture);vm.runInContext('data=fixture',ctx);return expr=>vm.runInContext(expr,ctx);}
test('invalids immediately follow gross with no duplicated component',()=>{const run=ui(),html=run('overview()');const composition=html.slice(html.indexOf('Composição financeira'));const labels=[...composition.matchAll(/<tr[^>]*><td>([^<]+)/g)].map(x=>x[1]);assert.deepEqual(labels.slice(0,2),['Receita gross','Inválidos']);assert.equal((html.match(/<td>Inválidos<\/td>/g)||[]).length,1);});
test('alphabetic domain families: parent then adjacent children, never revenue order',()=>{const run=ui();assert.equal(run("siteGroups([{site:'Eggbev Finanzas',gross:900},{site:'Lyzmo',gross:50},{site:'Eggbev',gross:1},{site:'Ducapes Finance',gross:200},{site:'Ducapes',gross:0}]).map(x=>x.site).join('|')"),'Ducapes|Ducapes Finance|Eggbev|Eggbev Finanzas|Lyzmo');});
test('MGS display aliases preserve unmapped source and filter shared managers',()=>{const run=ui();for(const value of ['NAO_MAPEADO','Não mapeado','Geizian','g002','G002','SEM_COMISSAO'])assert.equal(run(`managerLabel(${JSON.stringify(value)})`),'MGS');assert.equal(run("managerLabel('Nicolas / Geizian')"),'Nicolas / MGS');assert.equal(run("managerLabel('george / isliago / joe / kelly / nicolas')"),'Ícaro / Isliago / Joe / Kelly / Nicolas');const before=run('JSON.stringify(data.domain.facts)');run("manager='MGS'");assert.ok(run('filteredFacts().length')>0);assert.equal(run('JSON.stringify(data.domain.facts)'),before);});
test('highlighted sites rank by net profit after site expenses, not gross or operating profit',()=>{const run=ui();run("data.domain.facts=[{site:'High gross',status:'ATIVO',country:'US',partner:'SB Rede1',manager:'MGS',gross:1000,net:10,tax:0,spend:0,profit:1,invalid:0},{site:'High operating profit',status:'ATIVO',country:'US',partner:'SB Rede1',manager:'MGS',gross:100,net:60,tax:0,spend:0,profit:50,invalid:0}];data.domain.segments=[{site:'High gross',expenses:0},{site:'High operating profit',expenses:-60}]");const html=run('overview()'),box=html.slice(html.indexOf('Sites em destaque'));assert.ok(box.indexOf('High gross')<box.indexOf('High operating profit'));assert.match(box,/Maiores lucros líquidos no mês/);assert.match(box,/Lucro líquido após despesas do site · USD/);});
test('shared sites list only managers with realized revenue',()=>{const run=ui();run("data.domain.realized={cutoff_date:'2026-08-01',elapsed_days:1};data.domain.facts=[{site:'Shared',date:'2026-08-01',status:'ATIVO',country:'US',partner:'SB Rede1',manager:'SEM_COMISSAO',gross:10,net:9,tax:0,spend:0,profit:9,invalid:0},{site:'Shared',date:'2026-08-01',status:'ATIVO',country:'US',partner:'SB Rede1',manager:'joe',gross:20,net:18,tax:0,spend:0,profit:18,invalid:0},{site:'Shared',date:'2026-08-01',status:'ATIVO',country:'US',partner:'SB Rede1',manager:'kelly',gross:0,net:0,tax:0,spend:0,profit:0,invalid:0}];data.sites=[{name:'Shared',status:'ATIVO',manager:'COMPARTILHADO',manager_names:['MGS','Joe','Kelly'],network:'SB Rede1'}]");const managers=run("[...siteGroups().find(x=>x.site==='Shared').managers]");assert.equal(JSON.stringify(managers),JSON.stringify(['MGS','Joe']));});
test('inactive site revenue stays in company totals but status excludes allocation',()=>{const run=ui();run("data.domain.realized={cutoff_date:'2026-08-01',elapsed_days:1};data.domain.facts=[{site:'Inactive',date:'2026-08-01',status:'INATIVO',country:'US',partner:'SB Rede1',manager:'SEM_COMISSAO',gross:10,net:9,tax:0,spend:0,profit:9,invalid:0}];data.domain.segments=[{site:'Inactive',expenses:0}];data.domain.cash.company_expenses=-100;data.domain.cash.personnel=0;data.sites=[{name:'Inactive',status:'INATIVO',manager:'SEM_COMISSAO',network:'SB Rede1'}]");assert.equal(run('financialRows(data).at(-1).gross'),10);assert.equal(run("siteGroups().find(x=>x.site==='Inactive').status"),'INATIVO');const html=run('movement()');assert.match(html,/>Inativo</);assert.match(html,/receita e gastos continuam no resultado geral/);});
test('all country blocks retain every unique daily fact including complementary segments',()=>{const run=ui();for(const site of ['Eggbev','Openzed','CreditoParaVeiculo']){run(`selectedSite=${JSON.stringify(site)}`);const html=run('movement()');const expected=run('data.domain.facts.filter(f=>f.site===selectedSite).map(f=>f.id)');assert.ok(expected.length>0,site);const ids=[...html.matchAll(/data-edit-fact="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,expected.length,site);assert.equal(new Set(ids).size,expected.length,site);assert.ok(html.includes('Consolidado ·'),site);const countries=run('new Set(filteredFacts().map(f=>f.country)).size');assert.equal((html.match(/class="country-block"/g)||[]).length,countries);}});
test('source gross currency and both ROI columns visible, total ratios never average days',()=>{const run=ui();run("selectedSite='Eggbev'");const html=run('movement()');assert.match(html,/Gross CAD/);assert.match(html,/ROI gross/);assert.match(html,/ROI net/);assert.equal(run('rollup([{gross:100,net:80,tax:-8,spend:-20,profit:52,invalid:0},{gross:100,net:80,tax:-8,spend:-40,profit:32,invalid:0}]).roi_gross'),200/60-1);});
