import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').split("document.addEventListener('click'")[0];
const domain=JSON.parse(fs.readFileSync(new URL('../private/domain.json',import.meta.url)));
const model=JSON.parse(fs.readFileSync(new URL('../private/ui-model.json',import.meta.url)));
domain.expenses=[{id:'TEST-company',category:'company',label:'TEST expense',usd:-10,brl:-50,status:'A conferir'},{id:'TEST-personnel',category:'personnel',label:'TEST payroll',usd:-20,brl:-100,status:'Conferido',checked_on:'2026-09-08'}];
const fixture={domain,model,fx:5,additions:[],rates:[]}; // Fixed FX here is a test fixture only.
function ui(){const ctx=vm.createContext({Intl,console});vm.runInContext(source,ctx);ctx.fixture=structuredClone(fixture);vm.runInContext('data=fixture',ctx);return expr=>vm.runInContext(expr,ctx);}
test('invalids immediately follow gross with no duplicated component',()=>{const run=ui(),html=run('overview()');const composition=html.slice(html.indexOf('Composição financeira'));const labels=[...composition.matchAll(/<tr[^>]*><td>([^<]+)/g)].map(x=>x[1]);assert.deepEqual(labels.slice(0,2),['Receita gross','Inválidos']);assert.equal((html.match(/<td>Inválidos<\/td>/g)||[]).length,1);});
test('alphabetic domain families: parent then adjacent children, never revenue order',()=>{const run=ui();assert.equal(run("siteGroups([{site:'Eggbev Finanzas',gross:900},{site:'Lyzmo',gross:50},{site:'Eggbev',gross:1},{site:'Ducapes Finance',gross:200},{site:'Ducapes',gross:0}]).map(x=>x.site).join('|')"),'Ducapes|Ducapes Finance|Eggbev|Eggbev Finanzas|Lyzmo');});
test('MGS display aliases preserve unmapped source and filter shared managers',()=>{const run=ui();for(const value of ['NAO_MAPEADO','Não mapeado','Geizian','g002','G002'])assert.equal(run(`managerLabel(${JSON.stringify(value)})`),'MGS');assert.equal(run("managerLabel('Nicolas / Geizian')"),'Nicolas / MGS');const before=run('JSON.stringify(data.domain.facts)');run("manager='MGS'");assert.ok(run('filteredFacts().length')>0);assert.equal(run('JSON.stringify(data.domain.facts)'),before);});
test('all country blocks retain every unique daily fact including complementary segments',()=>{const run=ui();for(const site of ['Eggbev','Openzed','CreditoParaVeiculo']){run(`selectedSite=${JSON.stringify(site)}`);const html=run('movement()');const expected=run('data.domain.facts.filter(f=>f.site===selectedSite).map(f=>f.id)');assert.ok(expected.length>0,site);const ids=[...html.matchAll(/data-edit-fact="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,expected.length,site);assert.equal(new Set(ids).size,expected.length,site);assert.ok(html.includes('Consolidado ·'),site);const countries=run('new Set(filteredFacts().map(f=>f.country)).size');assert.equal((html.match(/class="country-block"/g)||[]).length,countries);}});
test('source gross currency and both ROI columns visible, total ratios never average days',()=>{const run=ui();run("selectedSite='Eggbev'");const html=run('movement()');assert.match(html,/Gross CAD/);assert.match(html,/ROI gross/);assert.match(html,/ROI net/);assert.equal(run('rollup([{gross:100,net:80,tax:-8,spend:-20,profit:52,invalid:0},{gross:100,net:80,tax:-8,spend:-40,profit:32,invalid:0}]).roi_gross'),200/60-1);});
