import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,scryptSync} from 'node:crypto';import {request} from 'node:http';import vm from 'node:vm';import {openPostgres,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const database=process.env.FINANCE_NAVIGATION_DATABASE;assert.equal(database,'mgs_finance_usability_1546729477319696405');const db=await openPostgres({database,user:'mgs_pg',options:'-c role=mgsfinance -c timezone=UTC -c statement_timeout=60000'});let server;
try{
 const initial=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.equal(initial.filter(x=>x.id.startsWith('workspace-')).length,17);
 const password=randomUUID()+'-ISOLATED',salt=randomUUID(),config={username:'rodolfo',salt,hash:scryptSync(password,salt,64).toString('hex'),origin:'https://dash.mgsdigitalcorp.com'};server=(await createApp(db,{auth:config})).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 function call(url,body,h={},expected=200){return new Promise((resolve,reject)=>{const req=request({hostname:'127.0.0.1',port:server.address().port,path:url,method:body===undefined?'GET':'POST',headers:{Host:'dash.mgsdigitalcorp.com',...(body===undefined?{}:{'Content-Type':'application/json',Origin:config.origin}),...h}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{try{let data;try{data=JSON.parse(s);}catch{}assert.equal(res.statusCode,expected,url+' '+JSON.stringify(data));resolve({data,headers:res.headers});}catch(e){reject(e);}})});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
 async function login(username,pw){const r=await call('/api/auth/login',{username,password:pw});const h={Cookie:r.headers['set-cookie'][0].split(';')[0]},me=(await call('/api/auth/me',undefined,h)).data;return {...h,'X-CSRF-Token':me.csrf};}
 const owner=await login('rodolfo',password),snapshots={workspace:{},manager:{}};for(const p of ['2026-08','2026-09']){snapshots.workspace[p]=(await call('/api/workspace?period='+p,undefined,owner)).data;snapshots.manager[p]=(await call('/api/manager-workspace?period='+p,undefined,owner)).data;}snapshots.activity=(await call('/api/finance/activity',undefined,owner)).data;await fs.writeFile(path.join(root,'private/usability-browser-api.json'),JSON.stringify(snapshots));console.log(JSON.stringify({pass:true,read_only_finances:true}));
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}
