import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const dir='private/usability-1546729477319696405',base='https://dash.mgsdigitalcorp.com',phase=process.argv[2]||'stage',staticFiles=['navigation.js','navigation.css','operations.js','app.js'];let browser;
try{const chunks=[];for await(const c of process.stdin)chunks.push(c);const credentials=JSON.parse(Buffer.concat(chunks).toString());browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:950},locale:'pt-BR'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(25000);
if(phase==='stage'){const api=JSON.parse(await fs.readFile(dir+'/stage-browser-api.json','utf8'));for(const f of staticFiles)await ctx.route(base+'/'+f,route=>route.fulfill({path:'public/'+f,contentType:f.endsWith('.css')?'text/css':'application/javascript'}));for(const[name,key]of [['manager-workspace','manager'],['workspace','workspace']])await ctx.route(base+'/api/'+name+'**',route=>{const p=new URL(route.request().url()).searchParams.get('period')||'2026-08';return api[key][p]?route.fulfill({json:api[key][p]}):route.continue();});await ctx.route(base+'/api/finance/activity**',route=>route.fulfill({json:api.activity}));}
await page.goto(base+'/login');assert.equal(await page.locator('h1').innerText(),'Fluxo de Caixa');await page.locator('#username').fill(credentials.username);await page.locator('#password').fill(credentials.password);await page.locator('button[type=submit]').click();await page.waitForSelector('.cards');
const views=[['overview',false],['movement',false],['sites',false],['accounts',false],['company',false],['personnel',false],['rates',false],['payments',true],['activity',true],['approvals',true],['users',true],['manager',true],['profile',true]],checks=[];
for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:950});for(const[view,op]of views){await page.goto(base+(op?'/operations':'/')+'?view='+view);await page.waitForFunction(()=>document.querySelector('#content')?.textContent&&!document.querySelector('#content').textContent.includes('Carregando…')&&document.querySelector('#title')?.textContent!=='Gestão financeira');if(view==='accounts')await page.waitForSelector('[data-account-table]');if(view==='manager')await page.waitForSelector('.manager-block');const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(overflow.scroll<=width+1,JSON.stringify({view,...overflow}));assert.equal(await page.locator('.topbar #accountMenu').count(),0);assert.equal(await page.locator('.sidebar #accountMenu').count(),1);
if(view==='overview'){if(await page.locator('body').evaluate(e=>e.classList.contains('sidebar-collapsed')))await page.locator('#sidebarToggle').click();const box=await page.locator('.sidebar').evaluate(e=>{const logo=e.querySelector('.official-logo').getBoundingClientRect(),r=e.getBoundingClientRect(),a=e.querySelector('.sidebar-account').getBoundingClientRect();return {background:getComputedStyle(e).backgroundColor,logoCenter:(logo.left+logo.right)/2,sidebarCenter:(r.left+r.right)/2,bottom:a.bottom,viewport:innerHeight,text:getComputedStyle(e.querySelector('#nav .nav-item')).color};});assert.equal(box.background,'rgb(0, 0, 0)');assert.equal(box.text,'rgb(255, 255, 255)');assert.ok(Math.abs(box.logoCenter-box.sidebarCenter)<2);assert.ok(Math.abs(box.viewport-box.bottom)<=20);await page.locator('#accountMenu summary').click();const drop=await page.locator('.account-dropdown').boundingBox();assert.ok(drop.y>=0&&drop.x>=0&&drop.x+drop.width<=width+1);await page.screenshot({path:dir+'/'+phase+'-sidebar-'+width+'.png'});await page.locator('#accountMenu summary').click();if(width<=700)await page.locator('#sidebarToggle').click();}
if(view==='manager'){assert.equal(await page.locator('.manager-cards .secondary-currency').count(),3);const usd=await page.locator('.manager-cards strong').allTextContents(),brl=await page.locator('.manager-cards small').allTextContents();assert.ok(usd.every(x=>x.includes('US$'))&&brl.every(x=>x.includes('R$')));const b=page.locator('.manager-block').first();assert.equal(await b.locator('[data-manager-day]').count(),31);const foot=await b.locator('tfoot td').allTextContents();assert.ok(foot.at(-1).includes('%')&&foot.at(-2).includes('%'));await page.screenshot({path:dir+'/'+phase+'-manager-'+width+'.png'});if(width===1440)await b.screenshot({path:dir+'/'+phase+'-roi-month.png'});}
if(view==='activity'){const text=await page.locator('#content').innerText();assert.ok(!text.includes('Invalid Date')&&!text.includes('LOGIN_SUCCESS')&&!text.includes('USER_PROFILE_CHANGED'));assert.ok(/\d{2}\/\d{2}\/\d{4}/.test(text));const detail=page.locator('.activity-detail').first();await detail.locator('summary').click();assert.equal(await page.locator('#content pre').count(),0);await page.screenshot({path:dir+'/'+phase+'-activity-'+width+'.png'});}
if(view==='personnel'){assert.ok(!(await page.locator('[data-expense-panel] .summary-note').innerText()).includes('planilha'));assert.ok((await page.locator('[data-expense-panel] .summary-note').innerText()).includes('R$ 100.000'));}
const selectors={rates:'[data-monthly-rates]',accounts:'[data-account-table]',sites:'[data-site-catalog]'};let maxRow=null;if(selectors[view]){const rows=await page.locator(selectors[view]+' tbody tr').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height));assert.ok(rows.length>0);maxRow=Math.max(...rows);assert.ok(maxRow<=(width<=700?60:52),JSON.stringify({view,width,maxRow}));}
const formButton={sites:'#addSite',accounts:'#addAccount',company:'#addExpense',personnel:'[data-expense]',rates:'[data-rate]',payments:'#payment',users:'#addUser'}[view];let form=false;if(formButton&&await page.locator(formButton).count()){await page.locator(formButton).first().click();const dialog=page.locator('dialog[open]');await dialog.waitFor();const fit=await dialog.evaluate(e=>{const b=e.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth};});assert.ok(fit.left>=0&&fit.right<=width+1&&fit.top>=0&&fit.bottom<=951&&fit.scrollWidth<=fit.clientWidth+1,JSON.stringify({view,width,fit}));await page.screenshot({path:dir+'/'+phase+'-form-'+view+'-'+width+'.png'});const close=dialog.locator('[data-close],#cancel');if(await close.count())await close.first().click();else await page.keyboard.press('Escape');form=true;}
checks.push({view,width,pass:true,maxRow,form});await fs.writeFile(dir+'/'+phase+'-checks.json',JSON.stringify(checks,null,2));}}
assert.equal(checks.length,views.length*4);assert.equal(new Set(checks.map(x=>x.view+':'+x.width)).size,checks.length);assert.equal(errors.length,0,JSON.stringify(errors));const out={pass:true,phase,views:views.length,viewports:[360,390,768,1440],checks:checks.length,forms:checks.filter(x=>x.form).length,js_errors:0,financial_test_writes:0};await fs.writeFile(dir+'/'+phase+'-browser.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));
}catch(e){console.log(JSON.stringify({pass:false,phase,error:e.message.slice(0,1800)}));process.exitCode=1;}finally{await browser?.close();}
