import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,scryptSync} from 'node:crypto';import {request} from 'node:http';import vm from 'node:vm';import {openPostgres,root} from '../storage.mjs';import {createApp} from '../server.mjs';
const database=process.env.FINANCE_NAVIGATION_DATABASE;assert.equal(database,'mgs_finance_usability_1546729477319696405');const db=await openPostgres({database,user:'mgs_pg',options:'-c role=mgsfinance -c timezone=UTC -c statement_timeout=60000'});let server;
try{
 const initial=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.equal(initial.filter(x=>x.id.startsWith('workspace-')).length,17);
 const password=randomUUID()+'-ISOLATED',salt=randomUUID(),config={username:'rodolfo',salt,hash:scryptSync(password,salt,64).toString('hex'),origin:'https://dash.mgsdigitalcorp.com'};server=(await createApp(db,{auth:config})).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 function call(url,body,h={},expected=200){return new Promise((resolve,reject)=>{const req=request({hostname:'127.0.0.1',port:server.address().port,path:url,method:body===undefined?'GET':'POST',headers:{Host:'dash.mgsdigitalcorp.com',...(body===undefined?{}:{'Content-Type':'application/json',Origin:config.origin}),...h}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{try{let data;try{data=JSON.parse(s);}catch{}assert.equal(res.statusCode,expected,url+' '+JSON.stringify(data));resolve({data,headers:res.headers});}catch(e){reject(e);}})});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
 async function login(username,pw){const r=await call('/api/auth/login',{username,password:pw});const h={Cookie:r.headers['set-cookie'][0].split(';')[0]},me=(await call('/api/auth/me',undefined,h)).data;return {...h,'X-CSRF-Token':me.csrf};}
 const owner=await login('rodolfo',password);const pw=randomUUID()+'-ISOLATED';for(const [username,role]of [['test_geizian','partner'],['test_nicolas','manager']]){await call('/api/finance/users',{username,display_name:username,role,manager_key:role==='manager'?'nicolas':null},owner,201);await call('/api/finance/users/'+username+'/credential',{password:pw,revision:0},owner);}
 await call('/api/finance/users',{username:'test_joe',display_name:'Not authorized pilot',role:'manager',manager_key:'joe'},owner,400);
 const partner=await login('test_geizian',pw),manager=await login('test_nicolas',pw);
 for(const url of ['/api/workspace','/api/cells','/api/catalog','/api/ad-accounts','/api/scenarios','/api/finance/users','/api/finance/activity','/api/finance/approvals','/api/scenarios/workspace-2026-08/audit','/api/finance/ledger?counterparty=geizian'])await call(url,undefined,manager,403);
 await call('/api/finance/activity',undefined,partner,403);await call('/api/scenarios/workspace-2026-08/audit',undefined,partner,403);await call('/api/finance/users/test_nicolas/credential',{password:randomUUID(),revision:1},partner,403);await call('/api/meta-account-lookups',{id:'bad'},partner,400);
 const snapshots={manager:{}};for(const period of ['2026-08','2026-09']){const m=(await call('/api/manager-workspace?period='+period,undefined,manager)).data;assert.equal(m.manager,'nicolas');assert.ok(!('cash' in m)&&!('results' in m));assert.ok(Number(m.fx)>0);assert.equal(m.blocks.length,8);assert.equal(m.blocks[0].monthly_values.length,m.blocks[0].columns.length);snapshots.manager[period]=m;}
 const m=snapshots.manager['2026-08'];assert.ok(Number(m.blocks[0].monthly_values[m.blocks[0].columns.indexOf('ROI · GROSS · TOTAL')])>0);assert.ok(Number(m.blocks[0].monthly_values[m.blocks[0].columns.indexOf('ROI · NET · TOTAL')])>0);
 const history=(await call('/api/finance/activity',undefined,owner)).data;assert.ok(history.rows.every(x=>typeof x.created_at==='string'&&Number.isFinite(Date.parse(x.created_at))));assert.ok(!JSON.stringify(history).includes(password));snapshots.activity=history;
 const before=(await call('/api/workspace?period=2026-08',undefined,owner)).data;const key='principal|Agosto 2026|I1';assert.equal(before.rates.find(r=>r.key===key).automatic,true);const september=(await call('/api/workspace?period=2026-09',undefined,owner)).data;assert.equal(september.rates.find(r=>r.key===key).automatic,false);
 await call('/api/scenarios/'+before.id+'/rates',{key,mode:'auto',status:'provisional',revision:before.revision,period:'2026-08'},owner);const after=(await call('/api/workspace?period=2026-08',undefined,owner)).data;const rate=after.rates.find(r=>r.key===key);assert.equal(rate.mode,'auto');assert.ok(Number(rate.value)>0);assert.equal(Number(rate.value),Number(rate.observed));for(const k of ['profit','net','gross','spend','personnel'])assert.ok(Math.abs(Number(before.domain.cash[k])-Number(after.domain.cash[k]))<1e-6,k);
 await call('/api/scenarios/'+september.id+'/rates',{key,mode:'auto',status:'provisional',revision:september.revision,period:'2026-09'},owner,400);const final=(await db.query("SELECT id,md5(result::text) hash,md5(overrides::text) inputs,md5(additions::text) additions FROM scenarios ORDER BY id")).rows;assert.deepEqual(final.filter(x=>x.id!=='workspace-2026-08'),initial.filter(x=>x.id!=='workspace-2026-08'));
 await fs.writeFile(path.join(root,'private/usability-api.json'),JSON.stringify(snapshots));const out={pass:true,database,periods:17,manager_blocks:8,manager_api_denials:10,owner_only_activity:true,dates_valid:true,monthly_roi_from_engine:true,fx_from_engine:true,gbp_auto_august:true,gbp_preserves_september:true,baseline_and_other_periods_preserved:true,gbp_no_financial_total_change:true,production_test_writes:0};await fs.writeFile(path.join(root,'private/usability-pg.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out));
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}
