import {test} from 'node:test';import assert from 'node:assert/strict';import {openDatabase,initialize,root} from '../storage.mjs';import {createApp} from '../server.mjs';import {WORKSPACE,effectiveOverrides,refreshQuotes} from '../workspace.mjs';import path from 'node:path';import fs from 'node:fs/promises';import {randomUUID} from 'node:crypto';
test('automatic quote never overwrites fixed payment rate',()=>{const key='principal|CAIXA SINTETICO|J2';assert.equal(effectiveOverrides({},[{kind:'rate',key,mode:'fixed',value:'5'}],{values:{[key]:6}})[key],'5');assert.equal(effectiveOverrides({},[],{values:{[key]:6}})[key],'6');});
test('financial workspace: daily blanks, expenses CRUD, payroll, FX lifecycle, readback', {timeout:300000},async()=>{
 const directory=path.join(root,'private','ui-test-'+randomUUID());const db=await openDatabase(directory);await initialize(db);const app=await createApp(db);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const get=async p=>{const r=await fetch(base+p);assert.equal(r.status,200);return r.json();};const post=async(p,b,code=200)=>{const r=await fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();assert.equal(r.status,code,JSON.stringify(d));return d;};const mutate=async(p,b,code=200)=>{const s=await get('/api/workspace');return post('/api/scenarios/'+WORKSPACE+'/'+p,{revision:s.revision,...b},code);};
 try{
  const baseline=await get('/api/scenarios/baseline');let w=await get('/api/workspace');assert.equal(w.id,'baseline');assert.equal(Object.keys(w.model.facts).length,2418);assert.equal(w.rates.length,10);
  await post('/api/workspace/open',{});await post('/api/workspace/open',{});assert.equal((await db.query("SELECT count(*)::int AS n FROM scenarios WHERE id=$1",[WORKSPACE])).rows[0].n,1);
  await mutate('ui-inputs',{changes:[{key:'principal|Agosto 2026|E5',value:'5'}]},400);
  await mutate('ui-inputs',{changes:[{key:'principal|Agosto 2026|D5',value:'12.5'}]});w=await get('/api/workspace');assert.equal(Number(w.model.inputs['principal|Agosto 2026|D5'].value),12.5);assert.ok(Number(w.domain.facts.find(f=>f.id==='contecta-geral-principal|US|1').gross)>0);
  await post('/api/scenarios/'+WORKSPACE+'/ui-inputs',{revision:0,changes:[{key:'principal|Agosto 2026|D5',value:'1'}]},409);
  const before=w.domain.cash.company_expenses;
  const invalidRevision=w.revision;
  for(const status of ['Pago','Pendente','Agendado'])await mutate('expenses',{category:'company',label:'TEST invalid status',amount:'1',currency:'USD',status},400);
  for(const checked_on of [null,'2026-02-30'])await mutate('expenses',{category:'company',label:'TEST invalid date',amount:'1',currency:'USD',status:'Conferido',checked_on},400);
  assert.equal((await get('/api/workspace')).revision,invalidRevision);
  await mutate('expenses',{category:'company',label:'TEST only - Office extra',amount:'25',currency:'USD',status:'A conferir'});w=await get('/api/workspace');let e=w.domain.expenses.find(e=>e.label==='TEST only - Office extra');assert.ok(e);assert.ok(Math.abs(Number(w.domain.cash.company_expenses)-Number(before)+25)<1e-6);
  await mutate('expenses',{category:'company',target:e.id,label:e.label,amount:'50',currency:'BRL',status:'Conferido',checked_on:'2026-09-08'});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(Number(e.brl),-50);assert.equal(e.status,'Conferido');assert.equal(e.checked_on,'2026-09-08');
  await mutate('expenses',{category:'company',target:e.id,label:e.label,status:'Conferido',checked_on:'2026-09-08',archived:true});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(Number(e.usd),0);assert.ok(e.archived);assert.equal(Number(e.edit_amount),50);
  await mutate('expenses',{category:'company',target:e.id,label:e.label,status:'Conferido',checked_on:'2026-09-08',archived:false});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(Number(e.brl),-50);assert.equal(e.archived,false);assert.equal(e.checked_on,'2026-09-08');await mutate('expenses',{category:'company',target:e.id,label:e.label,status:'a conferir',checked_on:'2026-09-08'});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(e.status,'A conferir');assert.equal(e.checked_on,null);
  const salary=w.domain.expenses.find(e=>e.mode==='COMMISSION_FLOOR');assert.ok(salary);await mutate('expenses',{category:'personnel',target:salary.id,label:salary.label,status:'Conferido',checked_on:'2026-09-08',amount:'1',currency:'USD'},400);await mutate('expenses',{category:'personnel',target:salary.id,label:salary.label,status:'Conferido',checked_on:'2026-09-08'});w=await get('/api/workspace');assert.equal(w.domain.expenses.find(e=>e.id===salary.id).usd,salary.usd);
  const fx='principal|CAIXA SINTETICO|J2';await mutate('rates',{key:fx,value:'5',mode:'fixed',status:'confirmed'});await refreshQuotes(db);w=await get('/api/workspace');assert.equal(Number(w.fx),5);assert.equal(w.rates.find(r=>r.key===fx).status,'confirmed');
  await mutate('rates',{key:'principal|Agosto 2026|J1',value:'0.01',mode:'fixed',status:'confirmed'});w=await get('/api/workspace');assert.equal(Number(w.rates.find(r=>r.source==='J1').value),0.01);
  await mutate('rates',{key:fx,mode:'auto',status:'provisional'});w=await get('/api/workspace');assert.equal(w.rates.find(r=>r.key===fx).mode,'auto');
  assert.deepEqual((await get('/api/scenarios/baseline')).domain.cash,baseline.domain.cash);assert.ok((await get('/api/scenarios/'+WORKSPACE+'/audit')).length>=10);
  await fs.writeFile(path.join(root,'private/ui-redesign-1546005809845243944/api-evidence.json'),JSON.stringify({pass:true,test_database:directory,baseline_preserved:true,blank_input:true,expense_crud:true,payroll_protected:true,fixed_quote_preserved:true,invalids_editable:true,revision_conflict:true}));
 }finally{await new Promise(r=>server.close(r));await db.close();}
});
