import {validateExpenseCharges,validatePrepaidCredit} from '../workspace.mjs';
import {test} from 'node:test';import assert from 'node:assert/strict';import {openDatabase,initialize,root} from '../storage.mjs';import {createApp} from '../server.mjs';import {WORKSPACE,effectiveOverrides,refreshQuotes,expenseReviewUnchanged} from '../workspace.mjs';import path from 'node:path';import fs from 'node:fs/promises';import {randomUUID} from 'node:crypto';
test('dated charges exact totals, month gate, legacy undated and input rejection',()=>{
 const rows=[{id:'a',date:'2026-09-05',amount:'0.1'},{id:'b',date:'2026-09-10',amount:'0.2'}];
 const v=validateExpenseCharges(rows,'2026-09');assert.equal(v.amount,'0.3');assert.deepEqual(v.charges,rows);
 for(const bad of [[],[{...rows[0],amount:'-1'}],[{...rows[0],amount:'NaN'}],[{...rows[0],date:'2026-09-31'}],[{...rows[0],date:'2026-08-05'}],[{...rows[0],date:null}],[rows[0],rows[0]]])assert.throws(()=>validateExpenseCharges(bad,'2026-09'));
 assert.throws(()=>validateExpenseCharges(rows,'2026-08'));
 assert.throws(()=>validateExpenseCharges(Array.from({length:101},(_,i)=>({...rows[0],id:String(i)})),'2026-09'));
 const old={edit_amount:'570.24',edit_currency:'USD'};const legacy=[{id:'legacy',date:null,amount:'570.24'}];assert.equal(validateExpenseCharges(legacy,'2026-09',old).amount,'570.24');assert.throws(()=>validateExpenseCharges([{...legacy[0],amount:'600'}],'2026-09',old));
 const prior={charges:legacy};assert.equal(validateExpenseCharges(legacy,'2026-09',old,prior).amount,'570.24');assert.equal(validateExpenseCharges([{id:'a',date:'2026-09-05',amount:'1.123456789012345678'},{id:'b',date:'2026-09-06',amount:'2'}],'2026-09').amount,'3.123456789012345678');
});
test('company expense review fast path proves financial origin and fails closed',()=>{
 const prior={kind:'expense',id:'company|142',target:'company|142',category:'company',label:'SB Tech Bot:',amount:'629.28',currency:'CAD',direction:'debit',archived:false,status:'A conferir',checked_on:null},existing={...prior,edit_amount:'629.28',edit_currency:'CAD'},next={...prior,status:'Conferido',checked_on:'2026-09-22'};
 assert.equal(expenseReviewUnchanged(existing,prior,next),true);
 for(const delta of [{amount:'630'},{currency:'USD'},{direction:'credit'},{label:'Outro'},{archived:true},{target:null},{category:'personnel'}])assert.equal(expenseReviewUnchanged(existing,prior,{...next,...delta}),false);
 for(const delta of [{edit_amount:undefined},{edit_amount:'1'},{edit_currency:'USD'},{archived:true}])assert.equal(expenseReviewUnchanged({...existing,...delta},prior,next),false);
 assert.equal(expenseReviewUnchanged(existing,{...prior,template_only:true},next),false);assert.equal(expenseReviewUnchanged(existing,undefined,next),false);
});
test('prepaid SMS credit stays a confirmed BRL cash asset from October onward',()=>{
 const row=validatePrepaidCredit({id:'sms-prepaid-2026-10-01',date:'2026-10-01',provider:'SMS Funnel',currency:'BRL',amount:'68000.00',status:'confirmed',authority:'1555464947394285580',label:'Recarga SMS Funnel'},'2026-10');
 assert.equal(row.kind,'prepaid_credit');assert.equal(row.amount,'68000.00');assert.equal(row.currency,'BRL');
 for(const bad of [{currency:'USD'},{amount:'0'},{status:'pending'},{authority:'x'},{date:'2026-09-30'},{date:'2026-10-99'},{id:'bad id'}])assert.throws(()=>validatePrepaidCredit({...row,...bad},'2026-10'));
 assert.throws(()=>validatePrepaidCredit({...row,date:'2026-09-01'},'2026-09'));
});
test('automatic quote never overwrites fixed payment rate',()=>{const key='principal|CAIXA SINTETICO|J2';assert.equal(effectiveOverrides({},[{kind:'rate',key,mode:'fixed',value:'5'}],{values:{[key]:6}})[key],'5');assert.equal(effectiveOverrides({},[],{values:{[key]:6}})[key],'6');});
test('financial workspace: daily blanks, expenses CRUD, payroll, FX lifecycle, readback', {timeout:500000},async()=>{
 const directory=path.join(root,'private','ui-test-'+randomUUID());const db=await openDatabase(directory);await initialize(db);await db.exec('CREATE ROLE mgsfinance');await db.exec(await fs.readFile(path.join(root,'deploy/history-schema.sql'),'utf8'));const hist=JSON.parse(await fs.readFile(path.join(root,'private/history-import-1546884731436671056/payloads/principal-2026-07.json'),'utf8'));await db.query('INSERT INTO finance_history(period,book,source_sha256,payload,authority) VALUES($1,$2,$3,$4::jsonb,$5)',['2026-07','principal',hist.source_sha256,JSON.stringify(hist),'1546884731436671056']);const app=await createApp(db);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const get=async p=>{const r=await fetch(base+p);assert.equal(r.status,200);return r.json();};const post=async(p,b,code=200)=>{const r=await fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();assert.equal(r.status,code,JSON.stringify(d));return d;};const mutate=async(p,b,code=200)=>{const s=await get('/api/workspace');return post('/api/scenarios/'+WORKSPACE+'/'+p,{revision:s.revision,...b},code);};
 try{
  const baseline=await get('/api/scenarios/baseline');let w=await get('/api/workspace');assert.equal(w.id,'baseline');assert.equal(Object.keys(w.model.facts).length,2418);assert.equal(w.rates.length,12);
  await post('/api/workspace/open',{});await post('/api/workspace/open',{});assert.equal((await db.query("SELECT count(*)::int AS n FROM scenarios WHERE id=$1",[WORKSPACE])).rows[0].n,1);
  const taxKey='principal|Agosto 2026|C1',snap=(await db.query('SELECT * FROM scenarios WHERE id=$1',[WORKSPACE])).rows[0],taxValue=String(snap.result.results[taxKey].actual);
  const confirmation=await mutate('rates',{key:taxKey,value:taxValue,mode:'fixed',status:'confirmed'});assert.equal(confirmation.recalculated,false);
  const confirmed=(await db.query('SELECT * FROM scenarios WHERE id=$1',[WORKSPACE])).rows[0];assert.deepEqual(confirmed.result,snap.result);assert.deepEqual(confirmed.overrides,snap.overrides);assert.equal(confirmed.revision,snap.revision+1);assert.equal(confirmed.additions.find(x=>x.kind==='rate'&&x.key===taxKey).status,'confirmed');
  await post('/api/scenarios/'+WORKSPACE+'/rates',{revision:snap.revision,key:taxKey,value:taxValue,mode:'fixed',status:'provisional'},409);
  const changedTax=await mutate('rates',{key:taxKey,value:'0.06',mode:'fixed',status:'confirmed',rateConfirmationOnly:true});assert.equal(changedTax.recalculated,true);assert.equal(Number((await get('/api/workspace')).rates.find(x=>x.key===taxKey).value),0.06);
  await mutate('rates',{key:taxKey,value:taxValue,mode:'fixed',status:'confirmed'});
  await mutate('ui-inputs',{changes:[{key:'principal|Agosto 2026|E5',value:'5'}]},400);
  await mutate('ui-inputs',{changes:[{key:'principal|Agosto 2026|D5',value:'12.5'}]});w=await get('/api/workspace');assert.equal(Number(w.model.inputs['principal|Agosto 2026|D5'].value),12.5);assert.ok(Number(w.domain.facts.find(f=>f.id==='contecta-geral-principal|US|1').gross)>0);
  await post('/api/scenarios/'+WORKSPACE+'/ui-inputs',{revision:0,changes:[{key:'principal|Agosto 2026|D5',value:'1'}]},409);
  const before=w.domain.cash.company_expenses;
  const invalidRevision=w.revision;
  for(const status of ['Pago','Pendente','Agendado'])await mutate('expenses',{category:'company',label:'TEST invalid status',amount:'1',currency:'USD',status},400);
  for(const checked_on of [null,'2026-02-30'])await mutate('expenses',{category:'company',label:'TEST invalid date',amount:'1',currency:'USD',status:'Conferido',checked_on},400);
  assert.equal((await get('/api/workspace')).revision,invalidRevision);
  await mutate('expenses',{category:'company',label:'TEST only - Office extra',amount:'25',currency:'USD',status:'A conferir'});w=await get('/api/workspace');let e=w.domain.expenses.find(e=>e.label==='TEST only - Office extra');assert.ok(e);assert.ok(Math.abs(Number(w.domain.cash.company_expenses)-Number(before)+25)<1e-6);
  await mutate('expenses',{category:'company',target:e.id,label:e.label,amount:'50',currency:'BRL',status:'Conferido',checked_on:'2026-09-08'});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(Number(e.brl),-50);assert.equal(e.status,'Conferido');assert.equal(e.checked_on,'2026-09-08');
  const reviewedBefore=(await db.query('SELECT * FROM scenarios WHERE id=$1',[WORKSPACE])).rows[0];
  const reviewOnly=await mutate('expenses',{category:'company',target:e.id,label:e.label,amount:'50',currency:'BRL',status:'Conferido',checked_on:'2026-09-09'});assert.equal(reviewOnly.recalculated,false);
  const reviewedAfter=(await db.query('SELECT * FROM scenarios WHERE id=$1',[WORKSPACE])).rows[0];assert.deepEqual(reviewedAfter.result,reviewedBefore.result);assert.deepEqual(reviewedAfter.overrides,reviewedBefore.overrides);assert.equal(reviewedAfter.revision,reviewedBefore.revision+1);assert.equal((await get('/api/workspace')).domain.expenses.find(x=>x.id===e.id).checked_on,'2026-09-09');
  await post('/api/scenarios/'+WORKSPACE+'/expenses',{revision:reviewedBefore.revision,category:'company',target:e.id,label:e.label,amount:'50',currency:'BRL',status:'A conferir'},409);
  const changedExpense=await mutate('expenses',{category:'company',target:e.id,label:e.label,amount:'51',currency:'BRL',status:'A conferir',expenseReviewOnly:true});assert.equal(changedExpense.recalculated,true);assert.equal(Number((await get('/api/workspace')).domain.expenses.find(x=>x.id===e.id).brl),-51);
  await mutate('expenses',{category:'company',target:e.id,label:e.label,amount:'50',currency:'BRL',status:'Conferido',checked_on:'2026-09-08'});
  await mutate('expenses',{category:'company',target:e.id,label:e.label,status:'Conferido',checked_on:'2026-09-08',archived:true});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(Number(e.usd),0);assert.ok(e.archived);assert.equal(Number(e.edit_amount),50);
  await mutate('expenses',{category:'company',target:e.id,label:e.label,status:'Conferido',checked_on:'2026-09-08',archived:false});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(Number(e.brl),-50);assert.equal(e.archived,false);assert.equal(e.checked_on,'2026-09-08');await mutate('expenses',{category:'company',target:e.id,label:e.label,status:'a conferir',checked_on:'2026-09-08'});w=await get('/api/workspace');e=w.domain.expenses.find(x=>x.id===e.id);assert.equal(e.status,'A conferir');assert.equal(e.checked_on,null);
  const creditBefore=Number(w.domain.cash.company_expenses);await mutate('expenses',{category:'company',label:'TEST credit - SPYFLIX',amount:'100',currency:'BRL',direction:'credit',status:'A conferir'});w=await get('/api/workspace');const credit=w.domain.expenses.find(x=>x.label==='TEST credit - SPYFLIX');assert.equal(Number(credit.brl),100);assert.equal(credit.direction,'credit');assert.ok(Number(w.domain.cash.company_expenses)>creditBefore);await mutate('expenses',{category:'personnel',label:'TEST invalid personnel credit',amount:'1',currency:'BRL',direction:'credit',status:'A conferir'},400);
  const salary=w.domain.expenses.find(e=>e.mode==='COMMISSION_FLOOR');assert.ok(salary);await mutate('expenses',{category:'personnel',target:salary.id,label:salary.label,status:'Conferido',checked_on:'2026-09-08',amount:'1',currency:'USD'},400);await mutate('expenses',{category:'personnel',target:salary.id,label:salary.label,status:'Conferido',checked_on:'2026-09-08'});w=await get('/api/workspace');assert.equal(w.domain.expenses.find(e=>e.id===salary.id).usd,salary.usd);
  const fx='principal|CAIXA SINTETICO|J2';await mutate('rates',{key:fx,value:'5',mode:'fixed',status:'confirmed'});await refreshQuotes(db);w=await get('/api/workspace');assert.equal(Number(w.fx),5);assert.equal(w.rates.find(r=>r.key===fx).status,'confirmed');const payment=await get('/api/finance/ledger?period=2026-08');const px=payment.indicators.exchange_rates.find(x=>x.key===fx);assert.equal(px.status,'Confirmado');assert.equal(Number(px.value),Number(w.fx));
  await mutate('rates',{key:'principal|Agosto 2026|J1',value:'0.01',mode:'fixed',status:'confirmed'});w=await get('/api/workspace');assert.equal(Number(w.rates.find(r=>r.source==='J1').value),0.01);
  await mutate('rates',{key:fx,mode:'auto',status:'provisional'});w=await get('/api/workspace');assert.equal(w.rates.find(r=>r.key===fx).mode,'auto');
  assert.deepEqual((await get('/api/scenarios/baseline')).domain.cash,baseline.domain.cash);assert.ok((await get('/api/scenarios/'+WORKSPACE+'/audit')).length>=10);
  // September-only dated charges: real HTTP -> transaction -> calculator -> readback.
  const augBefore=(await db.query('SELECT * FROM scenarios WHERE id=$1',[WORKSPACE])).rows[0];
  const {registerPeriods}=await import('../workspace.mjs');await registerPeriods(db,{periods:['2026-09']});
  const sept=()=>get('/api/workspace?period=2026-09');const change=async b=>{const w=await sept();return post('/api/scenarios/workspace-2026-09/expenses',{revision:w.revision,period:'2026-09',category:'company',status:'A conferir',...b});};
  const charges=[{id:'sep5',date:'2026-09-05',amount:'100.1'},{id:'sep10',date:'2026-09-10',amount:'20.2'}];
  const priorCompany=Number((await sept()).domain.cash.company_expenses);
  await change({label:'TEST dated Adspower',currency:'CAD',amount:'999',charges});let sw=await sept(),ce=sw.domain.expenses.find(e=>e.label==='TEST dated Adspower');assert.equal(ce.edit_amount,'120.3');assert.equal(ce.edit_currency,'CAD');assert.deepEqual(ce.charges,charges);assert.equal(sw.domain.expenses.filter(e=>e.id===ce.id).length,1);assert.ok(Math.abs(Number(sw.domain.cash.company_expenses)-priorCompany-Number(ce.usd))<1e-8);
  const frozen=sw.revision;for(const bad of [[],[{id:'bad',date:'2026-10-01',amount:'1'}],[{id:'bad',date:'2026-09-31',amount:'1'}],[{id:'bad',date:null,amount:'1'}]])await post('/api/scenarios/workspace-2026-09/expenses',{revision:frozen,period:'2026-09',category:'company',status:'A conferir',target:ce.id,label:ce.label,currency:'CAD',charges:bad},400);
  assert.equal((await sept()).revision,frozen);await post('/api/scenarios/'+WORKSPACE+'/expenses',{revision:(await get('/api/workspace')).revision,category:'company',status:'A conferir',label:'August rejected',currency:'USD',charges},400);
  await change({target:ce.id,label:ce.label,currency:'CAD',charges:[{...charges[1],amount:'50'}]});ce=(await sept()).domain.expenses.find(e=>e.id===ce.id);assert.equal(ce.edit_amount,'50');assert.equal(ce.charges.length,1);
  await post('/api/scenarios/workspace-2026-09/expenses',{revision:frozen,category:'company',target:ce.id,label:ce.label,status:'A conferir',currency:'CAD',charges},409);
  await change({target:ce.id,label:ce.label,status:'Conferido',checked_on:'2026-09-25'});ce=(await sept()).domain.expenses.find(e=>e.id===ce.id);assert.equal(ce.charges[0].date,'2026-09-10');assert.equal(ce.checked_on,'2026-09-25');
  await change({target:ce.id,label:ce.label,archived:true});ce=(await sept()).domain.expenses.find(e=>e.id===ce.id);assert.equal(Number(ce.usd),0);assert.equal(ce.charges.length,1);
  await change({target:ce.id,label:ce.label,archived:false});ce=(await sept()).domain.expenses.find(e=>e.id===ce.id);assert.equal(ce.edit_amount,'50');assert.equal(ce.charges.length,1);
  const augAfter=(await db.query('SELECT * FROM scenarios WHERE id=$1',[WORKSPACE])).rows[0];assert.deepEqual(augAfter,augBefore);
  await fs.writeFile(path.join(root,'private/ui-redesign-1546005809845243944/api-evidence.json'),JSON.stringify({pass:true,test_database:directory,baseline_preserved:true,blank_input:true,expense_crud:true,payroll_protected:true,fixed_quote_preserved:true,invalids_editable:true,revision_conflict:true}));
 }finally{await new Promise(r=>server.close(r));await db.close();}
});
